import { KoreaEvent } from '@/types/event';

export const KOREA_EVENTS: KoreaEvent[] = [
  {
    id: 'evt-001',
    title: 'CES Korea 2026',
    titleKo: 'CES 코리아 2026',
    description: 'CES의 한국 확장판. 글로벌 혁신 기술 전시 및 컨퍼런스.',
    category: 'exhibition',
    venue: 'COEX',
    startDate: '2026-03-18',
    endDate: '2026-03-20',
    url: 'https://www.ces.tech',
    tags: ['CES', '혁신', '테크'],
    isFree: false,
    source: 'curated',
  },
  {
    id: 'evt-002',
    title: 'NextRise 2026 Seoul',
    titleKo: '넥스트라이즈 2026 서울',
    description: '글로벌 스타트업 축제. 투자자와 스타트업의 만남의 장.',
    category: 'conference',
    venue: 'COEX',
    startDate: '2026-06-11',
    endDate: '2026-06-13',
    url: 'https://nextrise.co.kr',
    tags: ['스타트업', '투자', '글로벌'],
    isFree: false,
    source: 'curated',
  },
  {
    id: 'evt-003',
    title: 'COMEUP 2026',
    titleKo: '컴업 2026',
    description: '중기부 주최 글로벌 스타트업 페스티벌.',
    category: 'conference',
    venue: 'DDP',
    startDate: '2026-11-17',
    endDate: '2026-11-19',
    url: 'https://www.comeup.kr',
    tags: ['스타트업', '정부', '글로벌'],
    isFree: true,
    source: 'curated',
  },
  {
    id: 'evt-004',
    title: 'SWC Korea 2026',
    titleKo: 'SWC 코리아 2026',
    description: 'Startup World Cup 한국 지역 예선.',
    category: 'demoday',
    venue: 'Pangyo Startup Campus',
    startDate: '2026-05-22',
    endDate: '2026-05-22',
    url: 'https://www.startupworldcup.io',
    tags: ['피칭', '투자', '글로벌'],
    isFree: true,
    source: 'curated',
  },
  {
    id: 'evt-005',
    title: 'KDB NextRound',
    titleKo: 'KDB 넥스트라운드',
    description: 'KDB 산업은행 주최 스타트업 IR 데모데이.',
    category: 'demoday',
    venue: 'aT Center',
    startDate: '2026-04-15',
    endDate: '2026-04-15',
    url: 'https://www.kdb.co.kr',
    tags: ['IR', '투자', '데모데이'],
    isFree: true,
    source: 'curated',
  },
  {
    id: 'evt-006',
    title: 'D-Camp Demo Day',
    titleKo: '디캠프 데모데이',
    description: '은행권청년창업재단 주최 분기별 데모데이.',
    category: 'demoday',
    venue: 'Pangyo Startup Campus',
    startDate: '2026-03-27',
    endDate: '2026-03-27',
    url: 'https://dcamp.kr',
    tags: ['데모데이', '스타트업', '투자'],
    isFree: true,
    source: 'curated',
  },
  {
    id: 'evt-007',
    title: 'KITAS 2026',
    titleKo: '한국 국제 기술 산업 대전 2026',
    description: '한국 IT 및 첨단 기술 산업 전시회.',
    category: 'exhibition',
    venue: 'KINTEX',
    startDate: '2026-09-01',
    endDate: '2026-09-04',
    url: 'https://www.kitas.kr',
    tags: ['IT', '기술', '전시회'],
    isFree: false,
    source: 'curated',
  },
  {
    id: 'evt-008',
    title: 'Seoul AI Summit 2026',
    titleKo: '서울 AI 서밋 2026',
    description: '인공지능 기술 및 정책에 대한 글로벌 컨퍼런스.',
    category: 'conference',
    venue: 'COEX',
    startDate: '2026-05-13',
    endDate: '2026-05-15',
    url: 'https://www.seoulaisummit.kr',
    tags: ['AI', '인공지능', '정책'],
    isFree: false,
    source: 'curated',
  },
  {
    id: 'evt-009',
    title: 'K-Startup Grand Challenge 2026',
    titleKo: 'K-스타트업 그랜드 챌린지 2026',
    description: '해외 스타트업의 한국 시장 진출 지원 프로그램 데모데이.',
    category: 'demoday',
    venue: 'Pangyo Startup Campus',
    startDate: '2026-10-21',
    endDate: '2026-10-22',
    url: 'https://www.k-startupgc.org',
    tags: ['글로벌', '스타트업', '엑셀러레이팅'],
    isFree: true,
    source: 'curated',
  },
  {
    id: 'evt-010',
    title: 'Seoul International Book Fair 2026',
    titleKo: '서울국제도서전 2026',
    description: '출판·콘텐츠 산업의 대표적인 전시회.',
    category: 'exhibition',
    venue: 'COEX',
    startDate: '2026-06-17',
    endDate: '2026-06-21',
    url: 'https://www.sibf.or.kr',
    tags: ['출판', '콘텐츠', '도서'],
    isFree: false,
    source: 'curated',
  },
  {
    id: 'evt-011',
    title: 'COEX Food Week 2026',
    titleKo: '코엑스 푸드위크 2026',
    description: '식품·외식 산업 종합 전시회.',
    category: 'exhibition',
    venue: 'COEX',
    startDate: '2026-05-06',
    endDate: '2026-05-09',
    url: 'https://www.foodweek.co.kr',
    tags: ['식품', '외식', 'F&B'],
    isFree: false,
    source: 'curated',
  },
  {
    id: 'evt-012',
    title: 'IF (Innovation Festival) 2026',
    titleKo: 'IF 이노베이션 페스티벌 2026',
    description: '혁신 기업과 스타트업의 축제.',
    category: 'conference',
    venue: 'DDP',
    startDate: '2026-08-26',
    endDate: '2026-08-28',
    url: 'https://www.innovationfestival.kr',
    tags: ['혁신', '스타트업', '테크'],
    isFree: false,
    source: 'curated',
  },
  {
    id: 'evt-013',
    title: 'BIK (Born in Korea) 2026',
    titleKo: 'BIK 본인코리아 2026',
    description: '한국 스타트업의 글로벌 진출 데모데이.',
    category: 'demoday',
    venue: 'SETEC',
    startDate: '2026-07-08',
    endDate: '2026-07-09',
    url: 'https://www.borninkorea.kr',
    tags: ['글로벌', '스타트업', '해외진출'],
    isFree: true,
    source: 'curated',
  },
  {
    id: 'evt-014',
    title: 'Korea Blockchain Week 2026',
    titleKo: '코리아 블록체인 위크 2026',
    description: '웹3, 블록체인, 크립토 컨퍼런스.',
    category: 'conference',
    venue: 'COEX',
    startDate: '2026-09-08',
    endDate: '2026-09-12',
    url: 'https://koreablockchainweek.com',
    tags: ['블록체인', 'Web3', '크립토'],
    isFree: false,
    source: 'curated',
  },
  {
    id: 'evt-015',
    title: 'Seoul Startup Networking Night',
    titleKo: '서울 스타트업 네트워킹 나이트',
    description: '매월 개최되는 스타트업 종사자 네트워킹 이벤트.',
    category: 'networking',
    venue: 'Pangyo Startup Campus',
    startDate: '2026-03-14',
    endDate: '2026-03-14',
    url: 'https://festa.io',
    tags: ['네트워킹', '스타트업', '교류'],
    isFree: true,
    source: 'curated',
  },
  {
    id: 'evt-016',
    title: 'Pangyo Tech Forum Q1',
    titleKo: '판교 테크 포럼 Q1',
    description: '판교 기반 테크 기업 리더 초청 분기 포럼.',
    category: 'conference',
    venue: 'Pangyo Startup Campus',
    startDate: '2026-03-05',
    endDate: '2026-03-05',
    url: 'https://pangyo.kr',
    tags: ['판교', '테크', '포럼'],
    isFree: true,
    source: 'curated',
  },
  {
    id: 'evt-017',
    title: 'MWC Korea 2026',
    titleKo: 'MWC 코리아 2026',
    description: 'Mobile World Congress 한국판. 모바일·통신 기술 전시.',
    category: 'exhibition',
    venue: 'KINTEX',
    startDate: '2026-10-07',
    endDate: '2026-10-09',
    url: 'https://www.mwckorea.com',
    tags: ['모바일', '5G', '통신'],
    isFree: false,
    source: 'curated',
  },
  {
    id: 'evt-018',
    title: 'DevFest Seoul 2026',
    titleKo: '데브페스트 서울 2026',
    description: 'Google Developer Group 주최 개발자 컨퍼런스.',
    category: 'conference',
    venue: 'COEX',
    startDate: '2026-11-08',
    endDate: '2026-11-08',
    url: 'https://gdg.community.dev/gdg-seoul/',
    tags: ['개발자', 'Google', '컨퍼런스'],
    isFree: true,
    source: 'curated',
  },
  {
    id: 'evt-019',
    title: 'Korea Fintech Week 2026',
    titleKo: '코리아 핀테크 위크 2026',
    description: '금융위원회 주최 핀테크 산업 컨퍼런스.',
    category: 'conference',
    venue: 'DDP',
    startDate: '2026-08-04',
    endDate: '2026-08-06',
    url: 'https://www.koreafintech.or.kr',
    tags: ['핀테크', '금융', '정책'],
    isFree: true,
    source: 'curated',
  },
  {
    id: 'evt-020',
    title: 'Seoul Design Festival 2026',
    titleKo: '서울디자인페스티벌 2026',
    description: '디자인·크리에이티브 산업 전시회.',
    category: 'exhibition',
    venue: 'COEX',
    startDate: '2026-12-02',
    endDate: '2026-12-06',
    url: 'https://www.designfestival.co.kr',
    tags: ['디자인', '크리에이티브', '전시'],
    isFree: false,
    source: 'curated',
  },
  {
    id: 'evt-021',
    title: 'AI Expo Korea 2026',
    titleKo: 'AI 엑스포 코리아 2026',
    description: 'AI 기술 전시 및 비즈니스 매칭.',
    category: 'exhibition',
    venue: 'COEX',
    startDate: '2026-04-22',
    endDate: '2026-04-24',
    url: 'https://www.aiexpokorea.com',
    tags: ['AI', '전시', 'B2B'],
    isFree: false,
    source: 'curated',
  },
  {
    id: 'evt-022',
    title: 'Startup Founders Brunch',
    titleKo: '스타트업 파운더스 브런치',
    description: '스타트업 창업자 교류 브런치 모임.',
    category: 'networking',
    venue: 'Pangyo Startup Campus',
    startDate: '2026-04-11',
    endDate: '2026-04-11',
    url: 'https://festa.io',
    tags: ['창업자', '네트워킹', '브런치'],
    isFree: false,
    source: 'curated',
  },
  {
    id: 'evt-023',
    title: 'KINTEX Robot World 2026',
    titleKo: '킨텍스 로봇월드 2026',
    description: '로봇 기술 종합 전시회.',
    category: 'exhibition',
    venue: 'KINTEX',
    startDate: '2026-10-28',
    endDate: '2026-10-31',
    url: 'https://www.robotworld.or.kr',
    tags: ['로봇', '자동화', '기술'],
    isFree: false,
    source: 'curated',
  },
  {
    id: 'evt-024',
    title: 'Korea Cloud & Data Summit',
    titleKo: '코리아 클라우드 & 데이터 서밋',
    description: '클라우드 인프라, 데이터 분석 컨퍼런스.',
    category: 'conference',
    venue: 'COEX',
    startDate: '2026-06-03',
    endDate: '2026-06-04',
    url: 'https://www.cloudkorea.kr',
    tags: ['클라우드', '데이터', '인프라'],
    isFree: false,
    source: 'curated',
  },
  {
    id: 'evt-025',
    title: 'VC Night Seoul',
    titleKo: 'VC 나이트 서울',
    description: 'VC·엔젤 투자자 비공개 네트워킹 이벤트.',
    category: 'networking',
    venue: 'aT Center',
    startDate: '2026-05-30',
    endDate: '2026-05-30',
    url: 'https://festa.io',
    tags: ['VC', '투자', '네트워킹'],
    isFree: false,
    source: 'curated',
  },
  {
    id: 'evt-026',
    title: 'Seoul Smart City Expo',
    titleKo: '서울 스마트시티 엑스포',
    description: '스마트시티 기술 및 정책 전시·컨퍼런스.',
    category: 'exhibition',
    venue: 'COEX',
    startDate: '2026-09-23',
    endDate: '2026-09-25',
    url: 'https://www.smartcityexpo.kr',
    tags: ['스마트시티', 'IoT', '도시'],
    isFree: false,
    source: 'curated',
  },
  {
    id: 'evt-027',
    title: 'Startup Weekend Seoul',
    titleKo: '스타트업 위크엔드 서울',
    description: '54시간 해커톤 형식의 창업 체험 이벤트.',
    category: 'meetup',
    venue: 'DDP',
    startDate: '2026-04-03',
    endDate: '2026-04-05',
    url: 'https://startupweekend.org',
    tags: ['해커톤', '창업', '주말'],
    isFree: false,
    source: 'curated',
  },
  {
    id: 'evt-028',
    title: 'Korea ESG Summit 2026',
    titleKo: '코리아 ESG 서밋 2026',
    description: 'ESG 경영 및 지속가능성 컨퍼런스.',
    category: 'conference',
    venue: 'COEX',
    startDate: '2026-07-14',
    endDate: '2026-07-15',
    url: 'https://www.esgsummit.kr',
    tags: ['ESG', '지속가능성', '경영'],
    isFree: false,
    source: 'curated',
  },
  {
    id: 'evt-029',
    title: 'Seoul Game Show 2026',
    titleKo: '서울 게임쇼 2026',
    description: '한국 대표 게임 산업 전시회.',
    category: 'exhibition',
    venue: 'KINTEX',
    startDate: '2026-11-25',
    endDate: '2026-11-28',
    url: 'https://www.seoulgs.com',
    tags: ['게임', '엔터테인먼트', '전시'],
    isFree: false,
    source: 'curated',
  },
  {
    id: 'evt-030',
    title: 'D-Camp Friday Open Seminar',
    titleKo: '디캠프 프라이데이 오픈 세미나',
    description: '매주 금요일 스타트업 주제 오픈 세미나.',
    category: 'meetup',
    venue: 'Pangyo Startup Campus',
    startDate: '2026-03-06',
    endDate: '2026-03-06',
    url: 'https://dcamp.kr',
    tags: ['세미나', '스타트업', '교육'],
    isFree: true,
    source: 'curated',
  },
  {
    id: 'evt-031',
    title: 'Global Startup Fair 2026',
    titleKo: '글로벌 스타트업 페어 2026',
    description: '해외 스타트업과 한국 투자자를 연결하는 매칭 이벤트.',
    category: 'meetup',
    venue: 'SETEC',
    startDate: '2026-08-19',
    endDate: '2026-08-20',
    url: 'https://www.globalstartupfair.kr',
    tags: ['글로벌', '매칭', '투자'],
    isFree: true,
    source: 'curated',
  },
  {
    id: 'evt-032',
    title: 'Korea Health Tech Forum',
    titleKo: '코리아 헬스테크 포럼',
    description: '디지털 헬스케어·바이오 기술 컨퍼런스.',
    category: 'conference',
    venue: 'COEX',
    startDate: '2026-07-22',
    endDate: '2026-07-23',
    url: 'https://www.healthtech.kr',
    tags: ['헬스테크', '바이오', '디지털'],
    isFree: false,
    source: 'curated',
  },
  {
    id: 'evt-033',
    title: 'Semiconductor Korea 2026',
    titleKo: '세미컨 코리아 2026',
    description: '반도체 기술 및 장비 전시회.',
    category: 'exhibition',
    venue: 'COEX',
    startDate: '2026-02-04',
    endDate: '2026-02-06',
    url: 'https://www.semiconkorea.org',
    tags: ['반도체', '장비', '전시'],
    isFree: false,
    source: 'curated',
  },
  {
    id: 'evt-034',
    title: 'Seoul XR/Metaverse Expo',
    titleKo: '서울 XR/메타버스 엑스포',
    description: 'XR, AR, VR, 메타버스 기술 전시회.',
    category: 'exhibition',
    venue: 'DDP',
    startDate: '2026-04-08',
    endDate: '2026-04-10',
    url: 'https://www.xrexpo.kr',
    tags: ['XR', '메타버스', 'VR'],
    isFree: false,
    source: 'curated',
  },
  {
    id: 'evt-035',
    title: 'Startup CEO Dinner',
    titleKo: '스타트업 CEO 디너',
    description: '스타트업 대표이사 전용 네트워킹 디너.',
    category: 'networking',
    venue: 'aT Center',
    startDate: '2026-06-27',
    endDate: '2026-06-27',
    url: 'https://festa.io',
    tags: ['CEO', '네트워킹', '디너'],
    isFree: false,
    source: 'curated',
  },
];
