import { DirectorySite } from '@/types/directory';

/**
 * 「쓰는」 사이트 디렉토리.
 *
 * 나머지 디렉토리가 전부 읽을 거리(뉴스·유머)인 반면 여기 모은 것은 도구다.
 * 기준은 하나 — 오늘 당장 열어서 일을 끝낼 수 있는가.
 *
 * 순위(rank)는 카테고리 안에서의 중요도다. 트래픽 순이 아니라
 * "이 분야를 처음 접하는 사람에게 몇 번째로 알려줄 것인가" 순서로 매겼다.
 * 앞자리는 대체재가 마땅치 않은 사실상의 표준, 뒤로 갈수록 쓰임새가 갈린다.
 *
 * 제외 기준
 * - 뉴스·유머 매체 (이미 다른 디렉토리에 있다)
 * - 저작권 침해·불법 스트리밍·도박·성인물
 * - 가입하지 않으면 첫 화면조차 볼 수 없는 서비스
 *
 * free 필드는 "쓸 만한 무료 구간이 있다"는 뜻이다. 기간 제한 체험판만 있는
 * 유료 서비스에는 붙이지 않았다.
 */
export const TOOLS_DIRECTORY_SITES: DirectorySite[] = [
  // ══════════════════════════ AI 도구 ══════════════════════════
  { id: 't-ai-chatgpt', name: 'ChatGPT', nameKo: '챗GPT', url: 'https://chatgpt.com', country: 'US', group: 't-ai', rank: 1, free: true, note: '대화형 AI의 기준점, 무료로도 상당 부분 된다' },
  { id: 't-ai-claude', name: 'Claude', nameKo: '클로드', url: 'https://claude.ai', country: 'US', group: 't-ai', rank: 2, free: true, note: '긴 문서 읽기와 글쓰기에 강하다' },
  { id: 't-ai-gemini', name: 'Google Gemini', nameKo: '제미나이', url: 'https://gemini.google.com', country: 'US', group: 't-ai', rank: 3, free: true, note: '구글 검색·워크스페이스와 붙어 있다' },
  { id: 't-ai-perplexity', name: 'Perplexity', nameKo: '퍼플렉시티', url: 'https://www.perplexity.ai', country: 'US', group: 't-ai', rank: 4, free: true, note: '출처를 달아 주는 AI 검색' },
  { id: 't-ai-copilot', name: 'Microsoft Copilot', nameKo: 'MS 코파일럿', url: 'https://copilot.microsoft.com', country: 'US', group: 't-ai', rank: 5, free: true, note: '윈도우·오피스에 기본으로 들어 있다' },
  { id: 't-ai-notebooklm', name: 'NotebookLM', nameKo: '노트북LM', url: 'https://notebooklm.google.com', country: 'US', group: 't-ai', rank: 6, free: true, note: '내가 올린 자료만 근거로 답하는 연구 노트' },
  { id: 't-ai-deepseek', name: 'DeepSeek', nameKo: '딥시크', url: 'https://chat.deepseek.com', country: 'CN', group: 't-ai', rank: 7, free: true, note: '중국발 오픈 모델, 추론 성능 대비 저렴' },
  { id: 't-ai-grok', name: 'Grok', nameKo: '그록', url: 'https://grok.com', country: 'US', group: 't-ai', rank: 8, free: true, note: 'X 실시간 게시물을 함께 읽는다' },
  { id: 't-ai-mistral', name: 'Le Chat', nameKo: '르 샤', url: 'https://chat.mistral.ai', country: 'FR', group: 't-ai', rank: 9, free: true, note: '프랑스 미스트랄, 데이터 관할이 EU' },
  { id: 't-ai-huggingface', name: 'Hugging Face', nameKo: '허깅페이스', url: 'https://huggingface.co', country: 'US', group: 't-ai', rank: 10, free: true, note: '오픈 모델과 데이터셋이 모이는 곳' },
  { id: 't-ai-lmarena', name: 'LMArena', nameKo: 'LM아레나', url: 'https://lmarena.ai', country: 'US', group: 't-ai', rank: 11, free: true, note: '사람이 직접 비교 투표한 모델 순위표' },
  { id: 't-ai-cursor', name: 'Cursor', nameKo: '커서', url: 'https://cursor.com', country: 'US', group: 't-ai', rank: 12, free: true, note: 'AI가 코드베이스를 읽고 고치는 편집기' },
  { id: 't-ai-ghcopilot', name: 'GitHub Copilot', nameKo: '깃허브 코파일럿', url: 'https://github.com/features/copilot', country: 'US', group: 't-ai', rank: 13, note: '에디터 안에서 코드를 이어 쓴다' },
  { id: 't-ai-midjourney', name: 'Midjourney', nameKo: '미드저니', url: 'https://www.midjourney.com', country: 'US', group: 't-ai', rank: 14, note: '이미지 생성 품질의 기준선' },
  { id: 't-ai-krea', name: 'Krea', nameKo: '크레아', url: 'https://www.krea.ai', country: 'ES', group: 't-ai', rank: 15, free: true, note: '그리는 즉시 반응하는 실시간 생성' },
  { id: 't-ai-leonardo', name: 'Leonardo AI', nameKo: '레오나르도', url: 'https://leonardo.ai', country: 'AU', group: 't-ai', rank: 16, free: true, note: '매일 주는 무료 크레딧이 넉넉하다' },
  { id: 't-ai-runway', name: 'Runway', nameKo: '런웨이', url: 'https://runwayml.com', country: 'US', group: 't-ai', rank: 17, free: true, note: '영상 생성·편집 도구의 선두' },
  { id: 't-ai-elevenlabs', name: 'ElevenLabs', nameKo: '일레븐랩스', url: 'https://elevenlabs.io', country: 'US', group: 't-ai', rank: 18, free: true, note: '자연스러운 음성 합성, 한국어 지원' },
  { id: 't-ai-suno', name: 'Suno', nameKo: '수노', url: 'https://suno.com', country: 'US', group: 't-ai', rank: 19, free: true, note: '가사만 넣으면 곡이 나온다' },
  { id: 't-ai-heygen', name: 'HeyGen', nameKo: '헤이젠', url: 'https://www.heygen.com', country: 'US', group: 't-ai', rank: 20, free: true, note: 'AI 아바타 영상과 자동 더빙' },
  { id: 't-ai-gamma', name: 'Gamma', nameKo: '감마', url: 'https://gamma.app', country: 'US', group: 't-ai', rank: 21, free: true, note: '개요만 주면 발표자료를 만든다' },
  { id: 't-ai-poe', name: 'Poe', nameKo: '포', url: 'https://poe.com', country: 'US', group: 't-ai', rank: 22, free: true, note: '여러 모델을 한 창에서 갈아탄다' },
  { id: 't-ai-replicate', name: 'Replicate', nameKo: '리플리케이트', url: 'https://replicate.com', country: 'US', group: 't-ai', rank: 23, free: true, note: '오픈 모델을 API로 바로 호출' },
  { id: 't-ai-ollama', name: 'Ollama', nameKo: '올라마', url: 'https://ollama.com', country: 'US', group: 't-ai', rank: 24, free: true, note: '내 컴퓨터에서 모델을 돌린다' },
  { id: 't-ai-v0', name: 'v0', nameKo: 'v0', url: 'https://v0.app', country: 'US', group: 't-ai', rank: 25, free: true, note: '말로 설명하면 화면 코드가 나온다' },

  // ══════════════════════════ 검색·백과·아카이브 ══════════════════════════
  { id: 't-search-google', name: 'Google', nameKo: '구글', url: 'https://www.google.com', country: 'US', group: 't-search', rank: 1, free: true, note: '설명이 필요 없는 출발점' },
  { id: 't-search-wikipedia', name: 'Wikipedia', nameKo: '위키백과', url: 'https://www.wikipedia.org', country: 'US', group: 't-search', rank: 2, free: true, note: '300여 개 언어판, 한국어판도 활발' },
  { id: 't-search-archive', name: 'Internet Archive', nameKo: '인터넷 아카이브', url: 'https://archive.org', country: 'US', group: 't-search', rank: 3, free: true, note: '사라진 웹페이지를 되살리는 웨이백 머신' },
  { id: 't-search-scholar', name: 'Google Scholar', nameKo: '구글 학술검색', url: 'https://scholar.google.com', country: 'US', group: 't-search', rank: 4, free: true, note: '논문 검색과 피인용 추적' },
  { id: 't-search-wolfram', name: 'Wolfram Alpha', nameKo: '울프럼알파', url: 'https://www.wolframalpha.com', country: 'US', group: 't-search', rank: 5, free: true, note: '수식·단위·통계를 계산해서 답한다' },
  { id: 't-search-ddg', name: 'DuckDuckGo', nameKo: '덕덕고', url: 'https://duckduckgo.com', country: 'US', group: 't-search', rank: 6, free: true, note: '기록을 남기지 않는 검색' },
  { id: 't-search-bing', name: 'Bing', nameKo: '빙', url: 'https://www.bing.com', country: 'US', group: 't-search', rank: 7, free: true },
  { id: 't-search-brave', name: 'Brave Search', nameKo: '브레이브 검색', url: 'https://search.brave.com', country: 'US', group: 't-search', rank: 8, free: true, note: '자체 색인을 쓰는 독립 검색엔진' },
  { id: 't-search-yandex', name: 'Yandex', nameKo: '얀덱스', url: 'https://yandex.com', country: 'RU', group: 't-search', rank: 9, free: true, note: '이미지 역검색이 특히 강하다' },
  { id: 't-search-baidu', name: 'Baidu', nameKo: '바이두', url: 'https://www.baidu.com', country: 'CN', group: 't-search', rank: 10, free: true, note: '중국어 자료는 여기서 찾아야 나온다' },
  { id: 't-search-archivetoday', name: 'archive.today', nameKo: '아카이브 투데이', url: 'https://archive.ph', country: 'INT', group: 't-search', rank: 11, free: true, note: '페이지를 지금 이 상태로 박제한다' },
  { id: 't-search-britannica', name: 'Encyclopaedia Britannica', nameKo: '브리태니커', url: 'https://www.britannica.com', country: 'US', group: 't-search', rank: 12, free: true, note: '편집자가 검수한 백과사전' },
  { id: 't-search-ecosia', name: 'Ecosia', nameKo: '에코시아', url: 'https://www.ecosia.org', country: 'DE', group: 't-search', rank: 13, free: true, note: '검색 수익으로 나무를 심는다' },
  { id: 't-search-startpage', name: 'Startpage', nameKo: '스타트페이지', url: 'https://www.startpage.com', country: 'NL', group: 't-search', rank: 14, free: true, note: '구글 결과를 익명으로 대신 받아 온다' },
  { id: 't-search-kagi', name: 'Kagi', nameKo: '카기', url: 'https://kagi.com', country: 'US', group: 't-search', rank: 15, note: '광고 없는 구독형 검색' },
  { id: 't-search-books', name: 'Google Books', nameKo: '구글 도서', url: 'https://books.google.com', country: 'US', group: 't-search', rank: 16, free: true, note: '책 본문 안까지 검색된다' },
  { id: 't-search-worldcat', name: 'WorldCat', nameKo: '월드캣', url: 'https://search.worldcat.org', country: 'US', group: 't-search', rank: 17, free: true, note: '전세계 도서관 소장 자료 통합 목록' },
  { id: 't-search-wikidata', name: 'Wikidata', nameKo: '위키데이터', url: 'https://www.wikidata.org', country: 'INT', group: 't-search', rank: 18, free: true, note: '위키백과의 사실을 기계가 읽는 형태로' },
  { id: 't-search-snopes', name: 'Snopes', nameKo: '스노프스', url: 'https://www.snopes.com', country: 'US', group: 't-search', rank: 19, free: true, note: '떠도는 소문의 진위를 검증한다' },
  { id: 't-search-tineye', name: 'TinEye', nameKo: '틴아이', url: 'https://tineye.com', country: 'CA', group: 't-search', rank: 20, free: true, note: '이미지가 어디서 처음 나왔는지 역추적' },

  // ══════════════════════════ 온라인 강의·학습 ══════════════════════════
  { id: 't-learn-coursera', name: 'Coursera', nameKo: '코세라', url: 'https://www.coursera.org', country: 'US', group: 't-learn', rank: 1, free: true, note: '스탠퍼드·구글 등 정식 수료증 과정' },
  { id: 't-learn-khan', name: 'Khan Academy', nameKo: '칸아카데미', url: 'https://www.khanacademy.org', country: 'US', group: 't-learn', rank: 2, free: true, note: '수학·과학 전 과정 완전 무료, 한국어판 있음' },
  { id: 't-learn-edx', name: 'edX', nameKo: '에덱스', url: 'https://www.edx.org', country: 'US', group: 't-learn', rank: 3, free: true, note: 'MIT와 하버드가 만든 공개 강의 플랫폼' },
  { id: 't-learn-ocw', name: 'MIT OpenCourseWare', nameKo: 'MIT 오픈코스웨어', url: 'https://ocw.mit.edu', country: 'US', group: 't-learn', rank: 4, free: true, note: 'MIT 정규 강의 자료를 통째로 공개' },
  { id: 't-learn-fcc', name: 'freeCodeCamp', nameKo: '프리코드캠프', url: 'https://www.freecodecamp.org', country: 'US', group: 't-learn', rank: 5, free: true, note: '광고도 결제도 없는 개발 커리큘럼' },
  { id: 't-learn-cs50', name: 'Harvard CS50', nameKo: '하버드 CS50', url: 'https://cs50.harvard.edu', country: 'US', group: 't-learn', rank: 6, free: true, note: '컴퓨터과학 입문 강의의 세계 표준' },
  { id: 't-learn-udemy', name: 'Udemy', nameKo: '유데미', url: 'https://www.udemy.com', country: 'US', group: 't-learn', rank: 7, note: '실무 강의가 가장 많다, 상시 할인' },
  { id: 't-learn-classcentral', name: 'Class Central', nameKo: '클래스 센트럴', url: 'https://www.classcentral.com', country: 'US', group: 't-learn', rank: 8, free: true, note: '전 플랫폼 강의를 한 번에 검색·비교' },
  { id: 't-learn-w3schools', name: 'W3Schools', nameKo: 'W3스쿨', url: 'https://www.w3schools.com', country: 'NO', group: 't-learn', rank: 9, free: true, note: '웹 문법을 즉석에서 실행하며 배운다' },
  { id: 't-learn-brilliant', name: 'Brilliant', nameKo: '브릴리언트', url: 'https://brilliant.org', country: 'US', group: 't-learn', rank: 10, free: true, note: '수학·과학을 문제 풀이로 익힌다' },
  { id: 't-learn-openstax', name: 'OpenStax', nameKo: '오픈스택스', url: 'https://openstax.org', country: 'US', group: 't-learn', rank: 11, free: true, note: '라이스대가 만든 무료 대학 교재' },
  { id: 't-learn-codecademy', name: 'Codecademy', nameKo: '코드카데미', url: 'https://www.codecademy.com', country: 'US', group: 't-learn', rank: 12, free: true, note: '브라우저에서 바로 코드를 친다' },
  { id: 't-learn-datacamp', name: 'DataCamp', nameKo: '데이터캠프', url: 'https://www.datacamp.com', country: 'US', group: 't-learn', rank: 13, note: '데이터 분석·통계 실습 중심' },
  { id: 't-learn-kaggle', name: 'Kaggle Learn', nameKo: '캐글 런', url: 'https://www.kaggle.com/learn', country: 'US', group: 't-learn', rank: 14, free: true, note: '짧은 실습으로 머신러닝 입문' },
  { id: 't-learn-3b1b', name: '3Blue1Brown', nameKo: '3블루1브라운', url: 'https://www.3blue1brown.com', country: 'US', group: 't-learn', rank: 15, free: true, note: '수학을 그림으로 이해시키는 강의' },
  { id: 't-learn-linkedin', name: 'LinkedIn Learning', nameKo: '링크드인 러닝', url: 'https://www.linkedin.com/learning/', country: 'US', group: 't-learn', rank: 16, note: '직무 교육, 수료증이 프로필에 붙는다' },
  { id: 't-learn-futurelearn', name: 'FutureLearn', nameKo: '퓨처런', url: 'https://www.futurelearn.com', country: 'UK', group: 't-learn', rank: 17, free: true, note: '영국 대학 중심 공개 강의' },
  { id: 't-learn-openlearn', name: 'OpenLearn', nameKo: '오픈런', url: 'https://www.open.edu/openlearn/', country: 'UK', group: 't-learn', rank: 18, free: true, note: '영국 개방대학의 무료 강의' },
  { id: 't-learn-domestika', name: 'Domestika', nameKo: '도메스티카', url: 'https://www.domestika.org', country: 'ES', group: 't-learn', rank: 19, note: '디자인·공예 등 창작 분야에 강하다' },
  { id: 't-learn-skillshare', name: 'Skillshare', nameKo: '스킬셰어', url: 'https://www.skillshare.com', country: 'US', group: 't-learn', rank: 20, note: '창작·부업 강의 구독제' },
  { id: 't-learn-alison', name: 'Alison', nameKo: '앨리슨', url: 'https://alison.com', country: 'IE', group: 't-learn', rank: 21, free: true, note: '아일랜드발 무료 직업교육' },
  { id: 't-learn-saylor', name: 'Saylor Academy', nameKo: '세일러 아카데미', url: 'https://www.saylor.org', country: 'US', group: 't-learn', rank: 22, free: true, note: '학점 인정까지 되는 무료 강좌' },
  { id: 't-learn-exercism', name: 'Exercism', nameKo: '엑서시즘', url: 'https://exercism.org', country: 'US', group: 't-learn', rank: 23, free: true, note: '70여 개 언어를 멘토 첨삭으로 연습' },
  { id: 't-learn-quizlet', name: 'Quizlet', nameKo: '퀴즐렛', url: 'https://quizlet.com', country: 'US', group: 't-learn', rank: 24, free: true, note: '암기 카드의 사실상 표준' },

  // ══════════════════════════ 어학·번역·사전 ══════════════════════════
  { id: 't-lang-deepl', name: 'DeepL', nameKo: '딥엘', url: 'https://www.deepl.com/translator', country: 'DE', group: 't-lang', rank: 1, free: true, note: '문장이 가장 자연스러운 번역기' },
  { id: 't-lang-gtranslate', name: 'Google Translate', nameKo: '구글 번역', url: 'https://translate.google.com', country: 'US', group: 't-lang', rank: 2, free: true, note: '언어 수와 카메라 번역이 압도적' },
  { id: 't-lang-papago', name: 'Papago', nameKo: '파파고', url: 'https://papago.naver.com', country: 'KR', group: 't-lang', rank: 3, free: true, note: '한국어가 끼면 대체로 가장 낫다' },
  { id: 't-lang-duolingo', name: 'Duolingo', nameKo: '듀오링고', url: 'https://www.duolingo.com', country: 'US', group: 't-lang', rank: 4, free: true, note: '매일 5분 습관 만들기에는 최적' },
  { id: 't-lang-anki', name: 'Anki', nameKo: '앙키', url: 'https://apps.ankiweb.net', country: 'JP', group: 't-lang', rank: 5, free: true, note: '망각곡선 기반 반복 암기, 의대생 필수품' },
  { id: 't-lang-cambridge', name: 'Cambridge Dictionary', nameKo: '케임브리지 사전', url: 'https://dictionary.cambridge.org', country: 'UK', group: 't-lang', rank: 6, free: true, note: '학습자용 정의가 쉽고 예문이 좋다' },
  { id: 't-lang-mw', name: 'Merriam-Webster', nameKo: '메리엄웹스터', url: 'https://www.merriam-webster.com', country: 'US', group: 't-lang', rank: 7, free: true, note: '미국 영어의 기준 사전' },
  { id: 't-lang-oxford', name: 'Oxford Learner’s Dictionaries', nameKo: '옥스퍼드 학습사전', url: 'https://www.oxfordlearnersdictionaries.com', country: 'UK', group: 't-lang', rank: 8, free: true },
  { id: 't-lang-reverso', name: 'Reverso Context', nameKo: '리버소 컨텍스트', url: 'https://context.reverso.net', country: 'FR', group: 't-lang', rank: 9, free: true, note: '실제 문장 속 쓰임을 나란히 보여 준다' },
  { id: 't-lang-linguee', name: 'Linguee', nameKo: '링귀', url: 'https://www.linguee.com', country: 'DE', group: 't-lang', rank: 10, free: true, note: '번역 대역문 검색, 전문 번역가용' },
  { id: 't-lang-wordreference', name: 'WordReference', nameKo: '워드레퍼런스', url: 'https://www.wordreference.com', country: 'US', group: 't-lang', rank: 11, free: true, note: '유럽어 사전과 포럼 답변이 강하다' },
  { id: 't-lang-forvo', name: 'Forvo', nameKo: '포보', url: 'https://forvo.com', country: 'ES', group: 't-lang', rank: 12, free: true, note: '원어민이 직접 녹음한 발음 사전' },
  { id: 't-lang-youglish', name: 'YouGlish', nameKo: '유글리시', url: 'https://youglish.com', country: 'US', group: 't-lang', rank: 13, free: true, note: '그 단어가 나오는 영상 장면만 모아 재생' },
  { id: 't-lang-languagetool', name: 'LanguageTool', nameKo: '랭귀지툴', url: 'https://languagetool.org', country: 'DE', group: 't-lang', rank: 14, free: true, note: '30여 개 언어 문법 검사, 오픈소스' },
  { id: 't-lang-grammarly', name: 'Grammarly', nameKo: '그래머리', url: 'https://www.grammarly.com', country: 'US', group: 't-lang', rank: 15, free: true, note: '영어 문법·문체 교정의 표준' },
  { id: 't-lang-italki', name: 'italki', nameKo: '아이토키', url: 'https://www.italki.com', country: 'HK', group: 't-lang', rank: 16, note: '원어민 튜터와 1:1 화상 수업' },
  { id: 't-lang-tandem', name: 'Tandem', nameKo: '탠덤', url: 'https://tandem.net', country: 'DE', group: 't-lang', rank: 17, free: true, note: '서로의 모국어를 가르쳐 주는 언어 교환' },
  { id: 't-lang-hellotalk', name: 'HelloTalk', nameKo: '헬로톡', url: 'https://www.hellotalk.com', country: 'HK', group: 't-lang', rank: 18, free: true },
  { id: 't-lang-memrise', name: 'Memrise', nameKo: '메모라이즈', url: 'https://www.memrise.com', country: 'UK', group: 't-lang', rank: 19, free: true, note: '실제 원어민 영상으로 듣기 훈련' },
  { id: 't-lang-jisho', name: 'Jisho', nameKo: '지쇼', url: 'https://jisho.org', country: 'US', group: 't-lang', rank: 20, free: true, note: '일본어 한자·단어 사전의 정석' },
  { id: 't-lang-pleco', name: 'Pleco', nameKo: '플레코', url: 'https://www.pleco.com', country: 'US', group: 't-lang', rank: 21, free: true, note: '중국어 학습자가 가장 많이 쓰는 사전' },
  { id: 't-lang-tatoeba', name: 'Tatoeba', nameKo: '타토에바', url: 'https://tatoeba.org', country: 'INT', group: 't-lang', rank: 22, free: true, note: '400여 개 언어 예문 대역 말뭉치' },
  { id: 't-lang-languagereactor', name: 'Language Reactor', nameKo: '랭귀지 리액터', url: 'https://www.languagereactor.com', country: 'US', group: 't-lang', rank: 23, free: true, note: '넷플릭스·유튜브에 이중 자막을 얹는다' },

  // ══════════════════════════ 개발·코딩 ══════════════════════════
  { id: 't-dev-github', name: 'GitHub', nameKo: '깃허브', url: 'https://github.com', country: 'US', group: 't-dev', rank: 1, free: true, note: '세상의 코드가 모이는 곳' },
  { id: 't-dev-stackoverflow', name: 'Stack Overflow', nameKo: '스택오버플로', url: 'https://stackoverflow.com', country: 'US', group: 't-dev', rank: 2, free: true, note: '에러 메시지를 붙여넣으면 답이 있다' },
  { id: 't-dev-mdn', name: 'MDN Web Docs', nameKo: 'MDN 웹 문서', url: 'https://developer.mozilla.org', country: 'US', group: 't-dev', rank: 3, free: true, note: '웹 표준 문서의 기준, 한국어 번역 있음' },
  { id: 't-dev-caniuse', name: 'Can I use', nameKo: '캔아이유즈', url: 'https://caniuse.com', country: 'US', group: 't-dev', rank: 4, free: true, note: '이 기능을 어느 브라우저가 지원하는가' },
  { id: 't-dev-npm', name: 'npm', nameKo: 'npm', url: 'https://www.npmjs.com', country: 'US', group: 't-dev', rank: 5, free: true, note: '자바스크립트 패키지 저장소' },
  { id: 't-dev-devdocs', name: 'DevDocs', nameKo: '데브독스', url: 'https://devdocs.io', country: 'CA', group: 't-dev', rank: 6, free: true, note: '수백 개 공식 문서를 오프라인으로 한 창에' },
  { id: 't-dev-regex101', name: 'regex101', nameKo: '레제스101', url: 'https://regex101.com', country: 'DE', group: 't-dev', rank: 7, free: true, note: '정규식을 한 글자씩 해설해 준다' },
  { id: 't-dev-gitlab', name: 'GitLab', nameKo: '깃랩', url: 'https://gitlab.com', country: 'US', group: 't-dev', rank: 8, free: true, note: '자체 서버에 올릴 수 있는 대안' },
  { id: 't-dev-vercel', name: 'Vercel', nameKo: '버셀', url: 'https://vercel.com', country: 'US', group: 't-dev', rank: 9, free: true, note: '프론트엔드 배포가 푸시 한 번' },
  { id: 't-dev-cloudflare', name: 'Cloudflare', nameKo: '클라우드플레어', url: 'https://www.cloudflare.com', country: 'US', group: 't-dev', rank: 10, free: true, note: 'CDN·DNS·보안, 무료 구간이 넓다' },
  { id: 't-dev-netlify', name: 'Netlify', nameKo: '넷리파이', url: 'https://www.netlify.com', country: 'US', group: 't-dev', rank: 11, free: true },
  { id: 't-dev-supabase', name: 'Supabase', nameKo: '수파베이스', url: 'https://supabase.com', country: 'SG', group: 't-dev', rank: 12, free: true, note: '오픈소스 파이어베이스, 포스트그레스 기반' },
  { id: 't-dev-firebase', name: 'Firebase', nameKo: '파이어베이스', url: 'https://firebase.google.com', country: 'US', group: 't-dev', rank: 13, free: true },
  { id: 't-dev-docker', name: 'Docker Hub', nameKo: '도커 허브', url: 'https://hub.docker.com', country: 'US', group: 't-dev', rank: 14, free: true, note: '컨테이너 이미지 공개 저장소' },
  { id: 't-dev-postman', name: 'Postman', nameKo: '포스트맨', url: 'https://www.postman.com', country: 'US', group: 't-dev', rank: 15, free: true, note: 'API를 눌러 보며 시험한다' },
  { id: 't-dev-codepen', name: 'CodePen', nameKo: '코드펜', url: 'https://codepen.io', country: 'US', group: 't-dev', rank: 16, free: true, note: '프론트엔드 조각을 바로 만들고 공유' },
  { id: 't-dev-stackblitz', name: 'StackBlitz', nameKo: '스택블리츠', url: 'https://stackblitz.com', country: 'DE', group: 't-dev', rank: 17, free: true, note: '브라우저 안에서 도는 개발 환경' },
  { id: 't-dev-codesandbox', name: 'CodeSandbox', nameKo: '코드샌드박스', url: 'https://codesandbox.io', country: 'NL', group: 't-dev', rank: 18, free: true },
  { id: 't-dev-replit', name: 'Replit', nameKo: '리플릿', url: 'https://replit.com', country: 'US', group: 't-dev', rank: 19, free: true, note: '설치 없이 50여 개 언어를 실행' },
  { id: 't-dev-godbolt', name: 'Compiler Explorer', nameKo: '컴파일러 익스플로러', url: 'https://godbolt.org', country: 'UK', group: 't-dev', rank: 20, free: true, note: '내 코드가 어떤 어셈블리가 되는지 본다' },
  { id: 't-dev-excalidraw', name: 'Excalidraw', nameKo: '엑스칼리드로우', url: 'https://excalidraw.com', country: 'US', group: 't-dev', rank: 21, free: true, note: '손그림 느낌의 아키텍처 다이어그램' },
  { id: 't-dev-drawio', name: 'draw.io', nameKo: '드로우아이오', url: 'https://app.diagrams.net', country: 'DE', group: 't-dev', rank: 22, free: true, note: '순서도·ERD를 무료로 무제한' },
  { id: 't-dev-leetcode', name: 'LeetCode', nameKo: '리트코드', url: 'https://leetcode.com', country: 'US', group: 't-dev', rank: 23, free: true, note: '기술 면접 코딩테스트 준비의 표준' },
  { id: 't-dev-codeforces', name: 'Codeforces', nameKo: '코드포스', url: 'https://codeforces.com', country: 'RU', group: 't-dev', rank: 24, free: true, note: '실시간 알고리즘 대회' },
  { id: 't-dev-roadmap', name: 'roadmap.sh', nameKo: '로드맵', url: 'https://roadmap.sh', country: 'IN', group: 't-dev', rank: 25, free: true, note: '분야별로 무엇을 순서대로 배울지 지도' },
  { id: 't-dev-pypi', name: 'PyPI', nameKo: '파이파이', url: 'https://pypi.org', country: 'US', group: 't-dev', rank: 26, free: true, note: '파이썬 패키지 저장소' },
  { id: 't-dev-devto', name: 'DEV Community', nameKo: '데브투', url: 'https://dev.to', country: 'US', group: 't-dev', rank: 27, free: true, note: '개발자 블로그 커뮤니티' },
  { id: 't-dev-jsoncrack', name: 'JSON Crack', nameKo: 'JSON 크랙', url: 'https://jsoncrack.com', country: 'TR', group: 't-dev', rank: 28, free: true, note: '복잡한 JSON을 그래프로 펼쳐 본다' },

  // ══════════════════════════ 디자인·이미지 편집 ══════════════════════════
  { id: 't-design-figma', name: 'Figma', nameKo: '피그마', url: 'https://www.figma.com', country: 'US', group: 't-design', rank: 1, free: true, note: 'UI 디자인 협업의 사실상 표준' },
  { id: 't-design-canva', name: 'Canva', nameKo: '캔바', url: 'https://www.canva.com', country: 'AU', group: 't-design', rank: 2, free: true, note: '템플릿으로 끝내는 비전문가용 디자인' },
  { id: 't-design-photopea', name: 'Photopea', nameKo: '포토피아', url: 'https://www.photopea.com', country: 'CZ', group: 't-design', rank: 3, free: true, note: '브라우저에서 도는 무료 포토샵, PSD 지원' },
  { id: 't-design-removebg', name: 'remove.bg', nameKo: '리무브bg', url: 'https://www.remove.bg', country: 'AT', group: 't-design', rank: 4, free: true, note: '배경 제거 한 번에' },
  { id: 't-design-squoosh', name: 'Squoosh', nameKo: '스쿼시', url: 'https://squoosh.app', country: 'US', group: 't-design', rank: 5, free: true, note: '이미지 용량을 눈으로 비교하며 줄인다' },
  { id: 't-design-tinypng', name: 'TinyPNG', nameKo: '타이니PNG', url: 'https://tinypng.com', country: 'NL', group: 't-design', rank: 6, free: true, note: 'PNG·JPG를 티 안 나게 압축' },
  { id: 't-design-coolors', name: 'Coolors', nameKo: '쿨러스', url: 'https://coolors.co', country: 'PT', group: 't-design', rank: 7, free: true, note: '스페이스바를 누르며 배색을 고른다' },
  { id: 't-design-adobecolor', name: 'Adobe Color', nameKo: '어도비 컬러', url: 'https://color.adobe.com', country: 'US', group: 't-design', rank: 8, free: true, note: '색상환과 접근성 대비 검사' },
  { id: 't-design-realtimecolors', name: 'Realtime Colors', nameKo: '리얼타임 컬러', url: 'https://www.realtimecolors.com', country: 'US', group: 't-design', rank: 9, free: true, note: '고른 색을 실제 화면에 얹어 본다' },
  { id: 't-design-dribbble', name: 'Dribbble', nameKo: '드리블', url: 'https://dribbble.com', country: 'US', group: 't-design', rank: 10, free: true, note: '디자인 레퍼런스를 찾는 첫 곳' },
  { id: 't-design-behance', name: 'Behance', nameKo: '비핸스', url: 'https://www.behance.net', country: 'US', group: 't-design', rank: 11, free: true, note: '완성된 작업 전체를 보여 주는 포트폴리오' },
  { id: 't-design-awwwards', name: 'Awwwards', nameKo: '어워즈', url: 'https://www.awwwards.com', country: 'ES', group: 't-design', rank: 12, free: true, note: '웹사이트 디자인 수상작 모음' },
  { id: 't-design-mobbin', name: 'Mobbin', nameKo: '모빈', url: 'https://mobbin.com', country: 'SG', group: 't-design', rank: 13, free: true, note: '실제 앱 화면을 흐름째로 캡처해 모았다' },
  { id: 't-design-landbook', name: 'Land-book', nameKo: '랜드북', url: 'https://land-book.com', country: 'LT', group: 't-design', rank: 14, free: true, note: '랜딩페이지 레퍼런스 갤러리' },
  { id: 't-design-pinterest', name: 'Pinterest', nameKo: '핀터레스트', url: 'https://www.pinterest.com', country: 'US', group: 't-design', rank: 15, free: true, note: '무드보드를 만드는 가장 빠른 방법' },
  { id: 't-design-fontjoy', name: 'Fontjoy', nameKo: '폰트조이', url: 'https://fontjoy.com', country: 'US', group: 't-design', rank: 16, free: true, note: '어울리는 폰트 조합을 자동으로 짝지어 준다' },
  { id: 't-design-typescale', name: 'Type Scale', nameKo: '타입 스케일', url: 'https://typescale.com', country: 'US', group: 't-design', rank: 17, free: true, note: '제목·본문 크기 사다리를 계산한다' },
  { id: 't-design-svgomg', name: 'SVGOMG', nameKo: 'SVG오엠지', url: 'https://jakearchibald.github.io/svgomg/', country: 'UK', group: 't-design', rank: 18, free: true, note: 'SVG에서 군더더기를 걷어낸다' },
  { id: 't-design-vectorizer', name: 'Vectorizer.AI', nameKo: '벡터라이저', url: 'https://vectorizer.ai', country: 'US', group: 't-design', rank: 19, note: '비트맵 로고를 벡터로 되살린다' },
  { id: 't-design-upscayl', name: 'Upscayl', nameKo: '업스케일', url: 'https://upscayl.org', country: 'IN', group: 't-design', rank: 20, free: true, note: '오프라인에서 도는 오픈소스 이미지 확대' },
  { id: 't-design-haikei', name: 'Haikei', nameKo: '하이케이', url: 'https://haikei.app', country: 'AU', group: 't-design', rank: 21, free: true, note: 'SVG 배경 도형을 눌러서 만든다' },
  { id: 't-design-whimsical', name: 'Whimsical', nameKo: '윔지컬', url: 'https://whimsical.com', country: 'US', group: 't-design', rank: 22, free: true, note: '와이어프레임·플로차트를 빠르게' },
  { id: 't-design-pixlr', name: 'Pixlr', nameKo: '픽슬러', url: 'https://pixlr.com', country: 'SE', group: 't-design', rank: 23, free: true },

  // ══════════════════════════ 무료 소재·리소스 ══════════════════════════
  { id: 't-asset-unsplash', name: 'Unsplash', nameKo: '언스플래시', url: 'https://unsplash.com', country: 'CA', group: 't-asset', rank: 1, free: true, note: '상업적 이용까지 무료인 고화질 사진' },
  { id: 't-asset-pexels', name: 'Pexels', nameKo: '펙셀스', url: 'https://www.pexels.com', country: 'DE', group: 't-asset', rank: 2, free: true, note: '사진과 영상 클립을 함께 준다' },
  { id: 't-asset-pixabay', name: 'Pixabay', nameKo: '픽사베이', url: 'https://pixabay.com', country: 'DE', group: 't-asset', rank: 3, free: true, note: '사진·영상·음악·일러스트를 한곳에서' },
  { id: 't-asset-gfonts', name: 'Google Fonts', nameKo: '구글 폰트', url: 'https://fonts.google.com', country: 'US', group: 't-asset', rank: 4, free: true, note: '웹폰트의 기본값, 한글 폰트도 다수' },
  { id: 't-asset-noonnu', name: '눈누', nameKo: '눈누', url: 'https://noonnu.cc', country: 'KR', group: 't-asset', rank: 5, free: true, note: '상업용 무료 한글 폰트를 라이선스별로' },
  { id: 't-asset-flaticon', name: 'Flaticon', nameKo: '플랫아이콘', url: 'https://www.flaticon.com', country: 'ES', group: 't-asset', rank: 6, free: true, note: '아이콘 수가 가장 많다' },
  { id: 't-asset-lucide', name: 'Lucide', nameKo: '루사이드', url: 'https://lucide.dev', country: 'INT', group: 't-asset', rank: 7, free: true, note: '오픈소스 선형 아이콘, 굵기가 고르다' },
  { id: 't-asset-heroicons', name: 'Heroicons', nameKo: '히어로아이콘', url: 'https://heroicons.com', country: 'US', group: 't-asset', rank: 8, free: true, note: '테일윈드 팀이 만든 아이콘 세트' },
  { id: 't-asset-simpleicons', name: 'Simple Icons', nameKo: '심플아이콘', url: 'https://simpleicons.org', country: 'INT', group: 't-asset', rank: 9, free: true, note: '브랜드 로고 3,000여 개를 SVG로' },
  { id: 't-asset-nounproject', name: 'The Noun Project', nameKo: '노운 프로젝트', url: 'https://thenounproject.com', country: 'US', group: 't-asset', rank: 10, free: true },
  { id: 't-asset-undraw', name: 'unDraw', nameKo: '언드로우', url: 'https://undraw.co', country: 'PT', group: 't-asset', rank: 11, free: true, note: '색을 바꿔 쓰는 무료 일러스트' },
  { id: 't-asset-storyset', name: 'Storyset', nameKo: '스토리셋', url: 'https://storyset.com', country: 'ES', group: 't-asset', rank: 12, free: true, note: '움직이는 일러스트까지 무료' },
  { id: 't-asset-freesound', name: 'Freesound', nameKo: '프리사운드', url: 'https://freesound.org', country: 'ES', group: 't-asset', rank: 13, free: true, note: '효과음 공유 아카이브, 학술 프로젝트 출신' },
  { id: 't-asset-fma', name: 'Free Music Archive', nameKo: '프리 뮤직 아카이브', url: 'https://freemusicarchive.org', country: 'US', group: 't-asset', rank: 14, free: true, note: '라이선스가 명확한 무료 음원' },
  { id: 't-asset-mixkit', name: 'Mixkit', nameKo: '믹스킷', url: 'https://mixkit.co', country: 'US', group: 't-asset', rank: 15, free: true, note: '영상 클립·효과음·템플릿' },
  { id: 't-asset-coverr', name: 'Coverr', nameKo: '커버', url: 'https://coverr.co', country: 'IL', group: 't-asset', rank: 16, free: true, note: '배경으로 깔 영상 루프' },
  { id: 't-asset-openverse', name: 'Openverse', nameKo: '오픈버스', url: 'https://openverse.org', country: 'US', group: 't-asset', rank: 17, free: true, note: 'CC 라이선스 자료 통합 검색' },
  { id: 't-asset-nasa', name: 'NASA Image Library', nameKo: 'NASA 이미지 라이브러리', url: 'https://images.nasa.gov', country: 'US', group: 't-asset', rank: 18, free: true, note: '우주 사진·영상이 전부 퍼블릭 도메인' },
  { id: 't-asset-met', name: 'The Met Open Access', nameKo: '메트 오픈액세스', url: 'https://www.metmuseum.org/art/collection', country: 'US', group: 't-asset', rank: 19, free: true, note: '메트로폴리탄 소장품 40만 점 공개' },
  { id: 't-asset-si', name: 'Smithsonian Open Access', nameKo: '스미소니언 오픈액세스', url: 'https://www.si.edu/openaccess', country: 'US', group: 't-asset', rank: 20, free: true, note: '박물관 소장 자료 400만 점 무료' },
  { id: 't-asset-pdr', name: 'The Public Domain Review', nameKo: '퍼블릭 도메인 리뷰', url: 'https://publicdomainreview.org', country: 'UK', group: 't-asset', rank: 21, free: true, note: '저작권이 풀린 옛 그림·문헌 큐레이션' },
  { id: 't-asset-rawpixel', name: 'Rawpixel', nameKo: '로픽셀', url: 'https://www.rawpixel.com', country: 'SG', group: 't-asset', rank: 22, free: true, note: '빈티지 일러스트 컬렉션이 좋다' },
  { id: 't-asset-picsum', name: 'Lorem Picsum', nameKo: '로렘 픽섬', url: 'https://picsum.photos', country: 'INT', group: 't-asset', rank: 23, free: true, note: '개발 중 자리를 채울 더미 이미지 URL' },
  { id: 't-asset-fontsquirrel', name: 'Font Squirrel', nameKo: '폰트 스쿼럴', url: 'https://www.fontsquirrel.com', country: 'US', group: 't-asset', rank: 24, free: true, note: '상업용 무료 폰트만 걸러 모았다' },
  { id: 't-asset-dafont', name: 'DaFont', nameKo: '다폰트', url: 'https://www.dafont.com', country: 'FR', group: 't-asset', rank: 25, free: true, note: '장식용 영문 폰트가 방대하다' },

  // ══════════════════════════ 생산성·협업 ══════════════════════════
  { id: 't-work-notion', name: 'Notion', nameKo: '노션', url: 'https://www.notion.com', country: 'US', group: 't-work', rank: 1, free: true, note: '문서·표·위키를 한 덩어리로' },
  { id: 't-work-gworkspace', name: 'Google Workspace', nameKo: '구글 워크스페이스', url: 'https://workspace.google.com', country: 'US', group: 't-work', rank: 2, free: true, note: '문서·시트·드라이브, 개인은 무료' },
  { id: 't-work-m365', name: 'Microsoft 365', nameKo: '마이크로소프트 365', url: 'https://www.microsoft365.com', country: 'US', group: 't-work', rank: 3, free: true, note: '웹 버전 오피스는 무료로 쓸 수 있다' },
  { id: 't-work-slack', name: 'Slack', nameKo: '슬랙', url: 'https://slack.com', country: 'US', group: 't-work', rank: 4, free: true, note: '업무 대화의 사실상 표준' },
  { id: 't-work-obsidian', name: 'Obsidian', nameKo: '옵시디언', url: 'https://obsidian.md', country: 'US', group: 't-work', rank: 5, free: true, note: '내 컴퓨터에 마크다운으로 남는 노트' },
  { id: 't-work-zoom', name: 'Zoom', nameKo: '줌', url: 'https://zoom.us', country: 'US', group: 't-work', rank: 6, free: true, note: '40분까지 무료 화상회의' },
  { id: 't-work-trello', name: 'Trello', nameKo: '트렐로', url: 'https://trello.com', country: 'US', group: 't-work', rank: 7, free: true, note: '카드를 옮기는 가장 단순한 칸반' },
  { id: 't-work-todoist', name: 'Todoist', nameKo: '투두이스트', url: 'https://todoist.com', country: 'US', group: 't-work', rank: 8, free: true, note: '자연어로 "매주 금요일 오후 3시"가 통한다' },
  { id: 't-work-miro', name: 'Miro', nameKo: '미로', url: 'https://miro.com', country: 'US', group: 't-work', rank: 9, free: true, note: '무한 화이트보드로 하는 워크숍' },
  { id: 't-work-airtable', name: 'Airtable', nameKo: '에어테이블', url: 'https://www.airtable.com', country: 'US', group: 't-work', rank: 10, free: true, note: '스프레드시트 모양의 데이터베이스' },
  { id: 't-work-linear', name: 'Linear', nameKo: '리니어', url: 'https://linear.app', country: 'US', group: 't-work', rank: 11, free: true, note: '개발팀 이슈 추적, 속도가 빠르다' },
  { id: 't-work-asana', name: 'Asana', nameKo: '아사나', url: 'https://asana.com', country: 'US', group: 't-work', rank: 12, free: true },
  { id: 't-work-clickup', name: 'ClickUp', nameKo: '클릭업', url: 'https://clickup.com', country: 'US', group: 't-work', rank: 13, free: true },
  { id: 't-work-jira', name: 'Jira', nameKo: '지라', url: 'https://www.atlassian.com/software/jira', country: 'AU', group: 't-work', rank: 14, free: true, note: '대규모 조직의 표준 이슈 트래커' },
  { id: 't-work-calendly', name: 'Calendly', nameKo: '캘런들리', url: 'https://calendly.com', country: 'US', group: 't-work', rank: 15, free: true, note: '일정 조율 메일을 없애 준다' },
  { id: 't-work-zapier', name: 'Zapier', nameKo: '재피어', url: 'https://zapier.com', country: 'US', group: 't-work', rank: 16, free: true, note: '앱과 앱을 코드 없이 잇는다' },
  { id: 't-work-make', name: 'Make', nameKo: '메이크', url: 'https://www.make.com', country: 'CZ', group: 't-work', rank: 17, free: true, note: '재피어보다 복잡한 분기를 그릴 수 있다' },
  { id: 't-work-loom', name: 'Loom', nameKo: '룸', url: 'https://www.loom.com', country: 'US', group: 't-work', rank: 18, free: true, note: '화면 녹화 링크로 설명을 대신한다' },
  { id: 't-work-dropbox', name: 'Dropbox', nameKo: '드롭박스', url: 'https://www.dropbox.com', country: 'US', group: 't-work', rank: 19, free: true },
  { id: 't-work-raycast', name: 'Raycast', nameKo: '레이캐스트', url: 'https://www.raycast.com', country: 'US', group: 't-work', rank: 20, free: true, note: '맥 단축 실행기, 확장이 풍부하다' },
  { id: 't-work-toggl', name: 'Toggl Track', nameKo: '토글 트랙', url: 'https://toggl.com/track/', country: 'EE', group: 't-work', rank: 21, free: true, note: '무엇에 몇 시간 썼는지 기록' },
  { id: 't-work-otter', name: 'Otter.ai', nameKo: '오터', url: 'https://otter.ai', country: 'US', group: 't-work', rank: 22, free: true, note: '회의 녹음을 받아쓰고 요약한다' },
];
