import { DirectorySite } from '@/types/directory';

/**
 * 해외 국가별 뉴스 매체 디렉토리.
 * 각 나라의 기록신문(paper of record), 공영방송, 통신사, 그리고
 * 현지 사정을 영어로 전하는 매체를 중심으로 정리했다.
 */
export const WORLD_DIRECTORY_SITES: DirectorySite[] = [
  // ══════════════════════ 영국·아일랜드 ══════════════════════
  { id: 'w-bbc', name: 'BBC News', nameKo: 'BBC 뉴스', url: 'https://www.bbc.com/news', country: 'UK', group: 'uk', rank: 1, rssUrl: 'https://feeds.bbci.co.uk/news/rss.xml', free: true, note: '세계에서 가장 신뢰받는 방송' },
  { id: 'w-guardian', name: 'The Guardian', nameKo: '가디언', url: 'https://www.theguardian.com', country: 'UK', group: 'uk', rank: 3, rssUrl: 'https://www.theguardian.com/international/rss', free: true, lean: 'progressive', note: '페이월 없는 진보 성향 일간지' },
  { id: 'w-skynews', name: 'Sky News', nameKo: '스카이뉴스', url: 'https://news.sky.com', country: 'UK', group: 'uk', rank: 8, rssUrl: 'https://feeds.skynews.com/feeds/rss/world.xml', free: true },
  { id: 'w-telegraph', name: 'The Telegraph', nameKo: '텔레그래프', url: 'https://www.telegraph.co.uk', country: 'UK', group: 'uk', rank: 6, lean: 'conservative', note: '보수 성향 고급지' },
  { id: 'w-thetimes', name: 'The Times', nameKo: '더 타임스', url: 'https://www.thetimes.com', country: 'UK', group: 'uk', rank: 10, lean: 'conservative', note: '1785년 창간' },
  { id: 'w-independent', name: 'The Independent', nameKo: '인디펜던트', url: 'https://www.independent.co.uk', country: 'UK', group: 'uk', rank: 7, rssUrl: 'https://www.independent.co.uk/news/world/rss', free: true },
  { id: 'w-dailymail', name: 'Daily Mail', nameKo: '데일리메일', url: 'https://www.dailymail.co.uk', country: 'UK', group: 'uk', rank: 2, free: true, lean: 'conservative', note: '세계 최대 트래픽 뉴스 사이트' },
  { id: 'w-mirror', name: 'Daily Mirror', nameKo: '데일리 미러', url: 'https://www.mirror.co.uk', country: 'UK', group: 'uk', rank: 5, free: true, lean: 'progressive' },
  { id: 'w-express', name: 'Daily Express', nameKo: '데일리 익스프레스', url: 'https://www.express.co.uk', country: 'UK', group: 'uk', rank: 9, free: true, lean: 'conservative' },
  { id: 'w-thesun', name: 'The Sun', nameKo: '더 선', url: 'https://www.thesun.co.uk', country: 'UK', group: 'uk', rank: 4, free: true },
  { id: 'w-metro', name: 'Metro', nameKo: '메트로', url: 'https://metro.co.uk', country: 'UK', group: 'uk', rank: 11, free: true },
  { id: 'w-standard', name: 'Evening Standard', nameKo: '이브닝 스탠더드', url: 'https://www.standard.co.uk', country: 'UK', group: 'uk', rank: 12, free: true },
  { id: 'w-itvnews', name: 'ITV News', nameKo: 'ITV 뉴스', url: 'https://www.itv.com/news', country: 'UK', group: 'uk', rank: 13, free: true },
  { id: 'w-channel4news', name: 'Channel 4 News', nameKo: '채널4 뉴스', url: 'https://www.channel4.com/news/', country: 'UK', group: 'uk', rank: 14, free: true },
  { id: 'w-newstatesman', name: 'New Statesman', nameKo: '뉴 스테이츠먼', url: 'https://www.newstatesman.com', country: 'UK', group: 'uk', rank: 16, lean: 'progressive' },
  { id: 'w-spectator', name: 'The Spectator', nameKo: '스펙테이터', url: 'https://www.spectator.co.uk', country: 'UK', group: 'uk', rank: 15, lean: 'conservative', note: '1828년 창간 보수 주간지' },
  { id: 'w-rte', name: 'RTÉ News', nameKo: 'RTÉ 뉴스', url: 'https://www.rte.ie/news/', country: 'IE', group: 'uk', rank: 17, free: true, note: '아일랜드 공영방송' },
  { id: 'w-irishtimes', name: 'The Irish Times', nameKo: '아이리시 타임스', url: 'https://www.irishtimes.com', country: 'IE', group: 'uk', rank: 19, note: '아일랜드 기록신문' },
  { id: 'w-irishindependent', name: 'Irish Independent', nameKo: '아이리시 인디펜던트', url: 'https://www.independent.ie', country: 'IE', group: 'uk', rank: 18, free: true },
  { id: 'w-thejournal', name: 'TheJournal.ie', nameKo: '더저널', url: 'https://www.thejournal.ie', country: 'IE', group: 'uk', rank: 20, free: true },

  // ══════════════════════ 서유럽 ══════════════════════
  { id: 'w-spiegel', name: 'Der Spiegel', nameKo: '슈피겔', url: 'https://www.spiegel.de', country: 'DE', group: 'europe-west', rank: 1, rssUrl: 'https://www.spiegel.de/schlagzeilen/index.rss', note: '독일 대표 탐사 시사지' },
  { id: 'w-sueddeutsche', name: 'Süddeutsche Zeitung', nameKo: '쥐트도이체 차이퉁', url: 'https://www.sueddeutsche.de', country: 'DE', group: 'europe-west', rank: 8, lean: 'progressive' },
  { id: 'w-faz', name: 'Frankfurter Allgemeine', nameKo: '프랑크푸르터 알게마이네', url: 'https://www.faz.net', country: 'DE', group: 'europe-west', rank: 6, lean: 'conservative' },
  { id: 'w-welt', name: 'Die Welt', nameKo: '디 벨트', url: 'https://www.welt.de', country: 'DE', group: 'europe-west', rank: 9, lean: 'conservative' },
  { id: 'w-zeit', name: 'Die Zeit', nameKo: '디 차이트', url: 'https://www.zeit.de', country: 'DE', group: 'europe-west', rank: 7, note: '주간 고급지' },
  { id: 'w-taz', name: 'taz', nameKo: '타츠', url: 'https://taz.de', country: 'DE', group: 'europe-west', rank: 41, free: true, lean: 'progressive' },
  { id: 'w-bild', name: 'Bild', nameKo: '빌트', url: 'https://www.bild.de', country: 'DE', group: 'europe-west', rank: 2, free: true, note: '독일 최대 타블로이드' },
  { id: 'w-focus', name: 'Focus', nameKo: '포쿠스', url: 'https://www.focus.de', country: 'DE', group: 'europe-west', rank: 10, free: true },
  { id: 'w-stern', name: 'Stern', nameKo: '슈테른', url: 'https://www.stern.de', country: 'DE', group: 'europe-west', rank: 12, free: true },
  { id: 'w-handelsblatt', name: 'Handelsblatt', nameKo: '한델스블라트', url: 'https://www.handelsblatt.com', country: 'DE', group: 'europe-west', rank: 17, note: '독일 대표 경제지' },
  { id: 'w-tagesschau', name: 'Tagesschau', nameKo: '타게스샤우', url: 'https://www.tagesschau.de', country: 'DE', group: 'europe-west', rank: 11, free: true, note: 'ARD 공영 뉴스' },
  { id: 'w-dw', name: 'Deutsche Welle', nameKo: '도이체 벨레', url: 'https://www.dw.com', country: 'DE', group: 'europe-west', rank: 3, rssUrl: 'https://rss.dw.com/rdf/rss-en-all', free: true, note: '독일 국제방송, 한국어 제공' },
  { id: 'w-lemonde', name: 'Le Monde', nameKo: '르 몽드', url: 'https://www.lemonde.fr', country: 'FR', group: 'europe-west', rank: 4, note: '프랑스 기록신문' },
  { id: 'w-lefigaro', name: 'Le Figaro', nameKo: '르 피가로', url: 'https://www.lefigaro.fr', country: 'FR', group: 'europe-west', rank: 13, lean: 'conservative' },
  { id: 'w-liberation', name: 'Libération', nameKo: '리베라시옹', url: 'https://www.liberation.fr', country: 'FR', group: 'europe-west', rank: 15, lean: 'progressive' },
  { id: 'w-leparisien', name: 'Le Parisien', nameKo: '르 파리지앵', url: 'https://www.leparisien.fr', country: 'FR', group: 'europe-west', rank: 16 },
  { id: 'w-lesechos', name: 'Les Échos', nameKo: '레제코', url: 'https://www.lesechos.fr', country: 'FR', group: 'europe-west', rank: 18, note: '프랑스 대표 경제지' },
  { id: 'w-latribune', name: 'La Tribune', nameKo: '라 트리뷘', url: 'https://www.latribune.fr', country: 'FR', group: 'europe-west', rank: 42 },
  { id: 'w-humanite', name: "L'Humanité", nameKo: '뤼마니테', url: 'https://www.humanite.fr', country: 'FR', group: 'europe-west', rank: 43, lean: 'progressive' },
  { id: 'w-20minutes', name: '20 Minutes', nameKo: '20미뉘트', url: 'https://www.20minutes.fr', country: 'FR', group: 'europe-west', rank: 19, free: true },
  { id: 'w-mediapart', name: 'Mediapart', nameKo: '메디아파르', url: 'https://www.mediapart.fr', country: 'FR', group: 'europe-west', rank: 22, note: '구독 기반 탐사보도' },
  { id: 'w-lexpress', name: "L'Express", nameKo: '렉스프레스', url: 'https://www.lexpress.fr', country: 'FR', group: 'europe-west', rank: 21 },
  { id: 'w-lepoint', name: 'Le Point', nameKo: '르 푸앵', url: 'https://www.lepoint.fr', country: 'FR', group: 'europe-west', rank: 20 },
  { id: 'w-france24', name: 'France 24', nameKo: '프랑스24', url: 'https://www.france24.com/en/', country: 'FR', group: 'europe-west', rank: 5, rssUrl: 'https://www.france24.com/en/rss', free: true },
  { id: 'w-rfi', name: 'RFI', nameKo: 'RFI 국제방송', url: 'https://www.rfi.fr/en/', country: 'FR', group: 'europe-west', rank: 23, free: true },
  { id: 'w-nrc', name: 'NRC', nameKo: 'NRC', url: 'https://www.nrc.nl', country: 'NL', group: 'europe-west', rank: 26, note: '네덜란드 고급지' },
  { id: 'w-volkskrant', name: 'de Volkskrant', nameKo: '더 폴크스크란트', url: 'https://www.volkskrant.nl', country: 'NL', group: 'europe-west', rank: 27 },
  { id: 'w-telegraaf', name: 'De Telegraaf', nameKo: '더 텔레그라프', url: 'https://www.telegraaf.nl', country: 'NL', group: 'europe-west', rank: 25 },
  { id: 'w-nos', name: 'NOS', nameKo: 'NOS', url: 'https://nos.nl', country: 'NL', group: 'europe-west', rank: 24, free: true, note: '네덜란드 공영 뉴스' },
  { id: 'w-dutchnews', name: 'DutchNews.nl', nameKo: '더치뉴스', url: 'https://www.dutchnews.nl', country: 'NL', group: 'europe-west', rank: 37, free: true, note: '네덜란드 소식 영어판' },
  { id: 'w-lesoir', name: 'Le Soir', nameKo: '르 수아르', url: 'https://www.lesoir.be', country: 'BE', group: 'europe-west', rank: 35 },
  { id: 'w-standaard', name: 'De Standaard', nameKo: '더 스탄다르트', url: 'https://www.standaard.be', country: 'BE', group: 'europe-west', rank: 34 },
  { id: 'w-brusselstimes', name: 'The Brussels Times', nameKo: '브뤼셀 타임스', url: 'https://www.brusselstimes.com', country: 'BE', group: 'europe-west', rank: 36, free: true },
  { id: 'w-politicoeu', name: 'Politico Europe', nameKo: '폴리티코 유럽', url: 'https://www.politico.eu', country: 'EU', group: 'europe-west', rank: 28, free: true, note: 'EU 정책 전문' },
  { id: 'w-euractiv', name: 'Euractiv', nameKo: '유랙티브', url: 'https://www.euractiv.com', country: 'EU', group: 'europe-west', rank: 32, free: true, note: 'EU 정책 전문' },
  { id: 'w-euobserver', name: 'EUobserver', nameKo: 'EU옵서버', url: 'https://euobserver.com', country: 'EU', group: 'europe-west', rank: 38, free: true },
  { id: 'w-euronews', name: 'Euronews', nameKo: '유로뉴스', url: 'https://www.euronews.com', country: 'EU', group: 'europe-west', rank: 14, rssUrl: 'https://www.euronews.com/rss', free: true },
  { id: 'w-nzz', name: 'Neue Zürcher Zeitung', nameKo: 'NZZ', url: 'https://www.nzz.ch', country: 'CH', group: 'europe-west', rank: 29, note: '스위스 기록신문' },
  { id: 'w-letemps', name: 'Le Temps', nameKo: '르 탕', url: 'https://www.letemps.ch', country: 'CH', group: 'europe-west', rank: 39 },
  { id: 'w-swissinfo', name: 'SWI swissinfo.ch', nameKo: '스위스인포', url: 'https://www.swissinfo.ch/eng/', country: 'CH', group: 'europe-west', rank: 33, free: true },
  { id: 'w-derstandard', name: 'Der Standard', nameKo: '데어 슈탄다르트', url: 'https://www.derstandard.at', country: 'AT', group: 'europe-west', rank: 30, free: true },
  { id: 'w-diepresse', name: 'Die Presse', nameKo: '디 프레세', url: 'https://www.diepresse.com', country: 'AT', group: 'europe-west', rank: 40 },
  { id: 'w-orf', name: 'ORF News', nameKo: 'ORF 뉴스', url: 'https://orf.at', country: 'AT', group: 'europe-west', rank: 31, free: true, note: '오스트리아 공영방송' },
  { id: 'w-luxtimes', name: 'Luxembourg Times', nameKo: '룩셈부르크 타임스', url: 'https://www.luxtimes.lu', country: 'LU', group: 'europe-west', rank: 44 },

  // ══════════════════════ 북유럽 ══════════════════════
  { id: 'w-dn-se', name: 'Dagens Nyheter', nameKo: '다겐스 뉘헤테르', url: 'https://www.dn.se', country: 'SE', group: 'europe-nordic', rank: 3, note: '스웨덴 최대 조간지' },
  { id: 'w-svd', name: 'Svenska Dagbladet', nameKo: '스벤스카 다그블라데트', url: 'https://www.svd.se', country: 'SE', group: 'europe-nordic', rank: 8, lean: 'conservative' },
  { id: 'w-aftonbladet', name: 'Aftonbladet', nameKo: '아프톤블라데트', url: 'https://www.aftonbladet.se', country: 'SE', group: 'europe-nordic', rank: 1, free: true, note: '북유럽 최대 뉴스 사이트' },
  { id: 'w-expressen', name: 'Expressen', nameKo: '엑스프레센', url: 'https://www.expressen.se', country: 'SE', group: 'europe-nordic', rank: 4, free: true },
  { id: 'w-svtnyheter', name: 'SVT Nyheter', nameKo: 'SVT 뉘헤테르', url: 'https://www.svt.se/nyheter/', country: 'SE', group: 'europe-nordic', rank: 7, free: true, note: '스웨덴 공영방송' },
  { id: 'w-thelocalse', name: 'The Local Sweden', nameKo: '더 로컬(스웨덴)', url: 'https://www.thelocal.se', country: 'SE', group: 'europe-nordic', rank: 22, note: '스웨덴 소식 영어판' },
  { id: 'w-aftenposten', name: 'Aftenposten', nameKo: '아프텐포스텐', url: 'https://www.aftenposten.no', country: 'NO', group: 'europe-nordic', rank: 9, note: '노르웨이 기록신문' },
  { id: 'w-vg', name: 'VG', nameKo: 'VG', url: 'https://www.vg.no', country: 'NO', group: 'europe-nordic', rank: 2, free: true },
  { id: 'w-dagbladet', name: 'Dagbladet', nameKo: '다그블라데트', url: 'https://www.dagbladet.no', country: 'NO', group: 'europe-nordic', rank: 10, free: true },
  { id: 'w-nrk', name: 'NRK', nameKo: 'NRK', url: 'https://www.nrk.no', country: 'NO', group: 'europe-nordic', rank: 5, free: true, note: '노르웨이 공영방송' },
  { id: 'w-dn-no', name: 'Dagens Næringsliv', nameKo: '다겐스 네링슬리브', url: 'https://www.dn.no', country: 'NO', group: 'europe-nordic', rank: 20, note: '노르웨이 대표 경제지' },
  { id: 'w-politiken', name: 'Politiken', nameKo: '폴리티켄', url: 'https://politiken.dk', country: 'DK', group: 'europe-nordic', rank: 12, lean: 'progressive' },
  { id: 'w-jyllandsposten', name: 'Jyllands-Posten', nameKo: '윌란스포스텐', url: 'https://jyllands-posten.dk', country: 'DK', group: 'europe-nordic', rank: 14, lean: 'conservative' },
  { id: 'w-berlingske', name: 'Berlingske', nameKo: '베를링스케', url: 'https://www.berlingske.dk', country: 'DK', group: 'europe-nordic', rank: 15, note: '1749년 창간, 유럽 최고령 일간지 중 하나' },
  { id: 'w-dr-dk', name: 'DR Nyheder', nameKo: 'DR 뉘헤데르', url: 'https://www.dr.dk/nyheder', country: 'DK', group: 'europe-nordic', rank: 13, free: true, note: '덴마크 공영방송' },
  { id: 'w-borsen', name: 'Børsen', nameKo: '뵈르센', url: 'https://borsen.dk', country: 'DK', group: 'europe-nordic', rank: 21, note: '덴마크 경제지' },
  { id: 'w-cphpost', name: 'The Copenhagen Post', nameKo: '코펜하겐 포스트', url: 'https://cphpost.dk', country: 'DK', group: 'europe-nordic', rank: 24, free: true },
  { id: 'w-hs', name: 'Helsingin Sanomat', nameKo: '헬싱인 사노마트', url: 'https://www.hs.fi', country: 'FI', group: 'europe-nordic', rank: 6, note: '핀란드 최대 일간지' },
  { id: 'w-is-fi', name: 'Ilta-Sanomat', nameKo: '일타사노마트', url: 'https://www.is.fi', country: 'FI', group: 'europe-nordic', rank: 11, free: true },
  { id: 'w-ylenews', name: 'Yle News', nameKo: 'Yle 뉴스', url: 'https://yle.fi/news', country: 'FI', group: 'europe-nordic', rank: 16, free: true, note: '핀란드 공영방송 영어판' },
  { id: 'w-helsinkitimes', name: 'Helsinki Times', nameKo: '헬싱키 타임스', url: 'https://www.helsinkitimes.fi', country: 'FI', group: 'europe-nordic', rank: 23, free: true },
  { id: 'w-mbl', name: 'Morgunblaðið', nameKo: '모르귄블라디드', url: 'https://www.mbl.is', country: 'IS', group: 'europe-nordic', rank: 17, free: true, note: '아이슬란드 대표지' },
  { id: 'w-visir', name: 'Vísir', nameKo: '비시르', url: 'https://www.visir.is', country: 'IS', group: 'europe-nordic', rank: 18, free: true },
  { id: 'w-ruv', name: 'RÚV', nameKo: 'RÚV', url: 'https://www.ruv.is', country: 'IS', group: 'europe-nordic', rank: 19, free: true, note: '아이슬란드 공영방송' },
  { id: 'w-icelandreview', name: 'Iceland Review', nameKo: '아이슬란드 리뷰', url: 'https://www.icelandreview.com', country: 'IS', group: 'europe-nordic', rank: 25, free: true },

  // ══════════════════════ 남유럽 ══════════════════════
  { id: 'w-corriere', name: 'Corriere della Sera', nameKo: '코리에레 델라 세라', url: 'https://www.corriere.it', country: 'IT', group: 'europe-south', rank: 2, note: '이탈리아 최대 일간지' },
  { id: 'w-repubblica', name: 'la Repubblica', nameKo: '라 레푸블리카', url: 'https://www.repubblica.it', country: 'IT', group: 'europe-south', rank: 3, lean: 'progressive' },
  { id: 'w-lastampa', name: 'La Stampa', nameKo: '라 스탐파', url: 'https://www.lastampa.it', country: 'IT', group: 'europe-south', rank: 7 },
  { id: 'w-ilsole24ore', name: 'Il Sole 24 Ore', nameKo: '일 솔레 24 오레', url: 'https://www.ilsole24ore.com', country: 'IT', group: 'europe-south', rank: 11, note: '이탈리아 대표 경제지' },
  { id: 'w-ilfatto', name: 'Il Fatto Quotidiano', nameKo: '일 파토 쿼티디아노', url: 'https://www.ilfattoquotidiano.it', country: 'IT', group: 'europe-south', rank: 13, free: true },
  { id: 'w-rainews', name: 'Rai News', nameKo: '라이 뉴스', url: 'https://www.rainews.it', country: 'IT', group: 'europe-south', rank: 12, free: true, note: '이탈리아 공영방송' },
  { id: 'w-elpais', name: 'El País', nameKo: '엘 파이스', url: 'https://english.elpais.com', country: 'ES', group: 'europe-south', rank: 1, free: true, lean: 'progressive', note: '스페인 최대 일간지 영문판' },
  { id: 'w-elmundo', name: 'El Mundo', nameKo: '엘 문도', url: 'https://www.elmundo.es', country: 'ES', group: 'europe-south', rank: 4, lean: 'conservative' },
  { id: 'w-abces', name: 'ABC', nameKo: 'ABC(스페인)', url: 'https://www.abc.es', country: 'ES', group: 'europe-south', rank: 6, lean: 'conservative' },
  { id: 'w-lavanguardia', name: 'La Vanguardia', nameKo: '라 방과르디아', url: 'https://www.lavanguardia.com', country: 'ES', group: 'europe-south', rank: 5, free: true },
  { id: 'w-elconfidencial', name: 'El Confidencial', nameKo: '엘 콘피덴시알', url: 'https://www.elconfidencial.com', country: 'ES', group: 'europe-south', rank: 9, free: true },
  { id: 'w-eldiario', name: 'elDiario.es', nameKo: '엘디아리오', url: 'https://www.eldiario.es', country: 'ES', group: 'europe-south', rank: 10, free: true, lean: 'progressive' },
  { id: 'w-rtve', name: 'RTVE Noticias', nameKo: 'RTVE 뉴스', url: 'https://www.rtve.es/noticias/', country: 'ES', group: 'europe-south', rank: 8, free: true, note: '스페인 공영방송' },
  { id: 'w-publico-pt', name: 'Público', nameKo: '푸블리쿠', url: 'https://www.publico.pt', country: 'PT', group: 'europe-south', rank: 14 },
  { id: 'w-expresso', name: 'Expresso', nameKo: '엑스프레수', url: 'https://expresso.pt', country: 'PT', group: 'europe-south', rank: 16 },
  { id: 'w-jn', name: 'Jornal de Notícias', nameKo: '조르날 지 노티시아스', url: 'https://www.jn.pt', country: 'PT', group: 'europe-south', rank: 15 },
  { id: 'w-rtp', name: 'RTP Notícias', nameKo: 'RTP 뉴스', url: 'https://www.rtp.pt/noticias/', country: 'PT', group: 'europe-south', rank: 17, free: true, note: '포르투갈 공영방송' },
  { id: 'w-observador', name: 'Observador', nameKo: '옵세르바도르', url: 'https://observador.pt', country: 'PT', group: 'europe-south', rank: 18, free: true },
  { id: 'w-ekathimerini', name: 'Kathimerini English', nameKo: '카티메리니', url: 'https://www.ekathimerini.com', country: 'GR', group: 'europe-south', rank: 20, free: true, note: '그리스 기록신문 영문판' },
  { id: 'w-tovima', name: 'To Vima', nameKo: '토 비마', url: 'https://www.tovima.com', country: 'GR', group: 'europe-south', rank: 21, free: true },
  { id: 'w-protothema', name: 'Protothema', nameKo: '프로토테마', url: 'https://www.protothema.gr', country: 'GR', group: 'europe-south', rank: 19, free: true },
  { id: 'w-greekreporter', name: 'Greek Reporter', nameKo: '그릭 리포터', url: 'https://greekreporter.com', country: 'GR', group: 'europe-south', rank: 22, free: true },
  { id: 'w-timesofmalta', name: 'Times of Malta', nameKo: '타임스 오브 몰타', url: 'https://timesofmalta.com', country: 'MT', group: 'europe-south', rank: 23, free: true },
  { id: 'w-cyprusmail', name: 'Cyprus Mail', nameKo: '사이프러스 메일', url: 'https://cyprus-mail.com', country: 'CY', group: 'europe-south', rank: 24, free: true },

  // ══════════════════════ 중·동유럽 ══════════════════════
  { id: 'w-wyborcza', name: 'Gazeta Wyborcza', nameKo: '가제타 비보르차', url: 'https://wyborcza.pl', country: 'PL', group: 'europe-east', rank: 2, lean: 'progressive', note: '폴란드 대표 일간지' },
  { id: 'w-rzeczpospolita', name: 'Rzeczpospolita', nameKo: '제치포스폴리타', url: 'https://www.rp.pl', country: 'PL', group: 'europe-east', rank: 9, lean: 'conservative' },
  { id: 'w-onet', name: 'Onet', nameKo: '오넷', url: 'https://www.onet.pl', country: 'PL', group: 'europe-east', rank: 1, free: true, note: '폴란드 최대 포털' },
  { id: 'w-notesfrompoland', name: 'Notes from Poland', nameKo: '노츠 프롬 폴란드', url: 'https://notesfrompoland.com', country: 'PL', group: 'europe-east', rank: 35, free: true, note: '폴란드 소식 영어판' },
  { id: 'w-pap', name: 'PAP', nameKo: 'PAP 통신', url: 'https://www.pap.pl/en', country: 'PL', group: 'europe-east', rank: 33, free: true, note: '폴란드 국영 통신사' },
  { id: 'w-tvpworld', name: 'TVP World', nameKo: 'TVP 월드', url: 'https://tvpworld.com', country: 'PL', group: 'europe-east', rank: 34, free: true },
  { id: 'w-denikn', name: 'Deník N', nameKo: '데니크 N', url: 'https://denikn.cz', country: 'CZ', group: 'europe-east', rank: 12, note: '체코 독립 일간지' },
  { id: 'w-idnes', name: 'iDNES', nameKo: 'iDNES', url: 'https://www.idnes.cz', country: 'CZ', group: 'europe-east', rank: 3, free: true },
  { id: 'w-expatscz', name: 'Expats.cz', nameKo: '엑스팻츠 CZ', url: 'https://www.expats.cz', country: 'CZ', group: 'europe-east', rank: 37, free: true, note: '체코 소식 영어판' },
  { id: 'w-radioprague', name: 'Radio Prague International', nameKo: '라디오 프라하', url: 'https://english.radio.cz', country: 'CZ', group: 'europe-east', rank: 36, free: true },
  { id: 'w-slovakspectator', name: 'The Slovak Spectator', nameKo: '슬로바크 스펙테이터', url: 'https://spectator.sme.sk', country: 'SK', group: 'europe-east', rank: 38, free: true },
  { id: 'w-dennikn', name: 'Denník N', nameKo: '데니크 N(슬로바키아)', url: 'https://dennikn.sk', country: 'SK', group: 'europe-east', rank: 25 },
  { id: 'w-telex', name: 'Telex', nameKo: '텔렉스', url: 'https://telex.hu', country: 'HU', group: 'europe-east', rank: 5, free: true, note: '헝가리 독립 매체' },
  { id: 'w-444', name: '444', nameKo: '444', url: 'https://444.hu', country: 'HU', group: 'europe-east', rank: 8, free: true },
  { id: 'w-hvg', name: 'hvg.hu', nameKo: 'HVG', url: 'https://hvg.hu', country: 'HU', group: 'europe-east', rank: 7, free: true },
  { id: 'w-hungarytoday', name: 'Hungary Today', nameKo: '헝가리 투데이', url: 'https://hungarytoday.hu', country: 'HU', group: 'europe-east', rank: 39, free: true },
  { id: 'w-g4media', name: 'G4Media', nameKo: 'G4미디어', url: 'https://www.g4media.ro', country: 'RO', group: 'europe-east', rank: 21, free: true },
  { id: 'w-digi24', name: 'Digi24', nameKo: '디지24', url: 'https://www.digi24.ro', country: 'RO', group: 'europe-east', rank: 11, free: true },
  { id: 'w-romaniainsider', name: 'Romania Insider', nameKo: '루마니아 인사이더', url: 'https://www.romania-insider.com', country: 'RO', group: 'europe-east', rank: 40, free: true },
  { id: 'w-agerpres', name: 'Agerpres', nameKo: '아제르프레스', url: 'https://www.agerpres.ro/english', country: 'RO', group: 'europe-east', rank: 32, free: true, note: '루마니아 국영 통신사' },
  { id: 'w-dnevnik-bg', name: 'Dnevnik', nameKo: '드네브니크', url: 'https://www.dnevnik.bg', country: 'BG', group: 'europe-east', rank: 19, free: true },
  { id: 'w-sofiaglobe', name: 'The Sofia Globe', nameKo: '소피아 글로브', url: 'https://sofiaglobe.com', country: 'BG', group: 'europe-east', rank: 41, free: true },
  { id: 'w-novinite', name: 'Novinite', nameKo: '노비니테', url: 'https://www.novinite.com', country: 'BG', group: 'europe-east', rank: 42, free: true },
  { id: 'w-jutarnji', name: 'Jutarnji list', nameKo: '유타르니 리스트', url: 'https://www.jutarnji.hr', country: 'HR', group: 'europe-east', rank: 15, free: true },
  { id: 'w-indexhr', name: 'Index.hr', nameKo: '인덱스', url: 'https://www.index.hr', country: 'HR', group: 'europe-east', rank: 6, free: true },
  { id: 'w-totalcroatia', name: 'Total Croatia News', nameKo: '토탈 크로아티아 뉴스', url: 'https://total-croatia-news.com', country: 'HR', group: 'europe-east', rank: 43, free: true },
  { id: 'w-politika', name: 'Politika', nameKo: '폴리티카', url: 'https://www.politika.rs', country: 'RS', group: 'europe-east', rank: 13, free: true, note: '발칸 최고령 일간지' },
  { id: 'w-danas', name: 'Danas', nameKo: '다나스', url: 'https://www.danas.rs', country: 'RS', group: 'europe-east', rank: 17, free: true },
  { id: 'w-n1info', name: 'N1', nameKo: 'N1', url: 'https://n1info.rs', country: 'RS', group: 'europe-east', rank: 14, free: true },
  { id: 'w-balkaninsight', name: 'Balkan Insight', nameKo: '발칸 인사이트', url: 'https://balkaninsight.com', country: 'RS', group: 'europe-east', rank: 24, free: true, note: 'BIRN 탐사보도 네트워크' },
  { id: 'w-delo', name: 'Delo', nameKo: '델로', url: 'https://www.delo.si', country: 'SI', group: 'europe-east', rank: 20 },
  { id: 'w-rtvslo', name: 'RTV Slovenija', nameKo: 'RTV 슬로베니아', url: 'https://www.rtvslo.si', country: 'SI', group: 'europe-east', rank: 31, free: true },
  { id: 'w-kyivindependent', name: 'The Kyiv Independent', nameKo: '키이우 인디펜던트', url: 'https://kyivindependent.com', country: 'UA', group: 'europe-east', rank: 4, free: true, note: '우크라이나 대표 영자 매체' },
  { id: 'w-pravda-ua', name: 'Ukrainska Pravda', nameKo: '우크라인스카 프라우다', url: 'https://www.pravda.com.ua/eng/', country: 'UA', group: 'europe-east', rank: 10, free: true },
  { id: 'w-kyivpost', name: 'Kyiv Post', nameKo: '키이우 포스트', url: 'https://www.kyivpost.com', country: 'UA', group: 'europe-east', rank: 22, free: true },
  { id: 'w-suspilne', name: 'Suspilne', nameKo: '수스필네', url: 'https://suspilne.media', country: 'UA', group: 'europe-east', rank: 23, free: true, note: '우크라이나 공영방송' },
  { id: 'w-postimees', name: 'Postimees', nameKo: '포스티메스', url: 'https://news.postimees.ee', country: 'EE', group: 'europe-east', rank: 16, free: true },
  { id: 'w-errnews', name: 'ERR News', nameKo: 'ERR 뉴스', url: 'https://news.err.ee', country: 'EE', group: 'europe-east', rank: 28, free: true, note: '에스토니아 공영방송 영어판' },
  { id: 'w-lsm', name: 'LSM.lv English', nameKo: 'LSM 라트비아', url: 'https://eng.lsm.lv', country: 'LV', group: 'europe-east', rank: 29, free: true },
  { id: 'w-lrtenglish', name: 'LRT English', nameKo: 'LRT 리투아니아', url: 'https://www.lrt.lt/en/news-in-english', country: 'LT', group: 'europe-east', rank: 30, free: true },
  { id: 'w-15min', name: '15min', nameKo: '15min', url: 'https://www.15min.lt', country: 'LT', group: 'europe-east', rank: 18, free: true },
  { id: 'w-nashaniva', name: 'Nasha Niva', nameKo: '나샤 니바', url: 'https://nashaniva.com', country: 'BY', group: 'europe-east', rank: 26, free: true, note: '벨라루스 독립 매체' },
  { id: 'w-zerkalo', name: 'Zerkalo', nameKo: '제르칼로', url: 'https://news.zerkalo.io', country: 'BY', group: 'europe-east', rank: 27, free: true },

  // ══════════════════════ 러시아·구소련 ══════════════════════
  { id: 'w-ria', name: 'RIA Novosti', nameKo: '리아 노보스티', url: 'https://ria.ru', country: 'RU', group: 'russia', rank: 1, free: true, note: '러시아 국영 통신' },
  { id: 'w-interfax', name: 'Interfax', nameKo: '인테르팍스', url: 'https://interfax.com', country: 'RU', group: 'russia', rank: 6, free: true },
  { id: 'w-lenta', name: 'Lenta.ru', nameKo: '렌타', url: 'https://lenta.ru', country: 'RU', group: 'russia', rank: 2, free: true },
  { id: 'w-gazeta', name: 'Gazeta.ru', nameKo: '가제타', url: 'https://www.gazeta.ru', country: 'RU', group: 'russia', rank: 4, free: true },
  { id: 'w-kommersant', name: 'Kommersant', nameKo: '코메르산트', url: 'https://www.kommersant.ru', country: 'RU', group: 'russia', rank: 5, free: true, note: '경제 전문' },
  { id: 'w-vedomosti', name: 'Vedomosti', nameKo: '베도모스티', url: 'https://www.vedomosti.ru', country: 'RU', group: 'russia', rank: 8 },
  { id: 'w-rt', name: 'RT', nameKo: 'RT', url: 'https://www.rt.com', country: 'RU', group: 'russia', rank: 3, free: true, note: '국영 국제방송' },
  { id: 'w-meduza', name: 'Meduza', nameKo: '메두자', url: 'https://meduza.io/en', country: 'LV', group: 'russia', rank: 7, free: true, note: '망명 러시아 독립 매체' },
  { id: 'w-moscowtimes', name: 'The Moscow Times', nameKo: '모스크바 타임스', url: 'https://www.themoscowtimes.com', country: 'NL', group: 'russia', rank: 9, free: true, note: '독립 영자 매체' },
  { id: 'w-novayaeurope', name: 'Novaya Gazeta Europe', nameKo: '노바야 가제타 유럽', url: 'https://novayagazeta.eu/en', country: 'LV', group: 'russia', rank: 10, free: true, note: '노벨평화상 수상 매체의 망명판' },
  { id: 'w-istories', name: 'IStories', nameKo: '아이스토리스', url: 'https://istories.media/en/', country: 'RU', group: 'russia', rank: 13, free: true, note: '러시아 탐사보도' },
  { id: 'w-mediazona', name: 'Mediazona', nameKo: '메디아조나', url: 'https://en.zona.media', country: 'RU', group: 'russia', rank: 12, free: true, note: '사법·인권 전문' },
  { id: 'w-thebell', name: 'The Bell', nameKo: '더 벨', url: 'https://en.thebell.io', country: 'RU', group: 'russia', rank: 11, free: true, note: '러시아 경제 분석' },

  // ══════════════════════ 동아시아 ══════════════════════
  { id: 'w-nhk', name: 'NHK News', nameKo: 'NHK 뉴스', url: 'https://www3.nhk.or.jp/news/', country: 'JP', group: 'asia-east', rank: 1, free: true, note: '일본 공영방송' },
  { id: 'w-nhkworld', name: 'NHK World-Japan', nameKo: 'NHK 월드', url: 'https://www3.nhk.or.jp/nhkworld/en/news/', country: 'JP', group: 'asia-east', rank: 12, free: true, note: '영어·한국어 제공' },
  { id: 'w-yomiuri', name: 'Yomiuri Shimbun', nameKo: '요미우리 신문', url: 'https://www.yomiuri.co.jp', country: 'JP', group: 'asia-east', rank: 2, lean: 'conservative', note: '세계 최대 발행부수' },
  { id: 'w-asahi', name: 'Asahi Shimbun', nameKo: '아사히 신문', url: 'https://www.asahi.com', country: 'JP', group: 'asia-east', rank: 3, lean: 'progressive' },
  { id: 'w-mainichi', name: 'Mainichi Shimbun', nameKo: '마이니치 신문', url: 'https://mainichi.jp', country: 'JP', group: 'asia-east', rank: 5 },
  { id: 'w-nikkei', name: 'Nikkei', nameKo: '니혼게이자이 신문', url: 'https://www.nikkei.com', country: 'JP', group: 'asia-east', rank: 4, note: '일본 최고 경제지' },
  { id: 'w-sankei', name: 'Sankei Shimbun', nameKo: '산케이 신문', url: 'https://www.sankei.com', country: 'JP', group: 'asia-east', rank: 11, lean: 'conservative' },
  { id: 'w-chunichi', name: 'Chunichi Shimbun', nameKo: '주니치 신문', url: 'https://www.chunichi.co.jp', country: 'JP', group: 'asia-east', rank: 22 },
  { id: 'w-japantimes', name: 'The Japan Times', nameKo: '재팬 타임스', url: 'https://www.japantimes.co.jp', country: 'JP', group: 'asia-east', rank: 8, note: '일본 대표 영자지' },
  { id: 'w-japantoday', name: 'Japan Today', nameKo: '재팬 투데이', url: 'https://japantoday.com', country: 'JP', group: 'asia-east', rank: 20, free: true },
  { id: 'w-peoplecn', name: "People's Daily", nameKo: '인민일보', url: 'http://en.people.cn', country: 'CN', group: 'asia-east', rank: 10, free: true, note: '중국 공산당 기관지' },
  { id: 'w-globaltimes', name: 'Global Times', nameKo: '환구시보', url: 'https://www.globaltimes.cn', country: 'CN', group: 'asia-east', rank: 9, free: true },
  { id: 'w-chinadaily', name: 'China Daily', nameKo: '차이나 데일리', url: 'https://www.chinadaily.com.cn', country: 'CN', group: 'asia-east', rank: 7, free: true, note: '중국 최대 영자지' },
  { id: 'w-cctv', name: 'CCTV', nameKo: 'CCTV', url: 'https://english.cctv.com', country: 'CN', group: 'asia-east', rank: 14, free: true },
  { id: 'w-cgtn', name: 'CGTN', nameKo: 'CGTN', url: 'https://www.cgtn.com', country: 'CN', group: 'asia-east', rank: 13, free: true },
  { id: 'w-sixthtone', name: 'Sixth Tone', nameKo: '식스스 톤', url: 'https://www.sixthtone.com', country: 'CN', group: 'asia-east', rank: 21, free: true, note: '중국 사회 심층 르포' },
  { id: 'w-thepaper', name: 'The Paper', nameKo: '펑파이(澎湃)', url: 'https://www.thepaper.cn', country: 'CN', group: 'asia-east', rank: 18, free: true },
  { id: 'w-bjnews', name: 'The Beijing News', nameKo: '신경보', url: 'https://www.bjnews.com.cn', country: 'CN', group: 'asia-east', rank: 23, free: true },
  { id: 'w-gmw', name: 'Guangming Daily', nameKo: '광명일보', url: 'https://www.gmw.cn', country: 'CN', group: 'asia-east', rank: 26, free: true },
  { id: 'w-cecn', name: 'China Economic Net', nameKo: '중국경제망', url: 'http://en.ce.cn', country: 'CN', group: 'asia-east', rank: 27, free: true },
  { id: 'w-scmp', name: 'South China Morning Post', nameKo: 'SCMP', url: 'https://www.scmp.com', country: 'HK', group: 'asia-east', rank: 6, rssUrl: 'https://www.scmp.com/rss/91/feed', note: '홍콩 대표 영자지' },
  { id: 'w-hkfp', name: 'Hong Kong Free Press', nameKo: '홍콩 프리 프레스', url: 'https://hongkongfp.com', country: 'HK', group: 'asia-east', rank: 19, free: true, note: '비영리 독립 매체' },
  { id: 'w-rthk', name: 'RTHK News', nameKo: 'RTHK 뉴스', url: 'https://news.rthk.hk/rthk/en/', country: 'HK', group: 'asia-east', rank: 24, free: true },
  { id: 'w-focustaiwan', name: 'Focus Taiwan (CNA)', nameKo: '포커스 타이완', url: 'https://focustaiwan.tw', country: 'TW', group: 'asia-east', rank: 17, free: true, note: '대만 중앙통신 영문판' },
  { id: 'w-taipeitimes', name: 'Taipei Times', nameKo: '타이베이 타임스', url: 'https://www.taipeitimes.com', country: 'TW', group: 'asia-east', rank: 25, free: true },
  { id: 'w-libertytimes', name: 'Liberty Times', nameKo: '자유시보', url: 'https://www.ltn.com.tw', country: 'TW', group: 'asia-east', rank: 15, free: true, note: '대만 최대 발행부수' },
  { id: 'w-udn', name: 'United Daily News', nameKo: '연합보(UDN)', url: 'https://udn.com', country: 'TW', group: 'asia-east', rank: 16, free: true },
  { id: 'w-montsame', name: 'Montsame', nameKo: '몬차메 통신', url: 'https://montsame.mn/en/', country: 'MN', group: 'asia-east', rank: 29, free: true, note: '몽골 국영 통신사' },
  { id: 'w-newsmn', name: 'News.MN', nameKo: '뉴스MN', url: 'https://news.mn', country: 'MN', group: 'asia-east', rank: 28, free: true, note: '몽골 주요 뉴스 포털' },

  // ══════════════════════ 동남아시아 ══════════════════════
  { id: 'w-straitstimes', name: 'The Straits Times', nameKo: '스트레이츠 타임스', url: 'https://www.straitstimes.com', country: 'SG', group: 'asia-southeast', rank: 2, note: '싱가포르 기록신문' },
  { id: 'w-cna', name: 'CNA', nameKo: '채널뉴스아시아', url: 'https://www.channelnewsasia.com', country: 'SG', group: 'asia-southeast', rank: 1, free: true, note: '아시아 소식에 강한 영어 방송' },
  { id: 'w-businesstimes-sg', name: 'The Business Times', nameKo: '비즈니스 타임스(싱가포르)', url: 'https://www.businesstimes.com.sg', country: 'SG', group: 'asia-southeast', rank: 24 },
  { id: 'w-todayonline', name: 'TODAY', nameKo: '투데이 온라인', url: 'https://www.todayonline.com', country: 'SG', group: 'asia-southeast', rank: 21, free: true },
  { id: 'w-thestar-my', name: 'The Star', nameKo: '더 스타(말레이시아)', url: 'https://www.thestar.com.my', country: 'MY', group: 'asia-southeast', rank: 8, free: true },
  { id: 'w-nst', name: 'New Straits Times', nameKo: '뉴 스트레이츠 타임스', url: 'https://www.nst.com.my', country: 'MY', group: 'asia-southeast', rank: 12, free: true },
  { id: 'w-malaysiakini', name: 'Malaysiakini', nameKo: '말레이시아키니', url: 'https://www.malaysiakini.com', country: 'MY', group: 'asia-southeast', rank: 16, note: '구독 기반 독립 매체' },
  { id: 'w-fmt', name: 'Free Malaysia Today', nameKo: '프리 말레이시아 투데이', url: 'https://www.freemalaysiatoday.com', country: 'MY', group: 'asia-southeast', rank: 17, free: true },
  { id: 'w-theedgemy', name: 'The Edge Malaysia', nameKo: '디 엣지 말레이시아', url: 'https://theedgemalaysia.com', country: 'MY', group: 'asia-southeast', rank: 25, free: true, note: '말레이시아 경제 전문' },
  { id: 'w-bangkokpost', name: 'Bangkok Post', nameKo: '방콕 포스트', url: 'https://www.bangkokpost.com', country: 'TH', group: 'asia-southeast', rank: 9, free: true, note: '태국 대표 영자지' },
  { id: 'w-nationthailand', name: 'The Nation Thailand', nameKo: '더 네이션 타일랜드', url: 'https://www.nationthailand.com', country: 'TH', group: 'asia-southeast', rank: 18, free: true },
  { id: 'w-khaosodenglish', name: 'Khaosod English', nameKo: '카오솟 잉글리시', url: 'https://www.khaosodenglish.com', country: 'TH', group: 'asia-southeast', rank: 22, free: true },
  { id: 'w-thaipbsworld', name: 'Thai PBS World', nameKo: '타이 PBS 월드', url: 'https://www.thaipbsworld.com', country: 'TH', group: 'asia-southeast', rank: 26, free: true },
  { id: 'w-vnexpress', name: 'VnExpress International', nameKo: 'VN 익스프레스', url: 'https://e.vnexpress.net', country: 'VN', group: 'asia-southeast', rank: 11, free: true, note: '베트남 최대 온라인 신문' },
  { id: 'w-vietnamnews', name: 'Vietnam News', nameKo: '베트남 뉴스', url: 'https://vietnamnews.vn', country: 'VN', group: 'asia-southeast', rank: 27, free: true, note: '베트남 통신사(VNA) 영문지' },
  { id: 'w-vietnamnet', name: 'VietnamNet', nameKo: '베트남넷', url: 'https://vietnamnet.vn/en', country: 'VN', group: 'asia-southeast', rank: 19, free: true },
  { id: 'w-thanhnien', name: 'Thanh Nien', nameKo: '탄니엔', url: 'https://thanhnien.vn', country: 'VN', group: 'asia-southeast', rank: 20, free: true },
  { id: 'w-nhandan', name: 'Nhan Dan', nameKo: '년전', url: 'https://en.nhandan.vn', country: 'VN', group: 'asia-southeast', rank: 28, free: true, note: '베트남 공산당 기관지' },
  { id: 'w-vneconomy', name: 'VnEconomy', nameKo: 'VN 이코노미', url: 'https://vneconomy.vn', country: 'VN', group: 'asia-southeast', rank: 29, free: true },
  { id: 'w-rappler', name: 'Rappler', nameKo: '래플러', url: 'https://www.rappler.com', country: 'PH', group: 'asia-southeast', rank: 3, free: true, note: '노벨평화상 수상자 마리아 레사 창간' },
  { id: 'w-inquirer', name: 'Philippine Daily Inquirer', nameKo: '필리핀 데일리 인콰이어러', url: 'https://newsinfo.inquirer.net', country: 'PH', group: 'asia-southeast', rank: 4, free: true },
  { id: 'w-philstar', name: 'The Philippine Star', nameKo: '필리핀 스타', url: 'https://www.philstar.com', country: 'PH', group: 'asia-southeast', rank: 7, free: true },
  { id: 'w-manilabulletin', name: 'Manila Bulletin', nameKo: '마닐라 불레틴', url: 'https://mb.com.ph', country: 'PH', group: 'asia-southeast', rank: 14, free: true },
  { id: 'w-gmanews', name: 'GMA News', nameKo: 'GMA 뉴스', url: 'https://www.gmanetwork.com/news/', country: 'PH', group: 'asia-southeast', rank: 13, free: true },
  { id: 'w-jakartapost', name: 'The Jakarta Post', nameKo: '자카르타 포스트', url: 'https://www.thejakartapost.com', country: 'ID', group: 'asia-southeast', rank: 10, free: true },
  { id: 'w-kompas', name: 'Kompas', nameKo: '콤파스', url: 'https://www.kompas.com', country: 'ID', group: 'asia-southeast', rank: 5, free: true, note: '인도네시아 최대 일간지' },
  { id: 'w-tempo', name: 'Tempo', nameKo: '템포', url: 'https://en.tempo.co', country: 'ID', group: 'asia-southeast', rank: 15, free: true, note: '인도네시아 탐사보도' },
  { id: 'w-antaranews', name: 'Antara News', nameKo: '안타라 통신', url: 'https://en.antaranews.com', country: 'ID', group: 'asia-southeast', rank: 23, free: true },
  { id: 'w-detik', name: 'Detik', nameKo: '데틱', url: 'https://www.detik.com', country: 'ID', group: 'asia-southeast', rank: 6, free: true },
  { id: 'w-phnompenhpost', name: 'The Phnom Penh Post', nameKo: '프놈펜 포스트', url: 'https://www.phnompenhpost.com', country: 'KH', group: 'asia-southeast', rank: 32, free: true },
  { id: 'w-khmertimes', name: 'Khmer Times', nameKo: '크메르 타임스', url: 'https://www.khmertimeskh.com', country: 'KH', group: 'asia-southeast', rank: 31, free: true },
  { id: 'w-irrawaddy', name: 'The Irrawaddy', nameKo: '이라와디', url: 'https://www.irrawaddy.com', country: 'MM', group: 'asia-southeast', rank: 30, free: true, note: '미얀마 독립 매체' },
  { id: 'w-frontiermyanmar', name: 'Frontier Myanmar', nameKo: '프론티어 미얀마', url: 'https://www.frontiermyanmar.net', country: 'MM', group: 'asia-southeast', rank: 33, free: true },
  { id: 'w-vientianetimes', name: 'Vientiane Times', nameKo: '비엔티안 타임스', url: 'https://www.vientianetimes.org.la', country: 'LA', group: 'asia-southeast', rank: 34, free: true },
  { id: 'w-borneobulletin', name: 'Borneo Bulletin', nameKo: '보르네오 불레틴', url: 'https://borneobulletin.com.bn', country: 'BN', group: 'asia-southeast', rank: 35, free: true },

  // ══════════════════════ 남아시아 ══════════════════════
  { id: 'w-timesofindia', name: 'The Times of India', nameKo: '타임스 오브 인디아', url: 'https://timesofindia.indiatimes.com', country: 'IN', group: 'asia-south', rank: 1, rssUrl: 'https://timesofindia.indiatimes.com/rssfeedstopstories.cms', free: true, note: '세계 최대 영자 일간지' },
  { id: 'w-thehindu', name: 'The Hindu', nameKo: '더 힌두', url: 'https://www.thehindu.com', country: 'IN', group: 'asia-south', rank: 5, free: true, note: '인도 기록신문' },
  { id: 'w-hindustantimes', name: 'Hindustan Times', nameKo: '힌두스탄 타임스', url: 'https://www.hindustantimes.com', country: 'IN', group: 'asia-south', rank: 3, free: true },
  { id: 'w-indianexpress', name: 'The Indian Express', nameKo: '인디안 익스프레스', url: 'https://indianexpress.com', country: 'IN', group: 'asia-south', rank: 4, free: true },
  { id: 'w-ndtv', name: 'NDTV', nameKo: 'NDTV', url: 'https://www.ndtv.com', country: 'IN', group: 'asia-south', rank: 2, free: true },
  { id: 'w-economictimes', name: 'The Economic Times', nameKo: '이코노믹 타임스', url: 'https://economictimes.indiatimes.com', country: 'IN', group: 'asia-south', rank: 6, free: true, note: '인도 대표 경제지' },
  { id: 'w-livemint', name: 'Mint', nameKo: '민트', url: 'https://www.livemint.com', country: 'IN', group: 'asia-south', rank: 10, free: true },
  { id: 'w-businessstandard', name: 'Business Standard', nameKo: '비즈니스 스탠더드', url: 'https://www.business-standard.com', country: 'IN', group: 'asia-south', rank: 13, free: true },
  { id: 'w-scrollin', name: 'Scroll.in', nameKo: '스크롤', url: 'https://scroll.in', country: 'IN', group: 'asia-south', rank: 18, free: true },
  { id: 'w-thewire-in', name: 'The Wire', nameKo: '더 와이어', url: 'https://thewire.in', country: 'IN', group: 'asia-south', rank: 20, free: true, note: '독립 탐사보도' },
  { id: 'w-theprint', name: 'ThePrint', nameKo: '더프린트', url: 'https://theprint.in', country: 'IN', group: 'asia-south', rank: 19, free: true },
  { id: 'w-dawn', name: 'Dawn', nameKo: '던', url: 'https://www.dawn.com', country: 'PK', group: 'asia-south', rank: 7, free: true, note: '파키스탄 최고 권위 영자지' },
  { id: 'w-tribunepk', name: 'The Express Tribune', nameKo: '익스프레스 트리뷴', url: 'https://tribune.com.pk', country: 'PK', group: 'asia-south', rank: 9, free: true },
  { id: 'w-geonews', name: 'Geo News', nameKo: '지오 뉴스', url: 'https://www.geo.tv', country: 'PK', group: 'asia-south', rank: 8, free: true },
  { id: 'w-thenews-pk', name: 'The News International', nameKo: '더 뉴스 인터내셔널', url: 'https://www.thenews.com.pk', country: 'PK', group: 'asia-south', rank: 14, free: true },
  { id: 'w-dailystar-bd', name: 'The Daily Star', nameKo: '데일리 스타(방글라데시)', url: 'https://www.thedailystar.net', country: 'BD', group: 'asia-south', rank: 12, free: true },
  { id: 'w-prothomalo', name: 'Prothom Alo English', nameKo: '프로톰 알로', url: 'https://en.prothomalo.com', country: 'BD', group: 'asia-south', rank: 11, free: true, note: '방글라데시 최대 일간지' },
  { id: 'w-bdnews24', name: 'bdnews24.com', nameKo: 'bdnews24', url: 'https://bdnews24.com/english', country: 'BD', group: 'asia-south', rank: 16, free: true },
  { id: 'w-dhakatribune', name: 'Dhaka Tribune', nameKo: '다카 트리뷴', url: 'https://www.dhakatribune.com', country: 'BD', group: 'asia-south', rank: 21, free: true },
  { id: 'w-dailymirror-lk', name: 'Daily Mirror', nameKo: '데일리 미러(스리랑카)', url: 'https://www.dailymirror.lk', country: 'LK', group: 'asia-south', rank: 17, free: true },
  { id: 'w-adaderana', name: 'Ada Derana', nameKo: '아다 데라나', url: 'https://www.adaderana.lk', country: 'LK', group: 'asia-south', rank: 15, free: true },
  { id: 'w-dailyft', name: 'Daily FT', nameKo: '데일리 FT', url: 'https://www.ft.lk', country: 'LK', group: 'asia-south', rank: 23, free: true },
  { id: 'w-kathmandupost', name: 'The Kathmandu Post', nameKo: '카트만두 포스트', url: 'https://kathmandupost.com', country: 'NP', group: 'asia-south', rank: 22, free: true },
  { id: 'w-nepalitimes', name: 'Nepali Times', nameKo: '네팔리 타임스', url: 'https://nepalitimes.com', country: 'NP', group: 'asia-south', rank: 24, free: true },
  { id: 'w-tolonews', name: 'TOLOnews', nameKo: '톨로뉴스', url: 'https://tolonews.com', country: 'AF', group: 'asia-south', rank: 25, free: true, note: '아프가니스탄 대표 방송' },

  // ══════════════════════ 중앙아시아·코카서스 ══════════════════════
  { id: 'w-astanatimes', name: 'The Astana Times', nameKo: '아스타나 타임스', url: 'https://astanatimes.com', country: 'KZ', group: 'asia-central', rank: 4, free: true },
  { id: 'w-tengrinews', name: 'Tengrinews', nameKo: '텡그리뉴스', url: 'https://en.tengrinews.kz', country: 'KZ', group: 'asia-central', rank: 1, free: true },
  { id: 'w-vlast', name: 'Vlast.kz', nameKo: '블라스트', url: 'https://vlast.kz', country: 'KZ', group: 'asia-central', rank: 13, free: true, note: '카자흐스탄 독립 매체' },
  { id: 'w-gazetauz', name: 'Gazeta.uz', nameKo: '가제타 우즈', url: 'https://www.gazeta.uz/en/', country: 'UZ', group: 'asia-central', rank: 3, free: true },
  { id: 'w-uzdaily', name: 'UzDaily', nameKo: '우즈데일리', url: 'https://www.uzdaily.uz/en/', country: 'UZ', group: 'asia-central', rank: 12, free: true },
  { id: 'w-24kg', name: '24.kg', nameKo: '24.kg', url: 'https://24.kg/english/', country: 'KG', group: 'asia-central', rank: 2, free: true },
  { id: 'w-kloop', name: 'Kloop', nameKo: '클루프', url: 'https://kloop.asia', country: 'KG', group: 'asia-central', rank: 14, free: true, note: '키르기스스탄 탐사보도' },
  { id: 'w-asiaplus', name: 'Asia-Plus', nameKo: '아시아 플러스', url: 'https://asiaplustj.info/en', country: 'TJ', group: 'asia-central', rank: 11, free: true },
  { id: 'w-civilge', name: 'Civil.ge', nameKo: '시빌 조지아', url: 'https://civil.ge', country: 'GE', group: 'asia-central', rank: 9, free: true },
  { id: 'w-ocmedia', name: 'OC Media', nameKo: 'OC 미디어', url: 'https://oc-media.org', country: 'GE', group: 'asia-central', rank: 10, free: true, note: '코카서스 독립 저널리즘' },
  { id: 'w-armenpress', name: 'Armenpress', nameKo: '아르멘프레스', url: 'https://armenpress.am/eng/', country: 'AM', group: 'asia-central', rank: 8, free: true },
  { id: 'w-civilnet', name: 'CivilNet', nameKo: '시빌넷', url: 'https://www.civilnet.am/en/', country: 'AM', group: 'asia-central', rank: 15, free: true },
  { id: 'w-hetq', name: 'Hetq', nameKo: '헤트크', url: 'https://hetq.am/en', country: 'AM', group: 'asia-central', rank: 16, free: true, note: '아르메니아 탐사보도' },
  { id: 'w-trend', name: 'Trend News Agency', nameKo: '트렌드 통신', url: 'https://en.trend.az', country: 'AZ', group: 'asia-central', rank: 7, free: true },
  { id: 'w-eurasianet', name: 'Eurasianet', nameKo: '유라시아넷', url: 'https://eurasianet.org', country: 'US', group: 'asia-central', rank: 6, free: true, note: '중앙아시아·코카서스 전문 분석' },
  { id: 'w-timesca', name: 'The Times of Central Asia', nameKo: '타임스 오브 센트럴아시아', url: 'https://timesca.com', country: 'KZ', group: 'asia-central', rank: 17, free: true },
  { id: 'w-rferl', name: 'RFE/RL', nameKo: '자유유럽방송(RFE/RL)', url: 'https://www.rferl.org', country: 'CZ', group: 'asia-central', rank: 5, free: true, note: '구소련권 전역 취재망' },

  // ══════════════════════ 중동 ══════════════════════
  { id: 'w-aljazeera', name: 'Al Jazeera English', nameKo: '알자지라', url: 'https://www.aljazeera.com', country: 'QA', group: 'middle-east', rank: 1, rssUrl: 'https://www.aljazeera.com/xml/rss/all.xml', free: true, note: '중동 최고 영향력 매체' },
  { id: 'w-dohanews', name: 'Doha News', nameKo: '도하 뉴스', url: 'https://dohanews.co', country: 'QA', group: 'middle-east', rank: 36, free: true },
  { id: 'w-gulftimes', name: 'Gulf Times', nameKo: '걸프 타임스', url: 'https://www.gulf-times.com', country: 'QA', group: 'middle-east', rank: 23, free: true },
  { id: 'w-haaretz', name: 'Haaretz', nameKo: '하아레츠', url: 'https://www.haaretz.com', country: 'IL', group: 'middle-east', rank: 5, lean: 'progressive', note: '이스라엘 진보 고급지' },
  { id: 'w-jpost', name: 'The Jerusalem Post', nameKo: '예루살렘 포스트', url: 'https://www.jpost.com', country: 'IL', group: 'middle-east', rank: 4, free: true },
  { id: 'w-timesofisrael', name: 'The Times of Israel', nameKo: '타임스 오브 이스라엘', url: 'https://www.timesofisrael.com', country: 'IL', group: 'middle-east', rank: 3, free: true },
  { id: 'w-ynetnews', name: 'Ynetnews', nameKo: 'Ynet 뉴스', url: 'https://www.ynetnews.com', country: 'IL', group: 'middle-east', rank: 2, free: true },
  { id: 'w-i24news', name: 'i24NEWS', nameKo: 'i24 뉴스', url: 'https://www.i24news.tv/en', country: 'IL', group: 'middle-east', rank: 15, free: true },
  { id: 'w-arabnews', name: 'Arab News', nameKo: '아랍 뉴스', url: 'https://www.arabnews.com', country: 'SA', group: 'middle-east', rank: 7, free: true, note: '사우디 최초 영자 일간지' },
  { id: 'w-saudigazette', name: 'Saudi Gazette', nameKo: '사우디 가제트', url: 'https://saudigazette.com.sa', country: 'SA', group: 'middle-east', rank: 22, free: true },
  { id: 'w-alarabiya', name: 'Al Arabiya English', nameKo: '알아라비야', url: 'https://english.alarabiya.net', country: 'SA', group: 'middle-east', rank: 6, free: true },
  { id: 'w-thenationalae', name: 'The National', nameKo: '더 내셔널(UAE)', url: 'https://www.thenationalnews.com', country: 'AE', group: 'middle-east', rank: 13, free: true },
  { id: 'w-gulfnews', name: 'Gulf News', nameKo: '걸프 뉴스', url: 'https://gulfnews.com', country: 'AE', group: 'middle-east', rank: 8, free: true },
  { id: 'w-khaleejtimes', name: 'Khaleej Times', nameKo: '칼리즈 타임스', url: 'https://www.khaleejtimes.com', country: 'AE', group: 'middle-east', rank: 9, free: true },
  { id: 'w-zawya', name: 'Zawya', nameKo: '자위야', url: 'https://www.zawya.com', country: 'AE', group: 'middle-east', rank: 35, free: true, note: '중동 경제·금융 데이터' },
  { id: 'w-kuwaittimes', name: 'Kuwait Times', nameKo: '쿠웨이트 타임스', url: 'https://kuwaittimes.com', country: 'KW', group: 'middle-east', rank: 26, free: true },
  { id: 'w-tehrantimes', name: 'Tehran Times', nameKo: '테헤란 타임스', url: 'https://www.tehrantimes.com', country: 'IR', group: 'middle-east', rank: 19, free: true },
  { id: 'w-irna', name: 'IRNA', nameKo: 'IRNA 통신', url: 'https://en.irna.ir', country: 'IR', group: 'middle-east', rank: 21, free: true, note: '이란 국영 통신사' },
  { id: 'w-iranintl', name: 'Iran International', nameKo: '이란 인터내셔널', url: 'https://www.iranintl.com/en', country: 'UK', group: 'middle-east', rank: 20, free: true, note: '망명 이란 매체' },
  { id: 'w-radiofarda', name: 'Radio Farda', nameKo: '라디오 파르다', url: 'https://en.radiofarda.com', country: 'CZ', group: 'middle-east', rank: 34, free: true },
  { id: 'w-rudaw', name: 'Rudaw', nameKo: '루다우', url: 'https://www.rudaw.net/english', country: 'IQ', group: 'middle-east', rank: 18, free: true, note: '쿠르드 지역 대표 매체' },
  { id: 'w-kurdistan24', name: 'Kurdistan24', nameKo: '쿠르디스탄24', url: 'https://www.kurdistan24.net/en', country: 'IQ', group: 'middle-east', rank: 31, free: true },
  { id: 'w-hurriyetdaily', name: 'Hürriyet Daily News', nameKo: '휘리예트 데일리뉴스', url: 'https://www.hurriyetdailynews.com', country: 'TR', group: 'middle-east', rank: 11, free: true, note: '터키 최고령 영자지' },
  { id: 'w-dailysabah', name: 'Daily Sabah', nameKo: '데일리 사바', url: 'https://www.dailysabah.com', country: 'TR', group: 'middle-east', rank: 10, free: true },
  { id: 'w-anadolu', name: 'Anadolu Agency', nameKo: '아나돌루 통신', url: 'https://www.aa.com.tr/en', country: 'TR', group: 'middle-east', rank: 12, free: true, note: '터키 국영 통신사' },
  { id: 'w-duvarenglish', name: 'Duvar English', nameKo: '두바르 잉글리시', url: 'https://www.duvarenglish.com', country: 'TR', group: 'middle-east', rank: 32, free: true, note: '터키 독립 매체' },
  { id: 'w-bianet', name: 'Bianet', nameKo: '비아넷', url: 'https://bianet.org/english', country: 'TR', group: 'middle-east', rank: 33, free: true },
  { id: 'w-jordantimes', name: 'The Jordan Times', nameKo: '요르단 타임스', url: 'https://jordantimes.com', country: 'JO', group: 'middle-east', rank: 24, free: true },
  { id: 'w-lorienttoday', name: "L'Orient Today", nameKo: '로리앙 투데이', url: 'https://today.lorientlejour.com', country: 'LB', group: 'middle-east', rank: 25, free: true, note: '레바논 대표 영자 매체' },
  { id: 'w-naharnet', name: 'Naharnet', nameKo: '나하르넷', url: 'https://www.naharnet.com', country: 'LB', group: 'middle-east', rank: 28, free: true },
  { id: 'w-ahramonline', name: 'Ahram Online', nameKo: '알아흐람 온라인', url: 'https://english.ahram.org.eg', country: 'EG', group: 'middle-east', rank: 14, free: true, note: '이집트 최대 관영지 영문판' },
  { id: 'w-madamasr', name: 'Mada Masr', nameKo: '마다 마스르', url: 'https://www.madamasr.com/en/', country: 'EG', group: 'middle-east', rank: 30, free: true, note: '이집트 독립 매체' },
  { id: 'w-egyptindependent', name: 'Egypt Independent', nameKo: '이집트 인디펜던트', url: 'https://www.egyptindependent.com', country: 'EG', group: 'middle-east', rank: 29, free: true },
  { id: 'w-middleeasteye', name: 'Middle East Eye', nameKo: '미들이스트 아이', url: 'https://www.middleeasteye.net', country: 'UK', group: 'middle-east', rank: 16, free: true },
  { id: 'w-almonitor', name: 'Al-Monitor', nameKo: '알모니터', url: 'https://www.al-monitor.com', country: 'US', group: 'middle-east', rank: 17, note: '중동 정책 심층 분석' },
  { id: 'w-memo', name: 'Middle East Monitor', nameKo: '미들이스트 모니터', url: 'https://www.middleeastmonitor.com', country: 'UK', group: 'middle-east', rank: 27, free: true },
  { id: 'w-amwaj', name: 'Amwaj.media', nameKo: '암와즈 미디어', url: 'https://amwaj.media', country: 'UK', group: 'middle-east', rank: 37, free: true, note: '이란·걸프 심층 분석' },

  // ══════════════════════ 아프리카 ══════════════════════
  { id: 'w-allafrica', name: 'AllAfrica', nameKo: '올아프리카', url: 'https://allafrica.com', country: 'ZA', group: 'africa', rank: 4, free: true, note: '140여개 아프리카 매체 기사 집약' },
  { id: 'w-africanews', name: 'Africanews', nameKo: '아프리카뉴스', url: 'https://www.africanews.com', country: 'CG', group: 'africa', rank: 15, free: true, note: '유로뉴스 계열 범아프리카 채널' },
  { id: 'w-theafricareport', name: 'The Africa Report', nameKo: '디 아프리카 리포트', url: 'https://www.theafricareport.com', country: 'FR', group: 'africa', rank: 36, note: '아프리카 정치·경제 분석' },
  { id: 'w-issafrica', name: 'ISS Africa', nameKo: '아프리카 안보연구소', url: 'https://issafrica.org', country: 'ZA', group: 'africa', rank: 37, free: true, note: '분쟁·안보 리서치' },
  { id: 'w-news24', name: 'News24', nameKo: '뉴스24', url: 'https://www.news24.com', country: 'ZA', group: 'africa', rank: 1, free: true, note: '남아공 최대 뉴스 사이트' },
  { id: 'w-dailymaverick', name: 'Daily Maverick', nameKo: '데일리 매버릭', url: 'https://www.dailymaverick.co.za', country: 'ZA', group: 'africa', rank: 9, free: true, note: '남아공 탐사보도' },
  { id: 'w-mg', name: 'Mail & Guardian', nameKo: '메일 앤 가디언', url: 'https://mg.co.za', country: 'ZA', group: 'africa', rank: 16, free: true },
  { id: 'w-timeslive', name: 'TimesLIVE', nameKo: '타임스라이브', url: 'https://www.timeslive.co.za', country: 'ZA', group: 'africa', rank: 7, free: true },
  { id: 'w-iol', name: 'IOL', nameKo: 'IOL', url: 'https://www.iol.co.za', country: 'ZA', group: 'africa', rank: 6, free: true },
  { id: 'w-sabcnews', name: 'SABC News', nameKo: 'SABC 뉴스', url: 'https://www.sabcnews.com', country: 'ZA', group: 'africa', rank: 17, free: true, note: '남아공 공영방송' },
  { id: 'w-punchng', name: 'Punch', nameKo: '펀치', url: 'https://punchng.com', country: 'NG', group: 'africa', rank: 3, free: true, note: '나이지리아 최대 일간지' },
  { id: 'w-vanguardngr', name: 'Vanguard', nameKo: '뱅가드', url: 'https://www.vanguardngr.com', country: 'NG', group: 'africa', rank: 5, free: true },
  { id: 'w-premiumtimes', name: 'Premium Times', nameKo: '프리미엄 타임스', url: 'https://www.premiumtimesng.com', country: 'NG', group: 'africa', rank: 10, free: true, note: '나이지리아 탐사보도' },
  { id: 'w-guardianng', name: 'The Guardian Nigeria', nameKo: '가디언 나이지리아', url: 'https://guardian.ng', country: 'NG', group: 'africa', rank: 11, free: true },
  { id: 'w-saharareporters', name: 'Sahara Reporters', nameKo: '사하라 리포터스', url: 'https://saharareporters.com', country: 'NG', group: 'africa', rank: 20, free: true },
  { id: 'w-channelstv', name: 'Channels Television', nameKo: '채널스 TV', url: 'https://www.channelstv.com', country: 'NG', group: 'africa', rank: 14, free: true },
  { id: 'w-businessdayng', name: 'BusinessDay', nameKo: '비즈니스데이 나이지리아', url: 'https://businessday.ng', country: 'NG', group: 'africa', rank: 25, free: true },
  { id: 'w-nationafrica', name: 'Nation Africa', nameKo: '네이션 아프리카', url: 'https://nation.africa', country: 'KE', group: 'africa', rank: 2, free: true, note: '동아프리카 최대 매체' },
  { id: 'w-standardmedia', name: 'The Standard', nameKo: '더 스탠더드(케냐)', url: 'https://www.standardmedia.co.ke', country: 'KE', group: 'africa', rank: 8, free: true },
  { id: 'w-thestar-ke', name: 'The Star', nameKo: '더 스타(케냐)', url: 'https://www.the-star.co.ke', country: 'KE', group: 'africa', rank: 19, free: true },
  { id: 'w-businessdailyafrica', name: 'Business Daily Africa', nameKo: '비즈니스 데일리 아프리카', url: 'https://www.businessdailyafrica.com', country: 'KE', group: 'africa', rank: 24, free: true },
  { id: 'w-ghanaweb', name: 'GhanaWeb', nameKo: '가나웹', url: 'https://www.ghanaweb.com', country: 'GH', group: 'africa', rank: 12, free: true },
  { id: 'w-myjoyonline', name: 'MyJoyOnline', nameKo: '마이조이온라인', url: 'https://www.myjoyonline.com', country: 'GH', group: 'africa', rank: 13, free: true },
  { id: 'w-graphiconline', name: 'Graphic Online', nameKo: '그래픽 온라인', url: 'https://www.graphic.com.gh', country: 'GH', group: 'africa', rank: 21, free: true },
  { id: 'w-addisstandard', name: 'Addis Standard', nameKo: '아디스 스탠더드', url: 'https://addisstandard.com', country: 'ET', group: 'africa', rank: 32, free: true, note: '에티오피아 독립 매체' },
  { id: 'w-thereporterethiopia', name: 'The Reporter Ethiopia', nameKo: '더 리포터 에티오피아', url: 'https://www.thereporterethiopia.com', country: 'ET', group: 'africa', rank: 33, free: true },
  { id: 'w-moroccoworldnews', name: 'Morocco World News', nameKo: '모로코 월드 뉴스', url: 'https://www.moroccoworldnews.com', country: 'MA', group: 'africa', rank: 30, free: true },
  { id: 'w-hespress', name: 'Hespress English', nameKo: '헤스프레스', url: 'https://en.hespress.com', country: 'MA', group: 'africa', rank: 31, free: true },
  { id: 'w-thecitizen-tz', name: 'The Citizen', nameKo: '더 시티즌(탄자니아)', url: 'https://www.thecitizen.co.tz', country: 'TZ', group: 'africa', rank: 23, free: true },
  { id: 'w-monitor-ug', name: 'Daily Monitor', nameKo: '데일리 모니터', url: 'https://www.monitor.co.ug', country: 'UG', group: 'africa', rank: 18, free: true },
  { id: 'w-newvision', name: 'New Vision', nameKo: '뉴 비전', url: 'https://www.newvision.co.ug', country: 'UG', group: 'africa', rank: 22, free: true },
  { id: 'w-newsday-zw', name: 'NewsDay', nameKo: '뉴스데이(짐바브웨)', url: 'https://www.newsday.co.zw', country: 'ZW', group: 'africa', rank: 26, free: true },
  { id: 'w-zimlive', name: 'ZimLive', nameKo: '짐라이브', url: 'https://www.zimlive.com', country: 'ZW', group: 'africa', rank: 29, free: true },
  { id: 'w-newtimes-rw', name: 'The New Times', nameKo: '더 뉴 타임스(르완다)', url: 'https://www.newtimes.co.rw', country: 'RW', group: 'africa', rank: 27, free: true },
  { id: 'w-lusakatimes', name: 'Lusaka Times', nameKo: '루사카 타임스', url: 'https://www.lusakatimes.com', country: 'ZM', group: 'africa', rank: 28, free: true },
  { id: 'w-elwatan', name: 'El Watan', nameKo: '엘 와탄', url: 'https://elwatan-dz.com', country: 'DZ', group: 'africa', rank: 34, free: true },
  { id: 'w-aps-sn', name: 'APS Sénégal', nameKo: 'APS 세네갈', url: 'https://aps.sn', country: 'SN', group: 'africa', rank: 35, free: true },

  // ══════════════════════ 오세아니아 ══════════════════════
  { id: 'w-abcau', name: 'ABC News Australia', nameKo: 'ABC 뉴스 호주', url: 'https://www.abc.net.au/news', country: 'AU', group: 'oceania', rank: 1, rssUrl: 'https://www.abc.net.au/news/feed/2942460/rss.xml', free: true, note: '호주 공영방송' },
  { id: 'w-smh', name: 'The Sydney Morning Herald', nameKo: '시드니 모닝 헤럴드', url: 'https://www.smh.com.au', country: 'AU', group: 'oceania', rank: 3 },
  { id: 'w-theage', name: 'The Age', nameKo: '디 에이지', url: 'https://www.theage.com.au', country: 'AU', group: 'oceania', rank: 6, note: '멜버른 대표지' },
  { id: 'w-theaustralian', name: 'The Australian', nameKo: '디 오스트레일리안', url: 'https://www.theaustralian.com.au', country: 'AU', group: 'oceania', rank: 11, lean: 'conservative', note: '호주 유일 전국 일간지' },
  { id: 'w-afr', name: 'Australian Financial Review', nameKo: '오스트레일리안 파이낸셜 리뷰', url: 'https://www.afr.com', country: 'AU', group: 'oceania', rank: 14, note: '호주 대표 경제지' },
  { id: 'w-newscomau', name: 'news.com.au', nameKo: '뉴스닷컴', url: 'https://www.news.com.au', country: 'AU', group: 'oceania', rank: 2, free: true },
  { id: 'w-heraldsun', name: 'Herald Sun', nameKo: '헤럴드 선', url: 'https://www.heraldsun.com.au', country: 'AU', group: 'oceania', rank: 7 },
  { id: 'w-9news', name: '9News', nameKo: '나인 뉴스', url: 'https://www.9news.com.au', country: 'AU', group: 'oceania', rank: 4, free: true },
  { id: 'w-dailytelegraphau', name: 'The Daily Telegraph', nameKo: '데일리 텔레그래프(호주)', url: 'https://www.dailytelegraph.com.au', country: 'AU', group: 'oceania', rank: 10 },
  { id: 'w-guardianau', name: 'Guardian Australia', nameKo: '가디언 오스트레일리아', url: 'https://www.theguardian.com/au', country: 'AU', group: 'oceania', rank: 9, free: true },
  { id: 'w-sbsnews', name: 'SBS News', nameKo: 'SBS 뉴스(호주)', url: 'https://www.sbs.com.au/news', country: 'AU', group: 'oceania', rank: 12, free: true },
  { id: 'w-crikey', name: 'Crikey', nameKo: '크라이키', url: 'https://www.crikey.com.au', country: 'AU', group: 'oceania', rank: 18 },
  { id: 'w-conversationau', name: 'The Conversation', nameKo: '더 컨버세이션', url: 'https://theconversation.com', country: 'AU', group: 'oceania', rank: 15, free: true, note: '학자가 직접 쓰는 해설 매체' },
  { id: 'w-nzherald', name: 'The New Zealand Herald', nameKo: '뉴질랜드 헤럴드', url: 'https://www.nzherald.co.nz', country: 'NZ', group: 'oceania', rank: 5, free: true },
  { id: 'w-rnz', name: 'RNZ', nameKo: '라디오 뉴질랜드', url: 'https://www.rnz.co.nz/news', country: 'NZ', group: 'oceania', rank: 13, free: true },
  { id: 'w-stuff', name: 'Stuff', nameKo: '스터프', url: 'https://www.stuff.co.nz', country: 'NZ', group: 'oceania', rank: 8, free: true },
  { id: 'w-newsroom-nz', name: 'Newsroom', nameKo: '뉴스룸(뉴질랜드)', url: 'https://newsroom.co.nz', country: 'NZ', group: 'oceania', rank: 17, free: true },
  { id: 'w-thespinoff', name: 'The Spinoff', nameKo: '더 스핀오프', url: 'https://thespinoff.co.nz', country: 'NZ', group: 'oceania', rank: 16, free: true },
  { id: 'w-fijitimes', name: 'The Fiji Times', nameKo: '피지 타임스', url: 'https://www.fijitimes.com.fj', country: 'FJ', group: 'oceania', rank: 19, free: true },
  { id: 'w-postcourier', name: 'Post-Courier', nameKo: '포스트 쿠리어', url: 'https://www.postcourier.com.pg', country: 'PG', group: 'oceania', rank: 20, free: true },

  // ══════════════════════ 캐나다 ══════════════════════
  { id: 'w-cbc', name: 'CBC News', nameKo: 'CBC 뉴스', url: 'https://www.cbc.ca/news', country: 'CA', group: 'northam', rank: 1, rssUrl: 'https://www.cbc.ca/webfeed/rss/rss-topstories', free: true, note: '캐나다 공영방송' },
  { id: 'w-globeandmail', name: 'The Globe and Mail', nameKo: '글로브 앤 메일', url: 'https://www.theglobeandmail.com', country: 'CA', group: 'northam', rank: 5, note: '캐나다 기록신문' },
  { id: 'w-nationalpost', name: 'National Post', nameKo: '내셔널 포스트', url: 'https://nationalpost.com', country: 'CA', group: 'northam', rank: 6, lean: 'conservative' },
  { id: 'w-torontostar', name: 'Toronto Star', nameKo: '토론토 스타', url: 'https://www.thestar.com', country: 'CA', group: 'northam', rank: 4, lean: 'progressive' },
  { id: 'w-ctvnews', name: 'CTV News', nameKo: 'CTV 뉴스', url: 'https://www.ctvnews.ca', country: 'CA', group: 'northam', rank: 2, free: true },
  { id: 'w-globalnews', name: 'Global News', nameKo: '글로벌 뉴스', url: 'https://globalnews.ca', country: 'CA', group: 'northam', rank: 3, free: true },
  { id: 'w-lapresse', name: 'La Presse', nameKo: '라 프레스', url: 'https://www.lapresse.ca', country: 'CA', group: 'northam', rank: 7, free: true, note: '퀘벡 대표 불어 매체' },
  { id: 'w-ledevoir', name: 'Le Devoir', nameKo: '르 드부아르', url: 'https://www.ledevoir.com', country: 'CA', group: 'northam', rank: 9 },
  { id: 'w-financialpost', name: 'Financial Post', nameKo: '파이낸셜 포스트', url: 'https://financialpost.com', country: 'CA', group: 'northam', rank: 8, free: true },
  { id: 'w-thetyee', name: 'The Tyee', nameKo: '더 타이이', url: 'https://thetyee.ca', country: 'CA', group: 'northam', rank: 10, free: true, note: '독립 탐사보도' },
  { id: 'w-narwhal', name: 'The Narwhal', nameKo: '더 나왈', url: 'https://thenarwhal.ca', country: 'CA', group: 'northam', rank: 11, free: true, note: '환경 전문 비영리' },

  // ══════════════════════ 중남미 ══════════════════════
  { id: 'w-folha', name: 'Folha de S.Paulo', nameKo: '폴랴 지 상파울루', url: 'https://www1.folha.uol.com.br/internacional/en/', country: 'BR', group: 'latam', rank: 5, free: true, note: '브라질 최대 신문 영문판' },
  { id: 'w-oglobo', name: 'O Globo', nameKo: '오 글로부', url: 'https://oglobo.globo.com', country: 'BR', group: 'latam', rank: 4 },
  { id: 'w-estadao', name: 'Estadão', nameKo: '이스타당', url: 'https://www.estadao.com.br', country: 'BR', group: 'latam', rank: 6 },
  { id: 'w-g1', name: 'G1', nameKo: 'G1', url: 'https://g1.globo.com', country: 'BR', group: 'latam', rank: 1, free: true, note: '브라질 최대 뉴스 포털' },
  { id: 'w-valor', name: 'Valor Econômico', nameKo: '발로르 이코노미쿠', url: 'https://valor.globo.com', country: 'BR', group: 'latam', rank: 22, note: '브라질 대표 경제지' },
  { id: 'w-agenciabrasil', name: 'Agência Brasil', nameKo: '아젠시아 브라질', url: 'https://agenciabrasil.ebc.com.br/en', country: 'BR', group: 'latam', rank: 33, free: true },
  { id: 'w-brazilianreport', name: 'The Brazilian Report', nameKo: '브라질리안 리포트', url: 'https://brazilian.report', country: 'BR', group: 'latam', rank: 38, note: '브라질 정치·경제 영어 분석' },
  { id: 'w-clarin', name: 'Clarín', nameKo: '클라린', url: 'https://www.clarin.com', country: 'AR', group: 'latam', rank: 2, free: true, note: '중남미 최대 발행부수' },
  { id: 'w-lanacion-ar', name: 'La Nación', nameKo: '라 나시온', url: 'https://www.lanacion.com.ar', country: 'AR', group: 'latam', rank: 10 },
  { id: 'w-infobae', name: 'Infobae', nameKo: '인포바에', url: 'https://www.infobae.com', country: 'AR', group: 'latam', rank: 3, free: true },
  { id: 'w-pagina12', name: 'Página/12', nameKo: '파히나 12', url: 'https://www.pagina12.com.ar', country: 'AR', group: 'latam', rank: 20, free: true, lean: 'progressive' },
  { id: 'w-batimes', name: 'Buenos Aires Times', nameKo: '부에노스아이레스 타임스', url: 'https://www.batimes.com.ar', country: 'AR', group: 'latam', rank: 36, free: true },
  { id: 'w-emol', name: 'Emol (El Mercurio)', nameKo: '엘 메르쿠리오', url: 'https://www.emol.com', country: 'CL', group: 'latam', rank: 11, free: true, note: '칠레 최고령 일간지' },
  { id: 'w-latercera', name: 'La Tercera', nameKo: '라 테르세라', url: 'https://www.latercera.com', country: 'CL', group: 'latam', rank: 12, free: true },
  { id: 'w-biobiochile', name: 'BioBioChile', nameKo: '비오비오칠레', url: 'https://www.biobiochile.cl', country: 'CL', group: 'latam', rank: 15, free: true },
  { id: 'w-ciper', name: 'CIPER Chile', nameKo: '시페르 칠레', url: 'https://www.ciperchile.cl', country: 'CL', group: 'latam', rank: 35, free: true, note: '칠레 탐사보도' },
  { id: 'w-eltiempo', name: 'El Tiempo', nameKo: '엘 티엠포', url: 'https://www.eltiempo.com', country: 'CO', group: 'latam', rank: 8, free: true, note: '콜롬비아 최대 일간지' },
  { id: 'w-elespectador', name: 'El Espectador', nameKo: '엘 에스펙타도르', url: 'https://www.elespectador.com', country: 'CO', group: 'latam', rank: 14, free: true },
  { id: 'w-semana', name: 'Semana', nameKo: '세마나', url: 'https://www.semana.com', country: 'CO', group: 'latam', rank: 17, free: true },
  { id: 'w-lasillavacia', name: 'La Silla Vacía', nameKo: '라 시야 바시아', url: 'https://www.lasillavacia.com', country: 'CO', group: 'latam', rank: 34, free: true, note: '콜롬비아 정치 심층' },
  { id: 'w-elcomercio-pe', name: 'El Comercio', nameKo: '엘 코메르시오(페루)', url: 'https://elcomercio.pe', country: 'PE', group: 'latam', rank: 13, free: true, note: '페루 최대 언론그룹' },
  { id: 'w-gestion', name: 'Gestión', nameKo: '헤스티온', url: 'https://gestion.pe', country: 'PE', group: 'latam', rank: 23, free: true, note: '페루 경제지' },
  { id: 'w-larepublica-pe', name: 'La República', nameKo: '라 레푸블리카(페루)', url: 'https://larepublica.pe', country: 'PE', group: 'latam', rank: 18, free: true },
  { id: 'w-reforma', name: 'Reforma', nameKo: '레포르마', url: 'https://www.reforma.com', country: 'MX', group: 'latam', rank: 19, note: '멕시코 대표 일간지' },
  { id: 'w-eluniversal-mx', name: 'El Universal', nameKo: '엘 우니베르살', url: 'https://www.eluniversal.com.mx', country: 'MX', group: 'latam', rank: 7, free: true },
  { id: 'w-lajornada', name: 'La Jornada', nameKo: '라 호르나다', url: 'https://www.jornada.com.mx', country: 'MX', group: 'latam', rank: 16, free: true, lean: 'progressive' },
  { id: 'w-milenio', name: 'Milenio', nameKo: '밀레니오', url: 'https://www.milenio.com', country: 'MX', group: 'latam', rank: 9, free: true },
  { id: 'w-animalpolitico', name: 'Animal Político', nameKo: '아니말 폴리티코', url: 'https://animalpolitico.com', country: 'MX', group: 'latam', rank: 25, free: true, note: '멕시코 탐사보도' },
  { id: 'w-mexiconewsdaily', name: 'Mexico News Daily', nameKo: '멕시코 뉴스 데일리', url: 'https://mexiconewsdaily.com', country: 'MX', group: 'latam', rank: 37, free: true },
  { id: 'w-aristegui', name: 'Aristegui Noticias', nameKo: '아리스테기 노티시아스', url: 'https://aristeguinoticias.com', country: 'MX', group: 'latam', rank: 24, free: true },
  { id: 'w-efectococuyo', name: 'Efecto Cocuyo', nameKo: '에펙토 코쿠요', url: 'https://efectococuyo.com', country: 'VE', group: 'latam', rank: 39, free: true, note: '베네수엘라 독립 매체' },
  { id: 'w-caracaschronicles', name: 'Caracas Chronicles', nameKo: '카라카스 크로니클스', url: 'https://www.caracaschronicles.com', country: 'VE', group: 'latam', rank: 40, free: true },
  { id: 'w-elpais-uy', name: 'El País', nameKo: '엘 파이스(우루과이)', url: 'https://www.elpais.com.uy', country: 'UY', group: 'latam', rank: 27, free: true },
  { id: 'w-mercopress', name: 'MercoPress', nameKo: '메르코프레스', url: 'https://en.mercopress.com', country: 'UY', group: 'latam', rank: 43, free: true, note: '남미 영자 뉴스' },
  { id: 'w-eluniverso', name: 'El Universo', nameKo: '엘 우니베르소', url: 'https://www.eluniverso.com', country: 'EC', group: 'latam', rank: 21, free: true },
  { id: 'w-primicias', name: 'Primicias', nameKo: '프리미시아스', url: 'https://www.primicias.ec', country: 'EC', group: 'latam', rank: 26, free: true },
  { id: 'w-eldeber', name: 'El Deber', nameKo: '엘 데베르', url: 'https://eldeber.com.bo', country: 'BO', group: 'latam', rank: 28, free: true },
  { id: 'w-ultimahora', name: 'Última Hora', nameKo: '울티마 오라', url: 'https://www.ultimahora.com', country: 'PY', group: 'latam', rank: 29, free: true },
  { id: 'w-14ymedio', name: '14ymedio', nameKo: '14이메디오', url: 'https://www.14ymedio.com', country: 'CU', group: 'latam', rank: 41, free: true, note: '쿠바 독립 매체' },
  { id: 'w-ticotimes', name: 'The Tico Times', nameKo: '티코 타임스', url: 'https://ticotimes.net', country: 'CR', group: 'latam', rank: 42, free: true },
  { id: 'w-laprensa-pa', name: 'La Prensa', nameKo: '라 프렌사(파나마)', url: 'https://www.prensa.com', country: 'PA', group: 'latam', rank: 32, free: true },
  { id: 'w-diariolibre', name: 'Diario Libre', nameKo: '디아리오 리브레', url: 'https://www.diariolibre.com', country: 'DO', group: 'latam', rank: 30, free: true },
  { id: 'w-prensalibre', name: 'Prensa Libre', nameKo: '프렌사 리브레', url: 'https://www.prensalibre.com', country: 'GT', group: 'latam', rank: 31, free: true },
  { id: 'w-insightcrime', name: 'InSight Crime', nameKo: '인사이트 크라임', url: 'https://insightcrime.org', country: 'US', group: 'latam', rank: 44, free: true, note: '중남미 조직범죄 전문 분석' },
  { id: 'w-americasquarterly', name: 'Americas Quarterly', nameKo: '아메리카스 쿼털리', url: 'https://www.americasquarterly.org', country: 'US', group: 'latam', rank: 45, note: '미주 지역 정책지' },
];
