import { DirectorySite } from '@/types/directory';

/**
 * 국내 뉴스·전문 매체 디렉토리.
 * lekohoo.com 국내 카테고리 페이지(종합/경제/주식/코인/부동산/방송/포털/사설/만평/
 * 진보·보수/탐사/언론/IT/AI/과학/의학/건강/산업/국방/게임/자동차/스포츠/연예/법률/
 * 세무/환경/농업/북한/문화/커뮤니티)를 전수 수집해 정리했다.
 *
 * 중복 주의: 종합일간지는 kr-daily에만 두고 성향은 lean 필드로 표기한다.
 * kr-progressive / kr-conservative에는 종합지에 없는 매체만 넣는다.
 */
export const KR_DIRECTORY_SITES: DirectorySite[] = [
  // ─────────────────────── 종합일간지 ───────────────────────
  { id: 'kr-chosun', name: 'Chosun Ilbo', nameKo: '조선일보', url: 'https://www.chosun.com', country: 'KR', group: 'kr-daily', rank: 1, free: true, lean: 'conservative', note: '발행부수 1위 종합일간지' },
  { id: 'kr-joongang', name: 'JoongAng Ilbo', nameKo: '중앙일보', url: 'https://www.joongang.co.kr', country: 'KR', group: 'kr-daily', rank: 2, free: true, lean: 'conservative' },
  { id: 'kr-donga', name: 'Dong-A Ilbo', nameKo: '동아일보', url: 'https://www.donga.com', country: 'KR', group: 'kr-daily', rank: 3, free: true, lean: 'conservative' },
  { id: 'kr-hani', name: 'Hankyoreh', nameKo: '한겨레', url: 'https://www.hani.co.kr', country: 'KR', group: 'kr-daily', rank: 4, free: true, lean: 'progressive', note: '국민주 방식으로 창간된 진보지' },
  { id: 'kr-khan', name: 'Kyunghyang Shinmun', nameKo: '경향신문', url: 'https://www.khan.co.kr', country: 'KR', group: 'kr-daily', rank: 5, free: true, lean: 'progressive' },
  { id: 'kr-hankookilbo', name: 'Hankook Ilbo', nameKo: '한국일보', url: 'https://www.hankookilbo.com', country: 'KR', group: 'kr-daily', rank: 6, free: true, lean: 'center' },
  { id: 'kr-seoul', name: 'Seoul Shinmun', nameKo: '서울신문', url: 'https://www.seoul.co.kr', country: 'KR', group: 'kr-daily', rank: 7, free: true, lean: 'center' },
  { id: 'kr-munhwa', name: 'Munhwa Ilbo', nameKo: '문화일보', url: 'https://www.munhwa.com', country: 'KR', group: 'kr-daily', rank: 10, free: true, lean: 'conservative', note: '국내 유일 석간 종합지' },
  { id: 'kr-segye', name: 'Segye Ilbo', nameKo: '세계일보', url: 'https://www.segye.com', country: 'KR', group: 'kr-daily', rank: 9, free: true, lean: 'center' },
  { id: 'kr-kmib', name: 'Kukmin Ilbo', nameKo: '국민일보', url: 'https://www.kmib.co.kr', country: 'KR', group: 'kr-daily', rank: 8, free: true, lean: 'center' },

  // ─────────────────────── 방송뉴스 ───────────────────────
  { id: 'kr-kbs', name: 'KBS News', nameKo: 'KBS 뉴스', url: 'https://news.kbs.co.kr', country: 'KR', group: 'kr-broadcast', rank: 2, free: true, note: '공영방송' },
  { id: 'kr-mbc', name: 'MBC News', nameKo: 'MBC 뉴스', url: 'https://imnews.imbc.com', country: 'KR', group: 'kr-broadcast', rank: 3, free: true },
  { id: 'kr-sbs', name: 'SBS News', nameKo: 'SBS 뉴스', url: 'https://news.sbs.co.kr', country: 'KR', group: 'kr-broadcast', rank: 1, free: true },
  { id: 'kr-ytn', name: 'YTN', nameKo: 'YTN', url: 'https://www.ytn.co.kr', country: 'KR', group: 'kr-broadcast', rank: 4, free: true, note: '24시간 보도 전문 채널' },
  { id: 'kr-jtbc', name: 'JTBC News', nameKo: 'JTBC 뉴스', url: 'https://news.jtbc.co.kr', country: 'KR', group: 'kr-broadcast', rank: 5, free: true },
  { id: 'kr-tvchosun', name: 'TV Chosun', nameKo: 'TV조선 뉴스', url: 'https://news.tvchosun.com', country: 'KR', group: 'kr-broadcast', rank: 7, free: true, lean: 'conservative' },
  { id: 'kr-channela', name: 'Channel A', nameKo: '채널A 뉴스', url: 'https://ichannela.com', country: 'KR', group: 'kr-broadcast', rank: 8, free: true, lean: 'conservative' },
  { id: 'kr-mbn', name: 'MBN', nameKo: 'MBN 뉴스', url: 'https://www.mbn.co.kr/news/', country: 'KR', group: 'kr-broadcast', rank: 6, free: true, lean: 'conservative' },
  { id: 'kr-nocutnews', name: 'Nocut News', nameKo: '노컷뉴스', url: 'https://www.nocutnews.co.kr', country: 'KR', group: 'kr-broadcast', rank: 9, free: true, lean: 'progressive', note: 'CBS 계열' },

  // ─────────────────────── 포털뉴스 ───────────────────────
  { id: 'kr-navernews', name: 'Naver News', nameKo: '네이버 뉴스', url: 'https://news.naver.com', country: 'KR', group: 'kr-portal', rank: 1, free: true, note: '국내 최대 뉴스 유통 채널' },
  { id: 'kr-daumnews', name: 'Daum News', nameKo: '다음 뉴스', url: 'https://news.daum.net', country: 'KR', group: 'kr-portal', rank: 2, free: true },
  { id: 'kr-natenews', name: 'Nate News', nameKo: '네이트 뉴스', url: 'https://news.nate.com', country: 'KR', group: 'kr-portal', rank: 4, free: true },
  { id: 'kr-zumnews', name: 'Zum News', nameKo: '줌 뉴스', url: 'https://news.zum.com', country: 'KR', group: 'kr-portal', rank: 8, free: true },
  { id: 'kr-googlenews', name: 'Google News Korea', nameKo: '구글 뉴스(한국)', url: 'https://news.google.com/?hl=ko&gl=KR', country: 'KR', group: 'kr-portal', rank: 7, free: true },
  { id: 'kr-news1', name: 'News1', nameKo: '뉴스1', url: 'https://www.news1.kr', country: 'KR', group: 'kr-portal', rank: 5, free: true, note: '민영 뉴스통신사' },
  { id: 'kr-newsis', name: 'Newsis', nameKo: '뉴시스', url: 'https://www.newsis.com', country: 'KR', group: 'kr-portal', rank: 6, free: true, note: '민영 뉴스통신사' },
  { id: 'kr-yna', name: 'Yonhap News', nameKo: '연합뉴스', url: 'https://www.yna.co.kr', country: 'KR', group: 'kr-portal', rank: 3, free: true, note: '국가기간 뉴스통신사' },

  // ─────────────────────── 경제지 ───────────────────────
  { id: 'kr-hankyung', name: 'Korea Economic Daily', nameKo: '한국경제', url: 'https://www.hankyung.com', country: 'KR', group: 'kr-economy', rank: 1, free: true, note: '양대 경제지' },
  { id: 'kr-mk', name: 'Maeil Business', nameKo: '매일경제', url: 'https://www.mk.co.kr', country: 'KR', group: 'kr-economy', rank: 2, free: true, note: '양대 경제지' },
  { id: 'kr-sedaily', name: 'Seoul Economic Daily', nameKo: '서울경제', url: 'https://www.sedaily.com', country: 'KR', group: 'kr-economy', rank: 3, free: true },
  { id: 'kr-mt', name: 'Money Today', nameKo: '머니투데이', url: 'https://www.mt.co.kr', country: 'KR', group: 'kr-economy', rank: 4, free: true },
  { id: 'kr-edaily', name: 'Edaily', nameKo: '이데일리', url: 'https://www.edaily.co.kr', country: 'KR', group: 'kr-economy', rank: 5, free: true },
  { id: 'kr-einfomax', name: 'Yonhap Infomax', nameKo: '연합인포맥스', url: 'https://news.einfomax.co.kr', country: 'KR', group: 'kr-economy', rank: 6, free: true, note: '채권·외환 등 금융시장 전문' },
  { id: 'kr-asiae', name: 'Asia Economy', nameKo: '아시아경제', url: 'https://www.asiae.co.kr', country: 'KR', group: 'kr-economy', rank: 7, free: true },
  { id: 'kr-bizchosun', name: 'ChosunBiz', nameKo: '조선비즈', url: 'https://biz.chosun.com', country: 'KR', group: 'kr-economy', rank: 8, free: true },
  { id: 'kr-fnnews', name: 'Financial News', nameKo: '파이낸셜뉴스', url: 'https://www.fnnews.com', country: 'KR', group: 'kr-economy', rank: 9, free: true },
  { id: 'kr-etoday', name: 'Etoday', nameKo: '이투데이', url: 'https://www.etoday.co.kr', country: 'KR', group: 'kr-economy', rank: 10, free: true },
  { id: 'kr-ajunews', name: 'Aju Business Daily', nameKo: '아주경제', url: 'https://www.ajunews.com', country: 'KR', group: 'kr-economy', rank: 11, free: true },
  { id: 'kr-bizwatch', name: 'BizWatch', nameKo: '비즈워치', url: 'https://www.bizwatch.co.kr', country: 'KR', group: 'kr-economy', rank: 12, free: true },
  { id: 'kr-heraldbiz', name: 'Herald Economy', nameKo: '헤럴드경제', url: 'https://biz.heraldcorp.com', country: 'KR', group: 'kr-economy', rank: 13, free: true },
  { id: 'kr-economist', name: 'Economist Korea', nameKo: '이코노미스트', url: 'https://economist.co.kr', country: 'KR', group: 'kr-economy', rank: 14, free: true },
  { id: 'kr-econovill', name: 'Economic Review', nameKo: '이코노믹리뷰', url: 'https://www.econovill.com', country: 'KR', group: 'kr-economy', rank: 15, free: true },
  { id: 'kr-fortunekorea', name: 'Fortune Korea', nameKo: '포춘코리아', url: 'https://www.fortunekorea.co.kr', country: 'KR', group: 'kr-economy', rank: 16, free: true },
  { id: 'kr-viva100', name: 'Bridge Economy', nameKo: '브릿지경제', url: 'https://www.viva100.com', country: 'KR', group: 'kr-economy', rank: 17, free: true },
  { id: 'kr-hansbiz', name: 'Hans Economy', nameKo: '한스경제', url: 'https://www.hansbiz.co.kr', country: 'KR', group: 'kr-economy', rank: 18, free: true },
  { id: 'kr-ebn', name: 'EBN', nameKo: 'EBN 산업경제', url: 'https://www.ebn.co.kr', country: 'KR', group: 'kr-economy', rank: 19, free: true },
  { id: 'kr-newsprime', name: 'Prime Economy', nameKo: '프라임경제', url: 'https://www.newsprime.co.kr', country: 'KR', group: 'kr-economy', rank: 20, free: true },
  { id: 'kr-dnews', name: 'Daehan Economy', nameKo: 'e대한경제', url: 'https://www.dnews.co.kr', country: 'KR', group: 'kr-economy', rank: 21, free: true, note: '건설·SOC에 강함' },

  // ─────────────────────── 증시·투자 ───────────────────────
  { id: 'kr-naverfinance', name: 'Naver Finance', nameKo: '네이버 증권', url: 'https://finance.naver.com', country: 'KR', group: 'kr-stock', rank: 1, free: true, note: '국내 개인투자자 표준 시세 화면' },
  { id: 'kr-daumfinance', name: 'Daum Finance', nameKo: '다음 증권', url: 'https://m.finance.daum.net', country: 'KR', group: 'kr-stock', rank: 2, free: true },
  { id: 'kr-krxdata', name: 'KRX Data', nameKo: 'KRX 정보데이터시스템', url: 'http://data.krx.co.kr', country: 'KR', group: 'kr-stock', rank: 4, free: true, note: '한국거래소 공식 원본 데이터' },
  { id: 'kr-dart', name: 'DART', nameKo: '전자공시시스템 DART', url: 'https://dart.fss.or.kr', country: 'KR', group: 'kr-stock', rank: 3, free: true, note: '국내 상장사 공시 원본' },
  { id: 'kr-mkstock', name: 'MK Market', nameKo: '매경 마켓', url: 'https://stock.mk.co.kr', country: 'KR', group: 'kr-stock', rank: 10, free: true },
  { id: 'kr-hkkoreamarket', name: 'Hankyung Korea Market', nameKo: '한경 코리아마켓', url: 'https://www.hankyung.com/koreamarket/', country: 'KR', group: 'kr-stock', rank: 11, free: true },
  { id: 'kr-hkglobalmarket', name: 'Hankyung Global Market', nameKo: '한경 글로벌마켓', url: 'https://www.hankyung.com/globalmarket/', country: 'KR', group: 'kr-stock', rank: 12, free: true },
  { id: 'kr-investingkr', name: 'Investing.com Korea', nameKo: '인베스팅닷컴(한국)', url: 'https://kr.investing.com', country: 'KR', group: 'kr-stock', rank: 5, free: true },
  { id: 'kr-tradingviewkr', name: 'TradingView Korea', nameKo: '트레이딩뷰(한국)', url: 'https://kr.tradingview.com/markets/', country: 'KR', group: 'kr-stock', rank: 6, free: true },
  { id: 'kr-tvheatmap', name: 'TradingView Heatmap', nameKo: '트레이딩뷰 히트맵', url: 'https://kr.tradingview.com/heatmap/stock/', country: 'KR', group: 'kr-stock', rank: 7, free: true, note: '시장 전체를 한 화면에' },
  { id: 'kr-stockplus', name: 'Stockplus', nameKo: '증권플러스', url: 'https://stockplus.com', country: 'KR', group: 'kr-stock', rank: 13, free: true },
  { id: 'kr-kospd', name: 'KOSPD', nameKo: 'KOSPD', url: 'https://kospd.com', country: 'KR', group: 'kr-stock', rank: 14, free: true },
  { id: 'kr-googlefinance', name: 'Google Finance', nameKo: '구글 파이낸스', url: 'https://www.google.com/finance/', country: 'KR', group: 'kr-stock', rank: 8, free: true },
  { id: 'kr-finvizmap', name: 'Finviz Map', nameKo: '핀비즈 맵', url: 'https://finviz.com/map.ashx', country: 'KR', group: 'kr-stock', rank: 9, free: true, note: '미국 증시 히트맵' },

  // ─────────────────────── 코인 ───────────────────────
  { id: 'kr-blockmedia', name: 'Block Media', nameKo: '블록미디어', url: 'https://www.blockmedia.co.kr', country: 'KR', group: 'kr-crypto', rank: 1, free: true },
  { id: 'kr-coinness', name: 'Coinness', nameKo: '코인니스', url: 'https://coinness.live', country: 'KR', group: 'kr-crypto', rank: 2, free: true, note: '실시간 속보 피드' },
  { id: 'kr-tokenpost', name: 'TokenPost', nameKo: '토큰포스트', url: 'https://www.tokenpost.kr', country: 'KR', group: 'kr-crypto', rank: 3, free: true },
  { id: 'kr-bloomingbit', name: 'BloomingBit', nameKo: '블루밍비트', url: 'https://bloomingbit.io', country: 'KR', group: 'kr-crypto', rank: 4, free: true, note: '두나무 운영' },
  { id: 'kr-coindeskkr', name: 'CoinDesk Korea', nameKo: '코인데스크 코리아', url: 'https://www.coindesk.com/ko', country: 'KR', group: 'kr-crypto', rank: 5, free: true },
  { id: 'kr-coinreaders', name: 'CoinReaders', nameKo: '코인리더스', url: 'https://coinreaders.com', country: 'KR', group: 'kr-crypto', rank: 6, free: true },
  { id: 'kr-decenter', name: 'Decenter', nameKo: '디센터', url: 'https://www.decenter.kr', country: 'KR', group: 'kr-crypto', rank: 7, free: true, note: '서울경제 계열' },
  { id: 'kr-cryptohub', name: 'CryptoHub', nameKo: '크립토허브', url: 'https://www.cryptohub.or.kr', country: 'KR', group: 'kr-crypto', rank: 8, free: true },
  { id: 'kr-cryptonewskr', name: 'CryptoNews Korea', nameKo: '크립토뉴스(한국)', url: 'https://kr.cryptonews.com', country: 'KR', group: 'kr-crypto', rank: 9, free: true },
  { id: 'kr-investingcrypto', name: 'Investing Crypto', nameKo: '인베스팅 암호화폐', url: 'https://kr.investing.com/news/cryptocurrency-news', country: 'KR', group: 'kr-crypto', rank: 10, free: true },
  { id: 'kr-blockchaintoday', name: 'Blockchain Today', nameKo: '블록체인투데이', url: 'http://www.blockchaintoday.co.kr', country: 'KR', group: 'kr-crypto', rank: 11, free: true },

  // ─────────────────────── 부동산 ───────────────────────
  { id: 'kr-jipconomy', name: 'Jipconomy', nameKo: '집코노미', url: 'https://www.hankyung.com/realestate', country: 'KR', group: 'kr-realestate', rank: 1, free: true, note: '한국경제 부동산' },
  { id: 'kr-realtychosun', name: 'Ddangjipgo', nameKo: '땅집고', url: 'http://realty.chosun.com', country: 'KR', group: 'kr-realestate', rank: 2, free: true, note: '조선일보 부동산' },
  { id: 'kr-naverland', name: 'Naver Real Estate', nameKo: '네이버 부동산', url: 'https://land.naver.com/news/', country: 'KR', group: 'kr-realestate', rank: 3, free: true },
  { id: 'kr-jipsulang', name: 'Jipsulang', nameKo: '집슐랭', url: 'https://www.sedaily.com/realestate', country: 'KR', group: 'kr-realestate', rank: 4, free: true, note: '서울경제 부동산' },
  { id: 'kr-arunews', name: 'Korea Housing Economy', nameKo: '한국주택경제신문', url: 'https://www.arunews.com', country: 'KR', group: 'kr-realestate', rank: 5, free: true, note: '재건축·재개발 전문' },
  { id: 'kr-karnews', name: 'Korea Real Estate News', nameKo: '한국부동산뉴스', url: 'https://www.karnews.or.kr', country: 'KR', group: 'kr-realestate', rank: 6, free: true },
  { id: 'kr-r114', name: 'R114', nameKo: '부동산114', url: 'https://www.r114.com/?_c=research', country: 'KR', group: 'kr-realestate', rank: 7, free: true, note: '시세·리서치 데이터' },
  { id: 'kr-mkrealestate', name: 'MK Real Estate', nameKo: '매일경제 부동산', url: 'https://www.mk.co.kr/news/realestate', country: 'KR', group: 'kr-realestate', rank: 8, free: true },
  { id: 'kr-mtrealestate', name: 'MT Real Estate', nameKo: '머니투데이 부동산', url: 'https://news.mt.co.kr/newsList.html?pDepth1=estate&pDepth2=Etotal', country: 'KR', group: 'kr-realestate', rank: 9, free: true },
  { id: 'kr-fnrealestate', name: 'FN Real Estate', nameKo: '파이낸셜뉴스 부동산', url: 'https://www.fnnews.com/section/002003000', country: 'KR', group: 'kr-realestate', rank: 10, free: true },
  { id: 'kr-bizchosunrealestate', name: 'ChosunBiz Real Estate', nameKo: '조선비즈 부동산', url: 'https://biz.chosun.com/real_estate/', country: 'KR', group: 'kr-realestate', rank: 11, free: true },
  { id: 'kr-asiaerealestate', name: 'Asia Economy Real Estate', nameKo: '아시아경제 부동산', url: 'https://www.asiae.co.kr/list/realestate', country: 'KR', group: 'kr-realestate', rank: 12, free: true },
  { id: 'kr-edailyrealestate', name: 'Edaily Real Estate', nameKo: '이데일리 부동산', url: 'https://m.edaily.co.kr/NewsList/0401', country: 'KR', group: 'kr-realestate', rank: 13, free: true },
  { id: 'kr-etodayrealestate', name: 'Etoday Real Estate', nameKo: '이투데이 부동산', url: 'https://m.etoday.co.kr/section/list.php?MID=1400', country: 'KR', group: 'kr-realestate', rank: 14, free: true },

  // ─────────────────────── 사설·칼럼 ───────────────────────
  { id: 'kr-op-chosun', name: 'Chosun Opinion', nameKo: '조선일보 사설', url: 'https://www.chosun.com/opinion/', country: 'KR', group: 'kr-opinion', rank: 1, free: true, lean: 'conservative' },
  { id: 'kr-op-joongang', name: 'JoongAng Opinion', nameKo: '중앙일보 사설', url: 'https://www.joongang.co.kr/opinion', country: 'KR', group: 'kr-opinion', rank: 2, free: true, lean: 'conservative' },
  { id: 'kr-op-donga', name: 'Dong-A Opinion', nameKo: '동아일보 사설', url: 'https://www.donga.com/news/Opinion', country: 'KR', group: 'kr-opinion', rank: 3, free: true, lean: 'conservative' },
  { id: 'kr-op-hani', name: 'Hankyoreh Opinion', nameKo: '한겨레 사설', url: 'https://www.hani.co.kr/arti/opinion', country: 'KR', group: 'kr-opinion', rank: 4, free: true, lean: 'progressive' },
  { id: 'kr-op-khan', name: 'Kyunghyang Opinion', nameKo: '경향신문 사설', url: 'https://www.khan.co.kr/opinion', country: 'KR', group: 'kr-opinion', rank: 5, free: true, lean: 'progressive' },
  { id: 'kr-op-hankookilbo', name: 'Hankook Ilbo Opinion', nameKo: '한국일보 사설', url: 'https://www.hankookilbo.com/news/opinion', country: 'KR', group: 'kr-opinion', rank: 6, free: true, lean: 'center' },
  { id: 'kr-op-seoul', name: 'Seoul Shinmun Opinion', nameKo: '서울신문 사설', url: 'https://m.seoul.co.kr/newsList/editOpinion', country: 'KR', group: 'kr-opinion', rank: 7, free: true, lean: 'center' },
  { id: 'kr-op-munhwa', name: 'Munhwa Opinion', nameKo: '문화일보 사설', url: 'https://www.munhwa.com/opinion', country: 'KR', group: 'kr-opinion', rank: 8, free: true, lean: 'conservative' },
  { id: 'kr-op-segye', name: 'Segye Opinion', nameKo: '세계일보 사설', url: 'https://www.segye.com/news/opinion', country: 'KR', group: 'kr-opinion', rank: 9, free: true, lean: 'center' },
  { id: 'kr-op-kmib', name: 'Kukmin Opinion', nameKo: '국민일보 사설', url: 'https://www.kmib.co.kr/opinion/index.asp', country: 'KR', group: 'kr-opinion', rank: 10, free: true, lean: 'center' },

  // ─────────────────────── 시사만평 ───────────────────────
  { id: 'kr-toon-hani', name: 'Hankyoreh Cartoon', nameKo: '한겨레 만평', url: 'https://www.hani.co.kr/arti/cartoon/home01.html', country: 'KR', group: 'kr-cartoon', rank: 1, free: true, lean: 'progressive' },
  { id: 'kr-toon-khan', name: 'Kyunghyang Cartoon', nameKo: '경향신문 만평', url: 'https://www.khan.co.kr/cartoon', country: 'KR', group: 'kr-cartoon', rank: 2, free: true, lean: 'progressive' },
  { id: 'kr-toon-joongang', name: 'JoongAng Cartoon', nameKo: '중앙일보 만평', url: 'https://www.joongang.co.kr/opinion/satiricalcartoon', country: 'KR', group: 'kr-cartoon', rank: 3, free: true, lean: 'conservative' },
  { id: 'kr-toon-kmib', name: 'Kukmin Cartoon', nameKo: '국민일보 만평', url: 'https://www.kmib.co.kr/cartoon/index.asp', country: 'KR', group: 'kr-cartoon', rank: 4, free: true },
  { id: 'kr-toon-hankookilbo', name: 'Hankook Ilbo Cartoon', nameKo: '한국일보 만평', url: 'https://www.hankookilbo.com/news/opinion/cartoon', country: 'KR', group: 'kr-cartoon', rank: 5, free: true },
  { id: 'kr-toon-mk', name: 'MK Cartoon', nameKo: '매일경제 만평', url: 'https://www.mk.co.kr/opinion/cartoon', country: 'KR', group: 'kr-cartoon', rank: 6, free: true },
  { id: 'kr-toon-ohmynews', name: 'OhmyNews Cartoon', nameKo: '오마이뉴스 만평', url: 'http://m.ohmynews.com/NWS_Web/Mobile/comics.aspx', country: 'KR', group: 'kr-cartoon', rank: 7, free: true, lean: 'progressive' },
  { id: 'kr-toon-vop', name: 'Voice of People Cartoon', nameKo: '민중의소리 만평', url: 'https://www.vop.co.kr/list_cartoon.php', country: 'KR', group: 'kr-cartoon', rank: 8, free: true, lean: 'progressive' },
  { id: 'kr-toon-mindle', name: 'Mindle Cartoon', nameKo: '민들레 만평', url: 'https://www.mindlenews.com/news/articleList.html?sc_section_code=S1N9&view_type=sm', country: 'KR', group: 'kr-cartoon', rank: 9, free: true },
  { id: 'kr-toon-sisajournal', name: 'Sisa Journal Cartoon', nameKo: '시사저널 만평', url: 'http://www.sisajournal.com/news/articleList.html?sc_sub_section_code=S2N110&view_type=sm', country: 'KR', group: 'kr-cartoon', rank: 10, free: true },
  { id: 'kr-toon-sisain', name: 'SisaIN Cartoon', nameKo: '시사IN 만평', url: 'https://www.sisain.co.kr/news/articleList.html?sc_section_code=S1N14&view_type=sm', country: 'KR', group: 'kr-cartoon', rank: 11, free: true },
  { id: 'kr-toon-ddanzi', name: 'Ddanzi Cartoon', nameKo: '딴지일보 만평', url: 'https://www.ddanzi.com/index.php?mid=ddanziNews&category=977709', country: 'KR', group: 'kr-cartoon', rank: 12, free: true },
  { id: 'kr-toon-jangdori', name: 'Jangdori', nameKo: '장도리', url: 'https://jangdori.tistory.com', country: 'KR', group: 'kr-cartoon', rank: 13, free: true, note: '박순찬 작가 시사만평' },
  { id: 'kr-toon-kyeongin', name: 'Kyeongin Cartoon', nameKo: '경인일보 만평', url: 'https://www.kyeongin.com/opinion/satirical_cartoon', country: 'KR', group: 'kr-cartoon', rank: 14, free: true },
  { id: 'kr-toon-kyeonggi', name: 'Kyeonggi Cartoon', nameKo: '경기일보 만평', url: 'https://www.kyeonggi.com/seriesList/008116', country: 'KR', group: 'kr-cartoon', rank: 15, free: true },
  { id: 'kr-toon-joongboo', name: 'Joongboo Cartoon', nameKo: '중부일보 만평', url: 'https://www.joongboo.com/news/articleList.html?sc_sub_section_code=S2N105&sc_section_code=S1N12&view_type=sm', country: 'KR', group: 'kr-cartoon', rank: 16, free: true },
  { id: 'kr-toon-imaeil', name: 'Maeil Shinmun Cartoon', nameKo: '매일신문 만평', url: 'https://www.imaeil.com/writer_news?search=edtoon1@daum.net', country: 'KR', group: 'kr-cartoon', rank: 17, free: true },

  // ─────────────────────── 진보 성향 ───────────────────────
  { id: 'kr-ohmynews', name: 'OhmyNews', nameKo: '오마이뉴스', url: 'https://www.ohmynews.com', country: 'KR', group: 'kr-progressive', rank: 1, free: true, lean: 'progressive', note: '시민기자 모델의 원조' },
  { id: 'kr-pressian', name: 'Pressian', nameKo: '프레시안', url: 'https://www.pressian.com', country: 'KR', group: 'kr-progressive', rank: 2, free: true, lean: 'progressive' },
  { id: 'kr-vop', name: 'Voice of the People', nameKo: '민중의소리', url: 'https://www.vop.co.kr', country: 'KR', group: 'kr-progressive', rank: 3, free: true, lean: 'progressive' },
  { id: 'kr-mindle', name: 'Mindle News', nameKo: '민들레', url: 'https://www.mindlenews.com', country: 'KR', group: 'kr-progressive', rank: 4, free: true, lean: 'progressive' },
  { id: 'kr-ddanzi', name: 'Ddanzi Ilbo', nameKo: '딴지일보', url: 'https://www.ddanzi.com', country: 'KR', group: 'kr-progressive', rank: 5, free: true, lean: 'progressive' },
  { id: 'kr-sisain', name: 'SisaIN', nameKo: '시사IN', url: 'https://www.sisain.co.kr', country: 'KR', group: 'kr-progressive', rank: 6, free: true, lean: 'progressive', note: '탐사 시사주간지' },
  { id: 'kr-hani21', name: 'Hankyoreh 21', nameKo: '한겨레21', url: 'https://h21.hani.co.kr', country: 'KR', group: 'kr-progressive', rank: 7, free: true, lean: 'progressive' },
  { id: 'kr-weeklykhan', name: 'Weekly Kyunghyang', nameKo: '주간경향', url: 'https://weekly.khan.co.kr', country: 'KR', group: 'kr-progressive', rank: 8, free: true, lean: 'progressive' },
  { id: 'kr-newstomato', name: 'News Tomato', nameKo: '뉴스토마토', url: 'https://www.newstomato.com', country: 'KR', group: 'kr-progressive', rank: 9, free: true, lean: 'progressive' },
  { id: 'kr-polinews', name: 'Polinews', nameKo: '폴리뉴스', url: 'https://www.polinews.co.kr', country: 'KR', group: 'kr-progressive', rank: 10, free: true },
  { id: 'kr-newscham', name: 'Chamsesang', nameKo: '참세상', url: 'https://www.newscham.net', country: 'KR', group: 'kr-progressive', rank: 11, free: true, lean: 'progressive', note: '노동 운동 전문' },
  { id: 'kr-amn', name: 'Voice of Seoul', nameKo: '서울의소리', url: 'https://amn.kr', country: 'KR', group: 'kr-progressive', rank: 12, free: true, lean: 'progressive' },
  { id: 'kr-huffpostkr', name: 'HuffPost Korea', nameKo: '허프포스트코리아', url: 'https://www.huffingtonpost.kr', country: 'KR', group: 'kr-progressive', rank: 13, free: true },
  { id: 'kr-viewsnnews', name: 'Views & News', nameKo: '뷰스앤뉴스', url: 'https://www.viewsnnews.com', country: 'KR', group: 'kr-progressive', rank: 14, free: true },
  { id: 'kr-facttv', name: 'Fact TV', nameKo: '팩트TV', url: 'http://facttv.kr', country: 'KR', group: 'kr-progressive', rank: 15, free: true },
  { id: 'kr-eroun', name: 'Eroun', nameKo: '이로운넷', url: 'https://www.eroun.net', country: 'KR', group: 'kr-progressive', rank: 16, free: true, note: '사회적경제 전문' },
  { id: 'kr-redian', name: 'Redian', nameKo: '레디앙', url: 'http://www.redian.org', country: 'KR', group: 'kr-progressive', rank: 17, free: true, lean: 'progressive' },

  // ─────────────────────── 보수 성향 ───────────────────────
  { id: 'kr-dailian', name: 'Dailian', nameKo: '데일리안', url: 'https://www.dailian.co.kr', country: 'KR', group: 'kr-conservative', rank: 1, free: true, lean: 'conservative' },
  { id: 'kr-newdaily', name: 'New Daily', nameKo: '뉴데일리', url: 'https://www.newdaily.co.kr', country: 'KR', group: 'kr-conservative', rank: 2, free: true, lean: 'conservative' },
  { id: 'kr-pennmike', name: 'Penn & Mike', nameKo: '펜앤드마이크', url: 'https://www.pennmike.com', country: 'KR', group: 'kr-conservative', rank: 3, free: true, lean: 'conservative' },
  { id: 'kr-chogabje', name: 'Chogabje.com', nameKo: '조갑제닷컴', url: 'https://www.chogabje.com', country: 'KR', group: 'kr-conservative', rank: 4, free: true, lean: 'conservative' },
  { id: 'kr-weeklychosun', name: 'Weekly Chosun', nameKo: '주간조선', url: 'https://weekly.chosun.com', country: 'KR', group: 'kr-conservative', rank: 5, free: true, lean: 'conservative' },
  { id: 'kr-weeklydonga', name: 'Weekly Dong-A', nameKo: '주간동아', url: 'https://weekly.donga.com', country: 'KR', group: 'kr-conservative', rank: 6, free: true, lean: 'conservative' },
  { id: 'kr-monthlychosun', name: 'Monthly Chosun', nameKo: '월간조선', url: 'https://monthly.chosun.com', country: 'KR', group: 'kr-conservative', rank: 7, free: true, lean: 'conservative' },
  { id: 'kr-shindonga', name: 'Shin Dong-A', nameKo: '신동아', url: 'https://shindonga.donga.com', country: 'KR', group: 'kr-conservative', rank: 8, free: true, lean: 'conservative' },
  { id: 'kr-newstown', name: 'Newstown', nameKo: '뉴스타운', url: 'https://www.newstown.co.kr', country: 'KR', group: 'kr-conservative', rank: 9, free: true, lean: 'conservative' },
  { id: 'kr-futurekorea', name: 'Future Korea', nameKo: '미래한국', url: 'http://www.futurekorea.co.kr', country: 'KR', group: 'kr-conservative', rank: 10, free: true, lean: 'conservative' },

  // ─────────────────────── 탐사보도 ───────────────────────
  { id: 'kr-newstapa', name: 'Newstapa', nameKo: '뉴스타파', url: 'https://newstapa.org', country: 'KR', group: 'kr-investigative', rank: 3, free: true, note: '후원 기반 비영리 탐사보도' },
  { id: 'kr-sherlock', name: 'Sherlock', nameKo: '셜록', url: 'https://www.neosherlock.com', country: 'KR', group: 'kr-investigative', rank: 7, free: true },
  { id: 'kr-thescoop', name: 'The Scoop', nameKo: '더스쿠프', url: 'https://www.thescoop.co.kr', country: 'KR', group: 'kr-investigative', rank: 8, free: true },
  { id: 'kr-dunia', name: 'The Dunia', nameKo: '두니아', url: 'https://thedunia.org', country: 'KR', group: 'kr-investigative', rank: 9, free: true },
  { id: 'kr-newshada', name: 'Newshada', nameKo: '뉴스하다', url: 'https://newshada.org', country: 'KR', group: 'kr-investigative', rank: 10, free: true },
  { id: 'kr-pdnotebook', name: 'PD Notebook', nameKo: 'PD수첩', url: 'https://www.youtube.com/channel/UCawCv9kO2UXbTtsK4EammRQ', country: 'KR', group: 'kr-investigative', rank: 2, free: true, note: 'MBC 시사교양' },
  { id: 'kr-unanswered', name: 'Unanswered Questions', nameKo: '그것이 알고싶다', url: 'https://www.youtube.com/@sbstruth', country: 'KR', group: 'kr-investigative', rank: 1, free: true, note: 'SBS 탐사 프로그램' },
  { id: 'kr-window', name: 'Window', nameKo: '시사기획 창', url: 'https://www.youtube.com/playlist?list=PLjESAf4PvYLlXcqw6A_zHU52Ch9ahJXPL', country: 'KR', group: 'kr-investigative', rank: 6, free: true, note: 'KBS 시사기획' },
  { id: 'kr-chase60', name: 'Chase 60 Minutes', nameKo: '추적 60분', url: 'https://www.youtube.com/@KBS60min', country: 'KR', group: 'kr-investigative', rank: 4, free: true },
  { id: 'kr-straight', name: 'Straight', nameKo: '탐사기획 스트레이트', url: 'https://www.youtube.com/@mbc-straight', country: 'KR', group: 'kr-investigative', rank: 5, free: true },

  // ─────────────────────── 언론 비평 ───────────────────────
  { id: 'kr-mediatoday', name: 'Media Today', nameKo: '미디어오늘', url: 'https://www.mediatoday.co.kr', country: 'KR', group: 'kr-media', rank: 1, free: true, note: '언론 감시 전문지' },
  { id: 'kr-mediaus', name: 'Mediaus', nameKo: '미디어스', url: 'https://www.mediaus.co.kr', country: 'KR', group: 'kr-media', rank: 2, free: true },
  { id: 'kr-newswhere', name: 'News Where', nameKo: '뉴스어디', url: 'https://newswhere.org', country: 'KR', group: 'kr-media', rank: 3, free: true },
  { id: 'kr-pdjournal', name: 'PD Journal', nameKo: 'PD저널', url: 'http://www.pdjournal.com', country: 'KR', group: 'kr-media', rank: 4, free: true },
  { id: 'kr-journalist', name: 'Journalists Association of Korea', nameKo: '한국기자협회', url: 'https://www.journalist.or.kr', country: 'KR', group: 'kr-media', rank: 5, free: true },
  { id: 'kr-ccdm', name: 'CCDM', nameKo: '민주언론시민연합', url: 'https://www.ccdm.or.kr', country: 'KR', group: 'kr-media', rank: 6, free: true, note: '시민단체 모니터 보고서' },

  // ─────────────────────── IT·전자 ───────────────────────
  { id: 'kr-etnews', name: 'Electronic Times', nameKo: '전자신문', url: 'https://www.etnews.com', country: 'KR', group: 'kr-it', rank: 1, free: true, note: '국내 대표 IT 전문지' },
  { id: 'kr-zdnetkr', name: 'ZDNet Korea', nameKo: 'ZDNet 코리아', url: 'https://zdnet.co.kr', country: 'KR', group: 'kr-it', rank: 2, free: true },
  { id: 'kr-itworld', name: 'ITWorld Korea', nameKo: 'IT월드', url: 'https://www.itworld.co.kr', country: 'KR', group: 'kr-it', rank: 4, free: true },
  { id: 'kr-ddaily', name: 'Digital Daily', nameKo: '디지털데일리', url: 'http://www.ddaily.co.kr', country: 'KR', group: 'kr-it', rank: 3, free: true },
  { id: 'kr-cnetkr', name: 'CNET Korea', nameKo: 'CNET 코리아', url: 'https://www.cnet.co.kr', country: 'KR', group: 'kr-it', rank: 12, free: true },
  { id: 'kr-ciokorea', name: 'CIO Korea', nameKo: 'CIO 코리아', url: 'https://www.cio.com/kr/', country: 'KR', group: 'kr-it', rank: 13, free: true },
  { id: 'kr-thelec', name: 'The Elec', nameKo: '디일렉', url: 'https://www.thelec.kr', country: 'KR', group: 'kr-it', rank: 8, free: true, note: '전자부품·디스플레이 전문' },
  { id: 'kr-epnc', name: 'TechWorld', nameKo: '테크월드뉴스', url: 'https://www.epnc.co.kr', country: 'KR', group: 'kr-it', rank: 21, free: true },
  { id: 'kr-itbiznews', name: 'IT Biz News', nameKo: 'IT비즈뉴스', url: 'https://www.itbiznews.com', country: 'KR', group: 'kr-it', rank: 20, free: true },
  { id: 'kr-thetech', name: 'The Tech', nameKo: '더테크', url: 'https://www.the-tech.co.kr', country: 'KR', group: 'kr-it', rank: 19, free: true },
  { id: 'kr-techrecipe', name: 'Tech Recipe', nameKo: '테크레시피', url: 'https://techrecipe.co.kr', country: 'KR', group: 'kr-it', rank: 18, free: true },
  { id: 'kr-itdaily', name: 'IT Daily', nameKo: 'IT데일리', url: 'https://www.itdaily.kr', country: 'KR', group: 'kr-it', rank: 14, free: true },
  { id: 'kr-techm', name: 'Tech M', nameKo: '테크M', url: 'https://www.techm.kr', country: 'KR', group: 'kr-it', rank: 11, free: true },
  { id: 'kr-outstanding', name: 'Outstanding', nameKo: '아웃스탠딩', url: 'https://outstanding.kr', country: 'KR', group: 'kr-it', rank: 16, note: '스타트업 심층 분석' },
  { id: 'kr-comworld', name: 'Computer World', nameKo: '컴퓨터월드', url: 'http://www.comworld.co.kr', country: 'KR', group: 'kr-it', rank: 22, free: true },
  { id: 'kr-platum', name: 'Platum', nameKo: '플래텀', url: 'https://platum.kr', country: 'KR', group: 'kr-it', rank: 9, free: true, note: '스타트업·중화권 테크' },
  { id: 'kr-techdaily', name: 'Tech Daily', nameKo: '테크데일리', url: 'http://www.techdaily.co.kr', country: 'KR', group: 'kr-it', rank: 23, free: true },
  { id: 'kr-venturesquare', name: 'Venture Square', nameKo: '벤처스퀘어', url: 'https://www.venturesquare.net', country: 'KR', group: 'kr-it', rank: 17, free: true },
  { id: 'kr-boannews', name: 'Boan News', nameKo: '보안뉴스', url: 'https://m.boannews.com', country: 'KR', group: 'kr-it', rank: 5, free: true, note: '정보보안 전문' },
  { id: 'kr-itchosun', name: 'IT Chosun', nameKo: 'IT조선', url: 'http://it.chosun.com', country: 'KR', group: 'kr-it', rank: 6, free: true },
  { id: 'kr-itdonga', name: 'IT Dong-A', nameKo: 'IT동아', url: 'https://it.donga.com', country: 'KR', group: 'kr-it', rank: 7, free: true },
  { id: 'kr-betanews', name: 'Beta News', nameKo: '베타뉴스', url: 'http://www.betanews.net', country: 'KR', group: 'kr-it', rank: 15, free: true },
  { id: 'kr-datanet', name: 'DataNet', nameKo: '데이터넷', url: 'http://www.datanet.co.kr', country: 'KR', group: 'kr-it', rank: 24, free: true },
  { id: 'kr-geeknews', name: 'GeekNews', nameKo: '긱뉴스', url: 'https://news.hada.io', country: 'KR', group: 'kr-it', rank: 10, free: true, note: '한국판 해커뉴스' },

  // ─────────────────────── AI ───────────────────────
  { id: 'kr-aitimes', name: 'AI Times', nameKo: 'AI타임스', url: 'https://www.aitimes.com', country: 'KR', group: 'kr-ai', rank: 1, free: true, note: '국내 대표 AI 전문지' },
  { id: 'kr-aitimeskr', name: 'AI Newspaper', nameKo: '인공지능신문', url: 'https://www.aitimes.kr', country: 'KR', group: 'kr-ai', rank: 2, free: true },
  { id: 'kr-newstheai', name: 'The AI', nameKo: '더에이아이', url: 'https://www.newstheai.com', country: 'KR', group: 'kr-ai', rank: 3, free: true },
  { id: 'kr-aipost', name: 'AI Post', nameKo: 'AI포스트', url: 'https://www.aipostkorea.com', country: 'KR', group: 'kr-ai', rank: 4, free: true },
  { id: 'kr-irobotnews', name: 'Robot Newspaper', nameKo: '로봇신문', url: 'https://www.irobotnews.com', country: 'KR', group: 'kr-ai', rank: 5, free: true },
  { id: 'kr-aimatters', name: 'AI Matters', nameKo: 'AI매터스', url: 'https://aimatters.co.kr', country: 'KR', group: 'kr-ai', rank: 6, free: true },
  { id: 'kr-itworldai', name: 'ITWorld AI', nameKo: 'IT월드 인공지능', url: 'https://www.itworld.co.kr/artificial-intelligence/', country: 'KR', group: 'kr-ai', rank: 7, free: true },
  { id: 'kr-mitreviewkr', name: 'MIT Tech Review Korea', nameKo: 'MIT 테크놀로지리뷰(한국)', url: 'https://www.technologyreview.kr', country: 'KR', group: 'kr-ai', rank: 8, note: '한국어판' },

  // ─────────────────────── 과학 ───────────────────────
  { id: 'kr-dongascience', name: 'Dong-A Science', nameKo: '동아사이언스', url: 'https://www.dongascience.com', country: 'KR', group: 'kr-science', rank: 1, free: true, note: '과학동아 발행' },
  { id: 'kr-sciencetimes', name: 'Science Times', nameKo: '사이언스타임즈', url: 'https://www.sciencetimes.co.kr', country: 'KR', group: 'kr-science', rank: 2, free: true },
  { id: 'kr-popsci', name: 'Popular Science Korea', nameKo: '파퓰러사이언스', url: 'https://www.popsci.co.kr', country: 'KR', group: 'kr-science', rank: 3, free: true },
  { id: 'kr-scienceon', name: 'ScienceON', nameKo: '사이언스온', url: 'https://scienceon.kisti.re.kr', country: 'KR', group: 'kr-science', rank: 4, free: true, note: 'KISTI 논문·특허 검색' },
  { id: 'kr-haniscience', name: 'Hankyoreh Science', nameKo: '한겨레 미래과학', url: 'https://www.hani.co.kr/arti/science/home01.html', country: 'KR', group: 'kr-science', rank: 5, free: true },
  { id: 'kr-ytnscience', name: 'YTN Science', nameKo: 'YTN 사이언스', url: 'https://science.ytn.co.kr', country: 'KR', group: 'kr-science', rank: 6, free: true },
  { id: 'kr-hellodd', name: 'HelloDD', nameKo: '헬로디디', url: 'https://www.hellodd.com', country: 'KR', group: 'kr-science', rank: 7, free: true, note: '대덕연구단지 전문' },
  { id: 'kr-ibric', name: 'BRIC', nameKo: 'BRIC 생물학연구정보센터', url: 'https://www.ibric.org', country: 'KR', group: 'kr-science', rank: 8, free: true, note: '생명과학 연구자 커뮤니티' },
  { id: 'kr-khanscience', name: 'Kyunghyang Science', nameKo: '경향 과학·환경', url: 'https://www.khan.co.kr/science', country: 'KR', group: 'kr-science', rank: 9, free: true },
  { id: 'kr-scienceall', name: 'ScienceAll', nameKo: '사이언스올', url: 'https://www.scienceall.com', country: 'KR', group: 'kr-science', rank: 10, free: true },
  { id: 'kr-kistiscent', name: 'KISTI Science Scent', nameKo: 'KISTI 과학향기', url: 'https://scent.kisti.re.kr', country: 'KR', group: 'kr-science', rank: 11, free: true },
  { id: 'kr-natgeokr', name: 'National Geographic Korea', nameKo: '내셔널지오그래픽(한국)', url: 'https://www.natgeokorea.com', country: 'KR', group: 'kr-science', rank: 12 },

  // ─────────────────────── 의학·제약 ───────────────────────
  { id: 'kr-doctorsnews', name: 'Doctors News', nameKo: '의협신문', url: 'https://www.doctorsnews.co.kr', country: 'KR', group: 'kr-medical', rank: 1, free: true, note: '대한의사협회 기관지' },
  { id: 'kr-medigatenews', name: 'MediGate News', nameKo: '메디게이트뉴스', url: 'https://www.medigatenews.com', country: 'KR', group: 'kr-medical', rank: 2, free: true },
  { id: 'kr-medicaltimes', name: 'Medical Times', nameKo: '메디칼타임즈', url: 'https://m.medicaltimes.com', country: 'KR', group: 'kr-medical', rank: 3, free: true },
  { id: 'kr-dailymedi', name: 'Daily Medi', nameKo: '데일리메디', url: 'https://www.dailymedi.com', country: 'KR', group: 'kr-medical', rank: 4, free: true },
  { id: 'kr-medifonews', name: 'Medifo News', nameKo: '메디포뉴스', url: 'https://www.medifonews.com', country: 'KR', group: 'kr-medical', rank: 5, free: true },
  { id: 'kr-bosa', name: 'Medical Newspaper', nameKo: '의학신문', url: 'http://www.bosa.co.kr', country: 'KR', group: 'kr-medical', rank: 6, free: true },
  { id: 'kr-mdtoday', name: 'Medical Today', nameKo: '메디컬투데이', url: 'https://www.mdtoday.co.kr', country: 'KR', group: 'kr-medical', rank: 7, free: true },
  { id: 'kr-docdocdoc', name: 'Young Doctor', nameKo: '청년의사', url: 'https://www.docdocdoc.co.kr', country: 'KR', group: 'kr-medical', rank: 8, free: true },
  { id: 'kr-dailydental', name: 'Daily Dental', nameKo: '치의신보', url: 'https://www.dailydental.co.kr', country: 'KR', group: 'kr-medical', rank: 9, free: true, note: '치과 전문' },
  { id: 'kr-whosaeng', name: 'Whosaeng', nameKo: '후생신보', url: 'https://www.whosaeng.com', country: 'KR', group: 'kr-medical', rank: 10, free: true },
  { id: 'kr-medicalilbo', name: 'Medical Daily', nameKo: '의료일보', url: 'http://www.medicalilbo.com', country: 'KR', group: 'kr-medical', rank: 11, free: true },
  { id: 'kr-monews', name: 'Medical Observer', nameKo: '메디칼업저버', url: 'http://www.monews.co.kr', country: 'KR', group: 'kr-medical', rank: 12, free: true },
  { id: 'kr-thebionews', name: 'The Bio', nameKo: '더바이오', url: 'https://www.thebionews.net', country: 'KR', group: 'kr-medical', rank: 13, free: true, note: '바이오·제약 산업' },
  { id: 'kr-biotimes', name: 'BioTimes', nameKo: '바이오타임즈', url: 'https://www.biotimes.co.kr', country: 'KR', group: 'kr-medical', rank: 14, free: true },

  // ─────────────────────── 건강 ───────────────────────
  { id: 'kr-kormedi', name: 'Kormedi', nameKo: '코메디닷컴', url: 'https://kormedi.com', country: 'KR', group: 'kr-health', rank: 2, free: true },
  { id: 'kr-hidoc', name: 'Hidoc', nameKo: '하이닥', url: 'https://www.hidoc.co.kr', country: 'KR', group: 'kr-health', rank: 1, free: true },
  { id: 'kr-healthchosun', name: 'Health Chosun', nameKo: '헬스조선', url: 'https://health.chosun.com', country: 'KR', group: 'kr-health', rank: 3, free: true },
  { id: 'kr-jhealthmedia', name: 'Health JoongAng', nameKo: '헬스중앙', url: 'https://jhealthmedia.joins.com', country: 'KR', group: 'kr-health', rank: 8, free: true },
  { id: 'kr-ikunkang', name: 'Health Digest', nameKo: '건강다이제스트', url: 'http://www.ikunkang.com', country: 'KR', group: 'kr-health', rank: 12, free: true },
  { id: 'kr-ynahealth', name: 'Yonhap Health', nameKo: '연합뉴스 건강', url: 'https://www.yna.co.kr/health/index', country: 'KR', group: 'kr-health', rank: 5, free: true },
  { id: 'kr-mindgil', name: 'Mind Health Road', nameKo: '마음건강길', url: 'https://www.mindgil.com', country: 'KR', group: 'kr-health', rank: 11, free: true, note: '정신건강 전문' },
  { id: 'kr-healthinnews', name: 'Health In News', nameKo: '헬스인뉴스', url: 'https://www.healthinnews.co.kr', country: 'KR', group: 'kr-health', rank: 10, free: true },
  { id: 'kr-mkhealth', name: 'MK Health', nameKo: '매경헬스', url: 'https://www.mkhealth.co.kr', country: 'KR', group: 'kr-health', rank: 4, free: true },
  { id: 'kr-hanihealth', name: 'Hankyoreh Health', nameKo: '건강한겨레', url: 'https://www.hani.co.kr/arti/hanihealth', country: 'KR', group: 'kr-health', rank: 9, free: true },
  { id: 'kr-khealth', name: 'Health Kyunghyang', nameKo: '헬스경향', url: 'https://www.k-health.com', country: 'KR', group: 'kr-health', rank: 6, free: true },
  { id: 'kr-dongahealth', name: 'Health Dong-A', nameKo: '헬스동아', url: 'https://www.donga.com/news/Health', country: 'KR', group: 'kr-health', rank: 7, free: true },

  // ─────────────────────── 산업별 전문지 ───────────────────────
  { id: 'kr-zdnetsemi', name: 'ZDNet Semiconductor', nameKo: '지디넷 반도체', url: 'https://zdnet.co.kr/news/?lstcode=0050', country: 'KR', group: 'kr-industry', rank: 1, free: true },
  { id: 'kr-seminet', name: 'Semiconductor Network', nameKo: '반도체네트워크', url: 'https://www.seminet.co.kr', country: 'KR', group: 'kr-industry', rank: 2, free: true },
  { id: 'kr-conslove', name: 'Korea Construction News', nameKo: '한국건설신문', url: 'http://www.conslove.co.kr', country: 'KR', group: 'kr-industry', rank: 3, free: true },
  { id: 'kr-engdaily', name: 'Engineering Daily', nameKo: '엔지니어링데일리', url: 'https://www.engdaily.com', country: 'KR', group: 'kr-industry', rank: 4, free: true },
  { id: 'kr-energynews', name: 'Energy News', nameKo: '에너지신문', url: 'https://www.energy-news.co.kr', country: 'KR', group: 'kr-industry', rank: 5, free: true },
  { id: 'kr-electimes', name: 'Electric Times', nameKo: '전기신문', url: 'https://www.electimes.com', country: 'KR', group: 'kr-industry', rank: 6, free: true },
  { id: 'kr-globalautonews', name: 'Global Auto News', nameKo: '글로벌오토뉴스', url: 'http://www.global-autonews.com', country: 'KR', group: 'kr-industry', rank: 7, free: true },
  { id: 'kr-dealsite', name: 'DealSite', nameKo: '딜사이트', url: 'https://dealsite.co.kr', country: 'KR', group: 'kr-industry', rank: 8, free: true, note: 'M&A·자본시장 전문' },
  { id: 'kr-steeldaily', name: 'Steel Daily', nameKo: '스틸데일리', url: 'https://www.steeldaily.co.kr', country: 'KR', group: 'kr-industry', rank: 9, free: true },
  { id: 'kr-snmnews', name: 'Steel & Metal News', nameKo: '철강금속신문', url: 'http://www.snmnews.com', country: 'KR', group: 'kr-industry', rank: 10, free: true },
  { id: 'kr-ynaheavy', name: 'Yonhap Heavy Chemical', nameKo: '연합뉴스 중화학산업', url: 'https://www.yna.co.kr/industry/heavy-chemistry', country: 'KR', group: 'kr-industry', rank: 11, free: true },
  { id: 'kr-mkchemical', name: 'MK Chemicals', nameKo: '매일경제 중화학', url: 'https://www.mk.co.kr/news/business/chemical/', country: 'KR', group: 'kr-industry', rank: 12, free: true },
  { id: 'kr-apparelnews', name: 'Apparel News', nameKo: '어패럴뉴스', url: 'https://www.apparelnews.co.kr', country: 'KR', group: 'kr-industry', rank: 13, free: true },
  { id: 'kr-itnk', name: 'International Textile News', nameKo: '국제섬유신문', url: 'https://www.itnk.co.kr', country: 'KR', group: 'kr-industry', rank: 14, free: true },

  // ─────────────────────── 국방·군사 ───────────────────────
  { id: 'kr-bemil', name: 'BEMIL Military World', nameKo: 'BEMIL 군사세계', url: 'https://bemil.chosun.com', country: 'KR', group: 'kr-military', rank: 1, free: true },
  { id: 'kr-dailydefense', name: 'Daily Defense', nameKo: '데일리방산', url: 'https://www.dailydefense.co.kr', country: 'KR', group: 'kr-military', rank: 2, free: true, note: '방산 수출 동향' },
  { id: 'kr-milidom', name: 'Milidom', nameKo: '밀리돔', url: 'https://milidom.net', country: 'KR', group: 'kr-military', rank: 3, free: true },
  { id: 'kr-newsimpact', name: 'News Impact', nameKo: '뉴스임팩트', url: 'https://www.newsimpact.co.kr', country: 'KR', group: 'kr-military', rank: 4, free: true },
  { id: 'kr-defenseclub', name: 'Defense Club', nameKo: '디펜스클럽', url: 'https://military.asiae.co.kr', country: 'KR', group: 'kr-military', rank: 5, free: true },
  { id: 'kr-defensetoday', name: 'Defense Today', nameKo: '디펜스투데이', url: 'http://www.defensetoday.kr', country: 'KR', group: 'kr-military', rank: 6, free: true },
  { id: 'kr-kookbang', name: 'Kookbang Ilbo', nameKo: '국방일보', url: 'https://kookbang.dema.mil.kr', country: 'KR', group: 'kr-military', rank: 7, free: true, note: '국방부 발행' },
  { id: 'kr-gukbangnews', name: 'Gukbang News', nameKo: '국방신문', url: 'https://www.gukbangnews.com', country: 'KR', group: 'kr-military', rank: 8, free: true },
  { id: 'kr-defensetimes', name: 'Defense Times', nameKo: '디펜스타임즈', url: 'http://defensetimes.kr', country: 'KR', group: 'kr-military', rank: 9, free: true },
  { id: 'kr-platoon', name: 'Platoon', nameKo: '플래툰', url: 'http://www.platoon.co.kr', country: 'KR', group: 'kr-military', rank: 10, free: true },
  { id: 'kr-dcwar', name: 'DC Military Gallery', nameKo: '디시 군사갤러리', url: 'https://gall.dcinside.com/mgallery/board/lists/?id=war', country: 'KR', group: 'kr-military', rank: 11, free: true },
  { id: 'kr-arcamilitary', name: 'Arca Military', nameKo: '아카라이브 군사채널', url: 'https://arca.live/b/military815', country: 'KR', group: 'kr-military', rank: 12, free: true },

  // ─────────────────────── 게임 ───────────────────────
  { id: 'kr-thisisgame', name: 'This Is Game', nameKo: '디스이즈게임', url: 'https://www.thisisgame.com', country: 'KR', group: 'kr-game', rank: 3, free: true, note: '심층 게임 저널리즘' },
  { id: 'kr-inven', name: 'Inven', nameKo: '인벤', url: 'https://www.inven.co.kr', country: 'KR', group: 'kr-game', rank: 1, free: true, note: '국내 최대 게임 커뮤니티' },
  { id: 'kr-ruliweb', name: 'Ruliweb', nameKo: '루리웹', url: 'https://www.ruliweb.com', country: 'KR', group: 'kr-game', rank: 2, free: true },
  { id: 'kr-gamemeca', name: 'Game Meca', nameKo: '게임메카', url: 'https://www.gamemeca.com', country: 'KR', group: 'kr-game', rank: 4, free: true },
  { id: 'kr-dailygame', name: 'Daily Game', nameKo: '데일리게임', url: 'https://www.dailygame.co.kr', country: 'KR', group: 'kr-game', rank: 7, free: true },
  { id: 'kr-gamefocus', name: 'Game Focus', nameKo: '게임포커스', url: 'https://gamefocus.co.kr', country: 'KR', group: 'kr-game', rank: 8, free: true },
  { id: 'kr-quasarplay', name: 'Quasar Play', nameKo: '퀘이사플레이', url: 'https://quasarplay.com', country: 'KR', group: 'kr-game', rank: 9, free: true },
  { id: 'kr-playforum', name: 'Play Forum', nameKo: '플레이포럼', url: 'https://www.playforum.net', country: 'KR', group: 'kr-game', rank: 14, free: true },
  { id: 'kr-gametoc', name: 'Game Toc', nameKo: '게임톡', url: 'https://www.gametoc.co.kr', country: 'KR', group: 'kr-game', rank: 13, free: true },
  { id: 'kr-hungryapp', name: 'Hungry App', nameKo: '헝그리앱', url: 'http://www.hungryapp.co.kr', country: 'KR', group: 'kr-game', rank: 6, free: true, note: '모바일게임 전문' },
  { id: 'kr-gameinsight', name: 'Game Insight', nameKo: '게임인사이트', url: 'http://www.gameinsight.co.kr', country: 'KR', group: 'kr-game', rank: 15, free: true },
  { id: 'kr-gamey', name: 'Game Y', nameKo: '게임와이', url: 'http://www.gamey.kr', country: 'KR', group: 'kr-game', rank: 10, free: true },
  { id: 'kr-khgames', name: 'Kyunghyang Games', nameKo: '경향게임스', url: 'http://www.khgames.co.kr', country: 'KR', group: 'kr-game', rank: 11, free: true },
  { id: 'kr-gameshot', name: 'Game Shot', nameKo: '게임샷', url: 'http://www.gameshot.net', country: 'KR', group: 'kr-game', rank: 12, free: true },
  { id: 'kr-gamechosun', name: 'Game Chosun', nameKo: '게임조선', url: 'https://m.gamechosun.co.kr', country: 'KR', group: 'kr-game', rank: 5, free: true },

  // ─────────────────────── 자동차 ───────────────────────
  { id: 'kr-motorgraph', name: 'Motorgraph', nameKo: '모터그래프', url: 'https://www.motorgraph.com', country: 'KR', group: 'kr-auto', rank: 3, free: true },
  { id: 'kr-autoview', name: 'AutoView', nameKo: '오토뷰', url: 'https://www.autoview.co.kr', country: 'KR', group: 'kr-auto', rank: 4, free: true, note: '영상 시승기로 유명' },
  { id: 'kr-motormag', name: 'Motor Magazine', nameKo: '모터매거진', url: 'https://www.motormag.co.kr', country: 'KR', group: 'kr-auto', rank: 7, free: true },
  { id: 'kr-gpkorea', name: 'GP Korea', nameKo: '지피코리아', url: 'http://www.gpkorea.com', country: 'KR', group: 'kr-auto', rank: 8, free: true },
  { id: 'kr-motoya', name: 'Motoya', nameKo: '모토야', url: 'https://www.motoya.co.kr', country: 'KR', group: 'kr-auto', rank: 14, free: true },
  { id: 'kr-autocast', name: 'AutoCast', nameKo: '오토캐스트', url: 'https://www.autocast.co.kr', country: 'KR', group: 'kr-auto', rank: 13, free: true },
  { id: 'kr-autotimes', name: 'Auto Times', nameKo: '오토타임즈', url: 'http://autotimes.co.kr', country: 'KR', group: 'kr-auto', rank: 6, free: true },
  { id: 'kr-autospy', name: 'AutoSpy', nameKo: '오토스파이넷', url: 'https://www.autospy.net', country: 'KR', group: 'kr-auto', rank: 16, free: true },
  { id: 'kr-danawaauto', name: 'Danawa Auto', nameKo: '다나와 자동차', url: 'https://mauto.danawa.com', country: 'KR', group: 'kr-auto', rank: 2, free: true, note: '신차 가격 비교' },
  { id: 'kr-autoherald', name: 'Auto Herald', nameKo: '오토헤럴드', url: 'http://www.autoherald.co.kr', country: 'KR', group: 'kr-auto', rank: 11, free: true },
  { id: 'kr-cartech', name: 'CarTech', nameKo: '카테크', url: 'https://www.cartech.co.kr', country: 'KR', group: 'kr-auto', rank: 9, free: true },
  { id: 'kr-autotribune', name: 'Auto Tribune', nameKo: '오토트리뷴', url: 'https://www.autotribune.co.kr', country: 'KR', group: 'kr-auto', rank: 10, free: true },
  { id: 'kr-dailycar', name: 'Daily Car', nameKo: '데일리카', url: 'https://www.dailycar.co.kr', country: 'KR', group: 'kr-auto', rank: 5, free: true },
  { id: 'kr-carguy', name: 'CarGuy', nameKo: '카가이', url: 'http://www.carguy.kr', country: 'KR', group: 'kr-auto', rank: 15, free: true },
  { id: 'kr-thedrive', name: 'The Drive Korea', nameKo: '더드라이브', url: 'https://www.thedrive.co.kr', country: 'KR', group: 'kr-auto', rank: 12, free: true },
  { id: 'kr-ridemag', name: 'Ride Magazine', nameKo: '라이드매거진', url: 'http://m.ridemag.co.kr/news/section.html?section=car', country: 'KR', group: 'kr-auto', rank: 17, free: true },
  { id: 'kr-autoelectronics', name: 'Auto Electronics', nameKo: '오토모티브', url: 'https://www.autoelectronics.co.kr', country: 'KR', group: 'kr-auto', rank: 18, free: true, note: '차량용 전장 전문' },
  { id: 'kr-bobaedream', name: 'Bobaedream', nameKo: '보배드림', url: 'https://www.bobaedream.co.kr', country: 'KR', group: 'kr-auto', rank: 1, free: true, note: '중고차·자동차 커뮤니티' },

  // ─────────────────────── 스포츠 ───────────────────────
  { id: 'kr-naversports', name: 'Naver Sports', nameKo: '네이버 스포츠', url: 'https://sports.naver.com', country: 'KR', group: 'kr-sports', rank: 1, free: true, note: '중계·기록 통합' },
  { id: 'kr-daumsports', name: 'Daum Sports', nameKo: '다음 스포츠', url: 'https://sports.daum.net', country: 'KR', group: 'kr-sports', rank: 2, free: true },
  { id: 'kr-natesports', name: 'Nate Sports', nameKo: '네이트 스포츠', url: 'https://m.news.nate.com/spo', country: 'KR', group: 'kr-sports', rank: 5, free: true },
  { id: 'kr-spotvnews', name: 'SPOTV News', nameKo: '스포티비뉴스', url: 'https://www.spotvnews.co.kr', country: 'KR', group: 'kr-sports', rank: 3, free: true },
  { id: 'kr-isplus', name: 'Ilgan Sports', nameKo: '일간스포츠', url: 'https://isplus.joins.com', country: 'KR', group: 'kr-sports', rank: 6, free: true },
  { id: 'kr-sportschosun', name: 'Sports Chosun', nameKo: '스포츠조선', url: 'https://sports.chosun.com', country: 'KR', group: 'kr-sports', rank: 7, free: true },
  { id: 'kr-sportsseoul', name: 'Sports Seoul', nameKo: '스포츠서울', url: 'https://www.sportsseoul.com', country: 'KR', group: 'kr-sports', rank: 9, free: true },
  { id: 'kr-mksports', name: 'MK Sports', nameKo: 'MK스포츠', url: 'https://mksports.co.kr', country: 'KR', group: 'kr-sports', rank: 10, free: true },
  { id: 'kr-sportskhan', name: 'Sports Kyunghyang', nameKo: '스포츠경향', url: 'https://sports.khan.co.kr', country: 'KR', group: 'kr-sports', rank: 11, free: true },
  { id: 'kr-sportsdonga', name: 'Sports Dong-A', nameKo: '스포츠동아', url: 'https://sports.donga.com', country: 'KR', group: 'kr-sports', rank: 8, free: true },
  { id: 'kr-sportshankooki', name: 'Sports Korea', nameKo: '스포츠한국', url: 'https://sports.hankooki.com', country: 'KR', group: 'kr-sports', rank: 15, free: true },
  { id: 'kr-ynasports', name: 'Yonhap Sports', nameKo: '연합뉴스 스포츠', url: 'https://www.yna.co.kr/sports/index', country: 'KR', group: 'kr-sports', rank: 12, free: true },
  { id: 'kr-kbssports', name: 'KBS Sports', nameKo: 'KBS 스포츠', url: 'https://news.kbs.co.kr/sports/subMain.do', country: 'KR', group: 'kr-sports', rank: 13, free: true },
  { id: 'kr-mbcsports', name: 'MBC Sports', nameKo: 'MBC 스포츠', url: 'https://m.imbc.com/sports/', country: 'KR', group: 'kr-sports', rank: 14, free: true },
  { id: 'kr-mlbpark', name: 'MLBPARK', nameKo: '엠엘비파크', url: 'https://mlbpark.donga.com', country: 'KR', group: 'kr-sports', rank: 4, free: true, note: '야구 중심 대형 커뮤니티' },

  // ─────────────────────── 연예 ───────────────────────
  { id: 'kr-naverent', name: 'Naver Entertainment', nameKo: '네이버 엔터', url: 'https://entertain.naver.com', country: 'KR', group: 'kr-entertainment', rank: 1, free: true },
  { id: 'kr-daument', name: 'Daum Entertainment', nameKo: '다음 연예', url: 'https://entertain.daum.net', country: 'KR', group: 'kr-entertainment', rank: 2, free: true },
  { id: 'kr-nateent', name: 'Nate Entertainment', nameKo: '네이트 연예', url: 'https://m.news.nate.com/ent', country: 'KR', group: 'kr-entertainment', rank: 4, free: true },
  { id: 'kr-dispatch', name: 'Dispatch', nameKo: '디스패치', url: 'https://www.dispatch.co.kr', country: 'KR', group: 'kr-entertainment', rank: 3, free: true, note: '연예 단독 보도로 유명' },
  { id: 'kr-starnews', name: 'Star News', nameKo: '스타뉴스', url: 'https://www.starnewskorea.com', country: 'KR', group: 'kr-entertainment', rank: 6, free: true },
  { id: 'kr-osen', name: 'OSEN', nameKo: 'OSEN', url: 'https://www.osen.co.kr', country: 'KR', group: 'kr-entertainment', rank: 5, free: true },
  { id: 'kr-tenasia', name: 'Ten Asia', nameKo: '텐아시아', url: 'https://www.tenasia.co.kr', country: 'KR', group: 'kr-entertainment', rank: 8, free: true },
  { id: 'kr-ize', name: 'ize', nameKo: '아이즈', url: 'https://www.ize.co.kr', country: 'KR', group: 'kr-entertainment', rank: 13, free: true },
  { id: 'kr-ohmystar', name: 'OhmyStar', nameKo: '오마이스타', url: 'https://star.ohmynews.com', country: 'KR', group: 'kr-entertainment', rank: 12, free: true },
  { id: 'kr-sbsent', name: 'SBS Entertainment', nameKo: 'SBS 연예뉴스', url: 'https://ent.sbs.co.kr', country: 'KR', group: 'kr-entertainment', rank: 7, free: true },
  { id: 'kr-mbcent', name: 'MBC Entertainment', nameKo: 'MBC 연예', url: 'https://enews.imbc.com', country: 'KR', group: 'kr-entertainment', rank: 9, free: true },
  { id: 'kr-kbsstar', name: 'KBS Star', nameKo: 'KBS 스타', url: 'https://kstar.kbs.co.kr', country: 'KR', group: 'kr-entertainment', rank: 10, free: true },
  { id: 'kr-ytnstar', name: 'YTN Star', nameKo: 'YTN 스타', url: 'https://star.ytn.co.kr', country: 'KR', group: 'kr-entertainment', rank: 11, free: true },

  // ─────────────────────── 법률 ───────────────────────
  { id: 'kr-lawtimes', name: 'Law Times', nameKo: '법률신문', url: 'https://www.lawtimes.co.kr', country: 'KR', group: 'kr-law', rank: 1, free: true, note: '국내 대표 법조 전문지' },
  { id: 'kr-koreanbar', name: 'Korean Bar News', nameKo: '법조신문', url: 'https://news.koreanbar.or.kr', country: 'KR', group: 'kr-law', rank: 2, free: true, note: '대한변협 발행' },
  { id: 'kr-ltn', name: 'Legal Broadcasting News', nameKo: '법률방송뉴스', url: 'https://www.ltn.kr', country: 'KR', group: 'kr-law', rank: 3, free: true },
  { id: 'kr-thel', name: 'The L', nameKo: '더엘', url: 'https://thel.mt.co.kr', country: 'KR', group: 'kr-law', rank: 4, free: true, note: '머니투데이 법조' },
  { id: 'kr-cwatch', name: 'Court Watch', nameKo: '코트워치', url: 'https://c-watch.org', country: 'KR', group: 'kr-law', rank: 5, free: true },
  { id: 'kr-lawleader', name: 'Law Leader', nameKo: '로리더', url: 'https://www.lawleader.co.kr', country: 'KR', group: 'kr-law', rank: 6, free: true },
  { id: 'kr-legaltimes', name: 'Legal Times', nameKo: '리걸타임즈', url: 'https://www.legaltimes.co.kr', country: 'KR', group: 'kr-law', rank: 7, free: true },
  { id: 'kr-worklaw', name: 'Monthly Labor Law', nameKo: '월간노동법률', url: 'https://www.worklaw.co.kr', country: 'KR', group: 'kr-law', rank: 8, free: true },
  { id: 'kr-lec', name: 'Law Journal', nameKo: '법률저널', url: 'http://www.lec.co.kr', country: 'KR', group: 'kr-law', rank: 9, free: true },
  { id: 'kr-lawfact', name: 'Korea Law Daily', nameKo: '한국법률일보', url: 'http://www.lawfact.co.kr', country: 'KR', group: 'kr-law', rank: 10, free: true },
  { id: 'kr-casenote', name: 'CaseNote', nameKo: '케이스노트', url: 'https://casenote.kr', country: 'KR', group: 'kr-law', rank: 11, free: true, note: '판례 무료 검색' },
  { id: 'kr-law-go', name: 'Korea Law Information Center', nameKo: '국가법령정보센터', url: 'https://www.law.go.kr', country: 'KR', group: 'kr-law', rank: 12, free: true, note: '법령 원문 공식' },

  // ─────────────────────── 세무·조세 ───────────────────────
  { id: 'kr-taxwatch', name: 'TaxWatch', nameKo: '택스워치', url: 'https://www.taxwatch.co.kr', country: 'KR', group: 'kr-tax', rank: 1, free: true },
  { id: 'kr-joseilbo', name: 'Jose Ilbo', nameKo: '조세일보', url: 'http://www.joseilbo.com', country: 'KR', group: 'kr-tax', rank: 2, free: true },
  { id: 'kr-sejungilbo', name: 'Sejung Ilbo', nameKo: '세정일보', url: 'https://www.sejungilbo.com', country: 'KR', group: 'kr-tax', rank: 3, free: true },
  { id: 'kr-tfmedia', name: 'Tax & Finance News', nameKo: '조세금융신문', url: 'https://www.tfmedia.co.kr', country: 'KR', group: 'kr-tax', rank: 4, free: true },
  { id: 'kr-taxtimes', name: 'Korea Tax Times', nameKo: '한국세정신문', url: 'http://www.taxtimes.co.kr', country: 'KR', group: 'kr-tax', rank: 5, free: true },
  { id: 'kr-intn', name: 'Daily NTN', nameKo: '일간NTN', url: 'https://www.intn.co.kr', country: 'KR', group: 'kr-tax', rank: 6, free: true },
  { id: 'kr-kacpta', name: 'Tax Accountant News', nameKo: '세무사신문', url: 'https://webzine.kacpta.or.kr', country: 'KR', group: 'kr-tax', rank: 7, free: true },
  { id: 'kr-joseplus', name: 'Jose Plus', nameKo: '조세플러스', url: 'http://joseplus.com', country: 'KR', group: 'kr-tax', rank: 8, free: true },
  { id: 'kr-hometax', name: 'Hometax', nameKo: '국세청 홈택스', url: 'https://www.hometax.go.kr', country: 'KR', group: 'kr-tax', rank: 9, free: true, note: '세금 신고·조회 공식' },

  // ─────────────────────── 환경·기후 ───────────────────────
  { id: 'kr-newspenguin', name: 'News Penguin', nameKo: '뉴스펭귄', url: 'https://www.newspenguin.com', country: 'KR', group: 'kr-environment', rank: 1, free: true, note: '기후위기 전문' },
  { id: 'kr-greenium', name: 'Greenium', nameKo: '그리니엄', url: 'https://greenium.kr', country: 'KR', group: 'kr-environment', rank: 2, free: true, note: 'ESG·기후테크' },
  { id: 'kr-hanienv', name: 'Hankyoreh Environment', nameKo: '한겨레 환경', url: 'https://www.hani.co.kr/arti/society/environment', country: 'KR', group: 'kr-environment', rank: 3, free: true },
  { id: 'kr-planet03', name: 'Planet03', nameKo: '플래닛03', url: 'https://www.planet03.com', country: 'KR', group: 'kr-environment', rank: 4, free: true },
  { id: 'kr-fksm', name: 'Environment News', nameKo: '환경신문', url: 'https://www.fksm.co.kr', country: 'KR', group: 'kr-environment', rank: 5, free: true },
  { id: 'kr-greenpost', name: 'Green Post Korea', nameKo: '그린포스트코리아', url: 'https://www.greenpostkorea.co.kr', country: 'KR', group: 'kr-environment', rank: 6, free: true },
  { id: 'kr-co2korea', name: 'CO2 Korea', nameKo: 'CO2', url: 'https://www.co2korea.com', country: 'KR', group: 'kr-environment', rank: 7, free: true },
  { id: 'kr-netzeronews', name: 'Net Zero News', nameKo: '넷제로뉴스', url: 'https://www.netzeronews.kr', country: 'KR', group: 'kr-environment', rank: 8, free: true },
  { id: 'kr-hkbs', name: 'Environment Daily', nameKo: '환경일보', url: 'https://www.hkbs.co.kr', country: 'KR', group: 'kr-environment', rank: 9, free: true },
  { id: 'kr-airkorea', name: 'AirKorea', nameKo: '에어코리아', url: 'https://www.airkorea.or.kr', country: 'KR', group: 'kr-environment', rank: 10, free: true, note: '실시간 대기질 공식 데이터' },

  // ─────────────────────── 농업·수산 ───────────────────────
  { id: 'kr-nongmin', name: 'Nongmin Shinmun', nameKo: '농민신문', url: 'https://www.nongmin.com', country: 'KR', group: 'kr-agri', rank: 1, free: true, note: '농협 발행 대표 농업지' },
  { id: 'kr-agrinet', name: 'Korea Farmers & Fishermen News', nameKo: '한국농어민신문', url: 'https://www.agrinet.co.kr', country: 'KR', group: 'kr-agri', rank: 2, free: true },
  { id: 'kr-kenews', name: 'Korea Rural Economic News', nameKo: '한국농촌경제신문', url: 'https://www.kenews.co.kr', country: 'KR', group: 'kr-agri', rank: 3, free: true },
  { id: 'kr-newsfarm', name: 'Korea Agriculture News', nameKo: '한국농업신문', url: 'https://www.newsfarm.co.kr', country: 'KR', group: 'kr-agri', rank: 4, free: true },
  { id: 'kr-aflnews', name: 'Agriculture Fisheries Livestock News', nameKo: '농수축산신문', url: 'https://www.aflnews.co.kr', country: 'KR', group: 'kr-agri', rank: 5, free: true },
  { id: 'kr-ikpnews', name: 'Korea Nongjeong', nameKo: '한국농정신문', url: 'https://www.ikpnews.net', country: 'KR', group: 'kr-agri', rank: 6, free: true },
  { id: 'kr-nongupin', name: 'Farmers Newspaper', nameKo: '농업인신문', url: 'https://www.nongupin.co.kr', country: 'KR', group: 'kr-agri', rank: 7, free: true },
  { id: 'kr-kamis', name: 'KAMIS', nameKo: '농산물유통정보 KAMIS', url: 'https://www.kamis.or.kr', country: 'KR', group: 'kr-agri', rank: 8, free: true, note: '농산물 도소매 시세 원본' },

  // ─────────────────────── 북한 ───────────────────────
  { id: 'kr-dailynk', name: 'Daily NK', nameKo: '데일리NK', url: 'https://www.dailynk.com', country: 'KR', group: 'kr-nk', rank: 1, free: true, note: '내부 소식통 기반 보도' },
  { id: 'kr-ynank', name: 'Yonhap NK Portal', nameKo: '연합뉴스 북한포털', url: 'https://www.yna.co.kr/nk/index', country: 'KR', group: 'kr-nk', rank: 2, free: true },
  { id: 'kr-joongangnk', name: 'JoongAng The NK', nameKo: '중앙일보 더북한', url: 'https://www.joongang.co.kr/nk', country: 'KR', group: 'kr-nk', rank: 3, free: true },
  { id: 'kr-news1nk', name: 'News1 NK', nameKo: '뉴스1 북한', url: 'https://www.news1.kr/nk', country: 'KR', group: 'kr-nk', rank: 4, free: true },
  { id: 'kr-rfakorean', name: 'RFA Korean', nameKo: 'RFA 자유아시아방송', url: 'https://www.rfa.org/korean/', country: 'KR', group: 'kr-nk', rank: 5, free: true },
  { id: 'kr-spnews', name: 'Seoul Pyongyang News', nameKo: 'SPN 서울평양뉴스', url: 'https://www.spnews.co.kr', country: 'KR', group: 'kr-nk', rank: 6, free: true },
  { id: 'kr-tongilnews', name: 'Tongil News', nameKo: '통일뉴스', url: 'https://www.tongilnews.com', country: 'KR', group: 'kr-nk', rank: 7, free: true },
  { id: 'kr-nkinfo', name: 'NK Info Portal', nameKo: '통일부 북한정보포털', url: 'https://nkinfo.unikorea.go.kr', country: 'KR', group: 'kr-nk', rank: 8, free: true, note: '정부 공식 통계·자료' },

  // ─────────────────────── 문화 (영화·책·여행) ───────────────────────
  { id: 'kr-cine21', name: 'Cine21', nameKo: '씨네21', url: 'http://www.cine21.com', country: 'KR', group: 'kr-culture', rank: 1, free: true, note: '국내 대표 영화 주간지' },
  { id: 'kr-maxmovie', name: 'MaxMovie', nameKo: '맥스무비', url: 'https://www.maxmovie.com', country: 'KR', group: 'kr-culture', rank: 7, free: true },
  { id: 'kr-cinephile', name: 'Cinephile', nameKo: '시네필', url: 'https://www.cinephile.kr', country: 'KR', group: 'kr-culture', rank: 8, free: true },
  { id: 'kr-movist', name: 'Movist', nameKo: '무비스트', url: 'https://www.movist.com', country: 'KR', group: 'kr-culture', rank: 3, free: true },
  { id: 'kr-kobis', name: 'KOBIS', nameKo: '영화관입장권 통합전산망', url: 'https://www.kobis.or.kr', country: 'KR', group: 'kr-culture', rank: 2, free: true, note: '박스오피스 공식 집계' },
  { id: 'kr-extmovie', name: 'Extreme Movie', nameKo: '익스트림무비', url: 'https://extmovie.com', country: 'KR', group: 'kr-culture', rank: 4, free: true },
  { id: 'kr-muko', name: 'Muko', nameKo: '무코', url: 'https://muko.kr', country: 'KR', group: 'kr-culture', rank: 6, free: true },
  { id: 'kr-4flix', name: '4Flix', nameKo: '포플릭스', url: 'https://www.4flix.co.kr', country: 'KR', group: 'kr-culture', rank: 5, free: true, note: 'OTT 신작 정보' },
  { id: 'kr-hanibook', name: 'Hankyoreh Books', nameKo: '한겨레 책', url: 'https://www.hani.co.kr/arti/culture/book', country: 'KR', group: 'kr-culture', rank: 15, free: true },
  { id: 'kr-chosunbook', name: 'Chosun Books', nameKo: '조선일보 책', url: 'https://www.chosun.com/culture-life/book/', country: 'KR', group: 'kr-culture', rank: 16, free: true },
  { id: 'kr-joongangbook', name: 'JoongAng Books', nameKo: '중앙일보 책', url: 'https://www.joongang.co.kr/culture/book', country: 'KR', group: 'kr-culture', rank: 17, free: true },
  { id: 'kr-ynabook', name: 'Yonhap Books', nameKo: '연합뉴스 책', url: 'https://www.yna.co.kr/culture/books', country: 'KR', group: 'kr-culture', rank: 18, free: true },
  { id: 'kr-travie', name: 'Travie', nameKo: '트래비', url: 'https://www.travie.com', country: 'KR', group: 'kr-culture', rank: 10, free: true, note: '여행 전문 매거진' },
  { id: 'kr-hktravel', name: 'Hankyung Travel', nameKo: '한경 트래블', url: 'https://www.hankyung.com/travel', country: 'KR', group: 'kr-culture', rank: 9, free: true },
  { id: 'kr-ktsketch', name: 'Travel Sketch', nameKo: '여행스케치', url: 'http://www.ktsketch.co.kr', country: 'KR', group: 'kr-culture', rank: 12, free: true },
  { id: 'kr-tripplus', name: 'Trip Plus', nameKo: '여행플러스', url: 'https://tripplus.co.kr', country: 'KR', group: 'kr-culture', rank: 11, free: true },
  { id: 'kr-wolgansan', name: 'Monthly Mountain', nameKo: '월간산', url: 'https://san.chosun.com', country: 'KR', group: 'kr-culture', rank: 13, free: true },
  { id: 'kr-ktxmagazine', name: 'KTX Magazine', nameKo: 'KTX매거진', url: 'https://www.ktxmagazine.kr', country: 'KR', group: 'kr-culture', rank: 14, free: true },

  // ─────────────────────── 커뮤니티 ───────────────────────
  { id: 'kr-dcinside', name: 'DCInside', nameKo: '디시인사이드', url: 'https://www.dcinside.com', country: 'KR', group: 'kr-community', rank: 1, free: true, note: '국내 최대 갤러리형 커뮤니티' },
  { id: 'kr-fmkorea', name: 'FMKorea', nameKo: '에펨코리아', url: 'https://www.fmkorea.com', country: 'KR', group: 'kr-community', rank: 2, free: true },
  { id: 'kr-clien', name: 'Clien', nameKo: '클리앙', url: 'https://www.clien.net', country: 'KR', group: 'kr-community', rank: 5, free: true, note: 'IT·가전 중심' },
  { id: 'kr-ppomppu', name: 'Ppomppu', nameKo: '뽐뿌', url: 'https://www.ppomppu.co.kr', country: 'KR', group: 'kr-community', rank: 4, free: true, note: '핫딜 정보의 원조' },
  { id: 'kr-theqoo', name: 'theqoo', nameKo: '더쿠', url: 'https://theqoo.net', country: 'KR', group: 'kr-community', rank: 3, free: true },
  { id: 'kr-blind', name: 'Blind', nameKo: '블라인드', url: 'https://www.teamblind.com/kr/', country: 'KR', group: 'kr-community', rank: 8, free: true, note: '직장인 익명 커뮤니티' },
  { id: 'kr-etoland', name: 'Etoland', nameKo: '이토랜드', url: 'https://www.etoland.co.kr', country: 'KR', group: 'kr-community', rank: 11, free: true },
  { id: 'kr-instiz', name: 'Instiz', nameKo: '인스티즈', url: 'https://www.instiz.net', country: 'KR', group: 'kr-community', rank: 6, free: true },
  { id: 'kr-humoruniv', name: 'Humor University', nameKo: '웃긴대학', url: 'https://humoruniv.com', country: 'KR', group: 'kr-community', rank: 14, free: true },
  { id: 'kr-pann', name: 'Nate Pann', nameKo: '네이트판', url: 'https://m.pann.nate.com', country: 'KR', group: 'kr-community', rank: 7, free: true },
  { id: 'kr-dogdrip', name: 'Dogdrip', nameKo: '개드립', url: 'https://www.dogdrip.net', country: 'KR', group: 'kr-community', rank: 10, free: true },
  { id: 'kr-arcalive', name: 'Arca Live', nameKo: '아카라이브', url: 'https://arca.live', country: 'KR', group: 'kr-community', rank: 9, free: true },
  { id: 'kr-slrclub', name: 'SLR Club', nameKo: 'SLR클럽', url: 'https://www.slrclub.com', country: 'KR', group: 'kr-community', rank: 13, free: true, note: '카메라 커뮤니티에서 출발' },
  { id: 'kr-gasengi', name: 'Gasengi', nameKo: '가생이닷컴', url: 'http://www.gasengi.com/m', country: 'KR', group: 'kr-community', rank: 20, free: true },
  { id: 'kr-todayhumor', name: 'Today Humor', nameKo: '오늘의유머', url: 'https://www.todayhumor.co.kr', country: 'KR', group: 'kr-community', rank: 12, free: true },
  { id: 'kr-ygosu', name: 'Ygosu', nameKo: '와이고수', url: 'https://www.ygosu.com', country: 'KR', group: 'kr-community', rank: 16, free: true },
  { id: 'kr-82cook', name: '82Cook', nameKo: '82쿡', url: 'https://www.82cook.com', country: 'KR', group: 'kr-community', rank: 15, free: true, note: '요리·생활 커뮤니티' },
  { id: 'kr-damoang', name: 'Damoang', nameKo: '다모앙', url: 'https://damoang.net', country: 'KR', group: 'kr-community', rank: 17, free: true },
  { id: 'kr-dmitory', name: 'Dmitory', nameKo: '디미토리', url: 'https://www.dmitory.com', country: 'KR', group: 'kr-community', rank: 18, free: true },
  { id: 'kr-hygall', name: 'Hygall', nameKo: '해연갤', url: 'https://hygall.com', country: 'KR', group: 'kr-community', rank: 19, free: true },
  { id: 'kr-dvdprime', name: 'DVD Prime', nameKo: 'DVD프라임', url: 'https://dvdprime.com', country: 'KR', group: 'kr-community', rank: 21, free: true, note: 'AV·홈시어터 중심' },
  { id: 'kr-thredic', name: 'Thredic', nameKo: '스레딕', url: 'https://thredic.com', country: 'KR', group: 'kr-community', rank: 22, free: true },

  // ─────────────────────── 한국 영자매체 ───────────────────────
  { id: 'kr-koreaherald', name: 'The Korea Herald', nameKo: '코리아헤럴드', url: 'https://www.koreaherald.com', country: 'KR', group: 'korea-en', rank: 1, free: true, note: '한국 대표 영자지' },
  { id: 'kr-koreatimes', name: 'The Korea Times', nameKo: '코리아타임스', url: 'https://www.koreatimes.co.kr', country: 'KR', group: 'korea-en', rank: 2, free: true },
  { id: 'kr-koreajoongang', name: 'Korea JoongAng Daily', nameKo: '코리아중앙데일리', url: 'https://koreajoongangdaily.joins.com', country: 'KR', group: 'korea-en', rank: 3, free: true },
  { id: 'kr-yonhap-en', name: 'Yonhap News English', nameKo: '연합뉴스 영문', url: 'https://en.yna.co.kr', country: 'KR', group: 'korea-en', rank: 4, free: true, note: '국가기간 통신사 영문판' },
  { id: 'kr-chosun-en', name: 'Chosun Ilbo English', nameKo: '조선일보 영문', url: 'https://www.chosun.com/english/', country: 'KR', group: 'korea-en', rank: 5, free: true },
  { id: 'kr-hani-en', name: 'Hankyoreh English', nameKo: '한겨레 영문', url: 'https://english.hani.co.kr', country: 'KR', group: 'korea-en', rank: 6, free: true },
  { id: 'kr-donga-en', name: 'Dong-A Ilbo English', nameKo: '동아일보 영문', url: 'https://www.donga.com/en', country: 'KR', group: 'korea-en', rank: 7, free: true },
  { id: 'kr-kedglobal', name: 'KED Global', nameKo: '한경 글로벌', url: 'https://www.kedglobal.com', country: 'KR', group: 'korea-en', rank: 8, free: true, note: '한국경제 영문 경제뉴스' },
  { id: 'kr-pulse', name: 'Pulse by Maeil Business', nameKo: '매경 펄스', url: 'https://pulsenews.co.kr', country: 'KR', group: 'korea-en', rank: 9, free: true },
  { id: 'kr-kbsworld', name: 'KBS WORLD', nameKo: 'KBS 월드', url: 'https://world.kbs.co.kr', country: 'KR', group: 'korea-en', rank: 10, free: true, note: '다국어 라디오·뉴스' },
  { id: 'kr-arirang', name: 'Arirang TV', nameKo: '아리랑TV', url: 'https://www.arirang.com', country: 'KR', group: 'korea-en', rank: 11, free: true },
];
