/**
 * 전세계 뉴스·리서치 사이트 디렉토리.
 * lekohoo.com 링크 모음(미국/영국/독일/프랑스/일본/중국/러시아/호주/베트남/영자신문/과학)을
 * 기준으로 삼고, 카테고리별 주요 매체와 리서치·데이터 사이트를 추가로 정리했다.
 */

import {
  DirectoryGroup,
  DirectoryGroupId,
  DirectoryScope,
  DirectorySite,
  MediaLean,
} from '@/types/directory';
import { KR_DIRECTORY_SITES } from '@/lib/constants/source-directory-kr';
import { WORLD_DIRECTORY_SITES } from '@/lib/constants/source-directory-world';
import { WORLD_EXTRA_SITES } from '@/lib/constants/source-directory-world-extra';
import { HUMOR_DIRECTORY_SITES } from '@/lib/constants/source-directory-humor';

export type { DirectoryGroup, DirectoryGroupId, DirectoryScope, DirectorySite, MediaLean };

export const DIRECTORY_COUNTRIES: Record<string, { flag: string; nameKo: string }> = {
  US: { flag: '🇺🇸', nameKo: '미국' },
  UK: { flag: '🇬🇧', nameKo: '영국' },
  KR: { flag: '🇰🇷', nameKo: '한국' },
  JP: { flag: '🇯🇵', nameKo: '일본' },
  CN: { flag: '🇨🇳', nameKo: '중국' },
  HK: { flag: '🇭🇰', nameKo: '홍콩' },
  TW: { flag: '🇹🇼', nameKo: '대만' },
  SG: { flag: '🇸🇬', nameKo: '싱가포르' },
  TH: { flag: '🇹🇭', nameKo: '태국' },
  ID: { flag: '🇮🇩', nameKo: '인도네시아' },
  VN: { flag: '🇻🇳', nameKo: '베트남' },
  IN: { flag: '🇮🇳', nameKo: '인도' },
  DE: { flag: '🇩🇪', nameKo: '독일' },
  FR: { flag: '🇫🇷', nameKo: '프랑스' },
  IT: { flag: '🇮🇹', nameKo: '이탈리아' },
  ES: { flag: '🇪🇸', nameKo: '스페인' },
  NL: { flag: '🇳🇱', nameKo: '네덜란드' },
  BE: { flag: '🇧🇪', nameKo: '벨기에' },
  CH: { flag: '🇨🇭', nameKo: '스위스' },
  RU: { flag: '🇷🇺', nameKo: '러시아' },
  LV: { flag: '🇱🇻', nameKo: '라트비아' },
  AU: { flag: '🇦🇺', nameKo: '호주' },
  NZ: { flag: '🇳🇿', nameKo: '뉴질랜드' },
  CA: { flag: '🇨🇦', nameKo: '캐나다' },
  BR: { flag: '🇧🇷', nameKo: '브라질' },
  AR: { flag: '🇦🇷', nameKo: '아르헨티나' },
  MX: { flag: '🇲🇽', nameKo: '멕시코' },
  UY: { flag: '🇺🇾', nameKo: '우루과이' },
  QA: { flag: '🇶🇦', nameKo: '카타르' },
  IL: { flag: '🇮🇱', nameKo: '이스라엘' },
  SA: { flag: '🇸🇦', nameKo: '사우디아라비아' },
  AE: { flag: '🇦🇪', nameKo: 'UAE' },
  ZA: { flag: '🇿🇦', nameKo: '남아공' },
  KE: { flag: '🇰🇪', nameKo: '케냐' },
  NG: { flag: '🇳🇬', nameKo: '나이지리아' },
  EU: { flag: '🇪🇺', nameKo: '유럽연합' },
  INT: { flag: '🌐', nameKo: '국제기구' },
  IE: { flag: '🇮🇪', nameKo: '아일랜드' },
  AT: { flag: '🇦🇹', nameKo: '오스트리아' },
  LU: { flag: '🇱🇺', nameKo: '룩셈부르크' },
  PT: { flag: '🇵🇹', nameKo: '포르투갈' },
  GR: { flag: '🇬🇷', nameKo: '그리스' },
  MT: { flag: '🇲🇹', nameKo: '몰타' },
  CY: { flag: '🇨🇾', nameKo: '키프로스' },
  SE: { flag: '🇸🇪', nameKo: '스웨덴' },
  NO: { flag: '🇳🇴', nameKo: '노르웨이' },
  DK: { flag: '🇩🇰', nameKo: '덴마크' },
  FI: { flag: '🇫🇮', nameKo: '핀란드' },
  IS: { flag: '🇮🇸', nameKo: '아이슬란드' },
  PL: { flag: '🇵🇱', nameKo: '폴란드' },
  CZ: { flag: '🇨🇿', nameKo: '체코' },
  SK: { flag: '🇸🇰', nameKo: '슬로바키아' },
  HU: { flag: '🇭🇺', nameKo: '헝가리' },
  RO: { flag: '🇷🇴', nameKo: '루마니아' },
  BG: { flag: '🇧🇬', nameKo: '불가리아' },
  HR: { flag: '🇭🇷', nameKo: '크로아티아' },
  RS: { flag: '🇷🇸', nameKo: '세르비아' },
  SI: { flag: '🇸🇮', nameKo: '슬로베니아' },
  UA: { flag: '🇺🇦', nameKo: '우크라이나' },
  EE: { flag: '🇪🇪', nameKo: '에스토니아' },
  LT: { flag: '🇱🇹', nameKo: '리투아니아' },
  BY: { flag: '🇧🇾', nameKo: '벨라루스' },
  TR: { flag: '🇹🇷', nameKo: '튀르키예' },
  IR: { flag: '🇮🇷', nameKo: '이란' },
  IQ: { flag: '🇮🇶', nameKo: '이라크' },
  JO: { flag: '🇯🇴', nameKo: '요르단' },
  LB: { flag: '🇱🇧', nameKo: '레바논' },
  KW: { flag: '🇰🇼', nameKo: '쿠웨이트' },
  EG: { flag: '🇪🇬', nameKo: '이집트' },
  MA: { flag: '🇲🇦', nameKo: '모로코' },
  DZ: { flag: '🇩🇿', nameKo: '알제리' },
  TZ: { flag: '🇹🇿', nameKo: '탄자니아' },
  UG: { flag: '🇺🇬', nameKo: '우간다' },
  ZW: { flag: '🇿🇼', nameKo: '짐바브웨' },
  RW: { flag: '🇷🇼', nameKo: '르완다' },
  ZM: { flag: '🇿🇲', nameKo: '잠비아' },
  SN: { flag: '🇸🇳', nameKo: '세네갈' },
  ET: { flag: '🇪🇹', nameKo: '에티오피아' },
  GH: { flag: '🇬🇭', nameKo: '가나' },
  CG: { flag: '🇨🇬', nameKo: '콩고공화국' },
  PK: { flag: '🇵🇰', nameKo: '파키스탄' },
  BD: { flag: '🇧🇩', nameKo: '방글라데시' },
  LK: { flag: '🇱🇰', nameKo: '스리랑카' },
  NP: { flag: '🇳🇵', nameKo: '네팔' },
  AF: { flag: '🇦🇫', nameKo: '아프가니스탄' },
  MN: { flag: '🇲🇳', nameKo: '몽골' },
  KZ: { flag: '🇰🇿', nameKo: '카자흐스탄' },
  UZ: { flag: '🇺🇿', nameKo: '우즈베키스탄' },
  KG: { flag: '🇰🇬', nameKo: '키르기스스탄' },
  TJ: { flag: '🇹🇯', nameKo: '타지키스탄' },
  GE: { flag: '🇬🇪', nameKo: '조지아' },
  AM: { flag: '🇦🇲', nameKo: '아르메니아' },
  AZ: { flag: '🇦🇿', nameKo: '아제르바이잔' },
  PH: { flag: '🇵🇭', nameKo: '필리핀' },
  MY: { flag: '🇲🇾', nameKo: '말레이시아' },
  KH: { flag: '🇰🇭', nameKo: '캄보디아' },
  MM: { flag: '🇲🇲', nameKo: '미얀마' },
  LA: { flag: '🇱🇦', nameKo: '라오스' },
  BN: { flag: '🇧🇳', nameKo: '브루나이' },
  CL: { flag: '🇨🇱', nameKo: '칠레' },
  CO: { flag: '🇨🇴', nameKo: '콜롬비아' },
  PE: { flag: '🇵🇪', nameKo: '페루' },
  VE: { flag: '🇻🇪', nameKo: '베네수엘라' },
  EC: { flag: '🇪🇨', nameKo: '에콰도르' },
  BO: { flag: '🇧🇴', nameKo: '볼리비아' },
  PY: { flag: '🇵🇾', nameKo: '파라과이' },
  CU: { flag: '🇨🇺', nameKo: '쿠바' },
  CR: { flag: '🇨🇷', nameKo: '코스타리카' },
  PA: { flag: '🇵🇦', nameKo: '파나마' },
  DO: { flag: '🇩🇴', nameKo: '도미니카공화국' },
  GT: { flag: '🇬🇹', nameKo: '과테말라' },
  FJ: { flag: '🇫🇯', nameKo: '피지' },
  PG: { flag: '🇵🇬', nameKo: '파푸아뉴기니' },
};

export const DIRECTORY_GROUPS: DirectoryGroup[] = [
  // ─────────── 국내 (이용량 많은 순) ───────────
  { id: 'kr-portal', label: '포털·통신사', labelEn: 'Portals & Agencies', icon: '🔎', description: '네이버·다음과 국내 뉴스통신사', scope: 'kr' },
  { id: 'kr-daily', label: '종합일간지', labelEn: 'Korean Dailies', icon: '📰', description: '조·중·동·한겨레·경향 등 전국 종합지', scope: 'kr' },
  { id: 'kr-broadcast', label: '방송뉴스', labelEn: 'Korean Broadcast', icon: '📺', description: '지상파·종편·보도 전문 채널', scope: 'kr' },
  { id: 'kr-economy', label: '경제지', labelEn: 'Korean Business', icon: '💹', description: '한경·매경 등 경제 전문 일간지', scope: 'kr' },
  { id: 'kr-stock', label: '증시·공시', labelEn: 'Korean Markets', icon: '📈', description: '시세·차트·전자공시 원본', scope: 'kr' },
  { id: 'kr-community', label: '커뮤니티', labelEn: 'Korean Communities', icon: '💬', description: '여론의 출발점이 되는 대형 커뮤니티', scope: 'kr' },
  { id: 'kr-entertainment', label: '연예', labelEn: 'Korean Entertainment', icon: '🎤', description: 'K-팝·드라마·연예 단독', scope: 'kr' },
  { id: 'kr-sports', label: '스포츠', labelEn: 'Korean Sports', icon: '⚾', description: '스포츠 전문지와 포털 중계', scope: 'kr' },
  { id: 'kr-it', label: 'IT·전자', labelEn: 'Korean Tech', icon: '💾', description: '반도체·통신·스타트업 전문지', scope: 'kr' },
  { id: 'kr-realestate', label: '부동산', labelEn: 'Korean Real Estate', icon: '🏠', description: '분양·재건축·시세 데이터', scope: 'kr' },
  { id: 'kr-crypto', label: '코인', labelEn: 'Korean Crypto', icon: '🪙', description: '가상자산·블록체인 전문 매체', scope: 'kr' },
  { id: 'kr-health', label: '건강', labelEn: 'Korean Health', icon: '💊', description: '일반 독자용 건강 정보', scope: 'kr' },
  { id: 'kr-opinion', label: '사설·칼럼', labelEn: 'Korean Opinion', icon: '✍️', description: '주요 일간지 논설면 바로가기', scope: 'kr' },
  { id: 'kr-game', label: '게임', labelEn: 'Korean Gaming', icon: '🎮', description: '게임 산업과 대형 커뮤니티', scope: 'kr' },
  { id: 'kr-auto', label: '자동차', labelEn: 'Korean Auto', icon: '🚗', description: '신차 시승기와 전장 산업', scope: 'kr' },
  { id: 'kr-culture', label: '영화·책·여행', labelEn: 'Korean Culture', icon: '🎞', description: '영화 매거진·서평·여행 매체', scope: 'kr' },
  { id: 'kr-progressive', label: '진보 성향', labelEn: 'Progressive', icon: '🔵', description: '진보 논조 매체 (종합지 제외)', scope: 'kr' },
  { id: 'kr-conservative', label: '보수 성향', labelEn: 'Conservative', icon: '🔴', description: '보수 논조 매체 (종합지 제외)', scope: 'kr' },
  { id: 'kr-cartoon', label: '시사만평', labelEn: 'Political Cartoons', icon: '🎨', description: '하루 한 컷으로 읽는 정치', scope: 'kr' },
  { id: 'kr-ai', label: 'AI', labelEn: 'Korean AI', icon: '🤖', description: '국내 AI·로봇 전문 매체', scope: 'kr' },
  { id: 'kr-science', label: '과학', labelEn: 'Korean Science', icon: '🔬', description: '연구 현장과 과학 저널리즘', scope: 'kr' },
  { id: 'kr-medical', label: '의학·제약', labelEn: 'Korean Medical', icon: '🩺', description: '의료계·바이오 산업 전문지', scope: 'kr' },
  { id: 'kr-investigative', label: '탐사보도', labelEn: 'Investigative', icon: '🔦', description: '비영리·심층 탐사 저널리즘', scope: 'kr' },
  { id: 'kr-industry', label: '산업별 전문지', labelEn: 'Korean Industry', icon: '🏭', description: '반도체·건설·에너지·철강·섬유', scope: 'kr' },
  { id: 'kr-law', label: '법률', labelEn: 'Korean Legal', icon: '⚖️', description: '법조 전문지와 판례·법령 원본', scope: 'kr' },
  { id: 'kr-military', label: '국방·군사', labelEn: 'Korean Defense', icon: '🪖', description: '방산 수출과 안보 이슈', scope: 'kr' },
  { id: 'kr-nk', label: '북한', labelEn: 'North Korea', icon: '🕊', description: '북한 동향 전문 매체와 정부 자료', scope: 'kr' },
  { id: 'kr-environment', label: '환경·기후', labelEn: 'Korean Environment', icon: '🌱', description: '기후위기·ESG·대기질 데이터', scope: 'kr' },
  { id: 'kr-tax', label: '세무·조세', labelEn: 'Korean Tax', icon: '🧾', description: '세정 뉴스와 신고 실무', scope: 'kr' },
  { id: 'kr-media', label: '언론 비평', labelEn: 'Media Watch', icon: '📢', description: '언론을 감시하는 매체', scope: 'kr' },
  { id: 'kr-agri', label: '농업·수산', labelEn: 'Korean Agriculture', icon: '🌾', description: '농정 뉴스와 농산물 시세', scope: 'kr' },
  { id: 'kr-humor', label: '유머·짤', labelEn: 'Korean Humor', icon: '😂', description: '국내 밈이 처음 만들어지는 유머 게시판', scope: 'kr' },
  { id: 'kr-webtoon', label: '웹툰', labelEn: 'Korean Webtoons', icon: '📱', description: '국내 웹툰 플랫폼', scope: 'kr' },
  { id: 'korea-en', label: '한국 영자매체', labelEn: 'Korea in English', icon: '🇰🇷', description: '한국 뉴스를 영어로 전하는 매체', scope: 'kr' },

  // ─────────── 해외 — 주제별 (이용량 많은 순) ───────────
  { id: 'portal', label: '포털·무료뉴스', labelEn: 'Portals & Free', icon: '🆓', description: '페이월 없이 볼 수 있는 뉴스', scope: 'global' },
  { id: 'broadcast', label: '방송 뉴스', labelEn: 'Broadcast News', icon: '📺', description: '미국 지상파·케이블 뉴스 네트워크', scope: 'global' },
  { id: 'us-daily', label: '미국 신문', labelEn: 'US Newspapers', icon: '📰', description: '전국지와 주요 도시 지역지', scope: 'global' },
  { id: 'business', label: '경제·비즈니스', labelEn: 'Business', icon: '💼', description: '기업·산업·거시경제 보도', scope: 'global' },
  { id: 'markets', label: '증시·투자', labelEn: 'Markets', icon: '📈', description: '시세·차트·투자 리서치 도구', scope: 'global' },
  { id: 'tech', label: '테크', labelEn: 'Technology', icon: '💻', description: 'IT·스타트업·제품 리뷰', scope: 'global' },
  { id: 'sports', label: '스포츠', labelEn: 'Sports', icon: '⚽', description: '미국·유럽 스포츠 매체', scope: 'global' },
  { id: 'entertainment', label: '연예·엔터', labelEn: 'Entertainment', icon: '🎬', description: '할리우드와 셀럽 뉴스', scope: 'global' },
  { id: 'meme', label: '밈', labelEn: 'Memes', icon: '🃏', description: '전세계 밈이 모이고 만들어지는 플랫폼', scope: 'global' },
  { id: 'humor', label: '유머 사이트', labelEn: 'Humor', icon: '😂', description: '나라별로 사람들이 실제로 웃으러 가는 곳', scope: 'global' },
  { id: 'satire', label: '풍자 뉴스', labelEn: 'Satire', icon: '🗞', description: '어니언식 가짜 뉴스로 진짜를 비트는 매체', scope: 'global' },
  { id: 'gif', label: 'GIF·움짤', labelEn: 'GIFs', icon: '🎞', description: '움짤 검색과 편집', scope: 'global' },
  { id: 'comic', label: '웹코믹', labelEn: 'Webcomics', icon: '✏️', description: '오래 연재된 영어권 웹코믹', scope: 'global' },
  { id: 'politics', label: '정치·시사', labelEn: 'Politics', icon: '🏛️', description: '워싱턴 정가와 정책 전문 매체', scope: 'global' },
  { id: 'science', label: '과학', labelEn: 'Science', icon: '🔬', description: '학술지와 과학 저널리즘', scope: 'global' },
  { id: 'ai', label: 'AI', labelEn: 'AI', icon: '🤖', description: 'AI 연구 발표와 산업 동향', scope: 'global' },
  { id: 'weekly', label: '주간지·매거진', labelEn: 'Weeklies', icon: '📖', description: '심층 분석과 장문 기사', scope: 'global' },
  { id: 'medical', label: '의학·건강', labelEn: 'Medical', icon: '🩺', description: '임상 저널과 보건 당국 발표', scope: 'global' },
  { id: 'opinion', label: '사설·오피니언', labelEn: 'Opinion', icon: '✍️', description: '주요 매체 논설·칼럼 섹션', scope: 'global' },
  { id: 'auto', label: '자동차', labelEn: 'Automotive', icon: '🚗', description: '신차 리뷰와 전기차 산업', scope: 'global' },
  { id: 'learning', label: '쉬운 영어뉴스', labelEn: 'Easy English', icon: '🎓', description: '난이도를 낮춘 영어 학습용 뉴스', scope: 'global' },
  { id: 'data', label: '통계·데이터', labelEn: 'Data', icon: '📊', description: '경제지표·통계 원본 데이터', scope: 'global' },
  { id: 'thinktank', label: '싱크탱크·리서치', labelEn: 'Think Tanks', icon: '🧠', description: '정책 보고서와 국제관계 분석', scope: 'global' },
  { id: 'agency', label: '뉴스 통신사', labelEn: 'News Agencies', icon: '📡', description: '전세계 언론이 인용하는 1차 취재원', scope: 'global' },

  // ─────────── 해외 — 국가·권역별 ───────────
  { id: 'uk', label: '영국·아일랜드', labelEn: 'UK & Ireland', icon: '🇬🇧', description: '영국 신문·방송과 아일랜드 매체', scope: 'global' },
  { id: 'asia-east', label: '동아시아', labelEn: 'East Asia', icon: '🏯', description: '일본·중국·홍콩·대만·몽골', scope: 'global' },
  { id: 'europe-west', label: '서유럽', labelEn: 'Western Europe', icon: '🇪🇺', description: '독일·프랑스·베네룩스·스위스·오스트리아', scope: 'global' },
  { id: 'middle-east', label: '중동', labelEn: 'Middle East', icon: '🕋', description: '걸프·이스라엘·이란·튀르키예·이집트', scope: 'global' },
  { id: 'asia-southeast', label: '동남아시아', labelEn: 'Southeast Asia', icon: '🌴', description: '싱가포르·베트남·태국·필리핀·인니', scope: 'global' },
  { id: 'asia-south', label: '남아시아', labelEn: 'South Asia', icon: '🕌', description: '인도·파키스탄·방글라데시·스리랑카·네팔', scope: 'global' },
  { id: 'oceania', label: '오세아니아', labelEn: 'Oceania', icon: '🇦🇺', description: '호주·뉴질랜드·태평양 도서국', scope: 'global' },
  { id: 'northam', label: '캐나다', labelEn: 'Canada', icon: '🇨🇦', description: '캐나다 영어·불어 매체', scope: 'global' },
  { id: 'latam', label: '중남미', labelEn: 'Latin America', icon: '🌎', description: '브라질·멕시코·아르헨티나 등', scope: 'global' },
  { id: 'europe-south', label: '남유럽', labelEn: 'Southern Europe', icon: '🏛', description: '이탈리아·스페인·포르투갈·그리스', scope: 'global' },
  { id: 'europe-east', label: '중·동유럽', labelEn: 'Central & Eastern Europe', icon: '🗺', description: '폴란드·체코·헝가리·발칸·우크라이나·발트', scope: 'global' },
  { id: 'russia', label: '러시아·구소련', labelEn: 'Russia', icon: '🇷🇺', description: '관영 매체와 망명 독립 매체', scope: 'global' },
  { id: 'africa', label: '아프리카', labelEn: 'Africa', icon: '🌍', description: '남아공·나이지리아·케냐 등 주요 영어 매체', scope: 'global' },
  { id: 'europe-nordic', label: '북유럽', labelEn: 'Nordics', icon: '❄️', description: '스웨덴·노르웨이·덴마크·핀란드·아이슬란드', scope: 'global' },
  { id: 'asia-central', label: '중앙아·코카서스', labelEn: 'Central Asia & Caucasus', icon: '⛰', description: '카자흐·우즈벡·조지아·아르메니아', scope: 'global' },
];

/** 그룹 id → scope 조회용 */
export const GROUP_SCOPE: Record<DirectoryGroupId, DirectoryScope> = DIRECTORY_GROUPS.reduce(
  (acc, group) => {
    acc[group.id] = group.scope;
    return acc;
  },
  {} as Record<DirectoryGroupId, DirectoryScope>
);

/** 사이트에 scope가 없으면 소속 그룹의 scope를 따른다 */
export function scopeOf(site: DirectorySite): DirectoryScope {
  return site.scope ?? GROUP_SCOPE[site.group];
}

const GLOBAL_DIRECTORY_SITES: DirectorySite[] = [
  // ─────────────────────────── 통신사 ───────────────────────────
  { id: 'dir-reuters', name: 'Reuters', nameKo: '로이터', url: 'https://www.reuters.com', country: 'UK', group: 'agency', rank: 1, free: true, note: '세계 최대 국제 통신사' },
  { id: 'dir-ap', name: 'AP News', nameKo: 'AP 통신', url: 'https://apnews.com', country: 'US', group: 'agency', rank: 2, free: true, note: '미국 최대 비영리 통신사' },
  { id: 'dir-afp', name: 'AFP', nameKo: 'AFP 통신', url: 'https://www.afp.com/en', country: 'FR', group: 'agency', rank: 3, free: true, note: '프랑스 국제 통신사' },
  { id: 'dir-bloomberg', name: 'Bloomberg', nameKo: '블룸버그', url: 'https://www.bloomberg.com', country: 'US', group: 'agency', rank: 4, note: '금융 데이터 기반 경제 통신사' },
  { id: 'dir-upi', name: 'UPI', nameKo: 'UPI 통신', url: 'https://www.upi.com', country: 'US', group: 'agency', rank: 11, free: true },
  { id: 'dir-kyodo', name: 'Kyodo News', nameKo: '교도통신', url: 'https://english.kyodonews.net', country: 'JP', group: 'agency', rank: 7, free: true },
  { id: 'dir-xinhua', name: 'Xinhua', nameKo: '신화통신', url: 'https://english.news.cn', country: 'CN', group: 'agency', rank: 5, free: true, note: '중국 관영 통신사' },
  { id: 'dir-tass', name: 'TASS', nameKo: '타스 통신', url: 'https://tass.com', country: 'RU', group: 'agency', rank: 6, free: true, note: '러시아 국영 통신사' },
  { id: 'dir-ansa', name: 'ANSA', nameKo: 'ANSA 통신', url: 'https://www.ansa.it/english/', country: 'IT', group: 'agency', rank: 9, free: true },
  { id: 'dir-efe', name: 'EFE', nameKo: 'EFE 통신', url: 'https://efe.com/en/', country: 'ES', group: 'agency', rank: 8, free: true },
  { id: 'dir-pti', name: 'Press Trust of India', nameKo: 'PTI 통신', url: 'https://www.ptinews.com', country: 'IN', group: 'agency', rank: 10, free: true },

  // ─────────────────────────── 미국 신문 ───────────────────────────
  { id: 'dir-nytimes', name: 'The New York Times', nameKo: '뉴욕타임스', url: 'https://www.nytimes.com', country: 'US', group: 'us-daily', rank: 1, rssUrl: 'https://rss.nytimes.com/services/xml/rss/nyt/HomePage.xml', note: '미국의 기록 신문' },
  { id: 'dir-usatoday', name: 'USA Today', nameKo: 'USA 투데이', url: 'https://www.usatoday.com', country: 'US', group: 'us-daily', rank: 3, free: true, note: '미국 최대 발행부수 전국지' },
  { id: 'dir-washingtonpost', name: 'The Washington Post', nameKo: '워싱턴포스트', url: 'https://www.washingtonpost.com', country: 'US', group: 'us-daily', rank: 2, note: '수도 워싱턴의 대표 일간지' },
  { id: 'dir-latimes', name: 'Los Angeles Times', nameKo: 'LA 타임스', url: 'https://www.latimes.com', country: 'US', group: 'us-daily', rank: 4, note: '서부 최대 일간지' },
  { id: 'dir-chicagotribune', name: 'Chicago Tribune', nameKo: '시카고 트리뷴', url: 'https://www.chicagotribune.com', country: 'US', group: 'us-daily', rank: 6, note: '중서부 대표 일간지' },
  { id: 'dir-bostonglobe', name: 'The Boston Globe', nameKo: '보스턴 글로브', url: 'https://www.bostonglobe.com', country: 'US', group: 'us-daily', rank: 7, note: '뉴잉글랜드 대표 일간지' },
  { id: 'dir-seattletimes', name: 'The Seattle Times', nameKo: '시애틀 타임스', url: 'https://www.seattletimes.com', country: 'US', group: 'us-daily', rank: 15, note: '태평양 북서부 대표지' },
  { id: 'dir-nypost', name: 'New York Post', nameKo: '뉴욕포스트', url: 'https://nypost.com', country: 'US', group: 'us-daily', rank: 5, free: true, note: '뉴욕 타블로이드' },
  { id: 'dir-houstonchronicle', name: 'Houston Chronicle', nameKo: '휴스턴 크로니클', url: 'https://www.houstonchronicle.com', country: 'US', group: 'us-daily', rank: 14, note: '텍사스 최대 일간지' },
  { id: 'dir-denverpost', name: 'The Denver Post', nameKo: '덴버 포스트', url: 'https://www.denverpost.com', country: 'US', group: 'us-daily', rank: 17 },
  { id: 'dir-sfchronicle', name: 'San Francisco Chronicle', nameKo: '샌프란시스코 크로니클', url: 'https://www.sfchronicle.com', country: 'US', group: 'us-daily', rank: 8, note: '실리콘밸리 지역 일간지' },
  { id: 'dir-inquirer', name: 'The Philadelphia Inquirer', nameKo: '필라델피아 인콰이어러', url: 'https://www.inquirer.com', country: 'US', group: 'us-daily', rank: 12 },
  { id: 'dir-azcentral', name: 'The Arizona Republic', nameKo: '애리조나 리퍼블릭', url: 'https://www.azcentral.com', country: 'US', group: 'us-daily', rank: 16 },
  { id: 'dir-miamiherald', name: 'Miami Herald', nameKo: '마이애미 헤럴드', url: 'https://www.miamiherald.com', country: 'US', group: 'us-daily', rank: 13, note: '중남미 소식에 강한 남부 일간지' },
  { id: 'dir-newsday', name: 'Newsday', nameKo: '뉴스데이', url: 'https://www.newsday.com', country: 'US', group: 'us-daily', rank: 10 },
  { id: 'dir-startribune', name: 'Star Tribune', nameKo: '스타 트리뷴', url: 'https://www.startribune.com', country: 'US', group: 'us-daily', rank: 11 },
  { id: 'dir-dallasnews', name: 'The Dallas Morning News', nameKo: '댈러스 모닝뉴스', url: 'https://www.dallasnews.com', country: 'US', group: 'us-daily', rank: 9 },
  { id: 'dir-tampabay', name: 'Tampa Bay Times', nameKo: '탬파베이 타임스', url: 'https://www.tampabay.com', country: 'US', group: 'us-daily', rank: 18 },

  // ─────────────────────────── 방송 뉴스 ───────────────────────────
  { id: 'dir-cnn', name: 'CNN', nameKo: 'CNN', url: 'https://www.cnn.com', country: 'US', group: 'broadcast', rank: 1, rssUrl: 'http://rss.cnn.com/rss/edition.rss', free: true, note: '24시간 케이블 뉴스의 원조' },
  { id: 'dir-nbcnews', name: 'NBC News', nameKo: 'NBC 뉴스', url: 'https://www.nbcnews.com', country: 'US', group: 'broadcast', rank: 4, rssUrl: 'https://feeds.nbcnews.com/nbcnews/public/news', free: true },
  { id: 'dir-foxnews', name: 'Fox News', nameKo: '폭스뉴스', url: 'https://www.foxnews.com', country: 'US', group: 'broadcast', rank: 2, rssUrl: 'https://moxie.foxnews.com/google-publisher/latest.xml', free: true, note: '보수 성향 케이블 뉴스' },
  { id: 'dir-abcnews', name: 'ABC News', nameKo: 'ABC 뉴스', url: 'https://abcnews.go.com', country: 'US', group: 'broadcast', rank: 3, rssUrl: 'https://feeds.abcnews.com/abcnews/topstories', free: true },
  { id: 'dir-cbsnews', name: 'CBS News', nameKo: 'CBS 뉴스', url: 'https://www.cbsnews.com', country: 'US', group: 'broadcast', rank: 5, rssUrl: 'https://www.cbsnews.com/latest/rss/main', free: true },
  { id: 'dir-msnbc', name: 'MSNBC', nameKo: 'MSNBC', url: 'https://www.msnbc.com', country: 'US', group: 'broadcast', rank: 6, free: true, note: '진보 성향 케이블 뉴스' },
  { id: 'dir-pbs', name: 'PBS NewsHour', nameKo: 'PBS 뉴스아워', url: 'https://www.pbs.org/newshour/', country: 'US', group: 'broadcast', rank: 7, rssUrl: 'https://www.pbs.org/newshour/feeds/rss/headlines', free: true, note: '공영방송 심층 뉴스' },

  // ─────────────────────────── 주간지 ───────────────────────────
  { id: 'dir-time', name: 'TIME', nameKo: '타임', url: 'https://time.com', country: 'US', group: 'weekly', rank: 1, rssUrl: 'https://time.com/feed/', note: '세계에서 가장 유명한 시사 주간지' },
  { id: 'dir-newsweek', name: 'Newsweek', nameKo: '뉴스위크', url: 'https://www.newsweek.com', country: 'US', group: 'weekly', rank: 2, rssUrl: 'https://www.newsweek.com/rss', free: true },
  { id: 'dir-usnews', name: 'U.S. News & World Report', nameKo: 'US 뉴스', url: 'https://www.usnews.com', country: 'US', group: 'weekly', rank: 5, note: '대학·병원 랭킹으로 유명' },
  { id: 'dir-atlantic', name: 'The Atlantic', nameKo: '디 애틀랜틱', url: 'https://www.theatlantic.com', country: 'US', group: 'weekly', rank: 3, rssUrl: 'https://www.theatlantic.com/feed/all/', note: '장문 에세이 중심의 시사지' },
  { id: 'dir-newyorker', name: 'The New Yorker', nameKo: '뉴요커', url: 'https://www.newyorker.com', country: 'US', group: 'weekly', rank: 4, rssUrl: 'https://www.newyorker.com/feed/everything', note: '탐사보도와 문예 비평' },
  { id: 'dir-nationalreview', name: 'National Review', nameKo: '내셔널 리뷰', url: 'https://www.nationalreview.com', country: 'US', group: 'weekly', rank: 6, note: '미국 보수 지성지' },
  { id: 'dir-motherjones', name: 'Mother Jones', nameKo: '마더 존스', url: 'https://www.motherjones.com', country: 'US', group: 'weekly', rank: 7, free: true, note: '진보 성향 탐사보도' },

  // ─────────────────────────── 경제·비즈니스 ───────────────────────────
  { id: 'dir-wsj', name: 'The Wall Street Journal', nameKo: '월스트리트저널', url: 'https://www.wsj.com', country: 'US', group: 'business', rank: 1, note: '미국 최고 권위 경제지' },
  { id: 'dir-cnbc', name: 'CNBC', nameKo: 'CNBC', url: 'https://www.cnbc.com', country: 'US', group: 'business', rank: 2, rssUrl: 'https://search.cnbc.com/rs/search/combinedcms/view.xml?partnerId=wrss01&id=100003114', free: true, note: '실시간 증시 방송' },
  { id: 'dir-forbes', name: 'Forbes', nameKo: '포브스', url: 'https://www.forbes.com', country: 'US', group: 'business', rank: 5, free: true, note: '기업인·부자 랭킹으로 유명' },
  { id: 'dir-fortune', name: 'Fortune', nameKo: '포춘', url: 'https://fortune.com', country: 'US', group: 'business', rank: 7, note: 'Fortune 500 발표' },
  { id: 'dir-businessinsider', name: 'Business Insider', nameKo: '비즈니스 인사이더', url: 'https://www.businessinsider.com', country: 'US', group: 'business', rank: 6, free: true },
  { id: 'dir-cnnbusiness', name: 'CNN Business', nameKo: 'CNN 비즈니스', url: 'https://www.cnn.com/business', country: 'US', group: 'business', rank: 9, free: true },
  { id: 'dir-thestreet', name: 'TheStreet', nameKo: '더스트리트', url: 'https://www.thestreet.com', country: 'US', group: 'business', rank: 14, free: true },
  { id: 'dir-barrons', name: "Barron's", nameKo: '배런스', url: 'https://www.barrons.com', country: 'US', group: 'business', rank: 8, note: '주간 투자 분석지' },
  { id: 'dir-ft', name: 'Financial Times', nameKo: '파이낸셜타임스', url: 'https://www.ft.com', country: 'UK', group: 'business', rank: 3, note: '글로벌 금융의 권위지' },
  { id: 'dir-economist', name: 'The Economist', nameKo: '이코노미스트', url: 'https://www.economist.com', country: 'UK', group: 'business', rank: 4, note: '세계 정세 분석 주간지' },
  { id: 'dir-nikkeiasia', name: 'Nikkei Asia', nameKo: '닛케이 아시아', url: 'https://asia.nikkei.com', country: 'JP', group: 'business', rank: 10, note: '아시아 경제 심층 보도' },
  { id: 'dir-caixin', name: 'Caixin Global', nameKo: '차이신 글로벌', url: 'https://www.caixinglobal.com', country: 'CN', group: 'business', rank: 11, note: '중국 대표 독립 경제지' },
  { id: 'dir-quartz', name: 'Quartz', nameKo: '쿼츠', url: 'https://qz.com', country: 'US', group: 'business', rank: 13, free: true },
  { id: 'dir-semafor', name: 'Semafor', nameKo: '세마포', url: 'https://www.semafor.com', country: 'US', group: 'business', rank: 12, free: true, note: '뉴스레터 기반 신흥 경제 매체' },

  // ─────────────────────────── 증시·투자 ───────────────────────────
  { id: 'dir-yahoofinance', name: 'Yahoo Finance', nameKo: '야후 파이낸스', url: 'https://finance.yahoo.com', country: 'US', group: 'markets', rank: 1, free: true, note: '무료 시세·재무제표의 표준' },
  { id: 'dir-marketwatch', name: 'MarketWatch', nameKo: '마켓워치', url: 'https://www.marketwatch.com', country: 'US', group: 'markets', rank: 4, rssUrl: 'https://feeds.content.dowjones.io/public/rss/mw_topstories', free: true },
  { id: 'dir-investing', name: 'Investing.com', nameKo: '인베스팅닷컴', url: 'https://www.investing.com', country: 'US', group: 'markets', rank: 3, free: true, note: '글로벌 시세·경제 캘린더' },
  { id: 'dir-seekingalpha', name: 'Seeking Alpha', nameKo: '시킹알파', url: 'https://seekingalpha.com', country: 'US', group: 'markets', rank: 7, note: '개인 투자자 리서치 커뮤니티' },
  { id: 'dir-tradingview', name: 'TradingView', nameKo: '트레이딩뷰', url: 'https://www.tradingview.com', country: 'US', group: 'markets', rank: 2, free: true, note: '차트 분석 표준 도구' },
  { id: 'dir-finviz', name: 'Finviz', nameKo: '핀비즈', url: 'https://finviz.com', country: 'US', group: 'markets', rank: 6, free: true, note: '주식 스크리너·히트맵' },
  { id: 'dir-morningstar', name: 'Morningstar', nameKo: '모닝스타', url: 'https://www.morningstar.com', country: 'US', group: 'markets', rank: 8, note: '펀드·ETF 평가의 기준' },
  { id: 'dir-investopedia', name: 'Investopedia', nameKo: '인베스토피디아', url: 'https://www.investopedia.com', country: 'US', group: 'markets', rank: 5, free: true, note: '금융 용어 사전' },
  { id: 'dir-secedgar', name: 'SEC EDGAR', nameKo: 'SEC 에드가', url: 'https://www.sec.gov/edgar/searchedgar/companysearch', country: 'US', group: 'markets', rank: 11, free: true, note: '미국 상장사 공시 원본' },
  { id: 'dir-coindesk', name: 'CoinDesk', nameKo: '코인데스크', url: 'https://www.coindesk.com', country: 'US', group: 'markets', rank: 9, rssUrl: 'https://www.coindesk.com/arc/outboundfeeds/rss/', free: true, note: '가상자산 대표 매체' },
  { id: 'dir-cointelegraph', name: 'Cointelegraph', nameKo: '코인텔레그래프', url: 'https://cointelegraph.com', country: 'US', group: 'markets', rank: 10, rssUrl: 'https://cointelegraph.com/rss', free: true },

  // ─────────────────────────── 사설·오피니언 ───────────────────────────
  { id: 'dir-nyt-opinion', name: 'NYT Opinion', nameKo: '뉴욕타임스 사설', url: 'https://www.nytimes.com/section/opinion', country: 'US', group: 'opinion', rank: 1, rssUrl: 'https://rss.nytimes.com/services/xml/rss/nyt/Opinion.xml' },
  { id: 'dir-wapo-opinion', name: 'Washington Post Opinions', nameKo: '워싱턴포스트 사설', url: 'https://www.washingtonpost.com/opinions/', country: 'US', group: 'opinion', rank: 2 },
  { id: 'dir-wsj-opinion', name: 'WSJ Opinion', nameKo: '월스트리트저널 사설', url: 'https://www.wsj.com/opinion', country: 'US', group: 'opinion', rank: 3 },
  { id: 'dir-fox-opinion', name: 'Fox News Opinion', nameKo: '폭스뉴스 사설', url: 'https://www.foxnews.com/opinion', country: 'US', group: 'opinion', rank: 4, free: true },
  { id: 'dir-guardian-opinion', name: 'Guardian Opinion', nameKo: '가디언 사설', url: 'https://www.theguardian.com/uk/commentisfree', country: 'UK', group: 'opinion', rank: 5, rssUrl: 'https://www.theguardian.com/uk/commentisfree/rss', free: true },
  { id: 'dir-latimes-opinion', name: 'LA Times Opinion', nameKo: 'LA타임스 사설', url: 'https://www.latimes.com/opinion', country: 'US', group: 'opinion', rank: 9 },
  { id: 'dir-projectsyndicate', name: 'Project Syndicate', nameKo: '프로젝트 신디케이트', url: 'https://www.project-syndicate.org', country: 'CH', group: 'opinion', rank: 8, note: '석학·정책결정자 칼럼 신디케이션' },
  { id: 'dir-foreignaffairs', name: 'Foreign Affairs', nameKo: '포린어페어스', url: 'https://www.foreignaffairs.com', country: 'US', group: 'opinion', rank: 6, note: '국제관계 권위 저널' },
  { id: 'dir-foreignpolicy', name: 'Foreign Policy', nameKo: '포린폴리시', url: 'https://foreignpolicy.com', country: 'US', group: 'opinion', rank: 7, rssUrl: 'https://foreignpolicy.com/feed/' },

  // ─────────────────────────── 정치·시사 ───────────────────────────
  { id: 'dir-politico', name: 'Politico', nameKo: '폴리티코', url: 'https://www.politico.com', country: 'US', group: 'politics', rank: 1, rssUrl: 'https://rss.politico.com/politics-news.xml', free: true, note: '워싱턴 정가 1위 매체' },
  { id: 'dir-thehill', name: 'The Hill', nameKo: '더 힐', url: 'https://thehill.com', country: 'US', group: 'politics', rank: 2, rssUrl: 'https://thehill.com/news/feed/', free: true, note: '의회 전문 매체' },
  { id: 'dir-axios', name: 'Axios', nameKo: '악시오스', url: 'https://www.axios.com', country: 'US', group: 'politics', rank: 3, rssUrl: 'https://api.axios.com/feed/', free: true, note: '요점만 짚는 짧은 뉴스' },
  { id: 'dir-vox', name: 'Vox', nameKo: '복스', url: 'https://www.vox.com', country: 'US', group: 'politics', rank: 5, rssUrl: 'https://www.vox.com/rss/index.xml', free: true, note: '뉴스 배경 설명 저널리즘' },
  { id: 'dir-huffpost', name: 'HuffPost', nameKo: '허프포스트', url: 'https://www.huffpost.com', country: 'US', group: 'politics', rank: 4, free: true },
  { id: 'dir-dailybeast', name: 'The Daily Beast', nameKo: '데일리 비스트', url: 'https://www.thedailybeast.com', country: 'US', group: 'politics', rank: 6, free: true },
  { id: 'dir-intercept', name: 'The Intercept', nameKo: '디 인터셉트', url: 'https://theintercept.com', country: 'US', group: 'politics', rank: 10, rssUrl: 'https://theintercept.com/feed/?rss', free: true, note: '국가안보 탐사보도' },
  { id: 'dir-slate', name: 'Slate', nameKo: '슬레이트', url: 'https://slate.com', country: 'US', group: 'politics', rank: 7, free: true },
  { id: 'dir-realclearpolitics', name: 'RealClearPolitics', nameKo: '리얼클리어폴리틱스', url: 'https://www.realclearpolitics.com', country: 'US', group: 'politics', rank: 9, free: true, note: '여론조사 평균 집계' },
  { id: 'dir-propublica', name: 'ProPublica', nameKo: '프로퍼블리카', url: 'https://www.propublica.org', country: 'US', group: 'politics', rank: 8, rssUrl: 'https://www.propublica.org/feeds/propublica/main', free: true, note: '비영리 탐사보도, 퓰리처 다수' },
  { id: 'dir-c-span', name: 'C-SPAN', nameKo: 'C-SPAN', url: 'https://www.c-span.org', country: 'US', group: 'politics', rank: 11, free: true, note: '의회 의사중계 원본' },

  // ─────────────────────────── 싱크탱크 ───────────────────────────
  { id: 'dir-brookings', name: 'Brookings Institution', nameKo: '브루킹스 연구소', url: 'https://www.brookings.edu', country: 'US', group: 'thinktank', rank: 1, free: true, note: '미국 최고 권위 정책 연구소' },
  { id: 'dir-cfr', name: 'Council on Foreign Relations', nameKo: '미국외교협회(CFR)', url: 'https://www.cfr.org', country: 'US', group: 'thinktank', rank: 2, free: true },
  { id: 'dir-csis', name: 'CSIS', nameKo: '전략국제문제연구소', url: 'https://www.csis.org', country: 'US', group: 'thinktank', rank: 5, free: true, note: '안보·한반도 분석에 강함' },
  { id: 'dir-carnegie', name: 'Carnegie Endowment', nameKo: '카네기 국제평화기금', url: 'https://carnegieendowment.org', country: 'US', group: 'thinktank', rank: 7, free: true },
  { id: 'dir-rand', name: 'RAND Corporation', nameKo: '랜드 연구소', url: 'https://www.rand.org', country: 'US', group: 'thinktank', rank: 4, free: true, note: '국방·정책 계량 분석' },
  { id: 'dir-chathamhouse', name: 'Chatham House', nameKo: '채텀하우스', url: 'https://www.chathamhouse.org', country: 'UK', group: 'thinktank', rank: 8, free: true },
  { id: 'dir-piie', name: 'PIIE', nameKo: '피터슨 국제경제연구소', url: 'https://www.piie.com', country: 'US', group: 'thinktank', rank: 11, free: true, note: '통상·무역 정책 분석' },
  { id: 'dir-atlanticcouncil', name: 'Atlantic Council', nameKo: '애틀랜틱 카운슬', url: 'https://www.atlanticcouncil.org', country: 'US', group: 'thinktank', rank: 9, free: true },
  { id: 'dir-pewresearch', name: 'Pew Research Center', nameKo: '퓨 리서치 센터', url: 'https://www.pewresearch.org', country: 'US', group: 'thinktank', rank: 3, free: true, note: '여론·사회조사 원본 데이터' },
  { id: 'dir-weforum', name: 'World Economic Forum', nameKo: '세계경제포럼', url: 'https://www.weforum.org/stories/', country: 'INT', group: 'thinktank', rank: 6, free: true },
  { id: 'dir-imfblog', name: 'IMF Blog', nameKo: 'IMF 블로그', url: 'https://www.imf.org/en/Blogs', country: 'INT', group: 'thinktank', rank: 10, free: true },
  { id: 'dir-38north', name: '38 North', nameKo: '38 노스', url: 'https://www.38north.org', country: 'US', group: 'thinktank', rank: 12, free: true, note: '북한 전문 분석' },

  // ─────────────────────────── 통계·데이터 ───────────────────────────
  { id: 'dir-fred', name: 'FRED', nameKo: '세인트루이스 연준 FRED', url: 'https://fred.stlouisfed.org', country: 'US', group: 'data', rank: 2, free: true, note: '미국 거시경제 지표의 표준' },
  { id: 'dir-tradingeconomics', name: 'Trading Economics', nameKo: '트레이딩이코노믹스', url: 'https://tradingeconomics.com', country: 'US', group: 'data', rank: 4, free: true, note: '196개국 지표 한 곳에' },
  { id: 'dir-ourworldindata', name: 'Our World in Data', nameKo: '아워월드인데이터', url: 'https://ourworldindata.org', country: 'UK', group: 'data', rank: 5, free: true, note: '장기 시계열 시각화' },
  { id: 'dir-statista', name: 'Statista', nameKo: '스태티스타', url: 'https://www.statista.com', country: 'DE', group: 'data', rank: 3, note: '산업 통계 요약' },
  { id: 'dir-worldbankdata', name: 'World Bank Data', nameKo: '세계은행 데이터', url: 'https://data.worldbank.org', country: 'INT', group: 'data', rank: 6, free: true },
  { id: 'dir-imfdata', name: 'IMF Data', nameKo: 'IMF 데이터', url: 'https://www.imf.org/en/Data', country: 'INT', group: 'data', rank: 7, free: true },
  { id: 'dir-oecddata', name: 'OECD Data Explorer', nameKo: 'OECD 데이터', url: 'https://data-explorer.oecd.org', country: 'INT', group: 'data', rank: 8, free: true },
  { id: 'dir-eurostat', name: 'Eurostat', nameKo: '유로스타트', url: 'https://ec.europa.eu/eurostat', country: 'EU', group: 'data', rank: 9, free: true },
  { id: 'dir-kosis', name: 'KOSIS', nameKo: '국가통계포털', url: 'https://kosis.kr', country: 'KR', group: 'data', rank: 11, free: true, note: '한국 공식 통계' },
  { id: 'dir-ecos', name: 'ECOS', nameKo: '한국은행 경제통계시스템', url: 'https://ecos.bok.or.kr', country: 'KR', group: 'data', rank: 12, free: true },
  { id: 'dir-googletrends', name: 'Google Trends', nameKo: '구글 트렌드', url: 'https://trends.google.com', country: 'US', group: 'data', rank: 1, free: true, note: '검색 관심도 추이' },
  { id: 'dir-undata', name: 'UN Data', nameKo: 'UN 데이터', url: 'https://data.un.org', country: 'INT', group: 'data', rank: 10, free: true },

  // ─────────────────────────── 테크 ───────────────────────────
  { id: 'dir-techcrunch', name: 'TechCrunch', nameKo: '테크크런치', url: 'https://techcrunch.com', country: 'US', group: 'tech', rank: 1, rssUrl: 'https://techcrunch.com/feed/', free: true, note: '스타트업·투자 소식' },
  { id: 'dir-theverge', name: 'The Verge', nameKo: '더 버지', url: 'https://www.theverge.com', country: 'US', group: 'tech', rank: 2, rssUrl: 'https://www.theverge.com/rss/index.xml', free: true },
  { id: 'dir-wired', name: 'WIRED', nameKo: '와이어드', url: 'https://www.wired.com', country: 'US', group: 'tech', rank: 4, rssUrl: 'https://www.wired.com/feed/rss', note: '기술과 문화의 교차점' },
  { id: 'dir-cnet', name: 'CNET', nameKo: '씨넷', url: 'https://www.cnet.com', country: 'US', group: 'tech', rank: 3, rssUrl: 'https://www.cnet.com/rss/news/', free: true, note: '제품 리뷰 중심' },
  { id: 'dir-arstechnica', name: 'Ars Technica', nameKo: '아스 테크니카', url: 'https://arstechnica.com', country: 'US', group: 'tech', rank: 7, rssUrl: 'https://feeds.arstechnica.com/arstechnica/index', free: true, note: '기술 심층 해설' },
  { id: 'dir-engadget', name: 'Engadget', nameKo: '엔가젯', url: 'https://www.engadget.com', country: 'US', group: 'tech', rank: 5, rssUrl: 'https://www.engadget.com/rss.xml', free: true },
  { id: 'dir-gizmodo', name: 'Gizmodo', nameKo: '기즈모도', url: 'https://gizmodo.com', country: 'US', group: 'tech', rank: 6, rssUrl: 'https://gizmodo.com/feed', free: true },
  { id: 'dir-zdnet', name: 'ZDNET', nameKo: 'ZDNet', url: 'https://www.zdnet.com', country: 'US', group: 'tech', rank: 8, rssUrl: 'https://www.zdnet.com/news/rss.xml', free: true, note: '엔터프라이즈 IT' },
  { id: 'dir-mitreview', name: 'MIT Technology Review', nameKo: 'MIT 테크놀로지 리뷰', url: 'https://www.technologyreview.com', country: 'US', group: 'tech', rank: 12, rssUrl: 'https://www.technologyreview.com/feed/', note: 'MIT 발행 기술 매체' },
  { id: 'dir-venturebeat', name: 'VentureBeat', nameKo: '벤처비트', url: 'https://venturebeat.com', country: 'US', group: 'tech', rank: 13, rssUrl: 'https://venturebeat.com/feed/', free: true },
  { id: 'dir-theinformation', name: 'The Information', nameKo: '디 인포메이션', url: 'https://www.theinformation.com', country: 'US', group: 'tech', rank: 15, note: '실리콘밸리 고급 단독 보도' },
  { id: 'dir-restofworld', name: 'Rest of World', nameKo: '레스트 오브 월드', url: 'https://restofworld.org', country: 'US', group: 'tech', rank: 17, rssUrl: 'https://restofworld.org/feed/latest', free: true, note: '비서구권 테크 현장' },
  { id: 'dir-techradar', name: 'TechRadar', nameKo: '테크레이더', url: 'https://www.techradar.com', country: 'UK', group: 'tech', rank: 9, free: true },
  { id: 'dir-tomshardware', name: "Tom's Hardware", nameKo: '톰스 하드웨어', url: 'https://www.tomshardware.com', country: 'US', group: 'tech', rank: 10, free: true, note: 'PC 하드웨어 벤치마크' },
  { id: 'dir-hackernews', name: 'Hacker News', nameKo: '해커뉴스', url: 'https://news.ycombinator.com', country: 'US', group: 'tech', rank: 11, free: true, note: '개발자 커뮤니티 랭킹' },
  { id: 'dir-producthunt', name: 'Product Hunt', nameKo: '프로덕트 헌트', url: 'https://www.producthunt.com', country: 'US', group: 'tech', rank: 14, free: true, note: '신규 제품 출시 큐레이션' },
  { id: 'dir-stratechery', name: 'Stratechery', nameKo: '스트라테커리', url: 'https://stratechery.com', country: 'TW', group: 'tech', rank: 16, note: '테크 산업 전략 분석' },

  // ─────────────────────────── AI ───────────────────────────
  { id: 'dir-anthropic-news', name: 'Anthropic News', nameKo: 'Anthropic 뉴스', url: 'https://www.anthropic.com/news', country: 'US', group: 'ai', rank: 2, free: true, note: 'Claude 개발사 공식 발표' },
  { id: 'dir-openai-blog', name: 'OpenAI Blog', nameKo: 'OpenAI 블로그', url: 'https://openai.com/news/', country: 'US', group: 'ai', rank: 1, free: true },
  { id: 'dir-deepmind', name: 'Google DeepMind Blog', nameKo: '딥마인드 블로그', url: 'https://deepmind.google/discover/blog/', country: 'UK', group: 'ai', rank: 4, free: true },
  { id: 'dir-huggingface', name: 'Hugging Face Blog', nameKo: '허깅페이스 블로그', url: 'https://huggingface.co/blog', country: 'US', group: 'ai', rank: 3, free: true, note: '오픈소스 모델 생태계' },
  { id: 'dir-arxiv-ai', name: 'arXiv cs.AI', nameKo: 'arXiv AI 논문', url: 'https://arxiv.org/list/cs.AI/recent', country: 'US', group: 'ai', rank: 5, free: true, note: 'AI 논문 프리프린트' },
  { id: 'dir-thebatch', name: 'The Batch', nameKo: '더 배치', url: 'https://www.deeplearning.ai/the-batch/', country: 'US', group: 'ai', rank: 7, free: true, note: 'Andrew Ng의 주간 AI 뉴스레터' },
  { id: 'dir-importai', name: 'Import AI', nameKo: '임포트 AI', url: 'https://importai.substack.com', country: 'US', group: 'ai', rank: 9, free: true },
  { id: 'dir-paperswithcode', name: 'alphaXiv', nameKo: '알파Xiv', url: 'https://www.alphaxiv.org', country: 'US', group: 'ai', rank: 8, free: true, note: '논문 토론·해설 플랫폼' },
  { id: 'dir-lmarena', name: 'LMArena', nameKo: 'LM 아레나', url: 'https://lmarena.ai', country: 'US', group: 'ai', rank: 6, free: true, note: 'LLM 블라인드 성능 순위' },

  // ─────────────────────────── 과학 ───────────────────────────
  { id: 'dir-science', name: 'Science', nameKo: '사이언스', url: 'https://www.science.org/news', country: 'US', group: 'science', rank: 4, note: '세계 최고 권위 학술지' },
  { id: 'dir-nature', name: 'Nature', nameKo: '네이처', url: 'https://www.nature.com', country: 'UK', group: 'science', rank: 2, rssUrl: 'https://www.nature.com/nature.rss', note: '세계 최고 권위 학술지' },
  { id: 'dir-natgeo', name: 'National Geographic', nameKo: '내셔널지오그래픽', url: 'https://www.nationalgeographic.com', country: 'US', group: 'science', rank: 1, note: '탐험·자연 다큐멘터리' },
  { id: 'dir-livescience', name: 'Live Science', nameKo: '라이브사이언스', url: 'https://www.livescience.com', country: 'US', group: 'science', rank: 6, free: true },
  { id: 'dir-physorg', name: 'Phys.org', nameKo: '피즈닷오알지', url: 'https://phys.org', country: 'UK', group: 'science', rank: 7, rssUrl: 'https://phys.org/rss-feed/', free: true, note: '연구 보도자료 집약' },
  { id: 'dir-sciencenews', name: 'Science News', nameKo: '사이언스 뉴스', url: 'https://www.sciencenews.org', country: 'US', group: 'science', rank: 12, rssUrl: 'https://www.sciencenews.org/feed', free: true },
  { id: 'dir-sciencedaily', name: 'ScienceDaily', nameKo: '사이언스데일리', url: 'https://www.sciencedaily.com', country: 'US', group: 'science', rank: 5, rssUrl: 'https://www.sciencedaily.com/rss/all.xml', free: true },
  { id: 'dir-sciencealert', name: 'ScienceAlert', nameKo: '사이언스얼랏', url: 'https://www.sciencealert.com', country: 'AU', group: 'science', rank: 11, free: true },
  { id: 'dir-sciam', name: 'Scientific American', nameKo: '사이언티픽 아메리칸', url: 'https://www.scientificamerican.com', country: 'US', group: 'science', rank: 3, note: '175년 역사의 과학 대중지' },
  { id: 'dir-nasascience', name: 'NASA Science', nameKo: 'NASA 사이언스', url: 'https://science.nasa.gov', country: 'US', group: 'science', rank: 10, free: true },
  { id: 'dir-newscientist', name: 'New Scientist', nameKo: '뉴 사이언티스트', url: 'https://www.newscientist.com', country: 'UK', group: 'science', rank: 9 },
  { id: 'dir-quantamagazine', name: 'Quanta Magazine', nameKo: '콴타 매거진', url: 'https://www.quantamagazine.org', country: 'US', group: 'science', rank: 13, rssUrl: 'https://api.quantamagazine.org/feed/', free: true, note: '수학·물리 심층 해설' },
  { id: 'dir-spacecom', name: 'Space.com', nameKo: '스페이스닷컴', url: 'https://www.space.com', country: 'US', group: 'science', rank: 8, free: true },
  { id: 'dir-arxiv', name: 'arXiv', nameKo: 'arXiv', url: 'https://arxiv.org', country: 'US', group: 'science', rank: 14, free: true, note: '물리·수학·CS 프리프린트' },

  // ─────────────────────────── 의학·건강 ───────────────────────────
  { id: 'dir-medscape', name: 'Medscape', nameKo: '메드스케이프', url: 'https://www.medscape.com', country: 'US', group: 'medical', rank: 2, note: '의료진 대상 임상 정보' },
  { id: 'dir-medicalnewstoday', name: 'Medical News Today', nameKo: '메디컬뉴스투데이', url: 'https://www.medicalnewstoday.com', country: 'UK', group: 'medical', rank: 3, free: true },
  { id: 'dir-medicalxpress', name: 'Medical Xpress', nameKo: '메디컬익스프레스', url: 'https://medicalxpress.com', country: 'UK', group: 'medical', rank: 7, rssUrl: 'https://medicalxpress.com/rss-feed/', free: true },
  { id: 'dir-statnews', name: 'STAT News', nameKo: '스탯 뉴스', url: 'https://www.statnews.com', country: 'US', group: 'medical', rank: 12, note: '바이오·제약 산업 전문' },
  { id: 'dir-nejm', name: 'NEJM', nameKo: '뉴잉글랜드 의학저널', url: 'https://www.nejm.org', country: 'US', group: 'medical', rank: 8, note: '임상의학 최고 권위지' },
  { id: 'dir-lancet', name: 'The Lancet', nameKo: '랜싯', url: 'https://www.thelancet.com', country: 'UK', group: 'medical', rank: 9, note: '200년 역사의 의학저널' },
  { id: 'dir-jama', name: 'JAMA', nameKo: '미국의사협회지', url: 'https://jamanetwork.com', country: 'US', group: 'medical', rank: 10 },
  { id: 'dir-bmj', name: 'The BMJ', nameKo: '영국의학저널', url: 'https://www.bmj.com', country: 'UK', group: 'medical', rank: 11 },
  { id: 'dir-webmd', name: 'WebMD', nameKo: '웹엠디', url: 'https://www.webmd.com', country: 'US', group: 'medical', rank: 1, free: true, note: '일반인 대상 건강 정보' },
  { id: 'dir-pubmed', name: 'PubMed', nameKo: '펍메드', url: 'https://pubmed.ncbi.nlm.nih.gov', country: 'US', group: 'medical', rank: 4, free: true, note: '의학 논문 검색의 표준' },
  { id: 'dir-cdc', name: 'CDC Newsroom', nameKo: '미국 질병통제예방센터', url: 'https://www.cdc.gov/media/', country: 'US', group: 'medical', rank: 6, free: true },
  { id: 'dir-who', name: 'WHO News', nameKo: '세계보건기구', url: 'https://www.who.int/news', country: 'INT', group: 'medical', rank: 5, free: true },

  // ─────────────────────────── 자동차 ───────────────────────────
  { id: 'dir-caranddriver', name: 'Car and Driver', nameKo: '카앤드라이버', url: 'https://www.caranddriver.com', country: 'US', group: 'auto', rank: 1, free: true, note: '미국 대표 자동차 잡지' },
  { id: 'dir-motortrend', name: 'MotorTrend', nameKo: '모터트렌드', url: 'https://www.motortrend.com', country: 'US', group: 'auto', rank: 2, free: true, note: '올해의 차 선정' },
  { id: 'dir-autoweek', name: 'Autoweek', nameKo: '오토위크', url: 'https://www.autoweek.com', country: 'US', group: 'auto', rank: 9, free: true },
  { id: 'dir-autoblog', name: 'Autoblog', nameKo: '오토블로그', url: 'https://www.autoblog.com', country: 'US', group: 'auto', rank: 3, free: true },
  { id: 'dir-motor1', name: 'Motor1', nameKo: '모터원', url: 'https://www.motor1.com', country: 'US', group: 'auto', rank: 5, free: true },
  { id: 'dir-electrek', name: 'Electrek', nameKo: '일렉트렉', url: 'https://electrek.co', country: 'US', group: 'auto', rank: 7, rssUrl: 'https://electrek.co/feed/', free: true, note: '전기차 전문' },
  { id: 'dir-insideevs', name: 'InsideEVs', nameKo: '인사이드EVs', url: 'https://insideevs.com', country: 'US', group: 'auto', rank: 8, free: true, note: '전기차 판매·기술' },
  { id: 'dir-jalopnik', name: 'Jalopnik', nameKo: '잘롭닉', url: 'https://www.jalopnik.com', country: 'US', group: 'auto', rank: 4, free: true },
  { id: 'dir-topgear', name: 'Top Gear', nameKo: '탑기어', url: 'https://www.topgear.com', country: 'UK', group: 'auto', rank: 6, free: true },

  // ─────────────────────────── 스포츠 ───────────────────────────
  { id: 'dir-espn', name: 'ESPN', nameKo: 'ESPN', url: 'https://www.espn.com', country: 'US', group: 'sports', rank: 1, rssUrl: 'https://www.espn.com/espn/rss/news', free: true, note: '세계 최대 스포츠 매체' },
  { id: 'dir-yahoosports', name: 'Yahoo Sports', nameKo: '야후 스포츠', url: 'https://sports.yahoo.com', country: 'US', group: 'sports', rank: 3, free: true },
  { id: 'dir-bleacherreport', name: 'Bleacher Report', nameKo: '블리처 리포트', url: 'https://bleacherreport.com', country: 'US', group: 'sports', rank: 6, free: true },
  { id: 'dir-si', name: 'Sports Illustrated', nameKo: '스포츠 일러스트레이티드', url: 'https://www.si.com', country: 'US', group: 'sports', rank: 8, free: true },
  { id: 'dir-sbnation', name: 'SB Nation', nameKo: 'SB 네이션', url: 'https://www.sbnation.com', country: 'US', group: 'sports', rank: 12, free: true },
  { id: 'dir-foxsports', name: 'FOX Sports', nameKo: '폭스 스포츠', url: 'https://www.foxsports.com', country: 'US', group: 'sports', rank: 5, free: true },
  { id: 'dir-cbssports', name: 'CBS Sports', nameKo: 'CBS 스포츠', url: 'https://www.cbssports.com', country: 'US', group: 'sports', rank: 4, free: true },
  { id: 'dir-nbcsports', name: 'NBC Sports', nameKo: 'NBC 스포츠', url: 'https://www.nbcsports.com', country: 'US', group: 'sports', rank: 10, free: true },
  { id: 'dir-theathletic', name: 'The Athletic', nameKo: '디 애슬레틱', url: 'https://www.nytimes.com/athletic/', country: 'US', group: 'sports', rank: 11, note: '심층 스포츠 저널리즘' },
  { id: 'dir-bbcsport', name: 'BBC Sport', nameKo: 'BBC 스포츠', url: 'https://www.bbc.com/sport', country: 'UK', group: 'sports', rank: 2, rssUrl: 'https://feeds.bbci.co.uk/sport/rss.xml', free: true },
  { id: 'dir-skysports', name: 'Sky Sports', nameKo: '스카이 스포츠', url: 'https://www.skysports.com', country: 'UK', group: 'sports', rank: 7, free: true },
  { id: 'dir-goal', name: 'Goal.com', nameKo: '골닷컴', url: 'https://www.goal.com/en', country: 'UK', group: 'sports', rank: 9, free: true, note: '축구 전문' },

  // ─────────────────────────── 연예 ───────────────────────────
  { id: 'dir-people', name: 'People', nameKo: '피플', url: 'https://people.com', country: 'US', group: 'entertainment', rank: 2, free: true },
  { id: 'dir-etonline', name: 'Entertainment Tonight', nameKo: 'ET 온라인', url: 'https://www.etonline.com', country: 'US', group: 'entertainment', rank: 10, free: true },
  { id: 'dir-tmz', name: 'TMZ', nameKo: 'TMZ', url: 'https://www.tmz.com', country: 'US', group: 'entertainment', rank: 1, rssUrl: 'https://www.tmz.com/rss.xml', free: true, note: '셀럽 속보에 가장 빠름' },
  { id: 'dir-variety', name: 'Variety', nameKo: '버라이어티', url: 'https://variety.com', country: 'US', group: 'entertainment', rank: 5, rssUrl: 'https://variety.com/feed/', free: true, note: '엔터 산업 트레이드지' },
  { id: 'dir-hollywoodreporter', name: 'The Hollywood Reporter', nameKo: '할리우드 리포터', url: 'https://www.hollywoodreporter.com', country: 'US', group: 'entertainment', rank: 6, rssUrl: 'https://www.hollywoodreporter.com/feed/', free: true },
  { id: 'dir-deadline', name: 'Deadline', nameKo: '데드라인', url: 'https://deadline.com', country: 'US', group: 'entertainment', rank: 8, rssUrl: 'https://deadline.com/feed/', free: true, note: '캐스팅·계약 단독' },
  { id: 'dir-usweekly', name: 'Us Weekly', nameKo: 'US 위클리', url: 'https://www.usmagazine.com', country: 'US', group: 'entertainment', rank: 11, free: true },
  { id: 'dir-eonline', name: 'E! Online', nameKo: 'E! 온라인', url: 'https://www.eonline.com', country: 'US', group: 'entertainment', rank: 7, free: true },
  { id: 'dir-buzzfeed', name: 'BuzzFeed', nameKo: '버즈피드', url: 'https://www.buzzfeed.com', country: 'US', group: 'entertainment', rank: 3, free: true },
  { id: 'dir-rollingstone', name: 'Rolling Stone', nameKo: '롤링스톤', url: 'https://www.rollingstone.com', country: 'US', group: 'entertainment', rank: 9, rssUrl: 'https://www.rollingstone.com/feed/', free: true },
  { id: 'dir-billboard', name: 'Billboard', nameKo: '빌보드', url: 'https://www.billboard.com', country: 'US', group: 'entertainment', rank: 4, free: true, note: '음악 차트의 기준' },
  { id: 'dir-indiewire', name: 'IndieWire', nameKo: '인디와이어', url: 'https://www.indiewire.com', country: 'US', group: 'entertainment', rank: 12, free: true },

  // ─────────────────────────── 쉬운 영어뉴스 ───────────────────────────
  { id: 'dir-newsinlevels', name: 'News in Levels', nameKo: '뉴스인레벨스', url: 'https://www.newsinlevels.com', country: 'US', group: 'learning', rank: 3, free: true, note: '같은 기사를 3단계 난이도로' },
  { id: 'dir-voalearning', name: 'VOA Learning English', nameKo: 'VOA 러닝 잉글리시', url: 'https://learningenglish.voanews.com', country: 'US', group: 'learning', rank: 2, free: true, note: '느린 속도 오디오 제공' },
  { id: 'dir-bbclearning', name: 'BBC Learning English', nameKo: 'BBC 러닝 잉글리시', url: 'https://www.bbc.co.uk/learningenglish/', country: 'UK', group: 'learning', rank: 1, free: true, note: '6 Minute English로 유명' },
  { id: 'dir-newsforkids', name: 'News for Kids', nameKo: '뉴스포키즈', url: 'https://newsforkids.net', country: 'US', group: 'learning', rank: 9, free: true },
  { id: 'dir-dogonews', name: 'DOGO News', nameKo: '도고 뉴스', url: 'https://www.dogonews.com', country: 'US', group: 'learning', rank: 8, free: true },
  { id: 'dir-timeforkids', name: 'TIME for Kids', nameKo: '타임 포 키즈', url: 'https://www.timeforkids.com', country: 'US', group: 'learning', rank: 7, free: true },
  { id: 'dir-engoo', name: 'Engoo Daily News', nameKo: '엔구 데일리뉴스', url: 'https://engoo.com/app/daily-news', country: 'JP', group: 'learning', rank: 5, free: true, note: '토론 질문까지 제공' },
  { id: 'dir-cnn10', name: 'CNN 10', nameKo: 'CNN 10', url: 'https://edition.cnn.com/cnn10', country: 'US', group: 'learning', rank: 4, free: true, note: '10분짜리 학생용 뉴스 영상' },
  { id: 'dir-simpleenglishnews', name: 'Simple English News', nameKo: '심플 잉글리시 뉴스', url: 'https://simpleenglishnews.com', country: 'US', group: 'learning', rank: 10, free: true },
  { id: 'dir-breakingnewsenglish', name: 'Breaking News English', nameKo: '브레이킹 뉴스 잉글리시', url: 'https://breakingnewsenglish.com', country: 'UK', group: 'learning', rank: 6, free: true, note: '레벨별 워크시트 무료' },
  { id: 'dir-practicewithnews', name: 'Practice with News', nameKo: '프랙티스 위드 뉴스', url: 'https://practicewithnews.com', country: 'US', group: 'learning', rank: 11, free: true },

  // ─────────────────────────── 포털·무료뉴스 ───────────────────────────
  { id: 'dir-googlenews', name: 'Google News', nameKo: '구글 뉴스', url: 'https://news.google.com', country: 'US', group: 'portal', rank: 1, free: true, note: '알고리즘 집계 포털' },
  { id: 'dir-yahoonews', name: 'Yahoo News', nameKo: '야후 뉴스', url: 'https://news.yahoo.com', country: 'US', group: 'portal', rank: 2, free: true },
  { id: 'dir-msn', name: 'MSN News', nameKo: 'MSN 뉴스', url: 'https://www.msn.com/en-us/news', country: 'US', group: 'portal', rank: 3, free: true },
  { id: 'dir-aol', name: 'AOL News', nameKo: 'AOL 뉴스', url: 'https://www.aol.com/news/', country: 'US', group: 'portal', rank: 5, free: true },
  { id: 'dir-npr', name: 'NPR', nameKo: 'NPR', url: 'https://www.npr.org', country: 'US', group: 'portal', rank: 4, rssUrl: 'https://feeds.npr.org/1001/rss.xml', free: true, note: '미국 공영 라디오, 전면 무료' },
  { id: 'dir-voa', name: 'VOA News', nameKo: '미국의 소리(VOA)', url: 'https://www.voanews.com', country: 'US', group: 'portal', rank: 6, free: true, note: '미국 정부 운영, 저작권 자유' },
  { id: 'dir-newser', name: 'Newser', nameKo: '뉴저', url: 'https://www.newser.com', country: 'US', group: 'portal', rank: 9, free: true, note: '기사를 짧게 요약해 제공' },
  { id: 'dir-groundnews', name: 'Ground News', nameKo: '그라운드 뉴스', url: 'https://ground.news', country: 'CA', group: 'portal', rank: 7, free: true, note: '같은 사건의 좌·우 보도 비교' },
  { id: 'dir-allsides', name: 'AllSides', nameKo: '올사이즈', url: 'https://www.allsides.com', country: 'US', group: 'portal', rank: 8, free: true, note: '매체별 정치 편향 등급 공개' },
  { id: 'dir-memeorandum', name: 'memeorandum', nameKo: '미모랜덤', url: 'https://www.memeorandum.com', country: 'US', group: 'portal', rank: 10, free: true, note: '정치 뉴스 실시간 클러스터링' },

];

/** 국내 + 해외(주제별) + 해외(국가별) + 트래픽 보강 + 유머·밈 전체 */
export const DIRECTORY_SITES: DirectorySite[] = [
  ...KR_DIRECTORY_SITES,
  ...GLOBAL_DIRECTORY_SITES,
  ...WORLD_DIRECTORY_SITES,
  ...WORLD_EXTRA_SITES,
  ...HUMOR_DIRECTORY_SITES,
];

/**
 * 그룹 id → 사이트 배열.
 * 그룹은 DIRECTORY_GROUPS 순서(카테고리 인기순), 사이트는 rank 순으로 나온다.
 */
export function groupDirectorySites(sites: DirectorySite[] = DIRECTORY_SITES) {
  const byGroup = new Map<DirectoryGroupId, DirectorySite[]>();
  for (const site of sites) {
    const bucket = byGroup.get(site.group);
    if (bucket) bucket.push(site);
    else byGroup.set(site.group, [site]);
  }
  return DIRECTORY_GROUPS.filter(g => byGroup.has(g.id)).map(group => ({
    group,
    sites: byGroup.get(group.id)!.sort((a, b) => a.rank - b.rank),
  }));
}
