import { DirectorySite } from '@/types/directory';

/**
 * 「쓰는」 사이트 디렉토리 — 둘째 묶음.
 *
 * 기준과 제외 규칙은 source-directory-tools.ts 의 주석과 같다.
 * 파일을 나눈 이유는 순전히 길이 때문이다.
 */
export const TOOLS_DIRECTORY_SITES_2: DirectorySite[] = [
  // ══════════════════════════ 파일 변환·웹 유틸 ══════════════════════════
  { id: 't-util-ilovepdf', name: 'iLovePDF', nameKo: '아이러브PDF', url: 'https://www.ilovepdf.com', country: 'ES', group: 't-util', rank: 1, free: true, note: 'PDF 합치기·나누기·압축을 한자리에서' },
  { id: 't-util-smallpdf', name: 'Smallpdf', nameKo: '스몰PDF', url: 'https://smallpdf.com', country: 'CH', group: 't-util', rank: 2, free: true, note: '스위스 서버, 처리 후 파일을 지운다' },
  { id: 't-util-stirling', name: 'Stirling PDF', nameKo: '스털링 PDF', url: 'https://www.stirlingpdf.com', country: 'UK', group: 't-util', rank: 3, free: true, note: '내 서버에 올려 쓰는 오픈소스 PDF 도구' },
  { id: 't-util-pdf24', name: 'PDF24 Tools', nameKo: 'PDF24', url: 'https://tools.pdf24.org', country: 'DE', group: 't-util', rank: 4, free: true, note: '용량 제한 없이 전부 무료' },
  { id: 't-util-cloudconvert', name: 'CloudConvert', nameKo: '클라우드컨버트', url: 'https://cloudconvert.com', country: 'DE', group: 't-util', rank: 5, free: true, note: '200여 개 포맷 사이를 오간다' },
  { id: 't-util-convertio', name: 'Convertio', nameKo: '컨버티오', url: 'https://convertio.co', country: 'EE', group: 't-util', rank: 6, free: true },
  { id: 't-util-handbrake', name: 'HandBrake', nameKo: '핸드브레이크', url: 'https://handbrake.fr', country: 'INT', group: 't-util', rank: 7, free: true, note: '영상 재인코딩의 오픈소스 표준' },
  { id: 't-util-vlc', name: 'VLC', nameKo: 'VLC', url: 'https://www.videolan.org/vlc/', country: 'FR', group: 't-util', rank: 8, free: true, note: '코덱 걱정 없이 다 열리는 재생기' },
  { id: 't-util-7zip', name: '7-Zip', nameKo: '7집', url: 'https://www.7-zip.org', country: 'RU', group: 't-util', rank: 9, free: true, note: '압축 프로그램은 이거 하나면 끝난다' },
  { id: 't-util-cyberchef', name: 'CyberChef', nameKo: '사이버셰프', url: 'https://gchq.github.io/CyberChef/', country: 'UK', group: 't-util', rank: 10, free: true, note: '인코딩·암호·해시를 레시피처럼 조합' },
  { id: 't-util-diffchecker', name: 'Diffchecker', nameKo: '디프체커', url: 'https://www.diffchecker.com', country: 'CA', group: 't-util', rank: 11, free: true, note: '두 문서·이미지의 달라진 곳만 짚어 준다' },
  { id: 't-util-carbon', name: 'Carbon', nameKo: '카본', url: 'https://carbon.now.sh', country: 'US', group: 't-util', rank: 12, free: true, note: '코드를 예쁜 이미지로 만들어 공유' },
  { id: 't-util-timeis', name: 'time.is', nameKo: '타임이즈', url: 'https://time.is', country: 'NO', group: 't-util', rank: 13, free: true, note: '초 단위로 정확한 현재 시각' },
  { id: 't-util-wtb', name: 'World Time Buddy', nameKo: '월드 타임 버디', url: 'https://www.worldtimebuddy.com', country: 'US', group: 't-util', rank: 14, free: true, note: '여러 도시 시차를 한 줄에 겹쳐 본다' },
  { id: 't-util-speedtest', name: 'Speedtest', nameKo: '스피드테스트', url: 'https://www.speedtest.net', country: 'US', group: 't-util', rank: 15, free: true, note: '인터넷 속도 측정의 표준' },
  { id: 't-util-fast', name: 'Fast.com', nameKo: '패스트닷컴', url: 'https://fast.com', country: 'US', group: 't-util', rank: 16, free: true, note: '넷플릭스가 만든 군더더기 없는 속도 측정' },
  { id: 't-util-wetransfer', name: 'WeTransfer', nameKo: '위트랜스퍼', url: 'https://wetransfer.com', country: 'NL', group: 't-util', rank: 17, free: true, note: '가입 없이 대용량 파일을 보낸다' },
  { id: 't-util-sendanywhere', name: 'Send Anywhere', nameKo: '샌드 애니웨어', url: 'https://send-anywhere.com', country: 'KR', group: 't-util', rank: 18, free: true, note: '여섯 자리 키로 기기 간 직접 전송' },
  { id: 't-util-emojipedia', name: 'Emojipedia', nameKo: '이모지피디아', url: 'https://emojipedia.org', country: 'US', group: 't-util', rank: 19, free: true, note: '이모지가 기기마다 어떻게 보이는지' },
  { id: 't-util-qrmonkey', name: 'QRCode Monkey', nameKo: 'QR코드 몽키', url: 'https://www.qrcode-monkey.com', country: 'DE', group: 't-util', rank: 20, free: true, note: '기간 제한 없는 QR 코드 생성' },
  { id: 't-util-ninite', name: 'Ninite', nameKo: '나이나이트', url: 'https://ninite.com', country: 'US', group: 't-util', rank: 21, free: true, note: '윈도우 새로 깔고 프로그램을 한 번에' },
  { id: 't-util-jsonlint', name: 'JSONLint', nameKo: 'JSON린트', url: 'https://jsonlint.com', country: 'US', group: 't-util', rank: 22, free: true, note: 'JSON 어디가 깨졌는지 짚어 준다' },

  // ══════════════════════════ 공공데이터·통계 ══════════════════════════
  { id: 't-stat-owid', name: 'Our World in Data', nameKo: '아워 월드 인 데이터', url: 'https://ourworldindata.org', country: 'UK', group: 't-stat', rank: 1, free: true, note: '세계 문제를 그래프로 설명하는 옥스퍼드 프로젝트' },
  { id: 't-stat-worldbank', name: 'World Bank Open Data', nameKo: '세계은행 오픈데이터', url: 'https://data.worldbank.org', country: 'INT', group: 't-stat', rank: 2, free: true, note: '거의 모든 나라의 개발 지표 원본' },
  { id: 't-stat-imf', name: 'IMF Data', nameKo: 'IMF 데이터', url: 'https://www.imf.org/en/Data', country: 'INT', group: 't-stat', rank: 3, free: true, note: '환율·재정·국제수지 공식 통계' },
  { id: 't-stat-oecd', name: 'OECD Data Explorer', nameKo: 'OECD 데이터', url: 'https://data-explorer.oecd.org', country: 'INT', group: 't-stat', rank: 4, free: true, note: '선진국 비교 통계의 기준' },
  { id: 't-stat-fred', name: 'FRED', nameKo: '프레드', url: 'https://fred.stlouisfed.org', country: 'US', group: 't-stat', rank: 5, free: true, note: '80만 개 경제 시계열, 그래프를 바로 만든다' },
  { id: 't-stat-undata', name: 'UN Data', nameKo: 'UN 데이터', url: 'https://data.un.org', country: 'INT', group: 't-stat', rank: 6, free: true },
  { id: 't-stat-eurostat', name: 'Eurostat', nameKo: '유로스타트', url: 'https://ec.europa.eu/eurostat', country: 'EU', group: 't-stat', rank: 7, free: true, note: 'EU 공식 통계청' },
  { id: 't-stat-kosis', name: 'KOSIS 국가통계포털', nameKo: '국가통계포털', url: 'https://kosis.kr', country: 'KR', group: 't-stat', rank: 8, free: true, note: '한국 통계는 여기가 1차 출처' },
  { id: 't-stat-tradingeconomics', name: 'Trading Economics', nameKo: '트레이딩 이코노믹스', url: 'https://tradingeconomics.com', country: 'US', group: 't-stat', rank: 9, free: true, note: '나라별 지표를 한 화면에 모아 비교' },
  { id: 't-stat-statista', name: 'Statista', nameKo: '스타티스타', url: 'https://www.statista.com', country: 'DE', group: 't-stat', rank: 10, note: '시장 규모 자료가 필요할 때 먼저 나온다' },
  { id: 't-stat-who', name: 'WHO Global Health Observatory', nameKo: 'WHO 보건통계', url: 'https://www.who.int/data/gho', country: 'INT', group: 't-stat', rank: 11, free: true },
  { id: 't-stat-census', name: 'U.S. Census Bureau', nameKo: '미국 인구조사국', url: 'https://www.census.gov', country: 'US', group: 't-stat', rank: 12, free: true },
  { id: 't-stat-bls', name: 'U.S. Bureau of Labor Statistics', nameKo: '미국 노동통계국', url: 'https://www.bls.gov', country: 'US', group: 't-stat', rank: 13, free: true, note: '고용지표·CPI 발표 원문' },
  { id: 't-stat-datagov', name: 'Data.gov', nameKo: '데이터닷거브', url: 'https://data.gov', country: 'US', group: 't-stat', rank: 14, free: true, note: '미국 연방정부 공개 데이터 30만 건' },
  { id: 't-stat-gds', name: 'Google Dataset Search', nameKo: '구글 데이터셋 검색', url: 'https://datasetsearch.research.google.com', country: 'US', group: 't-stat', rank: 15, free: true, note: '흩어진 공개 데이터셋을 한 번에 찾는다' },
  { id: 't-stat-kaggle', name: 'Kaggle Datasets', nameKo: '캐글 데이터셋', url: 'https://www.kaggle.com/datasets', country: 'US', group: 't-stat', rank: 16, free: true, note: '바로 분석에 쓸 수 있게 정리된 데이터' },
  { id: 't-stat-oec', name: 'OEC', nameKo: '경제복잡성 관측소', url: 'https://oec.world', country: 'US', group: 't-stat', rank: 17, free: true, note: '나라별 수출입 구조를 그림으로' },
  { id: 't-stat-comtrade', name: 'UN Comtrade', nameKo: 'UN 콤트레이드', url: 'https://comtradeplus.un.org', country: 'INT', group: 't-stat', rank: 18, free: true, note: '품목별 국제 무역 통계 원본' },
  { id: 't-stat-faostat', name: 'FAOSTAT', nameKo: 'FAO 통계', url: 'https://www.fao.org/faostat/en/', country: 'INT', group: 't-stat', rank: 19, free: true, note: '농업·식량 생산 통계' },
  { id: 't-stat-iea', name: 'IEA', nameKo: '국제에너지기구', url: 'https://www.iea.org/data-and-statistics', country: 'INT', group: 't-stat', rank: 20, free: true, note: '에너지 수급·전환 데이터' },
  { id: 't-stat-hdx', name: 'HDX', nameKo: '인도적 데이터 교환소', url: 'https://data.humdata.org', country: 'INT', group: 't-stat', rank: 21, free: true, note: '분쟁·재난 지역 현황 데이터' },
  { id: 't-stat-numbeo', name: 'Numbeo', nameKo: '넘베오', url: 'https://www.numbeo.com', country: 'RS', group: 't-stat', rank: 22, free: true, note: '도시별 물가·집세·치안을 이용자가 입력' },
  { id: 't-stat-gapminder', name: 'Gapminder', nameKo: '갭마인더', url: 'https://www.gapminder.org', country: 'SE', group: 't-stat', rank: 23, free: true, note: '세계에 대한 오해를 데이터로 깨는 도구' },
  { id: 't-stat-hdr', name: 'UNDP Human Development Reports', nameKo: 'UNDP 인간개발보고서', url: 'https://hdr.undp.org', country: 'INT', group: 't-stat', rank: 24, free: true },

  // ══════════════════════════ 금융·투자 도구 ══════════════════════════
  { id: 't-money-tradingview', name: 'TradingView', nameKo: '트레이딩뷰', url: 'https://www.tradingview.com', country: 'US', group: 't-money', rank: 1, free: true, note: '차트 도구의 사실상 표준, 한국 주식도 나온다' },
  { id: 't-money-yahoo', name: 'Yahoo Finance', nameKo: '야후 파이낸스', url: 'https://finance.yahoo.com', country: 'US', group: 't-money', rank: 2, free: true, note: '무료로 볼 수 있는 재무제표 범위가 가장 넓다' },
  { id: 't-money-investing', name: 'Investing.com', nameKo: '인베스팅닷컴', url: 'https://www.investing.com', country: 'CY', group: 't-money', rank: 3, free: true, note: '경제지표 캘린더가 특히 쓸모 있다' },
  { id: 't-money-edgar', name: 'SEC EDGAR', nameKo: 'SEC 에드가', url: 'https://www.sec.gov/edgar', country: 'US', group: 't-money', rank: 4, free: true, note: '미국 상장사 공시 원문, 10-K·13F' },
  { id: 't-money-stockanalysis', name: 'Stock Analysis', nameKo: '스톡애널리시스', url: 'https://stockanalysis.com', country: 'US', group: 't-money', rank: 5, free: true, note: '광고 없이 깔끔한 종목 재무 요약' },
  { id: 't-money-finviz', name: 'Finviz', nameKo: '핀비즈', url: 'https://finviz.com', country: 'US', group: 't-money', rank: 6, free: true, note: '히트맵과 스크리너가 빠르다' },
  { id: 't-money-macrotrends', name: 'Macrotrends', nameKo: '매크로트렌드', url: 'https://www.macrotrends.net', country: 'US', group: 't-money', rank: 7, free: true, note: '수십 년치 장기 차트를 무료로' },
  { id: 't-money-morningstar', name: 'Morningstar', nameKo: '모닝스타', url: 'https://www.morningstar.com', country: 'US', group: 't-money', rank: 8, free: true, note: '펀드·ETF 평가의 기준' },
  { id: 't-money-justetf', name: 'justETF', nameKo: '저스트ETF', url: 'https://www.justetf.com', country: 'DE', group: 't-money', rank: 9, free: true, note: '유럽 상장 ETF 비교에 가장 좋다' },
  { id: 't-money-portfoliovisualizer', name: 'Portfolio Visualizer', nameKo: '포트폴리오 비주얼라이저', url: 'https://www.portfoliovisualizer.com', country: 'US', group: 't-money', rank: 10, free: true, note: '자산배분을 과거 데이터로 되돌려 본다' },
  { id: 't-money-damodaran', name: 'Damodaran Online', nameKo: '다모다란 온라인', url: 'https://pages.stern.nyu.edu/~adamodar/', country: 'US', group: 't-money', rank: 11, free: true, note: '기업가치 평가 데이터를 매년 무료 공개' },
  { id: 't-money-xe', name: 'XE', nameKo: 'XE 환율', url: 'https://www.xe.com', country: 'CA', group: 't-money', rank: 12, free: true, note: '환율 조회의 오래된 기준점' },
  { id: 't-money-wise', name: 'Wise', nameKo: '와이즈', url: 'https://wise.com', country: 'UK', group: 't-money', rank: 13, free: true, note: '해외 송금 수수료를 크게 낮춘 서비스' },
  { id: 't-money-coingecko', name: 'CoinGecko', nameKo: '코인게코', url: 'https://www.coingecko.com', country: 'SG', group: 't-money', rank: 14, free: true, note: '가상자산 시세, 상장 범위가 넓다' },
  { id: 't-money-coinmarketcap', name: 'CoinMarketCap', nameKo: '코인마켓캡', url: 'https://coinmarketcap.com', country: 'US', group: 't-money', rank: 15, free: true },
  { id: 't-money-defillama', name: 'DefiLlama', nameKo: '디파이라마', url: 'https://defillama.com', country: 'INT', group: 't-money', rank: 16, free: true, note: '디파이 예치금 통계의 사실상 표준' },
  { id: 't-money-etherscan', name: 'Etherscan', nameKo: '이더스캔', url: 'https://etherscan.io', country: 'INT', group: 't-money', rank: 17, free: true, note: '이더리움 거래를 직접 들여다본다' },
  { id: 't-money-seekingalpha', name: 'Seeking Alpha', nameKo: '시킹 알파', url: 'https://seekingalpha.com', country: 'US', group: 't-money', rank: 18, free: true, note: '개인 투자자 분석 글이 모인다' },
  { id: 't-money-simplywallst', name: 'Simply Wall St', nameKo: '심플리 월스트', url: 'https://simplywall.st', country: 'AU', group: 't-money', rank: 19, free: true, note: '재무 상태를 그림 하나로 요약' },
  { id: 't-money-bogleheads', name: 'Bogleheads', nameKo: '보글헤즈', url: 'https://www.bogleheads.org', country: 'US', group: 't-money', rank: 20, free: true, note: '인덱스 장기투자 원칙의 총본산' },
  { id: 't-money-slickcharts', name: 'Slickcharts', nameKo: '슬릭차트', url: 'https://www.slickcharts.com', country: 'US', group: 't-money', rank: 21, free: true, note: '지수 구성종목과 비중을 바로 본다' },
  { id: 't-money-nasdaq', name: 'Nasdaq', nameKo: '나스닥', url: 'https://www.nasdaq.com', country: 'US', group: 't-money', rank: 22, free: true, note: '실적 발표 일정과 공모 정보' },

  // ══════════════════════════ 여행·항공·숙박 ══════════════════════════
  { id: 't-travel-gflights', name: 'Google Flights', nameKo: '구글 항공권', url: 'https://www.google.com/travel/flights', country: 'US', group: 't-travel', rank: 1, free: true, note: '날짜를 넓게 훑어 최저가를 찾는다' },
  { id: 't-travel-skyscanner', name: 'Skyscanner', nameKo: '스카이스캐너', url: 'https://www.skyscanner.co.kr', country: 'UK', group: 't-travel', rank: 2, free: true, note: '목적지를 "어디든"으로 두고 검색된다' },
  { id: 't-travel-booking', name: 'Booking.com', nameKo: '부킹닷컴', url: 'https://www.booking.com', country: 'NL', group: 't-travel', rank: 3, free: true, note: '숙소 재고가 가장 많다' },
  { id: 't-travel-agoda', name: 'Agoda', nameKo: '아고다', url: 'https://www.agoda.com', country: 'SG', group: 't-travel', rank: 4, free: true, note: '아시아 숙소는 여기가 대체로 싸다' },
  { id: 't-travel-airbnb', name: 'Airbnb', nameKo: '에어비앤비', url: 'https://www.airbnb.co.kr', country: 'US', group: 't-travel', rank: 5, free: true },
  { id: 't-travel-rome2rio', name: 'Rome2Rio', nameKo: '로마투리오', url: 'https://www.rome2rio.com', country: 'AU', group: 't-travel', rank: 6, free: true, note: 'A에서 B까지 가는 모든 교통편을 비교' },
  { id: 't-travel-seat61', name: 'Seat 61', nameKo: '시트61', url: 'https://www.seat61.com', country: 'UK', group: 't-travel', rank: 7, free: true, note: '전세계 기차 여행의 백과사전' },
  { id: 't-travel-omio', name: 'Omio', nameKo: '오미오', url: 'https://www.omio.com', country: 'DE', group: 't-travel', rank: 8, free: true, note: '유럽 기차·버스를 한 번에 예약' },
  { id: 't-travel-trainline', name: 'Trainline', nameKo: '트레인라인', url: 'https://www.thetrainline.com', country: 'UK', group: 't-travel', rank: 9, free: true, note: '영국·유럽 철도표 예매' },
  { id: 't-travel-12go', name: '12Go', nameKo: '12고', url: 'https://12go.asia', country: 'TH', group: 't-travel', rank: 10, free: true, note: '동남아 버스·페리·기차 예약' },
  { id: 't-travel-hostelworld', name: 'Hostelworld', nameKo: '호스텔월드', url: 'https://www.hostelworld.com', country: 'IE', group: 't-travel', rank: 11, free: true, note: '배낭여행 숙소는 여기가 기준' },
  { id: 't-travel-kayak', name: 'KAYAK', nameKo: '카약', url: 'https://www.kayak.com', country: 'US', group: 't-travel', rank: 12, free: true },
  { id: 't-travel-tripadvisor', name: 'Tripadvisor', nameKo: '트립어드바이저', url: 'https://www.tripadvisor.com', country: 'US', group: 't-travel', rank: 13, free: true, note: '후기 총량이 여전히 가장 많다' },
  { id: 't-travel-wikivoyage', name: 'Wikivoyage', nameKo: '위키보야지', url: 'https://www.wikivoyage.org', country: 'INT', group: 't-travel', rank: 14, free: true, note: '광고 없는 위키 여행 가이드' },
  { id: 't-travel-lonelyplanet', name: 'Lonely Planet', nameKo: '론리플래닛', url: 'https://www.lonelyplanet.com', country: 'US', group: 't-travel', rank: 15, free: true },
  { id: 't-travel-getyourguide', name: 'GetYourGuide', nameKo: '겟유어가이드', url: 'https://www.getyourguide.com', country: 'DE', group: 't-travel', rank: 16, free: true, note: '현지 투어·입장권 예약' },
  { id: 't-travel-klook', name: 'Klook', nameKo: '클룩', url: 'https://www.klook.com', country: 'HK', group: 't-travel', rank: 17, free: true, note: '아시아 액티비티·교통패스에 강하다' },
  { id: 't-travel-tripcom', name: 'Trip.com', nameKo: '트립닷컴', url: 'https://www.trip.com', country: 'SG', group: 't-travel', rank: 18, free: true, note: '중국·아시아 노선 항공권이 자주 싸다' },
  { id: 't-travel-discovercars', name: 'Discover Cars', nameKo: '디스커버 카스', url: 'https://www.discovercars.com', country: 'LV', group: 't-travel', rank: 19, free: true, note: '렌터카 비교, 보험 조건이 명확하다' },
  { id: 't-travel-nomads', name: 'Nomad List', nameKo: '노마드 리스트', url: 'https://nomads.com', country: 'NL', group: 't-travel', rank: 20, note: '원격근무자용 도시 비교' },
  { id: 't-travel-iata', name: 'IATA Travel Centre', nameKo: 'IATA 여행센터', url: 'https://www.iatatravelcentre.com', country: 'INT', group: 't-travel', rank: 21, free: true, note: '비자·입국 요건 공식 확인' },

  // ══════════════════════════ 지도·실시간 관측 ══════════════════════════
  { id: 't-map-gmaps', name: 'Google Maps', nameKo: '구글 지도', url: 'https://www.google.com/maps', country: 'US', group: 't-map', rank: 1, free: true, note: '해외에서는 사실상 유일한 기본값' },
  { id: 't-map-osm', name: 'OpenStreetMap', nameKo: '오픈스트리트맵', url: 'https://www.openstreetmap.org', country: 'INT', group: 't-map', rank: 2, free: true, note: '누구나 고칠 수 있는 공개 지도' },
  { id: 't-map-earth', name: 'Google Earth', nameKo: '구글 어스', url: 'https://earth.google.com', country: 'US', group: 't-map', rank: 3, free: true, note: '위성사진으로 지구를 훑는다' },
  { id: 't-map-windy', name: 'Windy', nameKo: '윈디', url: 'https://www.windy.com', country: 'CZ', group: 't-map', rank: 4, free: true, note: '바람·강수를 애니메이션으로 보는 기상도' },
  { id: 't-map-flightradar', name: 'Flightradar24', nameKo: '플라이트레이더24', url: 'https://www.flightradar24.com', country: 'SE', group: 't-map', rank: 5, free: true, note: '지금 하늘에 뜬 비행기를 전부 본다' },
  { id: 't-map-marinetraffic', name: 'MarineTraffic', nameKo: '마린트래픽', url: 'https://www.marinetraffic.com', country: 'GR', group: 't-map', rank: 6, free: true, note: '선박 위치 추적, 물류 병목을 눈으로' },
  { id: 't-map-zoomearth', name: 'Zoom Earth', nameKo: '줌 어스', url: 'https://zoom.earth', country: 'UK', group: 't-map', rank: 7, free: true, note: '태풍·산불을 실시간 위성으로' },
  { id: 't-map-ventusky', name: 'Ventusky', nameKo: '벤투스키', url: 'https://www.ventusky.com', country: 'CZ', group: 't-map', rank: 8, free: true, note: '기상 요소를 층층이 겹쳐 본다' },
  { id: 't-map-usgs', name: 'USGS Earthquakes', nameKo: 'USGS 지진', url: 'https://earthquake.usgs.gov', country: 'US', group: 't-map', rank: 9, free: true, note: '전세계 지진을 발생 즉시 공개' },
  { id: 't-map-worldview', name: 'NASA Worldview', nameKo: 'NASA 월드뷰', url: 'https://worldview.earthdata.nasa.gov', country: 'US', group: 't-map', rank: 10, free: true, note: '어제 찍힌 지구 위성영상을 무료로' },
  { id: 't-map-copernicus', name: 'Copernicus Browser', nameKo: '코페르니쿠스 브라우저', url: 'https://browser.dataspace.copernicus.eu', country: 'EU', group: 't-map', rank: 11, free: true, note: '유럽 센티넬 위성 원본 영상' },
  { id: 't-map-iqair', name: 'IQAir', nameKo: '아이큐에어', url: 'https://www.iqair.com', country: 'CH', group: 't-map', rank: 12, free: true, note: '도시별 실시간 대기질 순위' },
  { id: 't-map-firms', name: 'NASA FIRMS', nameKo: 'NASA 화재지도', url: 'https://firms.modaps.eosdis.nasa.gov/map/', country: 'US', group: 't-map', rank: 13, free: true, note: '전세계 산불을 위성 열감지로' },
  { id: 't-map-submarine', name: 'Submarine Cable Map', nameKo: '해저케이블 지도', url: 'https://www.submarinecablemap.com', country: 'US', group: 't-map', rank: 14, free: true, note: '인터넷이 실제로 지나는 길' },
  { id: 't-map-w3w', name: 'what3words', nameKo: '왓쓰리워즈', url: 'https://what3words.com', country: 'UK', group: 't-map', rank: 15, free: true, note: '3미터 격자를 단어 세 개로 부른다' },
  { id: 't-map-lightpollution', name: 'Light Pollution Map', nameKo: '광공해 지도', url: 'https://www.lightpollutionmap.info', country: 'INT', group: 't-map', rank: 16, free: true, note: '별 보러 갈 곳을 고를 때' },
  { id: 't-map-timeanddate', name: 'timeanddate.com', nameKo: '타임앤드데이트', url: 'https://www.timeanddate.com', country: 'NO', group: 't-map', rank: 17, free: true, note: '일출·일몰·시차·천문 현상' },
  { id: 't-map-gcmap', name: 'Great Circle Mapper', nameKo: '대권항로 지도', url: 'http://www.gcmap.com', country: 'US', group: 't-map', rank: 18, free: true, note: '두 공항 사이 실제 비행 거리 — HTTPS를 지원하지 않는다' },
  { id: 't-map-openrailway', name: 'OpenRailwayMap', nameKo: '오픈레일웨이맵', url: 'https://www.openrailwaymap.org', country: 'DE', group: 't-map', rank: 19, free: true, note: '전세계 철도 노선·전철화 현황' },

  // ══════════════════════════ 쇼핑·가격비교 ══════════════════════════
  { id: 't-shop-amazon', name: 'Amazon', nameKo: '아마존', url: 'https://www.amazon.com', country: 'US', group: 't-shop', rank: 1, free: true, note: '직구의 기본값' },
  { id: 't-shop-aliexpress', name: 'AliExpress', nameKo: '알리익스프레스', url: 'https://www.aliexpress.com', country: 'CN', group: 't-shop', rank: 2, free: true, note: '중국 제조를 소량으로 직접 산다' },
  { id: 't-shop-ebay', name: 'eBay', nameKo: '이베이', url: 'https://www.ebay.com', country: 'US', group: 't-shop', rank: 3, free: true, note: '단종·중고 부품을 찾을 때' },
  { id: 't-shop-iherb', name: 'iHerb', nameKo: '아이허브', url: 'https://www.iherb.com', country: 'US', group: 't-shop', rank: 4, free: true, note: '영양제 직구, 한국어·원화 결제' },
  { id: 't-shop-camel', name: 'CamelCamelCamel', nameKo: '카멜카멜카멜', url: 'https://camelcamelcamel.com', country: 'US', group: 't-shop', rank: 5, free: true, note: '아마존 가격 이력, 진짜 할인인지 확인' },
  { id: 't-shop-keepa', name: 'Keepa', nameKo: '키파', url: 'https://keepa.com', country: 'DE', group: 't-shop', rank: 6, free: true, note: '아마존 가격 추적의 정밀판' },
  { id: 't-shop-pcpartpicker', name: 'PCPartPicker', nameKo: 'PC파트피커', url: 'https://pcpartpicker.com', country: 'US', group: 't-shop', rank: 7, free: true, note: '부품 호환성까지 검사하는 견적기' },
  { id: 't-shop-slickdeals', name: 'Slickdeals', nameKo: '슬릭딜스', url: 'https://slickdeals.net', country: 'US', group: 't-shop', rank: 8, free: true, note: '미국 특가 정보의 중심' },
  { id: 't-shop-kakaku', name: 'kakaku.com', nameKo: '가카쿠', url: 'https://kakaku.com', country: 'JP', group: 't-shop', rank: 9, free: true, note: '일본 최대 가격비교, 사양 정보가 상세' },
  { id: 't-shop-idealo', name: 'idealo', nameKo: '이데알로', url: 'https://www.idealo.de', country: 'DE', group: 't-shop', rank: 10, free: true, note: '독일 대표 가격비교' },
  { id: 't-shop-geizhals', name: 'Geizhals', nameKo: '가이츠할스', url: 'https://geizhals.de', country: 'AT', group: 't-shop', rank: 11, free: true, note: 'PC 부품 재고·가격 추적에 강하다' },
  { id: 't-shop-etsy', name: 'Etsy', nameKo: '엣시', url: 'https://www.etsy.com', country: 'US', group: 't-shop', rank: 12, free: true, note: '수공예·빈티지·디지털 파일 장터' },
  { id: 't-shop-rakuten', name: 'Rakuten', nameKo: '라쿠텐', url: 'https://www.rakuten.co.jp', country: 'JP', group: 't-shop', rank: 13, free: true, note: '일본 최대 온라인 몰' },
  { id: 't-shop-mercari', name: 'Mercari', nameKo: '메루카리', url: 'https://jp.mercari.com', country: 'JP', group: 't-shop', rank: 14, free: true, note: '일본 중고 거래의 표준' },
  { id: 't-shop-vinted', name: 'Vinted', nameKo: '빈티드', url: 'https://www.vinted.com', country: 'LT', group: 't-shop', rank: 15, free: true, note: '유럽 최대 중고 의류 거래' },
  { id: 't-shop-backmarket', name: 'Back Market', nameKo: '백마켓', url: 'https://www.backmarket.com', country: 'FR', group: 't-shop', rank: 16, free: true, note: '검수된 리퍼 전자제품' },
  { id: 't-shop-temu', name: 'Temu', nameKo: '테무', url: 'https://www.temu.com', country: 'CN', group: 't-shop', rank: 17, free: true },
  { id: 't-shop-newegg', name: 'Newegg', nameKo: '뉴에그', url: 'https://www.newegg.com', country: 'US', group: 't-shop', rank: 18, free: true, note: 'PC 부품 직구' },
  { id: 't-shop-bh', name: 'B&H Photo Video', nameKo: 'B&H', url: 'https://www.bhphotovideo.com', country: 'US', group: 't-shop', rank: 19, free: true, note: '카메라·영상 장비 직구의 정석' },
  { id: 't-shop-alibaba', name: 'Alibaba', nameKo: '알리바바', url: 'https://www.alibaba.com', country: 'CN', group: 't-shop', rank: 20, free: true, note: '도매·OEM 발주용' },

  // ══════════════════════════ 건강·의료 ══════════════════════════
  { id: 't-health-who', name: 'WHO', nameKo: '세계보건기구', url: 'https://www.who.int', country: 'INT', group: 't-health', rank: 1, free: true, note: '감염병·보건 권고의 1차 출처' },
  { id: 't-health-medlineplus', name: 'MedlinePlus', nameKo: '메드라인플러스', url: 'https://medlineplus.gov', country: 'US', group: 't-health', rank: 2, free: true, note: '미국 국립의학도서관이 쓰는 환자용 설명' },
  { id: 't-health-mayo', name: 'Mayo Clinic', nameKo: '메이요 클리닉', url: 'https://www.mayoclinic.org', country: 'US', group: 't-health', rank: 3, free: true, note: '증상·질환 설명이 가장 신뢰받는다' },
  { id: 't-health-pubmed', name: 'PubMed', nameKo: '펍메드', url: 'https://pubmed.ncbi.nlm.nih.gov', country: 'US', group: 't-health', rank: 4, free: true, note: '의학 논문 초록 3,700만 건' },
  { id: 't-health-cochrane', name: 'Cochrane Library', nameKo: '코크란 라이브러리', url: 'https://www.cochranelibrary.com', country: 'UK', group: 't-health', rank: 5, free: true, note: '치료법 효과를 종합한 최상위 근거' },
  { id: 't-health-nhs', name: 'NHS', nameKo: '영국 NHS', url: 'https://www.nhs.uk', country: 'UK', group: 't-health', rank: 6, free: true, note: '군더더기 없는 공공 건강 정보' },
  { id: 't-health-cdc', name: 'CDC', nameKo: '미국 질병통제센터', url: 'https://www.cdc.gov', country: 'US', group: 't-health', rank: 7, free: true, note: '여행 전 예방접종 권고도 여기서' },
  { id: 't-health-drugs', name: 'Drugs.com', nameKo: '드럭스닷컴', url: 'https://www.drugs.com', country: 'US', group: 't-health', rank: 8, free: true, note: '약 상호작용 검사기가 유용하다' },
  { id: 't-health-clinicaltrials', name: 'ClinicalTrials.gov', nameKo: '임상시험 등록부', url: 'https://clinicaltrials.gov', country: 'US', group: 't-health', rank: 9, free: true, note: '진행 중인 임상시험을 직접 찾는다' },
  { id: 't-health-examine', name: 'Examine', nameKo: '이그재민', url: 'https://examine.com', country: 'CA', group: 't-health', rank: 10, free: true, note: '보충제 효과를 논문 근거로 정리' },
  { id: 't-health-clevelandclinic', name: 'Cleveland Clinic', nameKo: '클리블랜드 클리닉', url: 'https://my.clevelandclinic.org/health', country: 'US', group: 't-health', rank: 11, free: true },
  { id: 't-health-hopkins', name: 'Johns Hopkins Medicine', nameKo: '존스홉킨스 의학', url: 'https://www.hopkinsmedicine.org/health', country: 'US', group: 't-health', rank: 12, free: true },
  { id: 't-health-nih', name: 'NIH', nameKo: '미국 국립보건원', url: 'https://www.nih.gov', country: 'US', group: 't-health', rank: 13, free: true },
  { id: 't-health-ema', name: 'EMA', nameKo: '유럽 의약품청', url: 'https://www.ema.europa.eu', country: 'EU', group: 't-health', rank: 14, free: true, note: '유럽 신약 허가 심사 보고서' },
  { id: 't-health-openfda', name: 'openFDA', nameKo: '오픈FDA', url: 'https://open.fda.gov', country: 'US', group: 't-health', rank: 15, free: true, note: '의약품 부작용 신고 데이터 공개' },
  { id: 't-health-fdc', name: 'USDA FoodData Central', nameKo: 'USDA 식품영양DB', url: 'https://fdc.nal.usda.gov', country: 'US', group: 't-health', rank: 16, free: true, note: '식품 영양성분의 원본 데이터' },
  { id: 't-health-sleepfoundation', name: 'Sleep Foundation', nameKo: '슬립 파운데이션', url: 'https://www.sleepfoundation.org', country: 'US', group: 't-health', rank: 17, free: true },
  { id: 't-health-healthline', name: 'Healthline', nameKo: '헬스라인', url: 'https://www.healthline.com', country: 'US', group: 't-health', rank: 18, free: true, note: '읽기 쉽지만 출처를 함께 단다' },
  { id: 't-health-gco', name: 'IARC Global Cancer Observatory', nameKo: '국제암연구소 통계', url: 'https://gco.iarc.fr', country: 'INT', group: 't-health', rank: 19, free: true },

  // ══════════════════════════ 취업·커리어 ══════════════════════════
  { id: 't-career-linkedin', name: 'LinkedIn', nameKo: '링크드인', url: 'https://www.linkedin.com', country: 'US', group: 't-career', rank: 1, free: true, note: '해외 취업은 여기서 시작한다' },
  { id: 't-career-indeed', name: 'Indeed', nameKo: '인디드', url: 'https://www.indeed.com', country: 'US', group: 't-career', rank: 2, free: true, note: '세계 최대 채용공고 집계' },
  { id: 't-career-glassdoor', name: 'Glassdoor', nameKo: '글래스도어', url: 'https://www.glassdoor.com', country: 'US', group: 't-career', rank: 3, free: true, note: '현직자 리뷰와 연봉 범위' },
  { id: 't-career-levelsfyi', name: 'Levels.fyi', nameKo: '레벨스', url: 'https://www.levels.fyi', country: 'US', group: 't-career', rank: 4, free: true, note: '테크 기업 직급별 실수령 연봉' },
  { id: 't-career-blind', name: 'Blind', nameKo: '블라인드', url: 'https://www.teamblind.com', country: 'US', group: 't-career', rank: 5, free: true, note: '회사 메일로 인증된 익명 대화' },
  { id: 't-career-wellfound', name: 'Wellfound', nameKo: '웰파운드', url: 'https://wellfound.com', country: 'US', group: 't-career', rank: 6, free: true, note: '스타트업 채용, 연봉·지분을 먼저 공개' },
  { id: 't-career-wwr', name: 'We Work Remotely', nameKo: '위 워크 리모틀리', url: 'https://weworkremotely.com', country: 'US', group: 't-career', rank: 7, free: true, note: '원격근무 공고만 모았다' },
  { id: 't-career-remoteok', name: 'Remote OK', nameKo: '리모트OK', url: 'https://remoteok.com', country: 'NL', group: 't-career', rank: 8, free: true },
  { id: 't-career-wttj', name: 'Welcome to the Jungle', nameKo: '웰컴 투 더 정글', url: 'https://www.welcometothejungle.com', country: 'FR', group: 't-career', rank: 9, free: true, note: '유럽 채용, 회사 소개 영상이 충실하다' },
  { id: 't-career-workatastartup', name: 'Work at a Startup', nameKo: 'YC 채용', url: 'https://www.workatastartup.com', country: 'US', group: 't-career', rank: 10, free: true, note: 'Y Combinator 포트폴리오사 채용' },
  { id: 't-career-upwork', name: 'Upwork', nameKo: '업워크', url: 'https://www.upwork.com', country: 'US', group: 't-career', rank: 11, free: true, note: '해외 프리랜서 수주의 대표 창구' },
  { id: 't-career-fiverr', name: 'Fiverr', nameKo: '파이버', url: 'https://www.fiverr.com', country: 'IL', group: 't-career', rank: 12, free: true, note: '서비스를 상품처럼 파는 방식' },
  { id: 't-career-toptal', name: 'Toptal', nameKo: '탑탈', url: 'https://www.toptal.com', country: 'US', group: 't-career', rank: 13, note: '심사를 통과한 상위 프리랜서만' },
  { id: 't-career-onet', name: 'O*NET OnLine', nameKo: '오넷 온라인', url: 'https://www.onetonline.org', country: 'US', group: 't-career', rank: 14, free: true, note: '직업마다 필요한 능력을 표준화해 정리' },
  { id: 't-career-payscale', name: 'PayScale', nameKo: '페이스케일', url: 'https://www.payscale.com', country: 'US', group: 't-career', rank: 15, free: true },
  { id: 't-career-rxresume', name: 'Reactive Resume', nameKo: '리액티브 레주메', url: 'https://rxresu.me', country: 'IN', group: 't-career', rank: 16, free: true, note: '광고도 결제도 없는 오픈소스 이력서' },
  { id: 't-career-flowcv', name: 'FlowCV', nameKo: '플로우CV', url: 'https://flowcv.com', country: 'NL', group: 't-career', rank: 17, free: true, note: 'ATS가 읽는 형식으로 PDF를 뽑는다' },
  { id: 't-career-europass', name: 'Europass', nameKo: '유로패스', url: 'https://europa.eu/europass/', country: 'EU', group: 't-career', rank: 18, free: true, note: 'EU 표준 이력서 양식' },
  { id: 't-career-seek', name: 'SEEK', nameKo: '시크', url: 'https://www.seek.com.au', country: 'AU', group: 't-career', rank: 19, free: true, note: '호주·뉴질랜드 최대 채용' },
  { id: 't-career-interviewingio', name: 'interviewing.io', nameKo: '인터뷰잉아이오', url: 'https://interviewing.io', country: 'US', group: 't-career', rank: 20, free: true, note: '현직 면접관과 익명 모의면접' },

  // ══════════════════════════ 국제기구·정부·법률 ══════════════════════════
  { id: 't-gov-un', name: 'United Nations', nameKo: '유엔', url: 'https://www.un.org', country: 'INT', group: 't-gov', rank: 1, free: true, note: '결의안과 공식 문서 원문' },
  { id: 't-gov-eu', name: 'European Union', nameKo: '유럽연합', url: 'https://european-union.europa.eu', country: 'EU', group: 't-gov', rank: 2, free: true },
  { id: 't-gov-worldbank', name: 'World Bank', nameKo: '세계은행', url: 'https://www.worldbank.org', country: 'INT', group: 't-gov', rank: 3, free: true },
  { id: 't-gov-imf', name: 'IMF', nameKo: '국제통화기금', url: 'https://www.imf.org', country: 'INT', group: 't-gov', rank: 4, free: true, note: '국가별 연례 협의 보고서가 알차다' },
  { id: 't-gov-oecd', name: 'OECD', nameKo: 'OECD', url: 'https://www.oecd.org', country: 'INT', group: 't-gov', rank: 5, free: true },
  { id: 't-gov-wto', name: 'WTO', nameKo: '세계무역기구', url: 'https://www.wto.org', country: 'INT', group: 't-gov', rank: 6, free: true, note: '관세·분쟁 해결 절차 원문' },
  { id: 't-gov-gpatents', name: 'Google Patents', nameKo: '구글 특허', url: 'https://patents.google.com', country: 'US', group: 't-gov', rank: 7, free: true, note: '전세계 특허를 한 번에 검색·번역' },
  { id: 't-gov-espacenet', name: 'Espacenet', nameKo: '에스파스넷', url: 'https://worldwide.espacenet.com', country: 'EU', group: 't-gov', rank: 8, free: true, note: '유럽특허청 공식 검색, 1억 건 이상' },
  { id: 't-gov-wipo', name: 'WIPO', nameKo: '세계지식재산기구', url: 'https://www.wipo.int', country: 'INT', group: 't-gov', rank: 9, free: true, note: '국제 상표·특허 출원 창구' },
  { id: 't-gov-uspto', name: 'USPTO', nameKo: '미국 특허상표청', url: 'https://www.uspto.gov', country: 'US', group: 't-gov', rank: 10, free: true },
  { id: 't-gov-eurlex', name: 'EUR-Lex', nameKo: '유렉스', url: 'https://eur-lex.europa.eu', country: 'EU', group: 't-gov', rank: 11, free: true, note: 'EU 법령 전문을 24개 언어로' },
  { id: 't-gov-congress', name: 'Congress.gov', nameKo: '미국 의회', url: 'https://www.congress.gov', country: 'US', group: 't-gov', rank: 12, free: true, note: '법안 진행 상황을 단계별로 추적' },
  { id: 't-gov-federalregister', name: 'Federal Register', nameKo: '연방관보', url: 'https://www.federalregister.gov', country: 'US', group: 't-gov', rank: 13, free: true, note: '미국 행정규칙이 공표되는 곳' },
  { id: 't-gov-lii', name: 'Cornell LII', nameKo: '코넬 법률정보연구소', url: 'https://www.law.cornell.edu', country: 'US', group: 't-gov', rank: 14, free: true, note: '미국 법전을 무료로 읽는다' },
  { id: 't-gov-courtlistener', name: 'CourtListener', nameKo: '코트리스너', url: 'https://www.courtlistener.com', country: 'US', group: 't-gov', rank: 15, free: true, note: '판결문·소송 기록 공개 아카이브' },
  { id: 't-gov-legislationuk', name: 'legislation.gov.uk', nameKo: '영국 법령', url: 'https://www.legislation.gov.uk', country: 'UK', group: 't-gov', rank: 16, free: true },
  { id: 't-gov-lawgokr', name: '국가법령정보센터', nameKo: '국가법령정보센터', url: 'https://www.law.go.kr', country: 'KR', group: 't-gov', rank: 17, free: true, note: '한국 법령·판례의 1차 출처' },
  { id: 't-gov-icj', name: 'International Court of Justice', nameKo: '국제사법재판소', url: 'https://www.icj-cij.org', country: 'INT', group: 't-gov', rank: 18, free: true },
  { id: 't-gov-unhcr', name: 'UNHCR', nameKo: '유엔난민기구', url: 'https://www.unhcr.org', country: 'INT', group: 't-gov', rank: 19, free: true },
  { id: 't-gov-unesco', name: 'UNESCO', nameKo: '유네스코', url: 'https://www.unesco.org', country: 'INT', group: 't-gov', rank: 20, free: true },
  { id: 't-gov-transparency', name: 'Transparency International', nameKo: '국제투명성기구', url: 'https://www.transparency.org', country: 'DE', group: 't-gov', rank: 21, free: true, note: '부패인식지수 발표' },
  { id: 't-gov-iaea', name: 'IAEA', nameKo: '국제원자력기구', url: 'https://www.iaea.org', country: 'INT', group: 't-gov', rank: 22, free: true },

  // ══════════════════════════ 보안·프라이버시 ══════════════════════════
  { id: 't-sec-hibp', name: 'Have I Been Pwned', nameKo: '해브아이빈폰드', url: 'https://haveibeenpwned.com', country: 'AU', group: 't-security', rank: 1, free: true, note: '내 이메일이 유출됐는지 먼저 확인' },
  { id: 't-sec-bitwarden', name: 'Bitwarden', nameKo: '비트워든', url: 'https://bitwarden.com', country: 'US', group: 't-security', rank: 2, free: true, note: '오픈소스 비밀번호 관리자, 무료로 충분' },
  { id: 't-sec-virustotal', name: 'VirusTotal', nameKo: '바이러스토탈', url: 'https://www.virustotal.com', country: 'ES', group: 't-security', rank: 3, free: true, note: '파일·링크를 70여 개 백신으로 한 번에' },
  { id: 't-sec-signal', name: 'Signal', nameKo: '시그널', url: 'https://signal.org', country: 'US', group: 't-security', rank: 4, free: true, note: '종단간 암호화 메신저의 기준' },
  { id: 't-sec-proton', name: 'Proton', nameKo: '프로톤', url: 'https://proton.me', country: 'CH', group: 't-security', rank: 5, free: true, note: '스위스 기반 암호화 메일·드라이브·VPN' },
  { id: 't-sec-1password', name: '1Password', nameKo: '원패스워드', url: 'https://1password.com', country: 'CA', group: 't-security', rank: 6, note: '가족·팀 공유가 편한 유료 관리자' },
  { id: 't-sec-tuta', name: 'Tuta', nameKo: '투타', url: 'https://tuta.com', country: 'DE', group: 't-security', rank: 7, free: true, note: '독일 암호화 메일, 무료 계정 제공' },
  { id: 't-sec-privacyguides', name: 'Privacy Guides', nameKo: '프라이버시 가이드', url: 'https://www.privacyguides.org', country: 'INT', group: 't-security', rank: 8, free: true, note: '무엇을 왜 쓰는지까지 설명하는 추천 목록' },
  { id: 't-sec-tor', name: 'Tor Project', nameKo: '토르 프로젝트', url: 'https://www.torproject.org', country: 'US', group: 't-security', rank: 9, free: true, note: '검열을 우회하는 익명 브라우저' },
  { id: 't-sec-mullvad', name: 'Mullvad VPN', nameKo: '멀바드 VPN', url: 'https://mullvad.net', country: 'SE', group: 't-security', rank: 10, note: '계정도 이메일도 요구하지 않는 VPN' },
  { id: 't-sec-ssllabs', name: 'SSL Labs', nameKo: 'SSL 랩스', url: 'https://www.ssllabs.com/ssltest/', country: 'US', group: 't-security', rank: 11, free: true, note: '사이트 TLS 설정을 등급으로 채점' },
  { id: 't-sec-securityheaders', name: 'Security Headers', nameKo: '시큐리티 헤더', url: 'https://securityheaders.com', country: 'UK', group: 't-security', rank: 12, free: true, note: '내 사이트 보안 헤더를 점검' },
  { id: 't-sec-urlscan', name: 'urlscan.io', nameKo: 'URL스캔', url: 'https://urlscan.io', country: 'DE', group: 't-security', rank: 13, free: true, note: '수상한 링크를 열지 않고 들여다본다' },
  { id: 't-sec-nvd', name: 'NIST NVD', nameKo: 'NVD 취약점DB', url: 'https://nvd.nist.gov', country: 'US', group: 't-security', rank: 14, free: true, note: 'CVE 취약점 공식 데이터베이스' },
  { id: 't-sec-kev', name: 'CISA KEV Catalog', nameKo: 'CISA 악용 취약점 목록', url: 'https://www.cisa.gov/known-exploited-vulnerabilities-catalog', country: 'US', group: 't-security', rank: 15, free: true, note: '실제로 공격에 쓰이는 취약점만 추렸다' },
  { id: 't-sec-shodan', name: 'Shodan', nameKo: '쇼단', url: 'https://www.shodan.io', country: 'US', group: 't-security', rank: 16, free: true, note: '인터넷에 노출된 기기를 검색' },
  { id: 't-sec-keepassxc', name: 'KeePassXC', nameKo: '킵패스XC', url: 'https://keepassxc.org', country: 'INT', group: 't-security', rank: 17, free: true, note: '서버를 안 쓰는 로컬 금고' },
  { id: 't-sec-cryptomator', name: 'Cryptomator', nameKo: '크립토메이터', url: 'https://cryptomator.org', country: 'DE', group: 't-security', rank: 18, free: true, note: '클라우드에 올리기 전에 암호화' },
  { id: 't-sec-ublock', name: 'uBlock Origin', nameKo: '유블록 오리진', url: 'https://ublockorigin.com', country: 'INT', group: 't-security', rank: 19, free: true, note: '가볍고 정확한 광고·추적 차단' },
  { id: 't-sec-tosdr', name: 'Terms of Service; Didn’t Read', nameKo: '토스디알', url: 'https://tosdr.org', country: 'INT', group: 't-security', rank: 20, free: true, note: '약관의 독소조항을 등급으로 요약' },
  { id: 't-sec-eff', name: 'EFF', nameKo: '전자프런티어재단', url: 'https://www.eff.org', country: 'US', group: 't-security', rank: 21, free: true, note: '디지털 권리 운동의 본산' },

  // ══════════════════════════ 논문·전자책·아카이브 ══════════════════════════
  { id: 't-read-arxiv', name: 'arXiv', nameKo: '아카이브', url: 'https://arxiv.org', country: 'US', group: 't-read', rank: 1, free: true, note: 'AI·물리 논문이 학술지보다 먼저 올라온다' },
  { id: 't-read-pmc', name: 'PubMed Central', nameKo: '펍메드 센트럴', url: 'https://www.ncbi.nlm.nih.gov/pmc/', country: 'US', group: 't-read', rank: 2, free: true, note: '의학 논문 전문을 무료로' },
  { id: 't-read-semanticscholar', name: 'Semantic Scholar', nameKo: '시맨틱 스칼라', url: 'https://www.semanticscholar.org', country: 'US', group: 't-read', rank: 3, free: true, note: 'AI가 요약과 인용 맥락을 붙여 준다' },
  { id: 't-read-gutenberg', name: 'Project Gutenberg', nameKo: '구텐베르크 프로젝트', url: 'https://www.gutenberg.org', country: 'US', group: 't-read', rank: 4, free: true, note: '저작권 만료 고전 7만 권' },
  { id: 't-read-openlibrary', name: 'Open Library', nameKo: '오픈 라이브러리', url: 'https://openlibrary.org', country: 'US', group: 't-read', rank: 5, free: true, note: '모든 책에 한 페이지씩, 대출도 된다' },
  { id: 't-read-standardebooks', name: 'Standard Ebooks', nameKo: '스탠더드 이북스', url: 'https://standardebooks.org', country: 'US', group: 't-read', rank: 6, free: true, note: '고전을 손으로 다듬어 조판한 무료 전자책' },
  { id: 't-read-doaj', name: 'DOAJ', nameKo: '오픈액세스 학술지 목록', url: 'https://doaj.org', country: 'SE', group: 't-read', rank: 7, free: true, note: '전문을 공개하는 학술지만 모았다' },
  { id: 't-read-core', name: 'CORE', nameKo: '코어', url: 'https://core.ac.uk', country: 'UK', group: 't-read', rank: 8, free: true, note: '전세계 기관 리포지터리 통합 검색' },
  { id: 't-read-unpaywall', name: 'Unpaywall', nameKo: '언페이월', url: 'https://unpaywall.org', country: 'US', group: 't-read', rank: 9, free: true, note: '유료 논문의 합법 무료본을 찾아 준다' },
  { id: 't-read-connectedpapers', name: 'Connected Papers', nameKo: '커넥티드 페이퍼스', url: 'https://www.connectedpapers.com', country: 'IL', group: 't-read', rank: 10, free: true, note: '논문 한 편에서 인접 연구 지도를 그린다' },
  { id: 't-read-zotero', name: 'Zotero', nameKo: '조테로', url: 'https://www.zotero.org', country: 'US', group: 't-read', rank: 11, free: true, note: '무료 문헌관리, 인용 형식 자동 생성' },
  { id: 't-read-biorxiv', name: 'bioRxiv', nameKo: '바이오아카이브', url: 'https://www.biorxiv.org', country: 'US', group: 't-read', rank: 12, free: true, note: '생명과학 프리프린트' },
  { id: 't-read-ssrn', name: 'SSRN', nameKo: 'SSRN', url: 'https://www.ssrn.com', country: 'US', group: 't-read', rank: 13, free: true, note: '사회과학·경제학 프리프린트' },
  { id: 't-read-paperswithcode', name: 'Papers with Code', nameKo: '페이퍼스 위드 코드', url: 'https://paperswithcode.com', country: 'US', group: 't-read', rank: 14, free: true, note: '논문과 구현 코드를 짝지어 둔다' },
  { id: 't-read-jstor', name: 'JSTOR', nameKo: 'JSTOR', url: 'https://www.jstor.org', country: 'US', group: 't-read', rank: 15, free: true, note: '가입하면 매달 100편까지 무료 열람' },
  { id: 't-read-hathitrust', name: 'HathiTrust', nameKo: '하티트러스트', url: 'https://www.hathitrust.org', country: 'US', group: 't-read', rank: 16, free: true, note: '대학 도서관 공동 디지털 서고' },
  { id: 't-read-wikisource', name: 'Wikisource', nameKo: '위키문헌', url: 'https://wikisource.org', country: 'INT', group: 't-read', rank: 17, free: true, note: '원전 텍스트를 검증해 옮긴 자료실' },
  { id: 't-read-librivox', name: 'LibriVox', nameKo: '리브리복스', url: 'https://librivox.org', country: 'INT', group: 't-read', rank: 18, free: true, note: '자원봉사자가 낭독한 무료 오디오북' },
  { id: 't-read-goodreads', name: 'Goodreads', nameKo: '굿리즈', url: 'https://www.goodreads.com', country: 'US', group: 't-read', rank: 19, free: true, note: '책 고를 때 참고하는 최대 독자 평점' },
  { id: 't-read-elicit', name: 'Elicit', nameKo: '엘리싯', url: 'https://elicit.com', country: 'US', group: 't-read', rank: 20, free: true, note: '질문을 던지면 논문에서 근거를 모아 온다' },

  // ══════════════════════════ 영상·음악 ══════════════════════════
  { id: 't-video-youtube', name: 'YouTube', nameKo: '유튜브', url: 'https://www.youtube.com', country: 'US', group: 't-video', rank: 1, free: true, note: '세계에서 가장 큰 배움터이자 아카이브' },
  { id: 't-video-spotify', name: 'Spotify', nameKo: '스포티파이', url: 'https://open.spotify.com', country: 'SE', group: 't-video', rank: 2, free: true, note: '음악·팟캐스트, 무료 등급 있음' },
  { id: 't-video-netflix', name: 'Netflix', nameKo: '넷플릭스', url: 'https://www.netflix.com', country: 'US', group: 't-video', rank: 3 },
  { id: 't-video-twitch', name: 'Twitch', nameKo: '트위치', url: 'https://www.twitch.tv', country: 'US', group: 't-video', rank: 4, free: true, note: '실시간 방송의 원형' },
  { id: 't-video-ted', name: 'TED', nameKo: 'TED', url: 'https://www.ted.com', country: 'US', group: 't-video', rank: 5, free: true, note: '자막 100여 개 언어, 한국어 포함' },
  { id: 't-video-justwatch', name: 'JustWatch', nameKo: '저스트워치', url: 'https://www.justwatch.com', country: 'DE', group: 't-video', rank: 6, free: true, note: '그 작품이 어느 OTT에 있는지 찾아 준다' },
  { id: 't-video-imdb', name: 'IMDb', nameKo: 'IMDb', url: 'https://www.imdb.com', country: 'US', group: 't-video', rank: 7, free: true, note: '영화·드라마 정보의 기준 데이터베이스' },
  { id: 't-video-letterboxd', name: 'Letterboxd', nameKo: '레터박스', url: 'https://letterboxd.com', country: 'NZ', group: 't-video', rank: 8, free: true, note: '영화 기록과 취향 공유' },
  { id: 't-video-rottentomatoes', name: 'Rotten Tomatoes', nameKo: '로튼 토마토', url: 'https://www.rottentomatoes.com', country: 'US', group: 't-video', rank: 9, free: true },
  { id: 't-video-vimeo', name: 'Vimeo', nameKo: '비메오', url: 'https://vimeo.com', country: 'US', group: 't-video', rank: 10, free: true, note: '광고 없는 고화질, 창작자 중심' },
  { id: 't-video-bandcamp', name: 'Bandcamp', nameKo: '밴드캠프', url: 'https://bandcamp.com', country: 'US', group: 't-video', rank: 11, free: true, note: '수익 대부분이 뮤지션에게 간다' },
  { id: 't-video-soundcloud', name: 'SoundCloud', nameKo: '사운드클라우드', url: 'https://soundcloud.com', country: 'DE', group: 't-video', rank: 12, free: true, note: '신인·언더그라운드 음악의 출발점' },
  { id: 't-video-bilibili', name: 'bilibili', nameKo: '빌리빌리', url: 'https://www.bilibili.com', country: 'CN', group: 't-video', rank: 13, free: true, note: '중국 최대 영상 커뮤니티' },
  { id: 't-video-niconico', name: 'ニコニコ動画', nameKo: '니코니코 동화', url: 'https://www.nicovideo.jp', country: 'JP', group: 't-video', rank: 14, free: true, note: '화면 위로 흐르는 댓글 문화의 원조' },
  { id: 't-video-mubi', name: 'MUBI', nameKo: '무비', url: 'https://mubi.com', country: 'UK', group: 't-video', rank: 15, note: '큐레이션된 예술영화 스트리밍' },
  { id: 't-video-radiogarden', name: 'Radio Garden', nameKo: '라디오 가든', url: 'https://radio.garden', country: 'NL', group: 't-video', rank: 16, free: true, note: '지구본을 돌려 세계 라디오를 듣는다' },
  { id: 't-video-nts', name: 'NTS Radio', nameKo: 'NTS 라디오', url: 'https://www.nts.live', country: 'UK', group: 't-video', rank: 17, free: true, note: '런던발 인터넷 라디오, 선곡이 좋다' },
  { id: 't-video-discogs', name: 'Discogs', nameKo: '디스콕스', url: 'https://www.discogs.com', country: 'US', group: 't-video', rank: 18, free: true, note: '음반 발매 정보와 중고 거래' },
  { id: 't-video-musicbrainz', name: 'MusicBrainz', nameKo: '뮤직브레인즈', url: 'https://musicbrainz.org', country: 'INT', group: 't-video', rank: 19, free: true, note: '누구나 쓸 수 있는 음악 메타데이터' },
  { id: 't-video-plex', name: 'Plex', nameKo: '플렉스', url: 'https://www.plex.tv', country: 'US', group: 't-video', rank: 20, free: true, note: '내 영상 파일을 내 넷플릭스처럼' },

  // ══════════════════════════ 게임 ══════════════════════════
  { id: 't-game-steam', name: 'Steam', nameKo: '스팀', url: 'https://store.steampowered.com', country: 'US', group: 't-game', rank: 1, free: true, note: 'PC 게임 유통의 사실상 표준' },
  { id: 't-game-epic', name: 'Epic Games Store', nameKo: '에픽게임즈 스토어', url: 'https://store.epicgames.com', country: 'US', group: 't-game', rank: 2, free: true, note: '매주 유료 게임을 무료로 푼다' },
  { id: 't-game-gog', name: 'GOG', nameKo: 'GOG', url: 'https://www.gog.com', country: 'PL', group: 't-game', rank: 3, free: true, note: 'DRM 없이 파일로 소장한다' },
  { id: 't-game-itch', name: 'itch.io', nameKo: '이치아이오', url: 'https://itch.io', country: 'US', group: 't-game', rank: 4, free: true, note: '인디·실험작이 모이는 곳' },
  { id: 't-game-isthereanydeal', name: 'IsThereAnyDeal', nameKo: '이즈데어애니딜', url: 'https://isthereanydeal.com', country: 'CZ', group: 't-game', rank: 5, free: true, note: '전 상점 가격과 역대 최저가 비교' },
  { id: 't-game-steamdb', name: 'SteamDB', nameKo: '스팀DB', url: 'https://steamdb.info', country: 'LT', group: 't-game', rank: 6, free: true, note: '동시접속·가격 이력·패치 내역' },
  { id: 't-game-protondb', name: 'ProtonDB', nameKo: '프로톤DB', url: 'https://www.protondb.com', country: 'US', group: 't-game', rank: 7, free: true, note: '리눅스·스팀덱에서 돌아가는지 확인' },
  { id: 't-game-lichess', name: 'Lichess', nameKo: '리체스', url: 'https://lichess.org', country: 'FR', group: 't-game', rank: 8, free: true, note: '광고도 유료도 없는 오픈소스 체스' },
  { id: 't-game-chesscom', name: 'Chess.com', nameKo: '체스닷컴', url: 'https://www.chess.com', country: 'US', group: 't-game', rank: 9, free: true, note: '세계 최대 체스 커뮤니티' },
  { id: 't-game-bgg', name: 'BoardGameGeek', nameKo: '보드게임긱', url: 'https://boardgamegeek.com', country: 'US', group: 't-game', rank: 10, free: true, note: '보드게임 정보의 절대 기준' },
  { id: 't-game-hltb', name: 'HowLongToBeat', nameKo: '하우롱투비트', url: 'https://howlongtobeat.com', country: 'US', group: 't-game', rank: 11, free: true, note: '이 게임을 깨는 데 몇 시간 걸리는가' },
  { id: 't-game-opencritic', name: 'OpenCritic', nameKo: '오픈크리틱', url: 'https://opencritic.com', country: 'US', group: 't-game', rank: 12, free: true, note: '리뷰 점수를 투명하게 집계' },
  { id: 't-game-metacritic', name: 'Metacritic', nameKo: '메타크리틱', url: 'https://www.metacritic.com', country: 'US', group: 't-game', rank: 13, free: true },
  { id: 't-game-pcgamingwiki', name: 'PCGamingWiki', nameKo: 'PC게이밍위키', url: 'https://www.pcgamingwiki.com', country: 'UK', group: 't-game', rank: 14, free: true, note: '게임이 안 돌 때 해결책이 여기 있다' },
  { id: 't-game-nexusmods', name: 'Nexus Mods', nameKo: '넥서스 모드', url: 'https://www.nexusmods.com', country: 'UK', group: 't-game', rank: 15, free: true, note: '모드 배포의 중심지' },
  { id: 't-game-speedrun', name: 'speedrun.com', nameKo: '스피드런닷컴', url: 'https://www.speedrun.com', country: 'US', group: 't-game', rank: 16, free: true, note: '기록 경쟁의 공식 리더보드' },
  { id: 't-game-humble', name: 'Humble Bundle', nameKo: '험블 번들', url: 'https://www.humblebundle.com', country: 'US', group: 't-game', rank: 17, free: true, note: '묶음 할인과 기부를 겸한다' },
  { id: 't-game-newgrounds', name: 'Newgrounds', nameKo: '뉴그라운즈', url: 'https://www.newgrounds.com', country: 'US', group: 't-game', rank: 18, free: true, note: '인터넷 초창기 창작 문화가 남아 있다' },
  { id: 't-game-crazygames', name: 'CrazyGames', nameKo: '크레이지게임즈', url: 'https://www.crazygames.com', country: 'BE', group: 't-game', rank: 19, free: true, note: '설치 없이 브라우저에서 바로' },

  // ══════════════════════════ 커뮤니티·Q&A ══════════════════════════
  { id: 't-forum-reddit', name: 'Reddit', nameKo: '레딧', url: 'https://www.reddit.com', country: 'US', group: 't-forum', rank: 1, free: true, note: '주제별 소모임 10만 개, 검색어에 붙여 쓴다' },
  { id: 't-forum-hn', name: 'Hacker News', nameKo: '해커뉴스', url: 'https://news.ycombinator.com', country: 'US', group: 't-forum', rank: 2, free: true, note: '기술·창업 담론의 중심, 댓글이 본문' },
  { id: 't-forum-stackexchange', name: 'Stack Exchange', nameKo: '스택익스체인지', url: 'https://stackexchange.com', country: 'US', group: 't-forum', rank: 3, free: true, note: '수학부터 요리까지 180개 전문 Q&A' },
  { id: 't-forum-discord', name: 'Discord', nameKo: '디스코드', url: 'https://discord.com', country: 'US', group: 't-forum', rank: 4, free: true, note: '요즘 커뮤니티는 여기로 옮겨 갔다' },
  { id: 't-forum-x', name: 'X', nameKo: 'X (트위터)', url: 'https://x.com', country: 'US', group: 't-forum', rank: 5, free: true, note: '속보와 1차 발언이 가장 먼저 올라온다' },
  { id: 't-forum-quora', name: 'Quora', nameKo: '쿼라', url: 'https://www.quora.com', country: 'US', group: 't-forum', rank: 6, free: true },
  { id: 't-forum-bluesky', name: 'Bluesky', nameKo: '블루스카이', url: 'https://bsky.app', country: 'US', group: 't-forum', rank: 7, free: true, note: '탈중앙 프로토콜 기반 소셜' },
  { id: 't-forum-mastodon', name: 'Mastodon', nameKo: '마스토돈', url: 'https://joinmastodon.org', country: 'DE', group: 't-forum', rank: 8, free: true, note: '서버를 골라 가입하는 연합형 소셜' },
  { id: 't-forum-substack', name: 'Substack', nameKo: '서브스택', url: 'https://substack.com', country: 'US', group: 't-forum', rank: 9, free: true, note: '독립 필자 뉴스레터가 모인 곳' },
  { id: 't-forum-medium', name: 'Medium', nameKo: '미디엄', url: 'https://medium.com', country: 'US', group: 't-forum', rank: 10, free: true },
  { id: 't-forum-zhihu', name: '知乎', nameKo: '즈후', url: 'https://www.zhihu.com', country: 'CN', group: 't-forum', rank: 11, free: true, note: '중국판 쿼라, 답변 수준이 높다' },
  { id: 't-forum-lobsters', name: 'Lobsters', nameKo: '롭스터스', url: 'https://lobste.rs', country: 'US', group: 't-forum', rank: 12, free: true, note: '초대제로 유지되는 기술 링크 게시판' },
  { id: 't-forum-indiehackers', name: 'Indie Hackers', nameKo: '인디 해커스', url: 'https://www.indiehackers.com', country: 'US', group: 't-forum', rank: 13, free: true, note: '1인 창업자들이 매출을 공개하며 논의' },
  { id: 't-forum-telegram', name: 'Telegram', nameKo: '텔레그램', url: 'https://telegram.org', country: 'AE', group: 't-forum', rank: 14, free: true, note: '대규모 공개 채널이 정보 유통 창구' },
  { id: 't-forum-meetup', name: 'Meetup', nameKo: '밋업', url: 'https://www.meetup.com', country: 'US', group: 't-forum', rank: 15, free: true, note: '오프라인 모임을 찾는 표준 플랫폼' },
  { id: 't-forum-slashdot', name: 'Slashdot', nameKo: '슬래시닷', url: 'https://slashdot.org', country: 'US', group: 't-forum', rank: 16, free: true, note: '1997년부터 이어진 기술 게시판' },

  // ══════════════════════════ 마케팅·SEO·트렌드 ══════════════════════════
  { id: 't-market-trends', name: 'Google Trends', nameKo: '구글 트렌드', url: 'https://trends.google.com', country: 'US', group: 't-market', rank: 1, free: true, note: '무엇이 언제부터 검색됐는지 무료로' },
  { id: 't-market-gsc', name: 'Google Search Console', nameKo: '구글 서치 콘솔', url: 'https://search.google.com/search-console', country: 'US', group: 't-market', rank: 2, free: true, note: '내 사이트가 어떤 검색어로 노출되는지' },
  { id: 't-market-ga', name: 'Google Analytics', nameKo: '구글 애널리틱스', url: 'https://analytics.google.com', country: 'US', group: 't-market', rank: 3, free: true },
  { id: 't-market-pagespeed', name: 'PageSpeed Insights', nameKo: '페이지스피드 인사이트', url: 'https://pagespeed.web.dev', country: 'US', group: 't-market', rank: 4, free: true, note: '실제 사용자 체감 속도까지 채점' },
  { id: 't-market-similarweb', name: 'Similarweb', nameKo: '시밀러웹', url: 'https://www.similarweb.com', country: 'IL', group: 't-market', rank: 5, free: true, note: '경쟁 사이트 트래픽을 추정한다' },
  { id: 't-market-ahrefs', name: 'Ahrefs', nameKo: '에이치레프스', url: 'https://ahrefs.com', country: 'SG', group: 't-market', rank: 6, note: '백링크 데이터가 가장 방대하다' },
  { id: 't-market-semrush', name: 'Semrush', nameKo: '셈러시', url: 'https://www.semrush.com', country: 'US', group: 't-market', rank: 7, note: '검색·광고 경쟁 분석 종합' },
  { id: 't-market-answerthepublic', name: 'AnswerThePublic', nameKo: '앤서더퍼블릭', url: 'https://answerthepublic.com', country: 'UK', group: 't-market', rank: 8, free: true, note: '사람들이 실제로 던지는 질문 형태로' },
  { id: 't-market-metaads', name: 'Meta Ad Library', nameKo: '메타 광고 라이브러리', url: 'https://www.facebook.com/ads/library', country: 'US', group: 't-market', rank: 9, free: true, note: '경쟁사가 지금 돌리는 광고를 그대로 본다' },
  { id: 't-market-tiktokcc', name: 'TikTok Creative Center', nameKo: '틱톡 크리에이티브 센터', url: 'https://ads.tiktok.com/business/creativecenter/', country: 'SG', group: 't-market', rank: 10, free: true, note: '인기 해시태그·음원·광고 트렌드' },
  { id: 't-market-explodingtopics', name: 'Exploding Topics', nameKo: '익스플로딩 토픽스', url: 'https://explodingtopics.com', country: 'US', group: 't-market', rank: 11, free: true, note: '아직 뜨기 전인 주제를 잡아낸다' },
  { id: 't-market-builtwith', name: 'BuiltWith', nameKo: '빌트위드', url: 'https://builtwith.com', country: 'AU', group: 't-market', rank: 12, free: true, note: '저 사이트가 무슨 기술로 만들어졌는지' },
  { id: 't-market-wappalyzer', name: 'Wappalyzer', nameKo: '와팔라이저', url: 'https://www.wappalyzer.com', country: 'PL', group: 't-market', rank: 13, free: true },
  { id: 't-market-gtmetrix', name: 'GTmetrix', nameKo: 'GT메트릭스', url: 'https://gtmetrix.com', country: 'CA', group: 't-market', rank: 14, free: true },
  { id: 't-market-mailchimp', name: 'Mailchimp', nameKo: '메일침프', url: 'https://mailchimp.com', country: 'US', group: 't-market', rank: 15, free: true, note: '뉴스레터 발송의 오래된 기본값' },
  { id: 't-market-buffer', name: 'Buffer', nameKo: '버퍼', url: 'https://buffer.com', country: 'US', group: 't-market', rank: 16, free: true, note: 'SNS 예약 발행' },
  { id: 't-market-plausible', name: 'Plausible', nameKo: '플로저블', url: 'https://plausible.io', country: 'EE', group: 't-market', rank: 17, note: '쿠키 없는 가벼운 분석, GDPR 친화' },
  { id: 't-market-matomo', name: 'Matomo', nameKo: '마토모', url: 'https://matomo.org', country: 'NZ', group: 't-market', rank: 18, free: true, note: '내 서버에 두는 오픈소스 애널리틱스' },
  { id: 't-market-hotjar', name: 'Hotjar', nameKo: '핫자', url: 'https://www.hotjar.com', country: 'MT', group: 't-market', rank: 19, free: true, note: '방문자가 어디를 클릭하는지 히트맵' },
  { id: 't-market-screamingfrog', name: 'Screaming Frog', nameKo: '스크리밍 프로그', url: 'https://www.screamingfrog.co.uk', country: 'UK', group: 't-market', rank: 20, free: true, note: '사이트 전체를 긁어 SEO 문제를 잡는다' },

  // ══════════════════════════ 스타트업·투자정보 ══════════════════════════
  { id: 't-startup-crunchbase', name: 'Crunchbase', nameKo: '크런치베이스', url: 'https://www.crunchbase.com', country: 'US', group: 't-startup', rank: 1, free: true, note: '누가 누구에게 얼마를 투자했는가' },
  { id: 't-startup-producthunt', name: 'Product Hunt', nameKo: '프로덕트 헌트', url: 'https://www.producthunt.com', country: 'US', group: 't-startup', rank: 2, free: true, note: '새 제품이 세상에 처음 소개되는 자리' },
  { id: 't-startup-yc', name: 'Y Combinator', nameKo: '와이콤비네이터', url: 'https://www.ycombinator.com', country: 'US', group: 't-startup', rank: 3, free: true, note: '창업 자료와 표준 계약서를 공개한다' },
  { id: 't-startup-startupschool', name: 'Startup School', nameKo: '스타트업 스쿨', url: 'https://www.startupschool.org', country: 'US', group: 't-startup', rank: 4, free: true, note: 'YC가 무료로 여는 창업 강의' },
  { id: 't-startup-pg', name: 'Paul Graham Essays', nameKo: '폴 그레이엄 에세이', url: 'https://paulgraham.com/articles.html', country: 'US', group: 't-startup', rank: 5, free: true, note: '창업 글쓰기의 원전' },
  { id: 't-startup-dealroom', name: 'Dealroom', nameKo: '딜룸', url: 'https://dealroom.co', country: 'NL', group: 't-startup', rank: 6, free: true, note: '유럽 스타트업 투자 데이터에 강하다' },
  { id: 't-startup-tracxn', name: 'Tracxn', nameKo: '트랙슨', url: 'https://tracxn.com', country: 'IN', group: 't-startup', rank: 7, note: '인도·아시아 커버리지가 좋다' },
  { id: 't-startup-cbinsights', name: 'CB Insights', nameKo: 'CB 인사이트', url: 'https://www.cbinsights.com', country: 'US', group: 't-startup', rank: 8, free: true, note: '무료 리서치 보고서만으로도 볼 게 많다' },
  { id: 't-startup-pitchbook', name: 'PitchBook', nameKo: '피치북', url: 'https://pitchbook.com', country: 'US', group: 't-startup', rank: 9, note: '사모·벤처 거래 데이터의 업계 표준' },
  { id: 't-startup-firstround', name: 'First Round Review', nameKo: '퍼스트라운드 리뷰', url: 'https://review.firstround.com', country: 'US', group: 't-startup', rank: 10, free: true, note: '창업자 인터뷰의 깊이가 남다르다' },
  { id: 't-startup-a16z', name: 'a16z', nameKo: '앤드리슨 호로위츠', url: 'https://a16z.com', country: 'US', group: 't-startup', rank: 11, free: true, note: '산업 전망 자료를 아낌없이 푼다' },
  { id: 't-startup-sequoia', name: 'Sequoia Capital', nameKo: '세쿼이아 캐피털', url: 'https://www.sequoiacap.com', country: 'US', group: 't-startup', rank: 12, free: true },
  { id: 't-startup-lenny', name: 'Lenny’s Newsletter', nameKo: '레니 뉴스레터', url: 'https://www.lennysnewsletter.com', country: 'US', group: 't-startup', rank: 13, free: true, note: '프로덕트 매니지먼트 실무의 교과서' },
  { id: 't-startup-saastr', name: 'SaaStr', nameKo: '사스터', url: 'https://www.saastr.com', country: 'US', group: 't-startup', rank: 14, free: true, note: 'SaaS 지표와 영업 조직 운영' },
  { id: 't-startup-openvc', name: 'OpenVC', nameKo: '오픈VC', url: 'https://www.openvc.app', country: 'FR', group: 't-startup', rank: 15, free: true, note: '연락 가능한 VC 명단을 공개' },
  { id: 't-startup-stripeatlas', name: 'Stripe Atlas', nameKo: '스트라이프 아틀라스', url: 'https://stripe.com/atlas', country: 'US', group: 't-startup', rank: 16, note: '해외에서 미국 법인을 세우는 통로' },
  { id: 't-startup-carta', name: 'Carta', nameKo: '카르타', url: 'https://carta.com', country: 'US', group: 't-startup', rank: 17, note: '지분·스톡옵션 관리의 표준' },
  { id: 't-startup-techstars', name: 'Techstars', nameKo: '테크스타즈', url: 'https://www.techstars.com', country: 'US', group: 't-startup', rank: 18, free: true },
  { id: 't-startup-eustartups', name: 'EU-Startups', nameKo: 'EU 스타트업', url: 'https://www.eu-startups.com', country: 'EU', group: 't-startup', rank: 19, free: true, note: '유럽 투자 소식과 채용' },
];
