import type { Signal } from '@/lib/services/signal-service';

function hoursAgo(h: number): string {
  return new Date(Date.now() - h * 60 * 60 * 1000).toISOString();
}

export const MOCK_SIGNALS: Signal[] = [
  // === Insider Trades ===
  {
    id: 'mock-it-1',
    type: 'insider_trade',
    title: 'NVIDIA CEO sells $50M in shares',
    titleKo: 'NVIDIA CEO, 5천만 달러 주식 매도',
    description: 'Jensen Huang sold 240,000 shares under a pre-arranged 10b5-1 trading plan.',
    descriptionKo: '젠슨 황이 사전 설정된 10b5-1 거래 계획에 따라 24만 주를 매도했습니다.',
    company: 'NVIDIA',
    ticker: 'NVDA',
    value: 50000000,
    source: 'SEC EDGAR',
    sourceUrl: 'https://www.sec.gov/cgi-bin/browse-edgar?action=getcompany&CIK=0001045810&type=4',
    detectedAt: hoursAgo(3),
    significance: 'high',
  },
  {
    id: 'mock-it-2',
    type: 'insider_trade',
    title: 'Apple CFO acquires 15,000 shares',
    titleKo: '애플 CFO, 15,000주 매수',
    description: 'Luca Maestri exercised stock options and acquired 15,000 shares at $178.',
    descriptionKo: '루카 마에스트리가 스톡옵션을 행사하여 주당 178달러에 15,000주를 취득했습니다.',
    company: 'Apple',
    ticker: 'AAPL',
    value: 2670000,
    source: 'SEC EDGAR',
    sourceUrl: 'https://www.sec.gov/cgi-bin/browse-edgar?action=getcompany&CIK=0000320193&type=4',
    detectedAt: hoursAgo(8),
    significance: 'medium',
  },
  {
    id: 'mock-it-3',
    type: 'insider_trade',
    title: 'Tesla Director sells $12M in shares',
    titleKo: '테슬라 이사, 1,200만 달러 주식 매도',
    description: 'Board member Robyn Denholm sold 48,000 shares at an average price of $250.',
    descriptionKo: '이사회 멤버 로빈 덴홀름이 평균 250달러에 48,000주를 매도했습니다.',
    company: 'Tesla',
    ticker: 'TSLA',
    value: 12000000,
    source: 'SEC EDGAR',
    sourceUrl: 'https://www.sec.gov/cgi-bin/browse-edgar?action=getcompany&CIK=0001318605&type=4',
    detectedAt: hoursAgo(14),
    significance: 'high',
  },
  {
    id: 'mock-it-4',
    type: 'insider_trade',
    title: 'Meta CTO purchases $5M in shares',
    titleKo: '메타 CTO, 500만 달러 주식 매수',
    description: 'Andrew Bosworth purchased shares on the open market showing confidence in AI initiatives.',
    descriptionKo: 'Andrew Bosworth가 AI 이니셔티브에 대한 자신감을 보이며 공개 시장에서 주식을 매입했습니다.',
    company: 'Meta',
    ticker: 'META',
    value: 5000000,
    source: 'SEC EDGAR',
    sourceUrl: 'https://www.sec.gov/cgi-bin/browse-edgar?action=getcompany&CIK=0001326801&type=4',
    detectedAt: hoursAgo(20),
    significance: 'medium',
  },
  {
    id: 'mock-it-5',
    type: 'insider_trade',
    title: 'AMD CEO sells $8.5M in shares',
    titleKo: 'AMD CEO, 850만 달러 주식 매도',
    description: 'Lisa Su sold shares under a 10b5-1 plan following strong Q4 earnings.',
    descriptionKo: '리사 수가 호실적 발표 후 10b5-1 계획에 따라 주식을 매도했습니다.',
    company: 'AMD',
    ticker: 'AMD',
    value: 8500000,
    source: 'SEC EDGAR',
    sourceUrl: 'https://www.sec.gov/cgi-bin/browse-edgar?action=getcompany&CIK=0000002488&type=4',
    detectedAt: hoursAgo(26),
    significance: 'medium',
  },
  {
    id: 'mock-it-6',
    type: 'insider_trade',
    title: 'JPMorgan Chase CEO buys $25M in stock',
    titleKo: 'JP모건 CEO, 2,500만 달러 주식 매수',
    description: 'Jamie Dimon made a rare personal stock purchase signaling strong belief in bank outlook.',
    descriptionKo: '제이미 다이먼이 은행 전망에 대한 강한 확신을 보이며 드물게 개인 주식 매입을 했습니다.',
    company: 'JPMorgan Chase',
    ticker: 'JPM',
    value: 25000000,
    source: 'SEC EDGAR',
    sourceUrl: 'https://www.sec.gov/cgi-bin/browse-edgar?action=getcompany&CIK=0000019617&type=4',
    detectedAt: hoursAgo(32),
    significance: 'high',
  },

  // === SEC Filings ===
  {
    id: 'mock-sf-1',
    type: 'sec_filing',
    title: 'Tesla files 10-K with significant risk factor updates',
    titleKo: '테슬라, 주요 위험 요인 업데이트된 10-K 제출',
    description: 'Tesla updated its annual report with new risk disclosures related to AI regulation and autonomous driving liability.',
    descriptionKo: '테슬라가 AI 규제 및 자율주행 책임 관련 새로운 위험 공시가 포함된 연차 보고서를 제출했습니다.',
    company: 'Tesla',
    ticker: 'TSLA',
    source: 'SEC EDGAR',
    sourceUrl: 'https://www.sec.gov/cgi-bin/browse-edgar?action=getcompany&CIK=0001318605&type=10-K',
    detectedAt: hoursAgo(6),
    significance: 'medium',
  },
  {
    id: 'mock-sf-2',
    type: 'sec_filing',
    title: 'NVIDIA files 10-Q revealing $4.2B AI chip backlog',
    titleKo: 'NVIDIA, 42억 달러 AI 칩 주문 잔량 공개한 10-Q 제출',
    description: 'Quarterly report shows record AI GPU demand with backlog extending into 2027.',
    descriptionKo: '분기 보고서에서 2027년까지 이어지는 사상 최대 AI GPU 수요와 주문 잔량을 공개했습니다.',
    company: 'NVIDIA',
    ticker: 'NVDA',
    value: 4200000000,
    source: 'SEC EDGAR',
    sourceUrl: 'https://www.sec.gov/cgi-bin/browse-edgar?action=getcompany&CIK=0001045810&type=10-Q',
    detectedAt: hoursAgo(12),
    significance: 'high',
  },
  {
    id: 'mock-sf-3',
    type: 'sec_filing',
    title: 'Amazon files 10-K with AWS revenue breakdown',
    titleKo: '아마존, AWS 매출 상세 분석이 포함된 10-K 제출',
    description: 'Annual report provides detailed AWS segment performance showing 35% YoY growth.',
    descriptionKo: '연차 보고서에서 전년 대비 35% 성장한 AWS 부문 실적 상세를 제공했습니다.',
    company: 'Amazon',
    ticker: 'AMZN',
    source: 'SEC EDGAR',
    sourceUrl: 'https://www.sec.gov/cgi-bin/browse-edgar?action=getcompany&CIK=0001018724&type=10-K',
    detectedAt: hoursAgo(18),
    significance: 'medium',
  },
  {
    id: 'mock-sf-4',
    type: 'sec_filing',
    title: 'Alphabet 10-Q shows Gemini AI investment surge',
    titleKo: '알파벳 10-Q, Gemini AI 투자 급증 공개',
    description: 'Google parent reports $15B quarterly AI R&D spend, up 65% from prior year.',
    descriptionKo: '구글 모회사가 분기 AI R&D 지출이 전년 대비 65% 증가한 150억 달러를 보고했습니다.',
    company: 'Alphabet',
    ticker: 'GOOGL',
    value: 15000000000,
    source: 'SEC EDGAR',
    sourceUrl: 'https://www.sec.gov/cgi-bin/browse-edgar?action=getcompany&CIK=0001652044&type=10-Q',
    detectedAt: hoursAgo(24),
    significance: 'high',
  },
  {
    id: 'mock-sf-5',
    type: 'sec_filing',
    title: 'Microsoft 10-Q: Azure revenue exceeds $30B/quarter',
    titleKo: '마이크로소프트 10-Q: Azure 분기 매출 300억 달러 돌파',
    description: 'Cloud division revenue surpasses expectations driven by AI copilot adoption.',
    descriptionKo: 'AI 코파일럿 채택에 힘입어 클라우드 사업부 매출이 기대치를 초과했습니다.',
    company: 'Microsoft',
    ticker: 'MSFT',
    value: 30000000000,
    source: 'SEC EDGAR',
    sourceUrl: 'https://www.sec.gov/cgi-bin/browse-edgar?action=getcompany&CIK=0000789019&type=10-Q',
    detectedAt: hoursAgo(36),
    significance: 'high',
  },
  {
    id: 'mock-sf-6',
    type: 'sec_filing',
    title: 'Intel files 10-K with foundry business details',
    titleKo: '인텔, 파운드리 사업 세부사항 포함 10-K 제출',
    description: 'Annual report details Intel Foundry Services segment and external customer pipeline.',
    descriptionKo: '연차 보고서에서 인텔 파운드리 서비스 사업부와 외부 고객 파이프라인을 상세히 기술했습니다.',
    company: 'Intel',
    ticker: 'INTC',
    source: 'SEC EDGAR',
    sourceUrl: 'https://www.sec.gov/cgi-bin/browse-edgar?action=getcompany&CIK=0000050863&type=10-K',
    detectedAt: hoursAgo(42),
    significance: 'medium',
  },

  // === Patents ===
  {
    id: 'mock-pt-1',
    type: 'patent',
    title: 'Apple patents new AR display technology',
    titleKo: '애플, 새로운 AR 디스플레이 기술 특허 취득',
    description: 'Apple received a patent for a novel augmented reality waveguide display system for lightweight glasses.',
    descriptionKo: '애플이 경량 안경용 새로운 증강현실 웨이브가이드 디스플레이 시스템에 대한 특허를 취득했습니다.',
    company: 'Apple',
    ticker: 'AAPL',
    source: 'USPTO',
    sourceUrl: 'https://www.uspto.gov',
    detectedAt: hoursAgo(24),
    significance: 'medium',
  },
  {
    id: 'mock-pt-2',
    type: 'patent',
    title: 'Google patents quantum error correction method',
    titleKo: '구글, 양자 오류 보정 방법 특허 취득',
    description: 'New approach to quantum computing error correction that could significantly reduce qubit overhead.',
    descriptionKo: '큐비트 오버헤드를 크게 줄일 수 있는 양자 컴퓨팅 오류 보정의 새로운 접근법 특허를 취득했습니다.',
    company: 'Google',
    ticker: 'GOOGL',
    source: 'USPTO',
    sourceUrl: 'https://www.uspto.gov',
    detectedAt: hoursAgo(30),
    significance: 'high',
  },
  {
    id: 'mock-pt-3',
    type: 'patent',
    title: 'NVIDIA patents multi-chip AI training architecture',
    titleKo: 'NVIDIA, 멀티칩 AI 학습 아키텍처 특허 취득',
    description: 'Novel chip interconnect system enabling faster distributed AI model training.',
    descriptionKo: '더 빠른 분산 AI 모델 학습을 가능하게 하는 새로운 칩 인터커넥트 시스템 특허를 취득했습니다.',
    company: 'NVIDIA',
    ticker: 'NVDA',
    source: 'USPTO',
    sourceUrl: 'https://www.uspto.gov',
    detectedAt: hoursAgo(36),
    significance: 'high',
  },
  {
    id: 'mock-pt-4',
    type: 'patent',
    title: 'Tesla patents solid-state battery cell design',
    titleKo: '테슬라, 전고체 배터리 셀 설계 특허 취득',
    description: 'New battery architecture could increase EV range by 40% while reducing costs.',
    descriptionKo: '새로운 배터리 아키텍처가 비용을 줄이면서 EV 주행 거리를 40% 늘릴 수 있습니다.',
    company: 'Tesla',
    ticker: 'TSLA',
    source: 'USPTO',
    sourceUrl: 'https://www.uspto.gov',
    detectedAt: hoursAgo(48),
    significance: 'high',
  },
  {
    id: 'mock-pt-5',
    type: 'patent',
    title: 'Microsoft patents AI code generation method',
    titleKo: '마이크로소프트, AI 코드 생성 방법 특허 취득',
    description: 'System for generating production-ready code from natural language with security guarantees.',
    descriptionKo: '보안 보장과 함께 자연어에서 프로덕션 코드를 생성하는 시스템 특허를 취득했습니다.',
    company: 'Microsoft',
    ticker: 'MSFT',
    source: 'USPTO',
    sourceUrl: 'https://www.uspto.gov',
    detectedAt: hoursAgo(54),
    significance: 'medium',
  },
  {
    id: 'mock-pt-6',
    type: 'patent',
    title: 'Samsung patents next-gen HBM4 memory architecture',
    titleKo: '삼성전자, 차세대 HBM4 메모리 아키텍처 특허 취득',
    description: 'High-bandwidth memory design for AI accelerators with 2x bandwidth improvement.',
    descriptionKo: '2배 대역폭 개선을 달성한 AI 가속기용 고대역폭 메모리 설계 특허를 취득했습니다.',
    company: 'Samsung Electronics',
    ticker: '005930',
    source: 'USPTO',
    sourceUrl: 'https://www.uspto.gov',
    detectedAt: hoursAgo(60),
    significance: 'high',
  },
  {
    id: 'mock-pt-7',
    type: 'patent',
    title: 'Meta patents haptic feedback for VR controllers',
    titleKo: '메타, VR 컨트롤러 햅틱 피드백 특허 취득',
    description: 'Precision haptic feedback system for next-generation Quest controllers.',
    descriptionKo: '차세대 Quest 컨트롤러를 위한 정밀 햅틱 피드백 시스템 특허를 취득했습니다.',
    company: 'Meta',
    ticker: 'META',
    source: 'USPTO',
    sourceUrl: 'https://www.uspto.gov',
    detectedAt: hoursAgo(66),
    significance: 'low',
  },

  // === Executive Moves ===
  {
    id: 'mock-em-1',
    type: 'executive_move',
    title: 'Google Cloud VP joins AI startup as CEO',
    titleKo: '구글 클라우드 VP, AI 스타트업 CEO로 이직',
    description: 'Former Google Cloud VP of Engineering Sarah Chen moves to lead Cerebras Systems, a well-funded AI chip startup.',
    descriptionKo: '전 구글 클라우드 엔지니어링 VP Sarah Chen이 대규모 투자를 받은 AI 칩 스타트업 Cerebras Systems의 CEO로 합류했습니다.',
    company: 'Google',
    ticker: 'GOOGL',
    source: 'LinkedIn / Press Release',
    sourceUrl: 'https://linkedin.com',
    detectedAt: hoursAgo(12),
    significance: 'high',
  },
  {
    id: 'mock-em-2',
    type: 'executive_move',
    title: 'Stripe CFO moves to Databricks',
    titleKo: '스트라이프 CFO, 데이터브릭스로 이직',
    description: 'Michael Torres joins Databricks as CFO amid the company\'s IPO preparations.',
    descriptionKo: 'Michael Torres가 데이터브릭스의 IPO 준비 중 CFO로 합류했습니다.',
    company: 'Databricks',
    source: 'Bloomberg',
    sourceUrl: 'https://bloomberg.com',
    detectedAt: hoursAgo(24),
    significance: 'high',
  },
  {
    id: 'mock-em-3',
    type: 'executive_move',
    title: 'Meta SVP of AI Research joins Anthropic as CTO',
    titleKo: '메타 AI 연구 SVP, Anthropic CTO로 이직',
    description: 'James Park\'s move signals intensifying competition in the AI safety space.',
    descriptionKo: 'James Park의 이직은 AI 안전 분야에서 경쟁이 심화되고 있음을 시사합니다.',
    company: 'Meta',
    ticker: 'META',
    source: 'The Information',
    sourceUrl: 'https://theinformation.com',
    detectedAt: hoursAgo(36),
    significance: 'high',
  },
  {
    id: 'mock-em-4',
    type: 'executive_move',
    title: 'Tesla Head of Autonomous Driving becomes Aurora CEO',
    titleKo: '테슬라 자율주행 총괄, Aurora CEO로 취임',
    description: 'Lisa Wang takes the helm at Aurora Innovation to lead commercialization of autonomous trucking.',
    descriptionKo: 'Lisa Wang이 Aurora Innovation의 자율주행 트럭 상용화를 이끌기 위해 CEO로 취임했습니다.',
    company: 'Tesla',
    ticker: 'TSLA',
    source: 'Reuters',
    sourceUrl: 'https://reuters.com',
    detectedAt: hoursAgo(48),
    significance: 'high',
  },
  {
    id: 'mock-em-5',
    type: 'executive_move',
    title: 'Samsung VP joins NVIDIA as SVP of Hardware',
    titleKo: '삼성전자 VP, NVIDIA 하드웨어 SVP로 이직',
    description: 'David Kim brings semiconductor manufacturing expertise to NVIDIA\'s hardware division.',
    descriptionKo: 'David Kim이 반도체 제조 전문성을 가지고 NVIDIA 하드웨어 사업부에 합류했습니다.',
    company: 'NVIDIA',
    ticker: 'NVDA',
    source: 'Korea Economic Daily',
    sourceUrl: 'https://www.kedglobal.com',
    detectedAt: hoursAgo(60),
    significance: 'medium',
  },
  {
    id: 'mock-em-6',
    type: 'executive_move',
    title: 'Microsoft ML Platform Head joins OpenAI',
    titleKo: '마이크로소프트 ML 플랫폼 총괄, OpenAI 합류',
    description: 'Priya Sharma joins OpenAI as VP of Engineering, strengthening their infrastructure team.',
    descriptionKo: 'Priya Sharma가 OpenAI의 엔지니어링 VP로 합류하여 인프라 팀을 강화했습니다.',
    company: 'Microsoft',
    ticker: 'MSFT',
    source: 'TechCrunch',
    sourceUrl: 'https://techcrunch.com',
    detectedAt: hoursAgo(72),
    significance: 'high',
  },
  {
    id: 'mock-em-7',
    type: 'executive_move',
    title: 'Netflix CMO moves to Spotify',
    titleKo: '넷플릭스 CMO, 스포티파이로 이직',
    description: 'Rachel Adams brings streaming marketing expertise to Spotify\'s expanding content strategy.',
    descriptionKo: 'Rachel Adams가 스트리밍 마케팅 전문성을 가지고 스포티파이의 확장 콘텐츠 전략에 합류했습니다.',
    company: 'Netflix',
    ticker: 'NFLX',
    source: 'Variety',
    sourceUrl: 'https://variety.com',
    detectedAt: hoursAgo(84),
    significance: 'medium',
  },

  // === Additional insider trades for volume ===
  {
    id: 'mock-it-7',
    type: 'insider_trade',
    title: 'Broadcom CEO sells $18M in shares',
    titleKo: '브로드컴 CEO, 1,800만 달러 주식 매도',
    description: 'Hock Tan sold shares under a pre-arranged trading plan after VMware integration.',
    descriptionKo: 'Hock Tan이 VMware 통합 후 사전 설정된 거래 계획에 따라 주식을 매도했습니다.',
    company: 'Broadcom',
    ticker: 'AVGO',
    value: 18000000,
    source: 'SEC EDGAR',
    sourceUrl: 'https://www.sec.gov/cgi-bin/browse-edgar',
    detectedAt: hoursAgo(40),
    significance: 'medium',
  },
  {
    id: 'mock-it-8',
    type: 'insider_trade',
    title: 'Salesforce insiders buy $3.2M in shares',
    titleKo: '세일즈포스 내부자, 320만 달러 주식 매수',
    description: 'Multiple executives purchased shares following strong earnings and AI cloud demand.',
    descriptionKo: '호실적 및 AI 클라우드 수요 증가 이후 다수의 임원이 주식을 매입했습니다.',
    company: 'Salesforce',
    ticker: 'CRM',
    value: 3200000,
    source: 'SEC EDGAR',
    sourceUrl: 'https://www.sec.gov/cgi-bin/browse-edgar',
    detectedAt: hoursAgo(50),
    significance: 'low',
  },

  // === Additional SEC filings ===
  {
    id: 'mock-sf-7',
    type: 'sec_filing',
    title: 'Meta 10-Q shows Reality Labs losses narrowing',
    titleKo: '메타 10-Q, Reality Labs 손실 축소 확인',
    description: 'Quarterly filing shows Quest 3 sales helped reduce VR division operating losses by 30%.',
    descriptionKo: '분기 보고서에서 Quest 3 판매가 VR 사업부 영업 손실을 30% 줄이는 데 기여했음을 확인했습니다.',
    company: 'Meta',
    ticker: 'META',
    source: 'SEC EDGAR',
    sourceUrl: 'https://www.sec.gov/cgi-bin/browse-edgar?action=getcompany&CIK=0001326801&type=10-Q',
    detectedAt: hoursAgo(28),
    significance: 'medium',
  },
  {
    id: 'mock-sf-8',
    type: 'sec_filing',
    title: 'Apple 10-K reveals Vision Pro production plans',
    titleKo: '애플 10-K, Vision Pro 생산 계획 공개',
    description: 'Annual filing details significant capital expenditure for spatial computing manufacturing.',
    descriptionKo: '연차 보고서에서 공간 컴퓨팅 제조를 위한 대규모 자본 지출 계획을 상세히 기술했습니다.',
    company: 'Apple',
    ticker: 'AAPL',
    source: 'SEC EDGAR',
    sourceUrl: 'https://www.sec.gov/cgi-bin/browse-edgar?action=getcompany&CIK=0000320193&type=10-K',
    detectedAt: hoursAgo(56),
    significance: 'medium',
  },

  // === Additional patents ===
  {
    id: 'mock-pt-8',
    type: 'patent',
    title: 'Amazon patents drone delivery weather system',
    titleKo: '아마존, 드론 배달 기상 시스템 특허 취득',
    description: 'Autonomous weather assessment system for drone delivery route optimization.',
    descriptionKo: '드론 배달 경로 최적화를 위한 자율 기상 평가 시스템 특허를 취득했습니다.',
    company: 'Amazon',
    ticker: 'AMZN',
    source: 'USPTO',
    sourceUrl: 'https://www.uspto.gov',
    detectedAt: hoursAgo(72),
    significance: 'low',
  },
  {
    id: 'mock-pt-9',
    type: 'patent',
    title: 'Intel patents photonic interconnect for data centers',
    titleKo: '인텔, 데이터센터용 광 인터커넥트 특허 취득',
    description: 'Silicon photonics chip-to-chip communication system with 10x bandwidth improvement.',
    descriptionKo: '10배 대역폭 개선을 달성한 실리콘 포토닉스 칩간 통신 시스템 특허를 취득했습니다.',
    company: 'Intel',
    ticker: 'INTC',
    source: 'USPTO',
    sourceUrl: 'https://www.uspto.gov',
    detectedAt: hoursAgo(78),
    significance: 'medium',
  },

  // === Additional executive moves ===
  {
    id: 'mock-em-8',
    type: 'executive_move',
    title: 'LG Energy VP joins QuantumScape as CTO',
    titleKo: 'LG에너지솔루션 VP, QuantumScape CTO로 이직',
    description: 'Robert Lee brings battery manufacturing expertise to the solid-state battery startup.',
    descriptionKo: 'Robert Lee가 배터리 제조 전문성을 가지고 전고체 배터리 스타트업에 합류했습니다.',
    company: 'LG Energy Solution',
    ticker: '373220',
    source: 'Korea Herald',
    sourceUrl: 'https://koreaherald.com',
    detectedAt: hoursAgo(90),
    significance: 'medium',
  },
  {
    id: 'mock-em-9',
    type: 'executive_move',
    title: 'Sony SVP joins Nintendo as COO',
    titleKo: '소니 SVP, 닌텐도 COO로 이직',
    description: 'Yuki Tanaka brings global operations experience as Nintendo prepares Switch 2 launch.',
    descriptionKo: 'Yuki Tanaka가 닌텐도의 Switch 2 출시 준비에 맞춰 글로벌 운영 경험을 가지고 COO로 합류했습니다.',
    company: 'Nintendo',
    source: 'Nikkei Asia',
    sourceUrl: 'https://asia.nikkei.com',
    detectedAt: hoursAgo(96),
    significance: 'medium',
  },
];
