import { NewsItem, TrendingItem, NewsCategory } from '@/types/news';

const mockSources = {
  reuters: { id: 'reuters', name: 'Reuters', nameKo: '로이터', country: 'US', countryFlag: '🇺🇸', url: 'https://reuters.com', category: 'international' as NewsCategory, reliability: 5 },
  bloomberg: { id: 'bloomberg', name: 'Bloomberg', nameKo: '블룸버그', country: 'US', countryFlag: '🇺🇸', url: 'https://bloomberg.com', category: 'economy' as NewsCategory, reliability: 5 },
  techcrunch: { id: 'techcrunch', name: 'TechCrunch', nameKo: '테크크런치', country: 'US', countryFlag: '🇺🇸', url: 'https://techcrunch.com', category: 'tech' as NewsCategory, reliability: 4 },
  bbc: { id: 'bbc', name: 'BBC News', nameKo: 'BBC 뉴스', country: 'UK', countryFlag: '🇬🇧', url: 'https://bbc.com', category: 'international' as NewsCategory, reliability: 5 },
  nikkei: { id: 'nikkei', name: 'Nikkei Asia', nameKo: '닛케이 아시아', country: 'JP', countryFlag: '🇯🇵', url: 'https://asia.nikkei.com', category: 'economy' as NewsCategory, reliability: 4 },
  guardian: { id: 'guardian', name: 'The Guardian', nameKo: '가디언', country: 'UK', countryFlag: '🇬🇧', url: 'https://theguardian.com', category: 'international' as NewsCategory, reliability: 4 },
  foreignpolicy: { id: 'foreignpolicy', name: 'Foreign Policy', nameKo: '포린폴리시', country: 'US', countryFlag: '🇺🇸', url: 'https://foreignpolicy.com', category: 'risk' as NewsCategory, reliability: 5 },
  politico: { id: 'politico', name: 'Politico', nameKo: '폴리티코', country: 'US', countryFlag: '🇺🇸', url: 'https://politico.com', category: 'politics' as NewsCategory, reliability: 4 },
};
export const MOCK_NEWS: NewsItem[] = [
  {
    id: 'mock-1',
    title: 'Federal Reserve Signals Potential Rate Cut in 2025',
    titleKo: '연준, 2025년 금리 인하 가능성 시사',
    summary: 'The Federal Reserve indicated it may begin cutting interest rates as inflation continues to cool.',
    summaryKo: '연방준비제도가 인플레이션이 계속 둔화됨에 따라 금리 인하를 시작할 수 있다고 시사했습니다.',
    url: 'https://www.bloomberg.com/markets',
    imageUrl: 'https://images.unsplash.com/photo-1611974789855-9c2a0a7236a3?w=800',
    source: mockSources.bloomberg,
    sourceId: 'bloomberg',
    category: 'economy',
    country: 'US',
    publishedAt: new Date(Date.now() - 1000 * 60 * 30).toISOString(),
    collectedAt: new Date().toISOString(),
    sentiment: 0.3,
    tags: ['Fed', 'Interest Rate', 'Economy'],
    viewCount: 15420,
    bookmarkCount: 342,
  },
  {
    id: 'mock-2',
    title: 'OpenAI Announces GPT-5 with Revolutionary Reasoning Capabilities',
    titleKo: 'OpenAI, 혁신적 추론 능력 갖춘 GPT-5 발표',
    summary: 'OpenAI unveiled its latest language model with significant improvements in logical reasoning and code generation.',
    summaryKo: 'OpenAI가 논리적 추론과 코드 생성에서 크게 향상된 최신 언어 모델을 공개했습니다.',
    url: 'https://techcrunch.com/category/artificial-intelligence/',
    imageUrl: 'https://images.unsplash.com/photo-1677442136019-21780ecad995?w=800',
    source: mockSources.techcrunch,
    sourceId: 'techcrunch',
    category: 'tech',
    country: 'US',
    publishedAt: new Date(Date.now() - 1000 * 60 * 60).toISOString(),
    collectedAt: new Date().toISOString(),
    sentiment: 0.7,
    tags: ['AI', 'OpenAI', 'GPT-5'],
    viewCount: 28930,
    bookmarkCount: 891,
  },
  {
    id: 'mock-3',
    title: 'EU and China Reach Historic Trade Agreement on Electric Vehicles',
    titleKo: 'EU-중국, 전기차 관련 역사적 무역 합의 달성',
    summary: 'The European Union and China have reached a landmark deal on EV tariffs after months of negotiations.',
    summaryKo: '유럽연합과 중국이 수개월간의 협상 끝에 전기차 관세에 대한 획기적인 합의에 도달했습니다.',
    url: 'https://www.reuters.com/business/',
    imageUrl: 'https://images.unsplash.com/photo-1593941707882-a5bba14938c7?w=800',
    source: mockSources.reuters,
    sourceId: 'reuters',
    category: 'international',
    country: 'EU',
    publishedAt: new Date(Date.now() - 1000 * 60 * 90).toISOString(),
    collectedAt: new Date().toISOString(),
    sentiment: 0.5,
    tags: ['EU', 'China', 'Trade', 'EV'],
    viewCount: 12300,
    bookmarkCount: 256,
  },
  {
    id: 'mock-4',
    title: 'Japan Semiconductor Revival: TSMC Kumamoto Factory Begins Mass Production',
    titleKo: '일본 반도체 부활: TSMC 구마모토 공장 양산 개시',
    summary: "TSMC's first Japanese factory has started mass production, marking Japan's semiconductor industry revival.",
    summaryKo: 'TSMC의 첫 일본 공장이 양산을 시작하며 일본 반도체 산업의 부활을 알렸습니다.',
    url: 'https://asia.nikkei.com/Business/Tech/Semiconductors',
    imageUrl: 'https://images.unsplash.com/photo-1518770660439-4636190af475?w=800',
    source: mockSources.nikkei,
    sourceId: 'nikkei',
    category: 'tech',
    country: 'JP',
    publishedAt: new Date(Date.now() - 1000 * 60 * 120).toISOString(),
    collectedAt: new Date().toISOString(),
    sentiment: 0.6,
    tags: ['Semiconductor', 'TSMC', 'Japan'],
    viewCount: 9870,
    bookmarkCount: 198,
  },
  {
    id: 'mock-5',
    title: 'Middle East Tensions Escalate as Iran Nuclear Talks Stall',
    titleKo: '이란 핵 협상 교착으로 중동 긴장 고조',
    summary: 'Diplomatic efforts to revive the Iran nuclear deal have hit a new impasse.',
    summaryKo: '이란 핵 협정 복원을 위한 외교적 노력이 새로운 교착 상태에 빠졌습니다.',
    url: 'https://foreignpolicy.com/category/analysis/',
    imageUrl: 'https://images.unsplash.com/photo-1529156069898-49953e39b3ac?w=800',
    source: mockSources.foreignpolicy,
    sourceId: 'foreignpolicy',
    category: 'risk',
    country: 'IR',
    publishedAt: new Date(Date.now() - 1000 * 60 * 150).toISOString(),
    collectedAt: new Date().toISOString(),
    sentiment: -0.6,
    tags: ['Iran', 'Nuclear', 'Middle East', 'Geopolitics'],
    viewCount: 7650,
    bookmarkCount: 145,
  },
  {
    id: 'mock-6',
    title: 'UK General Election: Labour Party Unveils Economic Reform Plan',
    titleKo: '영국 총선: 노동당, 경제 개혁 계획 공개',
    summary: 'The Labour Party has released a comprehensive economic reform package ahead of the general election.',
    summaryKo: '노동당이 총선을 앞두고 포괄적인 경제 개혁 패키지를 발표했습니다.',
    url: 'https://www.theguardian.com/politics',
    imageUrl: 'https://images.unsplash.com/photo-1529107386315-e1a2ed48a620?w=800',
    source: mockSources.guardian,
    sourceId: 'guardian',
    category: 'politics',
    country: 'UK',
    publishedAt: new Date(Date.now() - 1000 * 60 * 180).toISOString(),
    collectedAt: new Date().toISOString(),
    sentiment: 0.1,
    tags: ['UK', 'Election', 'Labour', 'Economy'],
    viewCount: 5430,
    bookmarkCount: 87,
  },
  {
    id: 'mock-7',
    title: 'Bitcoin Surges Past $100,000 as Institutional Adoption Accelerates',
    titleKo: '비트코인 10만 달러 돌파, 기관 투자 가속화',
    summary: 'Bitcoin reached a new all-time high as major financial institutions increase their crypto holdings.',
    summaryKo: '주요 금융기관들이 암호화폐 보유를 늘리면서 비트코인이 사상 최고가를 경신했습니다.',
    url: 'https://www.bloomberg.com/crypto',
    imageUrl: 'https://images.unsplash.com/photo-1518546305927-5a555bb7020d?w=800',
    source: mockSources.bloomberg,
    sourceId: 'bloomberg',
    category: 'economy',
    country: 'US',
    publishedAt: new Date(Date.now() - 1000 * 60 * 210).toISOString(),
    collectedAt: new Date().toISOString(),
    sentiment: 0.8,
    tags: ['Bitcoin', 'Crypto', 'Institutional'],
    viewCount: 34500,
    bookmarkCount: 1203,
  },
  {
    id: 'mock-8',
    title: 'US-China Tech War: New Export Controls on AI Chips',
    titleKo: '미중 기술 전쟁: AI 칩 수출 통제 강화',
    summary: 'Washington announces stricter export controls on advanced AI chips to China.',
    summaryKo: '워싱턴이 중국에 대한 첨단 AI 칩 수출 통제를 강화한다고 발표했습니다.',
    url: 'https://www.politico.com/technology',
    imageUrl: 'https://images.unsplash.com/photo-1555255707-c07966088b7b?w=800',
    source: mockSources.politico,
    sourceId: 'politico',
    category: 'politics',
    country: 'US',
    publishedAt: new Date(Date.now() - 1000 * 60 * 240).toISOString(),
    collectedAt: new Date().toISOString(),
    sentiment: -0.3,
    tags: ['US', 'China', 'AI', 'Export Controls'],
    viewCount: 11200,
    bookmarkCount: 367,
  },
  {
    id: 'mock-9',
    title: 'Climate Summit: 150 Nations Agree on Carbon Tax Framework',
    titleKo: '기후 정상회의: 150개국 탄소세 프레임워크 합의',
    summary: 'A breakthrough agreement at the climate summit establishes a global carbon pricing mechanism.',
    summaryKo: '기후 정상회의에서 글로벌 탄소 가격 메커니즘을 수립하는 획기적인 합의가 이루어졌습니다.',
    url: 'https://www.bbc.com/news/science-environment',
    imageUrl: 'https://images.unsplash.com/photo-1611273426858-450d8e3c9fce?w=800',
    source: mockSources.bbc,
    sourceId: 'bbc',
    category: 'international',
    country: 'UN',
    publishedAt: new Date(Date.now() - 1000 * 60 * 300).toISOString(),
    collectedAt: new Date().toISOString(),
    sentiment: 0.4,
    tags: ['Climate', 'Carbon Tax', 'UN'],
    viewCount: 8900,
    bookmarkCount: 234,
  },
  {
    id: 'mock-10',
    title: 'SpaceX Starship Successfully Completes Mars Simulation Mission',
    titleKo: 'SpaceX 스타십, 화성 시뮬레이션 미션 성공',
    summary: 'SpaceX achieved a major milestone with a successful end-to-end Mars mission simulation.',
    summaryKo: 'SpaceX가 종단간 화성 미션 시뮬레이션을 성공적으로 완료하며 주요 이정표를 달성했습니다.',
    url: 'https://techcrunch.com/category/space/',
    imageUrl: 'https://images.unsplash.com/photo-1541185933-ef5d8ed016c2?w=800',
    source: mockSources.techcrunch,
    sourceId: 'techcrunch',
    category: 'tech',
    country: 'US',
    publishedAt: new Date(Date.now() - 1000 * 60 * 360).toISOString(),
    collectedAt: new Date().toISOString(),
    sentiment: 0.9,
    tags: ['SpaceX', 'Mars', 'Space'],
    viewCount: 19400,
    bookmarkCount: 567,
  },
];
export const MOCK_TRENDING: TrendingItem[] = [
  { id: 'hn-1', title: 'Show HN: I built a real-time collaborative code editor', titleKo: 'Show HN: 실시간 협업 코드 에디터를 만들었습니다', url: 'https://news.ycombinator.com', source: 'hackernews', score: 542, commentCount: 187, publishedAt: new Date(Date.now() - 1000 * 60 * 45).toISOString() },
  { id: 'hn-2', title: 'The hidden cost of cloud computing', titleKo: '클라우드 컴퓨팅의 숨겨진 비용', url: 'https://news.ycombinator.com', source: 'hackernews', score: 389, commentCount: 234, publishedAt: new Date(Date.now() - 1000 * 60 * 90).toISOString() },
  { id: 'hn-3', title: 'Why SQLite is the most used database engine', titleKo: 'SQLite가 가장 많이 사용되는 데이터베이스 엔진인 이유', url: 'https://news.ycombinator.com', source: 'hackernews', score: 298, commentCount: 156, publishedAt: new Date(Date.now() - 1000 * 60 * 120).toISOString() },
  { id: 'ph-1', title: 'AI Meeting Assistant 2.0', titleKo: 'AI 미팅 어시스턴트 2.0', url: 'https://www.producthunt.com', source: 'producthunt', score: 1245, commentCount: 89, publishedAt: new Date(Date.now() - 1000 * 60 * 60).toISOString() },
  { id: 'ph-2', title: 'DesignOps - Automate your design workflow', titleKo: 'DesignOps - 디자인 워크플로우 자동화', url: 'https://www.producthunt.com', source: 'producthunt', score: 987, commentCount: 67, publishedAt: new Date(Date.now() - 1000 * 60 * 120).toISOString() },
  { id: 'rd-1', title: 'Tesla announces new battery technology breakthrough', titleKo: '테슬라, 새로운 배터리 기술 돌파구 발표', url: 'https://www.reddit.com/r/technology', source: 'reddit', score: 15600, commentCount: 2340, subreddit: 'technology', publishedAt: new Date(Date.now() - 1000 * 60 * 30).toISOString() },
  { id: 'rd-2', title: 'The job market in tech is finally recovering', titleKo: '테크 취업 시장이 드디어 회복되고 있다', url: 'https://www.reddit.com/r/programming', source: 'reddit', score: 8900, commentCount: 1567, subreddit: 'programming', publishedAt: new Date(Date.now() - 1000 * 60 * 75).toISOString() },
  { id: 'gh-1', title: 'microsoft/TypeScript - v6.0 Release', titleKo: 'microsoft/TypeScript - v6.0 릴리스', url: 'https://github.com/microsoft/TypeScript', source: 'github', score: 4500, publishedAt: new Date(Date.now() - 1000 * 60 * 150).toISOString() },
  { id: 'gh-2', title: 'vercel/next.js - App Router Performance Improvements', titleKo: 'vercel/next.js - App Router 성능 개선', url: 'https://github.com/vercel/next.js', source: 'github', score: 3200, publishedAt: new Date(Date.now() - 1000 * 60 * 200).toISOString() },
];
export function getMockNews(params?: { category?: string; page?: number; limit?: number }): NewsItem[] {
  let filtered = [...MOCK_NEWS];
  if (params?.category && params.category !== 'all') {
    filtered = filtered.filter(n => n.category === params.category);
  }
  const page = params?.page || 1;
  const limit = params?.limit || 10;
  const start = (page - 1) * limit;
  return filtered.slice(start, start + limit);
}

export function getMockTrending(source?: string): TrendingItem[] {
  if (source) {
    return MOCK_TRENDING.filter(t => t.source === source);
  }
  return MOCK_TRENDING;
}
